### ISSUE TITLE
Adjusting file size in SearchGui

### ISSUE THREAD

**Issue by AndreasISAS** [compomics/searchgui#100]
Hi everyone!

I think I just encountered an error in SearchGui.

I have a very big .mgf file, around 2.4 gb and I want SearchGui to split it into something like 900-1000mb parts.
Normaly I go to "advanced settings" and adjust the file size there. But everytime when I change the default number (25000) to 1000 mb and press ok, the programm automaticaly changes back to the default number.

At the moment it is not possible to change the file size there, it is not accepting any number besides the default.
Can this be fixed or am I doing something wrong?

Best regards
Andreas

**Comment by hbarsnes** [comment]
Hi Andreas,

Thanks for telling us about this. I was just a silly copy-paste error when reformatting the graphical user interface. It has now been fixed and we'll release a new version as soon as possible.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

SearchGUI v.2.8.4 has just been released which should fix this issue. Please let us know if this is not the case and we'll reopen the issue.

Best regards,
Harald

**Comment by AndreasISAS** [comment]
Hi!

Thanks for taking care of this problem that fast. 

I am not sure if it works realy properly now.

My .mgf file is around 2.6gb big and I told SearchGui to split it into 1000 mb big parts and another time I told SearchGui to split it into 500 mb big parts.

SearchGui is always splitting the .mgf file into parts like 100 to 150 mb size.

I think this is somehow not right is it?

Best regards
Andreas
   
__________________________


Andreas Hentschel, M. Sc.
Research Associate

ISAS  e.V.
Otto-Hahn-Straße 6b
44227 Dortmund, Germany

P: +49 (0)2 31.13 92-4206 
F: +49  (0)2 31.13 92-4850
Andreas.Hentschel@isas.de
www.isas.de  
__________________________

Leibniz-Institut  für Analytische Wissenschaften – ISAS – e.V.
Bunsen-Kirchhoff-Straße 11 |  44139 Dortmund, Germany
Sitz / Register: Dortmund | Amtsgericht Dortmund VR  1724
Vorstand: Prof. Dr. Albert Sickmann | Prof. Dr. Norbert Esser | Jürgen  Bethke
__________________________





 Von:   Harald Barsnes <notifications@github.com> 
 An:   compomics/searchgui <searchgui@noreply.github.com> 
 Kopie:   AndreasISAS <andreas.hentschel@isas.de>, Author <author@noreply.github.com> 
 Gesendet:   20.04.2016 16:40 
 Betreff:   Re: [compomics/searchgui] Adjusting file size in SearchGui (#100) 


Hi again, 
SearchGUI v.2.8.4 has just been released which should fix this issue. Please let us know if this is not the case and we'll reopen the issue. 
Best regards,
 Harald

**Comment by hbarsnes** [comment]
Hi Andreas,

The "maximum mgf size" option only tells SearchGUI when to start asking if you want to split the mgf file, it does not control the size of the resulting split mgf files. This is handled via the "maximum spectra in mgf file" option. In other words, you need to also alter the second option to control the resulting mgf file sizes.

I'm sorry that this can be a bit confusing. But to be honest we only implemented this feature to make it possible to run OMSSA on bigger mgf files. So if you don't have special reasons to run OMSSA, I'd recommend just keeping the original mgf file without splitting. Unless that causes issues for some of the other search engines as well of course.

Not sure if we ever tried with a 2.6 gb mgf file ourselves. Could I ask why the file is so big? Where does it come from? And have you checked if peak picking has been performed if the data was captured in profile mode?

Best regards,
Harald

**Comment by AndreasISAS** [comment]
Hi!

Thank you for the detailed answer.

I need to split the .mgf file because I am doing the search not only with SearchGui, but also with the MascotDaemon search interface. Our Mascot server is not able to handle that big .mgf files at once, so I need to split them to 1gb sized files.

The .mgf file is that big because it contains the measurement of a whole cell lysate, measured with a 5 hour gradient with nanohplc to qexactive plus mass spectrometer coupling in full scan mode.

Peak picking was already performed using NonLinear software but the file still contains about 350.000 spectra if I am not mistaken.

Best regards
Andreas
   
__________________________


Andreas Hentschel, M. Sc.
Research Associate

ISAS  e.V.
Otto-Hahn-Straße 6b
44227 Dortmund, Germany

P: +49 (0)2 31.13 92-4206 
F: +49  (0)2 31.13 92-4850
Andreas.Hentschel@isas.de
www.isas.de  
__________________________

Leibniz-Institut  für Analytische Wissenschaften – ISAS – e.V.
Bunsen-Kirchhoff-Straße 11 |  44139 Dortmund, Germany
Sitz / Register: Dortmund | Amtsgericht Dortmund VR  1724
Vorstand: Prof. Dr. Albert Sickmann | Prof. Dr. Norbert Esser | Jürgen  Bethke
__________________________





 Von:   Harald Barsnes <notifications@github.com> 
 An:   compomics/searchgui <searchgui@noreply.github.com> 
 Kopie:   AndreasISAS <andreas.hentschel@isas.de>, Author <author@noreply.github.com> 
 Gesendet:   20.04.2016 17:57 
 Betreff:   Re: [compomics/searchgui] Adjusting file size in SearchGui (#100) 


Hi Andreas, 
The "maximum mgf size" option only tells SearchGUI when to start asking if you want to split the mgf file, it does not control the size of the resulting split mgf files. This is handled via the "maximum spectra in mgf file" option. In other words, you need to also alter the second option to control the resulting mgf file sizes. 
I'm sorry that this can be a bit confusing. But to be honest we only implemented this feature to make it possible to run OMSSA on bigger mgf files. So if you don't have special reasons to run OMSSA, I'd recommend just keeping the original mgf file without splitting. Unless that causes issues for some of the other search engines as well of course. 
Not sure if we ever tried with a 2.6 gb mgf file ourselves. Could I ask why the file is so big? Where does it come from? And have you checked if peak picking has been performed if the data was captured in profile mode? 
Best regards,
 Harald

**Comment by mvaudel** [comment]
Hi Andrea,

If your file contains ~350,000 spectra splitting it in chunks of 100,000 should reduce it to ~1 GB. In the advanced parameters, you can only set the size of the chunks in number of spectra. Sorry that our system is so rudimentary but we never really got the time to improve this...

Hope this helps!

Marc

**Comment by AndreasISAS** [comment]
Hi Marc,

thanks for you effort :-)

The explanation that both of you gave me helped me to fix my problem :-)

I have splitted the .mgf file in about 900mb sized files now and its working fine!

Now that I know how to use it right, should be no problem any more :-)

Best regards
Andreas
   
__________________________


Andreas Hentschel, M. Sc.
Research Associate

ISAS  e.V.
Otto-Hahn-Straße 6b
44227 Dortmund, Germany

P: +49 (0)2 31.13 92-4206 
F: +49  (0)2 31.13 92-4850
Andreas.Hentschel@isas.de
www.isas.de  
__________________________

Leibniz-Institut  für Analytische Wissenschaften – ISAS – e.V.
Bunsen-Kirchhoff-Straße 11 |  44139 Dortmund, Germany
Sitz / Register: Dortmund | Amtsgericht Dortmund VR  1724
Vorstand: Prof. Dr. Albert Sickmann | Prof. Dr. Norbert Esser | Jürgen  Bethke
__________________________





 Von:   Marc Vaudel <notifications@github.com> 
 An:   compomics/searchgui <searchgui@noreply.github.com> 
 Kopie:   AndreasISAS <andreas.hentschel@isas.de>, Author <author@noreply.github.com> 
 Gesendet:   21.04.2016 9:37 
 Betreff:   Re: [compomics/searchgui] Adjusting file size in SearchGui (#100) 


Hi Andrea, 
If your file contains ~350,000 spectra splitting it in chunks of 100,000 should reduce it to ~1 GB. In the advanced parameters, you can only set the size of the chunks in number of spectra. Sorry that our system is so rudimentary but we never really got the time to improve this... 
Hope this helps! 
Marc
