### ISSUE TITLE
Being able to set the max missed cleavages when the using unspecific enzyme

### ISSUE THREAD

**Issue by ulrich-eckhard** [compomics/searchgui#101]
Hey guys ...

somehow I am doing something wrong but not sure what it is ... I created a "dimeth4" modification for lysine - see below.

![image](https://cloud.githubusercontent.com/assets/13509447/15139559/0b9c739a-1697-11e6-8c28-15d1707b790f.png)

but it doesn't translate into X! Tandem correctly ...

instead of going into the "residue, potential modification mass":
	
`
<note type="input" label="residue, potential modification ```
mass">57.021464@C,32.056407@[,15.994915@M</note>
<note>Carbamidomethylation of C,Dimethylation of peptide N-term 2H(4),Oxidation of M</note>
`
it goes into the "residue, potential modification motif"
`<note type="input" label="residue, potential modification motif">32.056407@[K]!{P}</note>`

which wouldn't be a problem if it wouldn't be followed by a trypsin-cleavage rule "!{P}", or do I miss the obvious?

hope you can help! all the best from Salzburg,
u

**Comment by ulrich-eckhard** [comment]
hmmm ... maybe it is a problem as I defined it as a "variable" modification and I fear the "potential modification motif" is handled as a "fixed" one.

**Comment by ulrich-eckhard** [comment]
and as a 2nd thing ... the number of missed cleavages doesn't translate into X! Tandem correctly when searched unspecific! it sticks with "50" - but that may be on purpose (I wanted to cut it down to 25 to save a bit on search time but guess it won't make that much of a difference).

**Comment by ulrich-eckhard** [comment]
Update: i tried the conventional dimeth@K (28Da) - and that one translates correctly. so it must be something with my modification specification.

**Comment by ulrich-eckhard** [comment]
UPDATE: dimth4@K FIXED - only minor "missed cleavages" issue remains! :-)

seems I am not allowed to have in the modification "pattern" the other residues in parenthesis but which came up automatically.

so "K" alone works, whereas "K[ACDEFGHIJKLMNQRSTYUOVW]" gives the above described behavior in X! Tandem.

**Comment by hbarsnes** [comment]
Hi Ulrich,

> so "K" alone works, whereas "K[ACDEFGHIJKLMNQRSTYUOVW]" gives the above described behavior in X! Tandem.

And that makes sense does it not? If you add a pattern (called motif in X! Tandem) it cannot be added as a residue modification.

> the number of missed cleavages doesn't translate into X! Tandem correctly when searched unspecific! it sticks with "50" - but that may be on purpose (I wanted to cut it down to 25 to save a bit on search time but guess it won't make that much of a difference).

I think this is the recommended value for unspecific searches in X! Tandem: http://www.thegpm.org/TANDEM/api/smmcs.html. Note the sentence "For a non-specific enzyme, such as pepsin, then a value of 50 is more appropriate." We therefore default to 50 missed cleavages if the unspecific enzyme is used. But I see now that this should be up to the user, so I will remove this limitation in the next release.

But in any case the second pass search will use 50 missed cleavages (http://www.thegpm.org/TANDEM/api/ruc.html). I don't think we can change this setting beyond turning it on or off.

Best regards,
Harald

**Comment by ulrich-eckhard** [comment]
Hey Harald,

thanks for the clarification. I wasn't aware that "K[ACDEFGHIJKLMNQRSTYUOVW]"
corresponds to a motif - I thought it means labeling of K but NOT the
others. but I realize now, it means K followed by any of the aminoacids -
my fault. as said, I didn't add the stuff in the parenthesis, it came
somehow automatically, and even had some short troubles to remove it. But
good to know for the future.

also the trouble is, that the "motif" option in X! Tandem corresponds to a
"fixed" modification (no?), whereas I had defined it as a variable one. so
there is maybe some minor inconsistency. but maybe I am also wrong with the
behaviour of the "motif" option in X! Tandem.

re 2nd search pass: I always switch the refine module off in X! Tandem,
thus not too much experience there. but was hoping that with a lenght of 25
I may save a bit on search time. but guess it wouldn't be much anyhow.

thanks a lot!!!
u

**Comment by hbarsnes** [comment]
> also the trouble is, that the "motif" option in X! Tandem corresponds to a "fixed" modification (no?), whereas I had defined it as a variable one. so there is maybe some minor inconsistency. but maybe I am also wrong with the behaviour of the "motif" option in X! Tandem.

As far as I can see all motifs in X! Tandem are of type "potential" which correspond to variable modifications (http://www.thegpm.org/TANDEM/api/rpmmotif.html). Fixed modifications are annotated via the "residue, modification mass" option (http://www.thegpm.org/TANDEM/api/rmm.html). 

However, just to make it complicated, in some cases a variable modification has to be changed into a "variable fixed modification" in order for certain combinations for modifications to be searchable... ;)

> re 2nd search pass: I always switch the refine module off in X! Tandem, thus not too much experience there. but was hoping that with a lenght of 25 I may save a bit on search time. but guess it wouldn't be much anyhow.

Should be a lot faster. At least according to the X! Tandem documentation: 

"The value chosen for this parameter affects the overall speed of the calculation. The number of peptides considered for a particular protein sequence is linearly proportional to the parameter value, so the amount of time necessary for the calculation will vary roughly linearly with the value chosen. In practice, TANDEM performs somewhat better than linear when doing this type of calculation."

But I guess you'll find out soon enough. ;)

**Comment by ulrich-eckhard** [comment]
thanks ... and yep, you must be right about the motif!!!

thanks again
u

**Comment by hbarsnes** [comment]
Just released SearchGUI v2.8.6 which allows you to control the mx missed cleavages for unspecific searches in X! Tandem.

**Comment by ulrich-eckhard** [comment]
thanks!!!
