### ISSUE TITLE
Feature Improvement - include spectra and database

### ISSUE THREAD

**Issue by ulrich-eckhard** [compomics/searchgui#102]
Hey Guys,

it is not really a biggie but I just noticed, that when I search e.g. 10 mgfs & I do:
- zip file per mgf &
- Include Spectra and Database

all 10 mgfs are added to each of the zip-files and not only the one actually needed.

nothing urgent but wanted to let you know

**Comment by hbarsnes** [comment]
Hi Ulrich,

Thanks for telling us about this. We'll try to get it fixed for the next release.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Ulrich,

Can you test this beta version? It should solve the problem.

https://www.dropbox.com/s/iwoyvwwge5fee6z/SearchGUI-2.8.7-beta-windows.zip?dl=0

Best regards,
Harald

**Comment by ulrich-eckhard** [comment]
worked like a charm as always!!! have a great weekend!!!
u

**Comment by hbarsnes** [comment]
Fixed in SearchGUI v2.9.0. :)
