### ISSUE TITLE
Change the min/max precursor mass filter for Comet (and others?)

### ISSUE THREAD

**Issue by ulrich-eckhard** [compomics/searchgui#103]
Hey Harald and Marc,

can you quickly check if Comet is still working in your hands? in my case it finishes within 1-5 seconds and gives only 8kb files in size. MSGF+ and X!Tandem are working fine though with the same settings.

not sure where it is coming from. I can dig deeper in case it works on your side.
cheers and thanks
u

PS: is there somewhere a repository of "old" SearchGUI versions? i wanted to test SearchGUI 2.2.2 as it was still converting the mgfs to ms2 file format to see if it is coming from there, but I don't have the zip file anymore, and my unzipped SearchGUI doesn't start anymore - guess because of a different Java Version on my system in between.

**Comment by ulrich-eckhard** [comment]
but I fear it is a problem on my side somehow ...

tried to rerun a comet search that I did roughly a week ago - and which worked back then. but it doesn't work now anymore ...

++++
++++

Tue May 24 13:04:23 PDT 2016        Indexing spectrum files.
Tue May 24 13:04:23 PDT 2016        Extracting search settings.

Tue May 24 13:04:23 PDT 2016        Processing 1604_PigDTT_Rd3_AmiToP-T_COL_F12_01_3771.mgf with Comet.

Tue May 24 13:04:24 PDT 2016        Comet finished for 1604_PigDTT_Rd3_AmiToP-T_COL_F12_01_3771.mgf (1.375 seconds).

Tue May 24 13:04:24 PDT 2016        Error: Source 'C:\Users\Overall Lab\Desktop\Pig-DTT\21_mgf\1604_PigDTT_Rd3_AmiToP-T_COL_F12_01_3771.comet.pep.xml' does not exist
Tue May 24 13:04:24 PDT 2016        An error occurred while running SearchGUI. Please contact the developers.
Tue May 24 13:04:24 PDT 2016        The search or processing did not finish properly!

Tue May 24 13:04:24 PDT 2016        Search Canceled!

**Comment by ulrich-eckhard** [comment]
i will send you a link to the data on my google drive in a second. wondering if you can reproduce the problem.

**Comment by hbarsnes** [comment]
Hi Ulrich,

Comet works fine on our test mgf file. Let me know what you find out. If you cannot find the problem I can try searching your data at work tomorrow.

Best regards,
Harald

**Comment by ulrich-eckhard** [comment]
did you get my google drive link?

can you try the mgf and the settings? I have no idea where the problem is coming from right now. but maybe it is the mgf?

**Comment by hbarsnes** [comment]
> can you try the mgf and the settings? I have no idea where the problem is coming from right now. but maybe it is the mgf?

I had a quick test on my laptop. I quickly get a Windows warning that comet.exe has stopped working. No idea why. Works fine if I change the mgf to our test mgf file. Well at least the search actually starts, didn't wait for it to complete.

**Comment by hbarsnes** [comment]
Using your mgf with out standard test settings also seems to be ok, so I guess it's the combination. Looks like a memory issue?

**Comment by ulrich-eckhard** [comment]
hmmmm ... interesting ... have to check the comet parameter file again. maybe something goes wrong there. will try to do that later today and should be able to give an update by your tomorrow! :-)

**Comment by ulrich-eckhard** [comment]
strange strange strange ... copied the data to a different computer and it works there without a problem. should have tried that right away.

**Comment by hbarsnes** [comment]
Ok, I will close the issue then. As it seems to be more of a Comet/computer issue than a SearchGUI issue? But do let us know if you figure out why moving to another computer helped?

**Comment by ulrich-eckhard** [comment]
yeah, definitely ... don't really understand it right now. will do some
windows restarts, check for updates and so on. but it is really weird to me
as the other ones (X!Ta and MSGF+) worked totally fine, and as it looked
like it simply can't load the mgf.

if i figure out something, I will let you know of course
cheers
u

**Comment by ulrich-eckhard** [comment]
hmmm ... so on the other system it still runs, but doesn't finish.

MSGF+ was done within 10 minutes, and Comet is typically not much slower, but runs now for 3 hours already. i will cancel it now to be able to try out some things. but maybe it is really memory related. have to double check also the parameter file ...

====

Tue May 24 15:58:43 PDT 2016        MS-GF+ finished for C:\Users\Ulrich\Desktop\1605_PICS\02_mgf\01_library\160520_UE_NS_PICS_K12libraryT_E3_01_4139.mgf (10 minutes 2 seconds).

Tue May 24 15:58:44 PDT 2016        Processing 160520_UE_NS_PICS_K12libraryT_E3_01_4139.mgf with Comet.

 Comet version "2016.01 rev. 2"
 
 Search start:  05/24/2016, 03:58:44 PM
 
 - Input file: C:\Users\Ulrich\Desktop\1605_PICS\02_mgf\01_library\160520_UE_NS_PICS_K12libraryT_E3_01_4139.mgf

**Comment by ulrich-eckhard** [comment]
without any variable modifications it looks great (29.4s).

also with Met-Oxidation as only variable modification, it runs really fast (33.8s). same result for dm0-Nter only (45.2s). combined, it also runs smoothly (53.0s).

when I remove the dm0-Nter again and add thioacyl@Nter instead, also no problem (53.3s). next I used both N-terminal variable modifications, plus Met-Oxidation, and surprisingly it worked again (82.2s). so i tried my original parameters file again, and again, it worked like a charm (77.5s).

so what next? in my original setting, comet was running AFTER MS-GF+. so I added that one to the pipeline. MSGF+ should take quite a bit longer, as in Comet I can use the semi-specific for the N-terminus only, whereas MSGF+ tests both, a variable N- and a variable C-terminus. Think last time it took 10 minutes - so let's see (yep, this is a life report! :-) ).

So even that worked now - MSGF+ (5min 1s), Comet (78.3s). So at the very beginning, I had also X! Tandem in, so let's try also that one. But my best guess right now, also that will work ... 

So let's see ... X!Tandem took 68.9s, MSGF+ finishes after 4min 57s, and Comet after 78.9s. Don't understand ... really don't understand. So suddently everything seems to work again.

will try it now with more than 1 mgf and then see again. but don't understand, as I didn't even restart the system or so. but let's see ...

**Comment by ulrich-eckhard** [comment]
hmmm ... when trying to use more than one mgf, comet failed. BUT: it started with a different mgf. trying that one alone now. and YEP, that one fails also now ...

so let's see:
the one that worked had something between 21318 (X! Tandem) and 23614 (MSGF+) spectra

- X! Tandem: Spectra matching criteria = 21318
- MSGF+: Spectrum 0-23613 (total: 23614)

the one that failed, not much more:

- X! Tandem: Spectra matching criteria = 23572
- MSGF+: Spectrum 0-24571 (total: 24572)

so let's try the batch size option: and yep, that seems to do the trick. ahhhh - didn't expect that honestly. but it makes sense I reckon. but never had to use it so far, and searching against E.coli and NOT human - so a bit surprised. also had files with MORE spectra already (pretty sure about that), and 3 variable modifications are also not that many.

somehow surprised ... but guess that could be the "fix". will try to run all files over night, and will report then again.

**Comment by ulrich-eckhard** [comment]
... very very weird update ... 

on the other system my searches still failed. but I realized that I had the following COMET advanced setting (that I usually don't have):

- Comet Advanced Settings -> Search -> Precursor Mass -> min was set to 0.0
- typically i have something like 500 there

after changing that one, it worked. I guess that makes sense as otherwise the search space explodes. possible? the weird thing though is that it was also set "0" on the system where it worked before, and which has only have the memory (16GB instead of 32GB). so I still don't understand, but it makes sense to a certain degree. 

I don't know what the default setting there is when you ship out SearchGUI, but could be an idea, if it isn't the case anyhow, to put it to something like 500Da maybe. but not sure if it was really the cause of my troubles today.

**Comment by hbarsnes** [comment]
> I don't know what the default setting there is when you ship out SearchGUI, but could be an idea, if it isn't the case anyhow, to put it to something like 500Da maybe.

We default to "digest_mass_range = 0.0 10000.0". Not really sure why we decided to deviate from the Comet default which is "digest_mass_range = 600.0 5000.0". Unless we have a good reason I guess we should use the same defaults as Comet.

**Comment by ulrich-eckhard** [comment]
fully agree ... maybe it also just recently changed. because I never had problems so far. or I typically took care of it and just don't remember! :-)
