### ISSUE TITLE
Problem loading my mgf files

### ISSUE THREAD

**Issue by Moaxle** [compomics/searchgui#104]
Hi!

i´m a new user to SearchGUI. I work in neuropeptidomic analysis in invertebrates and would love to use your application for automated searches using MALDI MS/MS data against my own transcriptomic database (fasta file with protein precursor genes with AA sequences). Everything seems to work except of the file conversion. Since i don´t have any complete LC-MS data sets (we analyze specific parts of neuronal tissue so no extracts needed) for conversion into mgf i have quiet a problem getting my single files into the software. I have managed to convert the files from an AB sciex 4800 (T2D via pepchem.org) into mzXML, however resulting mgf files from msconvert  (mzXML into mgf) seem to be empty. I have tried to set up an mgf by hand in order to see wether something is working at all; with the following error: No MS2 spectra found in the file. Do you have an example mgf file that i can check to see what prefixes in the file are missing, or even better do you know a way to convert single MS/MS files into mgf? 

Example of mgf file:

BEGIN IONS
PEPMASS=2031.1
CHARGE=1+
TITLE=Test
12.9	1
13.1	1
13.2	1
13.5	1
13.6	1
.
.
.

looking forward to your reply!

and keep up the good work!

cheers,
Max

**Comment by hbarsnes** [comment]
Hi Max,

Thanks for your interest in our software.

You can find a test mgf file [here](http://genesis.ugent.be/files/costore/practicals/bioinformatics-for-proteomics/1-Peptide-and-Protein-Identification/1.3-Peptide-Spectrum-Matching/resources/1.3-resources.zip), as part of our [Bioinformatics for Proteomics Tutorial](https://compomics.com/bioinformatics-for-proteomics/).

For all the details about mgf see [the Mascot help pages](http://www.matrixscience.com/help/data_file_help.html#GEN).

Given that you have AB sciex files I assume these are then WIFF files? SearchGUI should support the conversion of WIFF files to mgf as long as you have [ProteoWizard](http://proteowizard.sourceforge.net) installed (and you are on a Windows platform). But I guess you tried this option already? You can also download [ProteoWizard](http://proteowizard.sourceforge.net) and use the included MSConvertGUI to convert your files directly.

What do you mean by "single MS/MS file" btw? As in an mgf file with a single MS/MS spectrum?

Best regards,
Harald

**Comment by Moaxle** [comment]
Hi Harald,

thanks for the quick reply and the link for the example file. i have T2D files for single MS/MS spectra,  resulting from manual fragmentation on a single sample. 

Yes by "single MS/MS" file i mean a mgf file with a single MS/MS spectrum.

cheers,

Max

**Comment by ulrich-eckhard** [comment]
could your conversion problem come from here?

seems the 64-bit msConvert doesn't support T2D. maybe you can try the "Windows Installer" (32 bit?). maybe worth a try. and make sure you don't have any funky filters enabled for conversion.

![image](https://cloud.githubusercontent.com/assets/13509447/15524085/3bd188a0-21ed-11e6-93e0-1c3ff3623843.png)

**Comment by Moaxle** [comment]
Hi everybody,

got a workaround working. So the problem is that msconvert is not able to convert T2D into mgfs (in both variants 64bit, 32bit). However since i only have a few spectra to analyze i just builded my own mgf. The problem why the mgf was´t accpeted from SearchGUI in the first run was that the title in the mgf file (selfmade mgf) had to match the filename of the mgf. Search is ruining perfectly, got the right hits from a test peptide. 

So long and thanks for the quick help!

Cheers,

Max
