### ISSUE TITLE
installation using maven

### ISSUE THREAD

**Issue by dauss75** [compomics/searchgui#106]
Hello,

I have been trying to install using maven and yet keep getting errors from dependencies. Is there any instruction I can follow for a successful installation?

Many thanks,

Segun

**Comment by hbarsnes** [comment]
Hi Segun,

What sort of dependency issues are you getting? All the required dependencies and the repositories used should be in the SearchGUI pom file. This is how we build it ourselves.

Could I ask why you want to build your own version btw? As SearchGUI is not really intended to be used as a library in other tools.

Best regards,
Harald

**Comment by dauss75** [comment]
Hi Harald.

Thanks for the quick reply. 
There are many, but here are some of them:
[ERROR] bootstrap class path not set in conjunction with -source 1.6
/scratch/galaxy/test/searchgui/src/main/java/com/compomics/util/BinaryArrayImpl.java:[8,37] error: [ERROR] bootstrap class path not set in conjunction with -source 1.6
/scratch/galaxy/test/searchgui/src/main/java/com/compomics/util/BinaryArrayImpl.java:[8,37] error: package org.apache.xerces.impl.dv.util does not exist
[ERROR] /scratch/galaxy/test/searchgui/src/main/java/com/compomics/util/gui/export/graphics/ExportGraphicsDialog.java:[17,34] error: package org.apache.batik.transcoder does not exist
[ERROR] /scratch/galaxy/test/searchgui/src/main/java/com/compomics/util/Export.java:[8,31] error: package org.apache.batik.dom.svg does not exist
[ERROR] /scratch/galaxy/test/searchgui/src/main/java/com/compomics/util/Export.java:[40,32] error: cannot find symbol
[ERROR]   symbol:   class TranscoderException
  location: class Export
/scratch/galaxy/test/searchgui/src/main/java/com/compomics/util/Export.java:[60,32] error: cannot find symbol
[ERROR]   symbol:   class TranscoderException
  location: class Export

RE the pom file, it didn't work for me right away; for example, 
            <groupId>com.compomics</groupId>
            <artifactId>utilities</artifactId>
            <version>4.5.19</version>
I find 4.5.18 is the latest following the website: http://genesis.ugent.be/maven2/com/compomics/utilities/

I am trying to have searchgui and peptide shaker in a local machine as part of galaxy tools.

Thank you,

Segun

**Comment by hbarsnes** [comment]
Hi Segun,

> RE the pom file, it didn't work for me right away; for example,
 com.compomics
 utilities
 4.5.19
 I find 4.5.18 is the latest following the website: http://genesis.ugent.be/maven2/com/compomics/utilities/

Ah, yes, it seems like we didn't yet deploy the latest version of utilities. I will try to take care of this tomorrow. We're sort of in between two versions for both SearchGUI and PeptideShaker at the moment, as you can see from the "beta" addition to the version numbers.

I think that getting the correct utilities version should solve your dependency issues.

> I am trying to have searchgui and peptide shaker in a local machine as part of galaxy tools.

I should know this, but are you then required to build the tools yourselves? Can't you rely on the shared binaries?

Best regards,
Harald

**Comment by dauss75** [comment]
Thanks Harald again for the note.
I wished not to deal with building the tool myself, but when I was running searchgui, there were a missing java class such as FastaCLI that gave me an error.  Do you have precompiled java classes that I can have?

Many thanks,

Segun

**Comment by hbarsnes** [comment]
Hi Segun,

> I wished not to deal with building the tool myself, but when I was running searchgui, there were a missing java class such as FastaCLI that gave me an error.

Where did you get the binary with missing classes? Did you use the downloads from the Github pages? What is the command line you were trying to run and what was the error?

> Do you have precompiled java classes that I can have?

Everything should be in the default downloads. Command lines such as "java -cp SearchGUI-X.Y.Z.jar eu.isas.searchgui.cmd.FastaCLI" work fine on my side. No complaints about missing classes.

Best regards,
Harald

**Comment by dauss75** [comment]
Hi Harald,

I have the files, but can't remember where they came from since I have been looking at many different places.  I have SearchGUI-1.27.2.jar and it works with what you noted. I will try to work with this and let you know what things go.  Thanks!

Segun

**Comment by dauss75** [comment]
One note- I am using the version of 1.27.2.

**Comment by dauss75** [comment]
Hi Harald,

Finally it got worked for me with a minor change in the searchgui.xml file:
1. -id_params SEARCHGUI_IdentificationParameters.par --> -id_params SEARCHGUI_IdentificationParameters.par.parameters (or you could get rid of .par; i took the lazy way)
2. commented out the use_gene_mapping option

Thanks,

Segun

**Comment by dauss75** [comment]
Hi Harald,

I fed the search_gui output to peptide shaker and got into another problem as follows:
Fatal error: Java Exception
Path configuration completed.
Thu Jun 02 04:15:25 UTC 2016 Unzipping searchgui_input.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Thu Jun 02 04:15:25 UTC 2016 An error occurred while creating the PeptideShaker project.
Thu Jun 02 04:15:25 UTC 2016 Project successfully created.
Thu Jun 02 04:15:25 UTC 2016 Saving results.
Thu Jun 02 04:15:25 UTC 2016 An exception occurred while saving the project.

Thu Jun 02 04:15:25 UTC 2016 Zipping project.
Thu Jun 02 04:15:25 UTC 2016 PeptideShaker processing failed. See the PeptideShaker log for details.
<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>
Running Reports
Generating mzIdentML

PeptideShaker project (.cpsx or .zip file) '/scratch/galaxy/job_working_directory/000/550/peptideshaker_output.zip' not found.

Thank you,
Segun

**Comment by hbarsnes** [comment]
Hi Segun,

> One note- I am using the version of 1.27.2.

I would strongly recommend that you update to the most recent versions of SearchGUI and PeptideShaker (you'll find the binary downloads on the main Github page of the two tools, v2.8.6 for SearchGUI and v1.10.3 for PeptideShaker).

This should hopefully solve most of your problems. You may need to revise some of your command line though, but at least you'll then be using the current version and it'll be a lot easier for us to fix any issues you may find. Many issues found in older versions have also already been fixed in later releases.

Best regards,
Harald

**Comment by dauss75** [comment]
Hi Harald,

Many thanks for your help.  Everything worked out following your suggestions!

One tweak I made was the input of peptide shaker; somehow search_gui output was not available as an input to peptide shaker so commented out the options.
 
        <param name="searchgui_input" format="searchgui_archive" type="data" label="Compressed SearchGUI results"
            help="SearchGUI Results from History">
            

Best,

Segun

**Comment by hbarsnes** [comment]
Hi Segun,

> One tweak I made was the input of peptide shaker; somehow search_gui output was not available as an input to peptide shaker so commented out the options.

Not sure what you mean by "not available"? Can't you use the "-identification_files" option? And how do you get the SearchGUI output into PeptideShaker without this option?

Best regards,
Harald

**Comment by dauss75** [comment]
Hi Harald,

Sorry about the confusion. I meant "Compressed SearchGUI results" box shows  
"No searchgui_archive dataset available." although the search_gui output was in the history.

Thanks,
Segun

**Comment by hbarsnes** [comment]
Hi Segun,

Ok, sounds like you then got everything working and I will then close the issue. If you come across other problems please open a new issue.

Best regards,
Harald

**Comment by dauss75** [comment]
thank you!
