### ISSUE TITLE
MyriMatch: error on on CentOS 6: invalid symbol "2"

### ISSUE THREAD

**Issue by jflucier** [compomics/searchgui#109]
Hi,

i am trying to upgrade SearchguiGUIinstallation on our HPC system since we need to analyse SILAC MS experiments. WQe have alot of files to analyse, around 500. Tested on one MS file before lauching the whole set.

The error is linked to Myrimatch. Everything seems to go fine until the end of MyriMatch. Here the trace of execution:

myrimatch command: 
/ltmp/jflucier/temp_ms/GM18486_MSB15024_01B/softwares/SearchGUI-2.0.11/resources/MyriMatch/linux/linux_64bit/myrimatch -cpus 24 -ProteinDatabase /ltmp/jflucier/temp_ms/GM18486_MSB15024_01B/db/searchgui_db_concatenated_target_decoy.fasta /ltmp/jflucier/temp_ms/GM18486_MSB15024_01B/GM18486_MSB15024_01B.mgf -OutputFormat mzIdentML -workdir /ltmp/jflucier/temp_ms/GM18486_MSB15024_01B/search_results/.SearchGUI_temp -OutputSuffix .myrimatch -DecoyPrefix "" -MinPeptideLength 6 -MaxPeptideLength 30 -MaxResultRank 10 -SpectrumListFilters "" -FragmentMzTolerance "0.1 daltons" -MonoPrecursorMzTolerance "0.006 daltons" -PrecursorMzToleranceRule "mono" -StaticMods "C 57.021464" -DynamicMods "M 0 15.994915 ( 1 42.010565  2 0.0" -MaxDynamicMods 5 -StatusUpdateFrequency 10 -NumChargeStates 5+ -TicCutoffPercentage 0.98 -MinPeptideMass 0.0 -MaxPeptideMass 10000.0 -UseSmartPlusThreeModel true -ComputeXCorr false -NumIntensityClasses 3 -ClassSizeMultiplier 2 -NumBatches 50 -MaxPeakCount 100 -MonoisotopeAdjustmentSet [-1,2] -FragmentationAutoRule false -FragmentationRule "cid" -CleavageRules "Trypsin" -MinTerminiCleavages 2 -MaxMissedCleavages 2 

Mon Jun 20 14:41:40 EDT 2016 Processing GM18486_MSB15024_01B.mgf with MyriMatch.
.....
.....
Finished database search; 101.401 seconds elapsed.
Overall stats: 933212 proteins; 24697610 peptides; 73718061 variants; 82037020 comparisons
Writing search results to file "GM18486_MSB15024_01B.mgf.myrimatch.mzid".
[unimod::site] invalid symbol "2"

Mon Jun 20 14:43:33 EDT 2016 MyriMatch Process Finished (1 minute 52.872 seconds).

Mon Jun 20 14:43:33 EDT 2016 Could not find MyriMatch result file for GM18486_MSB15024_01B.mgf.

The SearchGUI command used is:
echo "Peptide identification using xtandem, omssa, msgf, myrimatch, comet and tide spectral search software"
java -Xmx30G -cp $SEARCHGUI_JAR_PATH eu.isas.searchgui.cmd.SearchCLI \
-protein_index 1 \
-spectrum_files $TEMPDIR/GM18486_MSB15024_01B.mgf \
-output_folder $TEMPDIR/search_results/ \
-temp_folder $TEMPDIR/ \
-id_params $TEMPDIR/searchgui.parameters.par \
-andromeda 0 \
-omssa 1 \
-xtandem 1 \
-msgf 1 \
-ms_amanda 0 \
-myrimatch 1 \
-comet 1 \
-tide 0 > $OUTPUT_DIR/logs/SearchCLI_run.log 2>&1

if  you require dataset file or anything else for testing, do not hesitate to ask me. Tks so much for all your help in advance.
JF

**Comment by hbarsnes** [comment]
Hi JF,

Not sure how much we can do on our side as the problem occurs inside MyriMatch when writing the mzid output file. The error message [unimod::site] invalid symbol "2" does not tell me much either I'm afraid. Does it happen for this file only?

I would recommend trying to contact the MyriMatch developers. This can be a bit tricky though, as the MyriMatch website does not exist anymore last time I checked...

Would it be an option to replace MyriMatch with one of the other search engines included in SearchGUI?

Best regards,
Harald

**Comment by jflucier** [comment]
Hi Harald, tks with quick reply. Will try to contact them. tks again

**Comment by hbarsnes** [comment]
Hi JF,

Any progress on this one? Can I close the issue? (As it's not really a SearchGUI issue anyway?)

Best regards,
Harald

**Comment by jflucier** [comment]
Hi Harald,

yes you can close. Dont remember however how i solve this... it as been to
long.

JF

**Comment by hbarsnes** [comment]
Hi JF,

Ok, thanks for the update.

Best regards,
Harald
