### ISSUE TITLE
list of supported modifications.

### ISSUE THREAD

**Issue by jflucier** [compomics/searchgui#110]
Hello i am trying to find where you defined all the supported modifications that can be passed to searchgui and peptideshaker. I found a list here:

https://github.com/compomics/searchgui/blob/master/resources/conf/searchGUI_configuration.txt

The list defined in this file seems to be incomplete. When i execute : 
java -cp /netmount/ip32_home/xroucou_group/apps/compomics/clean_install/SearchGUI-2.9.0/SearchGUI-2.9.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -mods

I get a long list of supported mods. Can you point me where i can find this in your code library. tks

JF

**Comment by mvaudel** [comment]
Hi JF,

Apologies for this, improving our handling of PTMs in command line has been on the todo list for a long time.

Running `java -cp /netmount/ip32_home/xroucou_group/apps/compomics/clean_install/SearchGUI-2.9.0/SearchGUI-2.9.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -mods` is the way to get all available PTMs in command line, and displays all supported modifications. In GUI mode, click on _Add_ or _Edit_ in front of  _Search Settings_, then _Spectrum Matching_, and click on the cogwheel above the table where all modifications are listed. That will allow you to see all details concerning the modifications and create your own.

The list of modifications consist of a list of default modifications complemented with user implemented modifications. The default modifications are hard coded I am afraid (see `setDefaultModifications()` in https://github.com/compomics/compomics-utilities/blob/master/src/main/java/com/compomics/util/experiment/biology/PTMFactory.java). For quite some time we wanted to move to a more open format. If it is something you would need we can start looking into it again.

https://github.com/compomics/searchgui/blob/master/resources/conf/searchGUI_configuration.txt is deprecated.

Hope this helps!

Marc

**Comment by hbarsnes** [comment]
Hi JF,

Just a minor correction regarding the searchGUI_configuration.txt file. It is not really deprecated, but it's only used in the graphical user interface to decide which PTMs to display in the "Most Used Modifications" list. A PTM is added to the list if it's used more than a certain number of times.

And maybe I can add a question: Why do you want to inspect the code showing how we set up the PTMs in the first place? If there are errors in some of the PTMs of if there are standard PTMs that ought be included please let us know. :)

Best regards,
Harald

**Comment by jflucier** [comment]
Thanks for all your help on this. So there is no open format. I will extract these using the eu.isas.searchgui.cmd.IdentificationParametersCLI -mods command. 

I just needed those for my software i develloped wrapping a SearchGUI and PeptideShaker analysis pipeline. Its more for user input validation purpose before I call the the searchgui and peptideshaker pipeline. For now the solution for me will be to run this command and extract output supported PTM using a regex that i will then try to match against user input.

Thanks alot for all you help.

JF

**Comment by jflucier** [comment]
tks so much for your help. you provide awesome support. tks
