### ISSUE TITLE
MyriMatch: relocation error

### ISSUE THREAD

**Issue by Thys3Potgieter** [compomics/searchgui#112]
Hi Guys, I noticed that Myrimatch scores were not reported in the mzIdentML output of PeptideShaker (I am running SearchGUI with tide, omssa, comet, xtandem, msgf+ and myrimatch). The other databases all have e-values reported in mzIdentML. Running with only Myrimatch selected the search fails:

myrimatch command:
/researchdata/fhgfs/ptgmat003/PS/tryptic_10_0.02/150715_SF_507_ML+(1)_150728113016/sg/resources/MyriMatch/linux/linux_64bit/myrimatch -cpus 64 -ProteinDatabase /researchdata/fhgfs/ptgmat003/PS/tryptic    _10_0.02/fasta/UP000001584_14_03_2016_crap_30_01_2015_concatenated_target_decoy.fasta /researchdata/fhgfs/ptgmat003/thys_raw/S507_S5527_test/150715_SF_507_ML+(1)_150728113016.mgf -OutputFormat mzIdent    ML -workdir /researchdata/fhgfs/ptgmat003/PS/tryptic_10_0.02/150715_SF_507_ML+(1)_150728113016/.SearchGUI_temp -OutputSuffix .myrimatch -DecoyPrefix "" -MinPeptideLength 8 -MaxPeptideLength 30 -MaxRes    ultRank 10 -SpectrumListFilters "" -FragmentMzTolerance "0.02 daltons" -MonoPrecursorMzTolerance "10.0 ppm" -PrecursorMzToleranceRule "mono" -StaticMods "C 57.021464" -DynamicMods "M 0 15.994915 ( 1 4    2.010565" -MaxDynamicMods 2 -StatusUpdateFrequency 10 -NumChargeStates 4+ -TicCutoffPercentage 0.98 -MinPeptideMass 600.0 -MaxPeptideMass 5000.0 -UseSmartPlusThreeModel true -ComputeXCorr false -NumIn    tensityClasses 3 -ClassSizeMultiplier 2 -NumBatches 50 -MaxPeakCount 300 -MonoisotopeAdjustmentSet [0,1] -FragmentationAutoRule false -FragmentationRule "cid" -CleavageRules "Trypsin" -MinTerminiCleav    ages 2 -MaxMissedCleavages 2

Sun Jul 03 13:36:17 SAST 2016 Processing 150715_SF_507_ML+(1)_150728113016.mgf with MyriMatch.

myrimatch: relocation error: /lib64/libnss_files.so.2: symbol __rawmemchr, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference

Sun Jul 03 13:36:17 SAST 2016 MyriMatch finished for /researchdata/fhgfs/ptgmat003/thys_raw/S507_S5527_test/150715_SF_507_ML+(1)_150728113016.mgf (32 milliseconds).

Sun Jul 03 13:36:17 SAST 2016 Could not find MyriMatch result file for 150715_SF_507_ML+(1)_150728113016.mgf.
Sun Jul 03 13:36:17 SAST 2016 Zipping output files.

Any ideas? 

My operating system:
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 11 (x86_64)
Release:        11
Codename:       n/a

PeptideShaker log:
 Sun Jul 03 13:36:07 SAST 2016: PeptideShaker version 3.0.2.
 Memory given to the Java virtual machine: 28631367680.
 Total amount of memory in the Java virtual machine: 2027945984.
 Free memory: 2006785688.
 Java version: 1.8.0_31.

And SearchGUI version:
3.0.2

Thanks in advance for any assistance, and thanks as always for the great tools :)
Thys

**Comment by Thys3Potgieter** [comment]
Here are some more details:
(ve) ptgmat003@srvslshpc614:~/software/SearchGUI/SearchGUI-3.0.2/resources/MyriMatch/linux/linux_64bit> ./myrimatch 
myrimatch: relocation error: /lib64/libnss_files.so.2: symbol __rawmemchr, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference

But the 32 bit runs:
(ve) ptgmat003@srvslshpc614:~/software/SearchGUI/SearchGUI-3.0.2/resources/MyriMatch/linux/linux_32bit> ./myrimatch 
Process #0 (srvslshpc614) is starting.
MyriMatch 2.2.140 (2014-4-4)
FreiCore 1.6.230 (2014-4-7)
ProteoWizard MSData 3.0.5941 (2014-3-20)
ProteoWizard Proteome 3.0.4080 (2012-11-7)
Vanderbilt University (c) 2012, D.Tabb/M.Chambers/S.Dasari
Licensed under the Apache License, Version 2.0

Not enough arguments.

Usage: "myrimatch" [optional arguments] <input spectra filemask 1> [input spectra filemask 2] ...
Optional arguments:
-cfg <config filepath>        : specify a configuration file other than the default
-workdir <working directory>  : change working directory (where output files are written)
-cpus <value>                 : force use of <value> worker threads
-ignoreConfigErrors           : ignore errors in configuration file or the command-line
-AnyParameterName <value>     : override the value of the given parameter to <value>
-dump                         : show runtime configuration settings before starting the run

(ve) ptgmat003@srvslshpc614:~/software/SearchGUI/SearchGUI-3.0.2/resources/MyriMatch/linux/linux_32bit>

**Comment by hbarsnes** [comment]
Hi Thys,

Thanks for telling us about this. However, I'm afraid there is not all that much we can do if MyriMatch breaks internally and it cannot be traced to using a specific set of input parameters. Especially not when it works fine on Windows which is our main operating system for running SearchGUI. (I think other users have used it without issues on Linux as well though.)

In most similar cases I would recommend that you contact the developers of the search engine for help, but in the case of MyriMatch that is a bit complicated as the tool's web page no longer exists. You could try contacting the authors on the MyriMatch paper directly?

But in the end you need to figure out if you really need MyriMatch or if it could be replaced by one of the other search engines supported in SearchGUI? In most cases the added contribution from a single search engine is limited, especially if using more than 3-4 search engines.

Best regards,
Harald

**Comment by Thys3Potgieter** [comment]
Hi Harald, thank you, I understand - I see that the links to Myrimatch source are not working - I will see if I can find a copy and compile from source, and get back to you. 
Best regards
Thys

**Comment by Thys3Potgieter** [comment]
Here is a link that should work, Myrimatch is included here.

https://sourceforge.net/p/proteowizard/code/HEAD/tree/trunk/pwiz/pwiz_tools/Bumbershoot/

Thanks to David Tabb and Matthew Chambers for pointing it out to me :)

**Comment by chambm** [comment]
@Thys3Potgieter Did you figure out the relocation error? Does it happen with the latest binaries that you can download from ProteoWizard's website (bumbershoot-linux-x86_64-xxx.tar.bz2)?
