### ISSUE TITLE
parameter file change during run via commandline

### ISSUE THREAD

**Issue by norazrin** [compomics/searchgui#117]
Hi, 

I use 3 search engines: myrimatch, omssa and comet for the run. i generated the parameter files via searchgui and IdentificationParametersCLI but after running the searcgui via command line, the parameter input : precursorAccuracyType has changed from Da to PPM (the initial/desired setting was Da) and it looks like it did not followed what was determined, instead it falls back to the default setting.

Any idea how to overcome this situation?

**Comment by hbarsnes** [comment]
Hi,

Thanks for telling us about this. Can you send us the specific command lines used so that we can try to reproduce the error on our side?

Best regards,
Harald

**Comment by norazrin** [comment]
command line for running the searchgui is as follows:
java -Xms8G -Xmx512G -cp /mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/SearchGUI-3.1.0/SearchGUI-3.1.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out "/mn
t/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/Ens41.par" -db "/mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/Ens41_concatenated_target_decoy.fasta" -fixed_mo
ds "iTRAQ 4-plex of K, iTRAQ 4-plex of peptide N-term, Methylthio of C" -variable_mods "iTRAQ 4-plex of Y, Oxidation of M"  

java -Xms8G -Xmx512G -cp /mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/SearchGUI-3.1.0/SearchGUI-3.1.0.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files "/mnt/fls01
-home01/mqbpkna2/scratch/ChickenMSData/" -id_params "/mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/Ens41.par" -xtandem 1 -myrimatch 1 -ms_amanda 0 -msgf 0 -omssa 0 -c
omet 1 -tide 1 -andromeda 0 -output_option 0 -output_data 1 -output_date 1 -output_folder "/mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/"

mv /mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/searchgui_out.zip /mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/searchgui_ENS41.zipx

exit 0


And this is the commoand line for creating the parameter file by using IdentificationParametersCLI:
java -Xms8G -Xmx512G -cp /mnt/fls01home01/mqbpkna2/scratch/03092016/SearchGUI_runs/SearchGUI-3.1.0/SearchGUI 
3.1.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out "/mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/Ens41.par" -db "/mnt/fls01home01/mqbpkna2/scratch/03092016/SearchGUI_runs/Ens41_concatenated_target_decoy.fasta" -prec_tol 2.0 -prec_ppm 0 -frag_tol 0.8 -frag_ppm 0 -enzyme Trypsin -fixed_mods "iTRAQ 4-plex of K, iTRAQ 4-plex of peptide N-term, Methylthio of C" -variable_mods "iTRAQ 4-plex of Y, Oxidation of M" -min_charge 2 -max_charge 4 -mc 2 -fi b -ri y -min_isotope 0 -max_isotope 1

java -Xms8G -Xmx512G -cp  /mnt/fls01home01/mqbpkna2/scratch/03092016/SearchGUI_runs/SearchGUI-3.1.0/SearchGUI-3.1.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -annotation_level 0.75 -annotation_high_resolution 1 -sequence_matching_type 2 -sequence_matching_x 0.25 -import_peptide_length_min 8 -import_peptide_length_max 8 -import_missed_cleavage_min 0 -import_missed_cleavage_max 2 -import_precursor_mz_ppm 0 -exclude_unknown_ptms 1 -ptm_score 1 -ptm_threshold -score_neutral_losses 0 -ptm_sequence_matching_type 2 -ptm_align
ment 1 

exit 0

Thanks
Azrin

**Comment by hbarsnes** [comment]
Hi Azrin,

Is there any reason why you're running IdentificationParametersCLI three times?

Also, note that by running the following two commands you will first set the precursor accuracy to ppm and then use that when running SearchGUI (i.e. the parameter is never reset to ppm, as it is never set to Dalton in the first place):

```
java -Xms8G -Xmx512G -cp /mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/SearchGUI-3.1.0/SearchGUI-3.1.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out "/mn
t/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/Ens41.par" -db "/mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/Ens41_concatenated_target_decoy.fasta" -fixed_mo
ds "iTRAQ 4-plex of K, iTRAQ 4-plex of peptide N-term, Methylthio of C" -variable_mods "iTRAQ 4-plex of Y, Oxidation of M" 

java -Xms8G -Xmx512G -cp /mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/SearchGUI-3.1.0/SearchGUI-3.1.0.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files "/mnt/fls01
-home01/mqbpkna2/scratch/ChickenMSData/" -id_params "/mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/Ens41.par" -xtandem 1 -myrimatch 1 -ms_amanda 0 -msgf 0 -omssa 0 -c
omet 1 -tide 1 -andromeda 0 -output_option 0 -output_data 1 -output_date 1 -output_folder "/mnt/fls01-home01/mqbpkna2/scratch/03092016/SearchGUI_runs/"
```

In other words, whatever you do in the two preceding IdentificationParametersCLI command lines will be ignored.

So I'd recommend using **one** IdentificationParametersCLI command line followed by **one** SearchCLI command line. This will also make your command lines easier to debug. 

Best regards,
Harald

**Comment by norazrin** [comment]
Is there any reason why you're running IdentificationParametersCLI three times? inexperience maybe?lol

will try to do that. thanks.

**Comment by hbarsnes** [comment]
Hi Azrin,

Let me know if it solves the problem so that I can close the issue.

Best regards,
Harald

**Comment by norazrin** [comment]
problem solved. thanks!
