### ISSUE TITLE
Program freezes during database search

### ISSUE THREAD

**Issue by carlaurangasolis** [compomics/searchgui#118]
Hello,

I have tried running SearchGUI/MSGF+ using both the interface and the command line. During both methods, the database search freezes at the very beginning, still at "0% complete". I am encountering this problem using both my Mac OSX and via ssh with a 24-core server. My .mgf file is only ~200MB.  I did try splitting this file into two, but this did not resolve the fact that every time the program is run, it freezes. I would appreciate any help you could give, I am including a screenshot of the place where the freeze occurs.

Sincerely,

Carla Uranga
![image](https://cloud.githubusercontent.com/assets/22406027/18811197/ee89db2a-825d-11e6-8dac-bf6b9aa26692.png)

**Comment by hbarsnes** [comment]
Hi Carla,

How much memory are you giving to SearchGUI? As this is the memory that is also used by MS-GF+. You can change the memory setting via Edit > Java Settings. Or by adding the -Xmx argument to your java SearchGUI command line. Note that in order to use more than around 1 GB you need to have a 64 bit Java installation.

BTW, what do you mean by "the database search freezes"? Do you mean that the tool is not responsive anymore, i.e. that you cannot even click the Cancel button? Or that the MS-GF+ search seems to be stuck and makes no progress?

Best regards,
Harald

**Comment by carlaurangasolis** [comment]
Hi,

Thank you for your reply.

My parameter file command line is:

java -cp SearchGUI-3.1.1.jar
eu.isas.searchgui.cmd.IdentificationParametersCLI [ -msgf_decoy 1
-msgf_instrument 2 -msgf_fragmentation 1 -msgf_protocol 0
-msgf_min_pep_length 6 -msgf_max_pep_length 40 -msgf_num_matches 1
-msgf_termini 1 -msgf_num_ptms 3 -ptm_score 0 -mc 2 -fixed_mods
"Carbamidomethylation of C" -prec_tol 50 -variable_mods "Phosphorylation of
S, Methylation of K, Acetylation of K” -db "uniprot_all.fasta" -out
"msgfplus2.par" ]
and my command line is:

 java -Xmx50G -cp SearchGUI-3.1.1.jar eu.isas.searchgui.cmd.SearchCLI [
-spectrum_files "carla_lasiodip_1.mgf, carla_lasiodip_2.mgf" -output_folder
"output_test" -id_params "msgfplus2.par" -msgf 1 ]

Even with that much memory it is getting stuck at the same place.

Sincerely,

Carla

**Comment by carlaurangasolis** [comment]
Even at 5000G java memory it is still freezing. I do need to mention that I am running it via the graphical interface on my computer with split files and a smaller database and now it is working, albeit quite slowly. There is something about the interface vs. command line running methods that is different, but I am a biochemist. Again, thank you for your help.

**Comment by mvaudel** [comment]
Dear Carla,

Nowadays for a biochemist it is as important to know how to use a computer than a microscope ;) Can you go to the _Edit_ -> _Java Settings_ menu and make a screenshot of the dialog displayed?

Note that increasing the java memory beyond the capacity of your machine is not a good idea - you might want to check your hardware limitation. Also, is there anything special to know about your setup? Any synced disc or network configuration that would slow down the process?

Best regards,

Marc

**Comment by carlaurangasolis** [comment]
Hi, I agree biochemists need to learn as much as possible about computers, which is why I am here :) on github. Computers and bioinformatics are awesome. If you know of any accredited online programming courses I would appreciate the reference.

I am on a 4GB MacOSX El Capitan....... so I hope I don't break my machine during this process. Please let me know if I should interrupt this process because of the too much memory issue. Another thing you should know, is that I am working from Mexico (Ensenada, Baja California), and my internet connection is not very good. I am also using the VPN at my current institution, CICESE for use of the 24-core server. Again thank you, I had the privilege to take a proteomics class from Nuno Bandeira at UCSD. I am sure you know of him. 

Please find the screenshot of the current graphical interface output, this process is being run from my personal computer terminal command line:

Command line: 
/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java -splash:resources/conf/searchgui-splash.png -Xms128M -Xmx60000M -cp /Users/carlaurangasolis/Documents/SearchGUI-3.1.1/SearchGUI-3.1.1.jar eu.isas.searchgui.gui.SearchGUI 

![screen shot 2016-09-26 at 5 39 07 am](https://cloud.githubusercontent.com/assets/22406027/18834622/cd8a8df8-83ab-11e6-8f86-25609feceabb.png)

**Comment by hbarsnes** [comment]
Hi Carla,

From your command line it may seem like you're running your search against the whole of UniProt (-db "uniprot_all.fasta")? Or is this just a poorly named FASTA file? As running against the whole of UniProt will have a significant impact on your search time.

BTW, do the other search engines also have problems with this specific input?

Best regads,
Harald

**Comment by mvaudel** [comment]
Dear Carla,

I must say I am impressed and can only encourage you to pursue your training in bioinformatics!  If you have been at a course with Nuno, you might already know more than me :) There are some online courses in bioinformatics on Coursera, including some from UCSD. I heard great things from them. 

Here are some other possible sources of trouble when processing the files with ms-gf+:
1- I see your mgf file is quite big. Can you make sure that the spectra are centroided and not profile? ie can you verify that a peak picker was used?
2- Can you make sure that java 64 bits is installed? If you are running java 32 bits, it will not be possible for ms-gf+ to use all the memory available.
3- Can you make sure that all files are on the same machine as the one executing the command? If your files are on the server when you work on your mac, or on the mac when working with the server, this will make the processing much slower :) Also, if your user folder or disc is synced to the server, please avoid them for storing your files and SearchGUI. This will also make th processing slower.

And one last thing, did you try X!Tandem? It is usually much faster than ms-gf+ :)

Best regards and good luck,

Marc

**Comment by carlaurangasolis** [comment]
Hahaha, ok so I guess I may be too ambitious with the database. I did indeed, download the entire Uniprot database and have been trying to run my data against it. It is the ideal because fungi are taxonomically and evolutionarily fascinating, and comparing with the entire Uniprot database gives a lot of info. The data is already centroided as is in the .mgf file I am using, with ~56000 spectra in the file.  I will try splitting the file even further, into four files.

I was hoping the 24-core server would work and be able to handle the Uniprot database. I will keep trying, and will try peak-picking on msconvert. I am trying to publish my results because they are novel, but want to make sure I am reporting the proteomics according to acceptable standards. I already have all-Uniprot database searches using Mascot and Peaks 7 (all with a 1% FDR) but obviously the programs in SearchGUI are open source and very, very important to include due to the wonderful field-changing contributions SearchGUI is making. It is just going to take patience to learn the basics. Believe you me, Marc and Harald, you know WAY more than me on this!

When I get it to work you will be the first to know! Take care and be well.
