### ISSUE TITLE
MS-GF+ utilizes part of the available cores

### ISSUE THREAD

**Issue by uhaifabioinfo** [compomics/searchgui#120]
Hi,

I'm running a 20 core machine, MyriMatch uses all of them, but MSGF uses only 9, anything I can do about it?

David.

**Comment by hbarsnes** [comment]
Hi David,

The number of cores used by MS-GF+ (and all other search engines that supports this to be controlled externally) is set via Edit > Processing Settings. The default value is the total number of cores on the machine.

For MS-GF+ the value is translated into the "-thread" parameter for MS-GF+. After that I'm afraid there is not much we can do as the rest is controlled by MS-GF+. It could be that MS-GF+ has some upper limit, but this is a bit hard to test without access to the MS-GF+ code. I would have recommend that you contact the MS-GF+ developers, but MS-GF+ is sadly not actively maintained anymore.

BTW, is MS-GF+ always using 9 cores or is the value changing during the search? As it could be that not all processes are able to utilize all cores, or that some process are waiting for other cores to finish etc.?

Best regards,
Harald

**Comment by uhaifabioinfo** [comment]
Hi Harald,

SearchGui is set to 20 cores (And other search engines use them). maybe it's something about MSGF+, but it didn't happen before.

well, there are other engines to use then...

Cheers,
David.

**Comment by hbarsnes** [comment]
Hi David,

> well, there are other engines to use then...

Note that MS-GF+ should still complete even though it is using less cores. And there is also no guarantee that using more cores always is faster. Depends a lot on how the use of the cores is implemented. (But yes, usually the more cores the better of course.)

I will now close this issue. But please feel free to reopen it if you figure out more about why MS-GF+ is not using all the cores available.

Best regards,
Harald
