### ISSUE TITLE
Fluorine atom in custom modification

### ISSUE THREAD

**Issue by ohgane** [compomics/searchgui#123]
Hi,

I would appreciate if you could add F atom 
to the available elements list for custom modifications.
(Or, if possible, "user-defined element" might save future time to add additional elements)

Best regards,

Kenji

**Comment by mvaudel** [comment]
Hi,

Thanks for your suggestion. The atom has been added and new versions supporting this will be released soon.

Best regards,

Marc

**Comment by ohgane** [comment]
Hi Marc,

Thank you a lot for your quick response!
Best regards,

Kenji

**Comment by mvaudel** [comment]
You are welcome! Don't hesitate if there are other atoms you would need. We will keep the issue open until the fix is released so that other users who might encounter the same problem can see it.

Have a nice day,

Marc

**Comment by hbarsnes** [comment]
Hi Kenji,

SearchGUI v3.2.0 has now been released which includes support for the Fluorine atom as an option when creating custom PTMs.

Best regards,
Harald
