### ISSUE TITLE
validation question

### ISSUE THREAD

**Issue by carlaurangasolis** [compomics/searchgui#126]
Hello, I was able to surmise that the two unique peptide rule is optimal, but that validation is also possible by a certain number of validated PSMs, of the same peptide sequence. What is this valid PSM threshold? In other words, how many valid PSMs of peptides with the same sequences would deem that protein identification as valid? Thank you for your patience and help.

Best,

Carla Uranga, M.Sc.

**Comment by hbarsnes** [comment]
Hi Carla,

>  In other words, how many valid PSMs of peptides with the same sequences would deem that protein identification as valid?

The default quality level for a protein to be considered as confident is that it has been identified by at least two peptides from at least two confident spectra. A peptide is considered confident if it is identified by at least one confident PSM. Finally, a confident PSM depends on the fragment ion sequence coverage and the mass deviation.

Note that you can inspect all the confidence filters by clicking the "Validated" column (the right-most column in the protein, peptide and PSM tables), and that you can edit the quality filters via the Validation Filters option on the Edit menu.

Please see our [tutorials](https://compomics.com/bioinformatics-for-proteomics/) for more details on validation and quality filters, in particular chapter 1.5. And keep in mind that statistical validation and the use of quality filters is not the same thing, as detailed in the given chapter.

Best regards,
Harald
