### ISSUE TITLE
Searchgui x tandem output for Skyline 

### ISSUE THREAD

**Issue by jurest** [compomics/searchgui#128]
Hi,
Is it possible to import the x! tandem xml file from the Searchgui output folder into Skyline to produce a spectral library? I tried renaming it to .xtan.xml, as required by Skyline, but with no success. 
Thanks,
Jure

**Comment by mvaudel** [comment]
Hi Jure,

I am not sure to which extent Skyline supports raw search engine results. But if you load your results in PeptideShaker and export them as mzIdentML, Skyline supports these files.

Hope this helps,

Marc

**Comment by hbarsnes** [comment]
Issue assumed resolved by using the mzIdentML export. If this is not the case, please let us know and we'll reopen the issue.
