### ISSUE TITLE
How to speed up Comet in SearchGUI 3.1.4 ?

### ISSUE THREAD

**Issue by lparsons42** [compomics/searchgui#129]
I am running SearchGUI 3.1.4 on a 64bit Windows 2k8r2 server with 64gb RAM and 8 physical cores.  I have spectra that take ~20 minutes to search in X!Tandem, MyriMatch, or Amanda that are taking several hours to run through Comet.  I have not changed the Comet-specific parameters for these searches, is there anything I might want to start with if I want to reduce the time it takes for Comet to search?  

thank you
Lee

**Comment by hbarsnes** [comment]
Hi Lee,

I think this question would be better to ask the Comet developers: https://groups.google.com/forum/#!forum/comet-ms?

I'm also on the Comet list myself. I will therefore close this as a SearchGUI issue and follow up via the Comet list (if needed) as soon as you set up a new issue there.

Best regards,
Harald
