### ISSUE TITLE
Where can I define a new protease?

### ISSUE THREAD

**Issue by roberthardt** [compomics/searchgui#130]
Hi,

I'm going trough all the options, bt I seem not to be able to set a new protease (I digested with GluC followed by Lys-C).

Regards

Robert

**Comment by hbarsnes** [comment]
Hi Robert,

At the moment it is not possible to add a new protease in the graphical user interface. However, there is a command line option that is in development and not yet properly tested. We will let you know when we've had the time to document and make it more easily available.

However, most of the search engines do not support a combination of proteases, i.e. even if you could set up this custom protease most of the search engines would not support it. Would it make sense to define GluC + Lyc-C as a single enzyme cleaving after E and K?

I note that Lys-C has a "not if followed by P"-rule, but we cannot have this only for the K and not for the E. So the P-rule would be either for both or for none of the two possible cleavage sites. Which one do you prefer?

Best regards,
Harald

**Comment by roberthardt** [comment]
Hi Harald,

well if I could define GluC + LysC as a single protease cleaving after K and E, that would be sufficient. I would leave out the P-rule then. 

By the way in the meantime I looked around and found the following: In the old SearchGUI release 3.1.4 there was a searchGUI_enzymes.xml file in the conf-folder which allowed me to define such a protease myself. Unfortunately, I cannot find this file in the newest release anymore.

Any ideas?

Robert 
-----------------------------------------
Robert Hardt
Feudenheimer Str. 30
69123 Heidelberg
Phone: +49 176 61573795
roberthardt@gmail.com <mailto:roberthardt@gmail.com>

**Comment by hbarsnes** [comment]
Hi Robert,

> well if I could define GluC + LysC as a single protease cleaving after K and E, that would be sufficient. I would leave out the P-rule then.

Ok, I will look into allowing you to add this combined protease yourself in the graphical user interface as soon as possible.

> By the way in the meantime I looked around and found the following: In the old SearchGUI release 3.1.4 there was a searchGUI_enzymes.xml file in the conf-folder which allowed me to define such a protease myself. Unfortunately, I cannot find this file in the newest release anymore.

We simplified the way the proteases are handled in the latest version and removed the enzyme file. It was a leftover from when we were basing everything on the OMSSA enzyme names and indexes. The new structure is a lot more flexible, but it is still in development.

Would it be an option for you to keep using the previous SearchGUI and PeptideShaker versions until we manage to allow you to re-add the protease you're missing in the new version?

Best regards,
Harald

**Comment by roberthardt** [comment]
Sure,
Thanks for the effort Harald. It's really appreciated. So long I can still work with the old version. 

Regards 

Robert

**Comment by davidemfGH** [comment]
Dear all.

I am involved in a project were I have peptides digested by both Trypsin and AspN, hence being able to  define a new protease with rules from both proteases or being allowed to pick more than one protease would be great.

In the meanwhile, I am happy I found this thread and the information about version 3.1.4 and searchGUI_enzymes.xml, I will use that.

Best regards,
Davi

**Comment by hbarsnes** [comment]
A new version of SearchGUI has just been released which allows you to define custom enzymes via Edit > Enzymes in the main SearchGUI window. If this does not work as wanted, please let us know and we'll reopen the issue.
