### ISSUE TITLE
Unspecific enzyme problem

### ISSUE THREAD

**Issue by hale94** [compomics/searchgui#131]
In the newest release (3.2.1) I am having a problem saving search parameters using the unspecific enzyme setting in the search settings.  When I select this, the enzyme box greys out, but the specificity box is still active.  I cannot save the settings.  Shouldn't the specificity box also be greyed out for unspecific seargches?

**Comment by hbarsnes** [comment]
Hi,

Thanks for pointing this out. We'll fix it and release a new version shortly.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

We just released new versions of both SearchGUI and PeptideShaker which should fix this problem. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by hale94** [comment]
Harald,

 

That appears to have fixed the problem.  Thanks,

 

John
