### ISSUE TITLE
SearchGUI throws null error at the end of every search and larger search never finishes

### ISSUE THREAD

**Issue by akwalker** [compomics/searchgui#133]
This seems to have started with 3.2.3. I actually have 2 problems that may or may not be related

I am doing an X!Tandem search on a very small database because it's a 2 protein complex. It completes in 1 minute and zips the files. Then it says the search has completed but gives an Error:null (full error at the bottom) and says it was cancelled. During this time, the search window is totally nonresponsive. I cannot use the scroll bar, I cannot click on the arrow on the tip of the day and even the cancel button does not work

Luckily, the search actually did complete and I can view the data. 

I have another experiment that I'm searching against rat. That search ran over 16 hours (it usually takes 10-20 minutes max) and once again the window is non responsive so I can't cancel the search. I went into task manager to kill it and saw that neither SearchGUI nor X!Tandem were using any CPU and only about 4Gb of RAM (I have 32 cores and 32 Gb RAM). After I killed SearchGUI in task manager, the XTandem process shot up from 0% CPU to 99% CPU so it doesn't even look like it was doing the search. I have tried multiple times (letting it go maybe an hour or so) and the same thing happens each time (tandem using 0% then going to 100% when I kill SearchGUI). 

I don't know if this error is related to the other search not seeming to finish. I doubt it but they both started in the same update. 

At this point, I don't know if I should just do the search against rat and see if it ever finishes or what to do. I can't imagine it should take more than 16 hours because I've done similar searches before with no problems. I can go back to an earlier version and try it but I only have 3.1.4 and don't remember how far back it was that I searched rat successfully. 

The error at the end of the "completed" search is:

java.lang.NullPointerException
	at com.compomics.util.experiment.identification.identification_parameters.SearchParameters.toString(SearchParameters.java:949)
	at eu.isas.searchgui.SearchHandler.saveReport(SearchHandler.java:681)
	at eu.isas.searchgui.SearchHandler.searchCompleted(SearchHandler.java:601)
	at eu.isas.searchgui.SearchHandler.access$5000(SearchHandler.java:56)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2489)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Angela

**Comment by hbarsnes** [comment]
Hi Angela,

Am I correct in guessing at you are using the enzyme set to either "unspecific" or "whole protein"? If so, the problem is the creation of the report file after the search has completed, as it tries to include the name of the enzyme used in this report and the two "enzymes" above do not have such a specific enzyme name. I will fix this and release a new version. Should be online shortly.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Angela,

SearchGUI v3.2.5 has just been released which should fix the problem. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
