### ISSUE TITLE
User defined PTMs are not backwards compatible

### ISSUE THREAD

**Issue by akwalker** [compomics/searchgui#134]
For a week, I've been trying to search a rat database with an mgf file that is ~100Mb with tandem and recently my searches won't finish. I would say that in the past they ran in half an hour or less but this time I have let them go for 2 days and they seem to be stuck at 67% in the GUI. 

Then this happens, the search window is unresponsive and I can't even use the Cancel button to stop the search. Tandem is showing in the process window, but is only using about 0-2% of my CPU. If I kill the SearchGUI process, the Tandem process jumps to 100% CPU. I only have 3.2.4 and 3.2.5 available and they both do this. 

I am getting data from an Orbitrap Fusion and converting the RAW file with Proteowizard as always. I have similar datasets in the past that worked and ran in maybe 30 minutes or less. It has been several months (and releases) since I've analyzed a complex sample but I'm sure others have and I don't see any issues posted.

I have tried:
- small fasta file with isolated protein complex (mgf ~20Mb)- works fine (~20 seconds)
- mgf file from previous experiment that worked previously - hangs
- reduced search parameters to a smaller search space (trypsin only, 2 mods, etc.) - hangs. 
- CLI - hangs
- Tandem command line - finishes
- Mascot - works fine
- new rat fasta file from Uniprot.org - hangs
- mgf file from new run today - hangs
- created search parameters from scratch - hangs

So in my hands, this version of SearchGUI can work on the small protein complexes but isn't  working for the sample from rat. 

Any suggestions? 
Angela

**Comment by hbarsnes** [comment]
Hi Angela,

Thanks for telling us about this. Can you send us your SearchGUI log file (Help > Bug Report)? It should be able to tell us what is going on.

Best regards,
Harald

**Comment by akwalker** [comment]
The only entry in the bug report is the xtandem command. There are no errors. It looks like it sends the command and then tandem starts but doesn't really do anything. The window just scrolls "G" along the left edge and nothing else. When I run tandem from the SG folder from the command line, it also scrolls that "G" and never finishes. 

I've narrowed it down to something in the parameter file. I started playing around with running tandem alone from the SG folder and from the tandem that I downloaded separately and using the tandem default_input.xml. Both ran fine until I used the parameters_searchGUI.xml file instead. 

I downloaded a fresh copy of SG, created a very basic parameter set, and it seems to be running. And interestingly, there is no scrolling "G" as it runs. Maybe that is some way it shows it is in error? 

Now I have to add back in my modifications and other settings and see if it continues to run OK. This time it finished in 18 minutes instead of sitting 3 days :-).

So the problem is solved, but I am still not sure what the cause was. Maybe something got corrupted in that parameter file and Tandem wasn't smart enough to send an error back so both were just stuck.

Angela

**Comment by hbarsnes** [comment]
Hi Angela,

Could you send me your SearchGUI parameter file that does not work? You'll find it in your user home folder under .compomics\identification_parameters.

Hopefully we'll be able to locate the problem by inspecting this file.

Best regards,
Harald

**Comment by akwalker** [comment]
I hope so. It was working this morning and I made a couple of changes to the settings and then it hung up again. I've tried to attach the one from this morning. 
Angela
[Jan 6 01.zip](https://github.com/compomics/searchgui/files/690489/Jan.6.01.zip)

**Comment by hbarsnes** [comment]
Hi Angela,

I can confirm that I see the same issue when using your search parameter file with my own unrelated mgf and FASTA files. So it's clearly linked with something in the search settings. I will have a closer look and get back to you as soon as possible.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Angela,

I located the problem and it's the user defined n-terminal modification without a specific target, i.e. "Carbamylation of peptide n-term". We seem to have changed something recently which broke the backwards compatibility of this specific type of user-defined modifications.

It is quite easy to fix on your end though. Simply open the user defined modification in the dialog where you initially created it and click OK to resave. It will then get the correct new format and you should be able to run your X!Tandem searches again.

We'll try to fix the backwards compatibility for the next release. I'll keep you posted.

Best regard,
Harald
