### ISSUE TITLE
Search for PTMs doesn't give any hits

### ISSUE THREAD

**Issue by 1Moe** [compomics/searchgui#135]
Hi all,

This is my first PTM monitoring experiment and would like to ask for some advice.
I've run a DDA time-course experiment to measure the formation of four specific PTMs (initial precursors of protein cross-links). I quenched the reaction so that the precursor adducts are stable. The sample is purified protein with a handful of minor contaminants. 

I'm pretty confident that some of the adducts have formed because of mass changes I observe in MS of the whole protein. I also observe cross-linking at later stages of the time time-trial. When I run searchgui/peptideshaker I do not get any hits for these modifications.

Perhaps I am not setting up the search correctly and I was wondering if you could give me some help on how to find these PTMs, especially with regards to 

1) search settings (e.g. how many variable mods at a time)
2) size of database (i.e. just the protein of interest or larger?)
3) peptideshaker confidence threshold (I know the protein, I just need to know the PTMs and their location)

I have attached a screenshot of my settings in SearchGui.
Cheers
Moe

![capture](https://cloud.githubusercontent.com/assets/12740165/21753353/4f4aa778-d650-11e6-80e7-0b1c5a05ec93.PNG)
)

**Comment by 1Moe** [comment]
quick update:

Problem solved, had the wrong modification setting:
As modification Type I had accidentally chosen "Protein N-term - Particular Amino Acid(s)" where I should have chosen "Particular Amino Acid"
 
Getting plenty of confident hits now

**Comment by hbarsnes** [comment]
Hi Moe,

Great! Always nice to see issues solve themselves even before we get the chance to look into them. ;)

Best regards,
Harald
