### ISSUE TITLE
Memory issues?

### ISSUE THREAD

**Issue by carlaurangasolis** [compomics/searchgui#137]
Hi is there some way of fixing these issues? I am trying to run 3-4 GB Orbitrap files on a server using SearchGUI and have no idea how to fix these memory issues. Thanks!

[hs_err_pid21910log.txt](https://github.com/compomics/searchgui/files/736679/hs_err_pid21910log.txt)
 
Best wishes.

**Comment by hbarsnes** [comment]
It seems like you're crashing your Java installation by using too much memory. Please ensure that you are not giving PeptideShaker more memory than it has available. How much memory does the server have? And what do you use for the Xmx variable when running the command line?

**Comment by hbarsnes** [comment]
Just noticed that this is when running SearchGUI and not PeptideShaker, is that correct? If so, which search engines are you using? MS-GF+ is the only one using Java, so if you avoid that one the Java memory issues should go away.

Also, please ensure that your spectrum input is peak picked if run in profile mode, as this will reduce the size of the files significantly.

**Comment by hbarsnes** [comment]
Hi Carla,

As I didn't hear back from you I assume you managed to resolve the issue? If not please let is know and we'll reopen the issue.

Best regards,
Harald

**Comment by carlaurangasolis** [comment]
Hi thank you, I did resolve the BLAST output issue. However on the protein
score issue, I did look at the Novor publication, and they compare the
score to the PEAKS algorithm score, which is a -10logP, but it is not
stated explicitly. I don't like to assume anything, so this is why I am
asking around. Again thank you!

Best wishes,

Carla
