### ISSUE TITLE
SearchGUI-3.2.5

### ISSUE THREAD

**Issue by carlaurangasolis** [compomics/searchgui#138]
Hi, I am not able to run SearchGUI, I get error messages. The files included in this issue are:  Parameter CLI (HCD_par.txt), the SearchGUI CLI  (L2_HCD_shCLI.txt), and the error file (L2_HCD_err.txt). Thank you in advance.

Best wishes,

Carla Uranga

[HCD_par.txt](https://github.com/compomics/searchgui/files/752734/HCD_par.txt)
[L2_HCD_err.txt](https://github.com/compomics/searchgui/files/752736/L2_HCD_err.txt)
[L2_HCD_shCLI.txt](https://github.com/compomics/searchgui/files/752741/L2_HCD_shCLI.txt)

**Comment by hbarsnes** [comment]
Hi Carla,

Does the outputfolder "/LUSTRE/curanga/proteomica/PeptideShaker-1.15.0/" exist? As it will not be created if it does not. Also, please make sure that you have writing privileges to this folder.

I'd also recommend using complete paths to the mgf and id parameter files.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Carla,

As I didn't hear back from you I assume you managed to resolve the issue? If not please let is know and we'll reopen the issue.

Best regards,
Harald
