### ISSUE TITLE
Total number of proteins

### ISSUE THREAD

**Issue by sudeep71** [compomics/searchgui#141]
Just a new user of this software. I have 28K uniprot ids and the decoy file has 56K. Now, when I look at result using peptide shaker, it just shows 11K ids? So how do I make it show all the 28K ids?

Thanks

**Comment by hbarsnes** [comment]
Hi,

I would recommend that you start by looking at our tutorials: https://compomics.com/bioinformatics-for-proteomics. These will hopefully provide you with the required background to better understand the output of PeptideShaker and how to interpret it. If anything it still unclear, please let us know and we'll do our best to help.

Best regards,
Harald

**Comment by mvaudel** [comment]
As a short complement to what Harald correctly pointed: for the sake of time and memory, the search engines have built-in score thresholds to avoid reporting completely incorrect matches. So if a protein does not match at least one spectrum with a minimal quality it will not be reported.

Hope this helps,

Marc
