### ISSUE TITLE
Splitting and Indexing .mgf files is not working correctly

### ISSUE THREAD

**Issue by AndreasISAS** [compomics/searchgui#145]
Hello!

I just encountered another problem by using SearchGui. I wanted to split
a huge .mgf file into several parts using the newest SearchGui version 3.2.14. It is splitting the files so far but at the point of "indexing" nothing happens anymore, the bar ist just not progressing. The program is not responding then anymore and I have to terminate it completly. I compared this with an older version (2.8.5) there its running just fine and > progressing right after the splitting. Is this already known?

Best regards
Andreas

ps.: this is what the bug report is telling me  

Reindexing: Insulin cytosolic fraction.mgf. (changes in the file detected)
Exception in thread "SplitThread" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.checkBounds(Unknown Source)
	at java.lang.String.<init>(Unknown Source)
	at uk.ac.ebi.pride.tools.braf.BufferedRandomAccessFile.getNextLine(BufferedRandomAccessFile.java:195)
	at com.compomics.util.experiment.io.massspectrometry.MgfReader.getIndexMap(MgfReader.java:235)
	at com.compomics.util.experiment.io.massspectrometry.MgfReader.splitFile(MgfReader.java:1015)
	at eu.isas.searchgui.gui.SearchGUI$104.run(SearchGUI.java:5592)

**Comment by hbarsnes** [comment]
Hi Andreas,

Thanks for telling us about this. To be honest we pretty much stay away from the mgf splitting as it can have a minor impact on the results (as each mgf file is processed separately by the search engines). Can I ask you where the mgf files comes from and why it's so big? And how big is it btw?

I've just tested the splitting though, and it still works fine on my side. Does it fail for all files on your side or just this particular one?

Best regards,
Harald

**Comment by AndreasISAS** [comment]
Hey Harald,

so far it fails for all splitting of .mgf files. I generate them with progenesis QI by exporting the ms/ms spectra from there. I do a filtering where I exclude all hits that are ranked in the ms/ms spectra 10 or higher to make searches faster and still not losing IDs.

Unfortunately I need to split those big .mgf files (this file here has a size of around 1.7 gb) because somehow our mascot search engine cannot handle .mfg files which are bigger than 1gb.

The .mgf files are made from high resolution mass spec .raw files with a long gradient (5h).

Best regards
Andreas
   
__________________________


Andreas Hentschel, M. Sc.
Research Associate Lipidomics

ISAS  e.V.
Otto-Hahn-Straße 6b
44227 Dortmund, Germany

P: +49 (0)2 31.13 92-4206 
F: +49  (0)2 31.13 92-4850
Andreas.Hentschel@isas.de
www.isas.de  
__________________________

Leibniz-Institut  für Analytische Wissenschaften – ISAS – e.V.
Bunsen-Kirchhoff-Straße 11 |  44139 Dortmund, Germany
Sitz / Register: Dortmund | Amtsgericht Dortmund VR  1724
Vorstand: Prof. Dr. Albert Sickmann | Prof. Dr. Norbert Esser | Jürgen  Bethke
__________________________





 Von:   Harald Barsnes <notifications@github.com> 
 An:   compomics/searchgui <searchgui@noreply.github.com> 
 Kopie:   AndreasISAS <andreas.hentschel@isas.de>, Author <author@noreply.github.com> 
 Gesendet:   08.05.2017 15:30 
 Betreff:   Re: [compomics/searchgui] Splitting and Indexing .mgf files is not working correctly (#145) 


Hi Andreas, 
Thanks for telling us about this. To be honest we pretty much stay away from the mgf splitting as it can have a minor impact on the results (as each mgf file is processed separately by the search engines). Can I ask you where the mgf files comes from and why it's so big? And how big is it btw? 
I've just tested the splitting though, and it still works fine on my side. Does it fail for all files on your side or just this particular one? 
Best regards,
 Harald

**Comment by hbarsnes** [comment]
Hi Andreas,

Would it be possible for you to share one of these mgf files with us so that we can try to reproduce the issue on our end?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Zip it first and then share via Dropbox or similar?

**Comment by mvaudel** [comment]
Hi Andreas,

Jens has a great cloud tool for sharing files :) In addition, can you send us the log of the tool?

Best regards,

Marc

**Comment by AndreasISAS** [comment]
Ok I will do this. So I am zipping right now, this takes one hour and I will ask Jens, but that I can do only from tomorrow. I will let you know as soon as I can :-)

Btw what log file exactly? The Bug report of SearchGui?

   
__________________________


Andreas Hentschel, M. Sc.
Research Associate Lipidomics

ISAS  e.V.
Otto-Hahn-Straße 6b
44227 Dortmund, Germany

P: +49 (0)2 31.13 92-4206 
F: +49  (0)2 31.13 92-4850
Andreas.Hentschel@isas.de
www.isas.de  
__________________________

Leibniz-Institut  für Analytische Wissenschaften – ISAS – e.V.
Bunsen-Kirchhoff-Straße 11 |  44139 Dortmund, Germany
Sitz / Register: Dortmund | Amtsgericht Dortmund VR  1724
Vorstand: Prof. Dr. Albert Sickmann | Prof. Dr. Norbert Esser | Jürgen  Bethke
__________________________





 Von:   Marc Vaudel <notifications@github.com> 
 An:   compomics/searchgui <searchgui@noreply.github.com> 
 Kopie:   AndreasISAS <andreas.hentschel@isas.de>, Author <author@noreply.github.com> 
 Gesendet:   08.05.2017 17:46 
 Betreff:   Re: [compomics/searchgui] Splitting and Indexing .mgf files is not working correctly (#145) 


Hi Andreas, 
Jens has a great cloud tool for sharing files :) In addition, can you send us the log of the tool? 
Best regards, 
Marc

**Comment by mvaudel** [comment]
In SearchGUI, you will find the log under the _Help_ -> _Bug Report_ menu.

**Comment by hbarsnes** [comment]
> In SearchGUI, you will find the log under the Help -> Bug Report menu.

@mvaudel He already sent us the bug report. See the first message above. :)

**Comment by mvaudel** [comment]
Ooops, sorry @AndreasISAS, doing too many things at the same time!

**Comment by AndreasISAS** [comment]
No problem :-)

I uploaded the file, Jens is not here today so I did it my way, hope it is working for you. So just klick here

Best regards 
Andreas

   
__________________________


Andreas Hentschel, M. Sc.
Research Associate Lipidomics

ISAS  e.V.
Otto-Hahn-Straße 6b
44227 Dortmund, Germany

P: +49 (0)2 31.13 92-4206 
F: +49  (0)2 31.13 92-4850
Andreas.Hentschel@isas.de
www.isas.de  
__________________________

Leibniz-Institut  für Analytische Wissenschaften – ISAS – e.V.
Bunsen-Kirchhoff-Straße 11 |  44139 Dortmund, Germany
Sitz / Register: Dortmund | Amtsgericht Dortmund VR  1724
Vorstand: Prof. Dr. Albert Sickmann | Prof. Dr. Norbert Esser | Jürgen  Bethke
__________________________





 Von:   Marc Vaudel <notifications@github.com> 
 An:   compomics/searchgui <searchgui@noreply.github.com> 
 Kopie:   AndreasISAS <andreas.hentschel@isas.de>, Mention <mention@noreply.github.com> 
 Gesendet:   08.05.2017 20:43 
 Betreff:   Re: [compomics/searchgui] Splitting and Indexing .mgf files is not working correctly (#145) 


Ooops, sorry @AndreasISAS, doing too many things at the same time!

**Comment by hbarsnes** [comment]
Hi Andreas,

Seems like the link to click got lost along the way. Can you try sharing it again?

Best regards,
Harald

**Comment by AndreasISAS** [comment]
Hi,

here is the Link again:  https://transferxl.com/08v4ZkZFwwHSP3

hope it works :-)

   
__________________________


Andreas Hentschel, M. Sc.
Research Associate Lipidomics

ISAS  e.V.
Otto-Hahn-Straße 6b
44227 Dortmund, Germany

P: +49 (0)2 31.13 92-4206 
F: +49  (0)2 31.13 92-4850
Andreas.Hentschel@isas.de
www.isas.de  
__________________________

Leibniz-Institut  für Analytische Wissenschaften – ISAS – e.V.
Bunsen-Kirchhoff-Straße 11 |  44139 Dortmund, Germany
Sitz / Register: Dortmund | Amtsgericht Dortmund VR  1724
Vorstand: Prof. Dr. Albert Sickmann | Prof. Dr. Norbert Esser | Jürgen  Bethke
__________________________





 Von:   Harald Barsnes <notifications@github.com> 
 An:   compomics/searchgui <searchgui@noreply.github.com> 
 Kopie:   AndreasISAS <andreas.hentschel@isas.de>, Mention <mention@noreply.github.com> 
 Gesendet:   09.05.2017 14:50 
 Betreff:   Re: [compomics/searchgui] Splitting and Indexing .mgf files is not working correctly (#145) 


Hi Andreas, 
Seems like the link to click got lost along the way. Can you try sharing it again? 
Best regards,
 Harald

**Comment by AndreasISAS** [comment]
https://transferxl.com/08v4ZkZFwwHSP3

**Comment by hbarsnes** [comment]
Hi Andreas,

Thanks for the file. I can confirm that I have the same error on my end. I will look into it in more detail and get back to you.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Andreas,

The problem was some strange end line characters that occurred at the end of _some_ of the lines in your mgf file, which caused issues for the indexing of the split files. I've now added a fix that seems to solve the problem and released a new version of SearchGUI (v3.2.17). If you still experience problems, please let us know and we'll reopen the issue.

Best regards,
Harald

PS: If Mascot does not support your big Progenisis mgf files have you considered using one of the search engines supported in SearchGUI instead? ;)

**Comment by AndreasISAS** [comment]
Hey there!

Just wanted to thank you for your effort in solving this problem that quickly =)
Its working now!

Best regards
Andreas
   
__________________________


Andreas Hentschel, M. Sc.
Research Associate Lipidomics

ISAS  e.V.
Otto-Hahn-Straße 6b
44227 Dortmund, Germany

P: +49 (0)2 31.13 92-4206 
F: +49  (0)2 31.13 92-4850
Andreas.Hentschel@isas.de
www.isas.de  
__________________________

Leibniz-Institut  für Analytische Wissenschaften – ISAS – e.V.
Bunsen-Kirchhoff-Straße 11 |  44139 Dortmund, Germany
Sitz / Register: Dortmund | Amtsgericht Dortmund VR  1724
Vorstand: Prof. Dr. Albert Sickmann | Prof. Dr. Norbert Esser | Jürgen  Bethke
__________________________





 Von:   Harald Barsnes <notifications@github.com> 
 An:   compomics/searchgui <searchgui@noreply.github.com> 
 Kopie:   AndreasISAS <andreas.hentschel@isas.de>, Mention <mention@noreply.github.com> 
 Gesendet:   10.05.2017 15:49 
 Betreff:   Re: [compomics/searchgui] Splitting and Indexing .mgf files is not working correctly (#145) 


Hi Andreas, 
The problem was some strange end line characters that occurred at the end of some of the lines in your mgf file, which caused issues for the indexing of the split files. I've now added a fix that seems to solve the problem and released a new version of SearchGUI (v3.2.17). If you still experience problems, please let us know and we'll reopen the issue. 
Best regards,
 Harald 
PS: If Mascot does not support your big Progenisis mgf files have you considered using one of the search engines supported in SearchGUI instead? ;)
