### ISSUE TITLE
java.lang.NullPointerException while running MSGF+ search

### ISSUE THREAD

**Issue by RiegardtJohnson** [compomics/searchgui#146]
Good day all, 

I am running an MSGF search with a particularly large dataset, and am experiencing errors with the output. It appears to finish the search perfectly fine, but is unable to write the results to the specified output folder. I used the following command to run the search:
java -Xmx50g -cp SearchGUI-3.2.18.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files /run/media/user/Data/rmj_proteomics/proteomics/RECONVERTED/ -output_folder /run/media/user/Data/rmj_proteomics/proteomics/nr_fungal_lin -id_params /run/media/user/Data/rmj_proteomics/nr_fungal.par -msgf 1 -msgf_folder /run/media/user/Data/rmj_proteomics/SearchGUI-3.2.18/resources/MS-GF+/ -threads 23 
The report looks perfectly normal, and it appears that the search is completed, but the output files are not written:

MS-GF+ Beta (v10282) (12/19/2014)
Loading database files...
Loading database finished (elapsed time: 400.31 sec)
Reading spectra...
Ignoring 0 profile spectra.
Ignoring 0 spectra having less than 10 peaks.
Reading spectra finished (elapsed time: 407.14 sec)
Using 24 threads.
Search Parameters:
	PrecursorMassTolerance: 10.0ppm
	IsotopeError: 0,4
	TargetDecoyAnalysis: false
	FragmentationMethod: HCD
	Instrument: QExactive
	Enzyme: Tryp
	Protocol: Standard
	NumTolerableTermini: 2
	MinPeptideLength: 8
	MaxPeptideLength: 45
	NumMatchesPerSpec: 10
Spectrum 0-44937 (total: 44938)

pool-1-thread-20: Database search finished (elapsed time: 48257.00 sec)
pool-1-thread-20: Computing spectral E-values...
pool-1-thread-21: Computing spectral E-values... 53.4% complete
pool-1-thread-20: Computing spectral E-values... 53.4% complete
pool-1-thread-21: Computing spectral E-values finished (elapsed time: 204.00 sec)
pool-1-thread-20: Computing spectral E-values finished (elapsed time: 201.00 sec)
Writing results...
java.lang.NullPointerException
	at edu.ucsd.msjava.mzid.MZIdentMLGen.getDBSequence(MZIdentMLGen.java:544)
	at edu.ucsd.msjava.mzid.MZIdentMLGen.getPeptideEvidenceList(MZIdentMLGen.java:500)
	at edu.ucsd.msjava.mzid.MZIdentMLGen.addSpectrumIdentificationResults(MZIdentMLGen.java:251)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:413)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:142)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:80)

Wed May 31 23:45:54 CAT 2017        MS-GF+ finished for D:\rmj_proteomics\proteomics\RECONVERTED\RJ_FC1_SCE_170317060502.mgf (13 hours 36 minutes 37.0 seconds).

Wed May 31 23:45:58 CAT 2017        Could not find MS-GF+ result file for RJ_FC1_SCE_170317060502.mgf.
Wed May 31 23:45:58 CAT 2017        Zipping output files.

Wed May 31 23:46:05 CAT 2017        Search Completed (13 hours 36 minutes 48.0 seconds).

Please advise on how to resolve this issue.

Kind regards, 
Riegardt Johnson

**Comment by hbarsnes** [comment]
Hi Riegardt,

It seems like MS-GF+ is having a problem with the creation of the mzIdentML output file. Do you get the same error for other smaller files with the same command line or is it only occurring with this big dataset?

As the error happens inside the MS-GF+ code I'm afraid there is not a lot we can do on our side. Have you tried contacting the [MS-GF+ developers](https://github.com/sangtaekim/msgfplus)? I just noticed that they are now on GitHub and have become open source.

I also noticed that they have a newer version released compared to the one included in SearchGUI. You may therefore also want to try updating the version in SearchGUI (just replace the MSGFPlus.jar file in the resources\MS-GF+ folder) to see of that helps. If nothing else, it will at least ensure that the MS-GF+ error message refers to the correct line number in the new code. So I'd recommend trying this before contacting the MS-GF+ developers.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Riegardt,

I see that you have set up the issue in the [MS-GF+ issue tracker](https://github.com/sangtaekim/msgfplus/issues/13). I will therefore close it as a SearchGUI issue, but please feel free to reopen it if this turns out to be something that can be solved in SearchGUI after all.

Best regards,
Harald
