### ISSUE TITLE
De novo sequencing 

### ISSUE THREAD

**Issue by fazeliniah** [compomics/searchgui#147]
Hi 
I have few questions regarding the de novo sequencing options in searchgui:
1- Is it correct to assume that the de novo sequencing is only performed on unassigned spectra?
2- Can I use peptideshaker to visualize de novo matches and view the spectrum?
3- What is the proper way to produce the list of de novo peptides for Blast? What tools can I use for automatic blast search of de novo peptides. 
4- In what scenarios it is preferable to use DeNovogui (and not searchgui)? 
Thanks for your help in advance.
H

**Comment by hbarsnes** [comment]
Hi H,

> 1- Is it correct to assume that the de novo sequencing is only performed on unassigned spectra?

No, the de novo algorithms process all the spectra as for the search engines. But the hope is of course that the de novo algorithms will be able to identify spectra that the search engines do not. If you want to process only the unassigned spectra with de novo you can export such spectra via Export > Follow Up Analysis in PeptideShaker.

> 2- Can I use peptideshaker to visualize de novo matches and view the spectrum?

Yes, as long as the de novo search is carried out via SearchGUI this should be straightforward. However, this feature is still in development and will hopefully further improve in future versions of PeptideShaker.

> 3- What is the proper way to produce the list of de novo peptides for Blast? What tools can I use for automatic blast search of de novo peptides.

For creating the list I would recommend having a look at the BLAST export option in DeNovoGUI. As for the automatic BLAST search we use https://blast.ncbi.nlm.nih.gov/Blast.cgi, which is also directly accessible from DeNovoGUI by clicking the search icon at the end of a row in the De Novo Matches table.

> 4- In what scenarios it is preferable to use DeNovogui (and not searchgui)?

It all depends on your use case. If you don't plan on loading the results in PeptideShaker and inspect the findings at the protein level (and/or compare it with the output from standard search engines), I would recommend going with DeNovoGUI. As then you get to inspect the de novo results in detail without having to map them to a list of known protein sequences. On the other hand, if you have such a list of protein sequences, then PeptideShaker would be the simplest option. The difference is mainly in how the results are presented, the actual de novo sequencing is identical for both tools.

Best regards,
Harald
