### ISSUE TITLE
Comparing two TMT experiment

### ISSUE THREAD

**Issue by MBeyens** [compomics/searchgui#148]
Dear

First, thank you for the wonderful tools you provide. I am playing around with some test TMT labelled data and I am learning a lot using the different provided tools!
 
But I have one question, I was wondering if it might be possible to compare two different TMT experiment, as such performing a interrun differential analysis on both sample sets.

**Experimental design (TMT sixplex data)**
_TMT labeling run 1:_ Xa1, 126; Xa2, 127; Xa3, 128; Ya1, 129; Ya2, 130; Ya3, 131
_TMT labeling run 2:_ Xb1, 126; Xb2, 127; Xb3, 128; Yb1, 129; Yb2, 130; Yb3, 131

I want to compare the replicates of TMT run 1 (eg. Xa1-2-3) with the replicates of TMT run 2 (eg. Xb1-2-3). Problem, I cannot analyse both runs together via Peptide Shaker, as the samples have the same TMT label... So I performed the analyse on every run individually using SearchGUI, Peptide Shaker and Reporter. But now using Reporter it is only possible to compare within one TMT labelling set (thus run), and this comparison has no biological relevance in the test datasets as it are different tissues. How would you solve this problem?

Thank you in advance

Kind regards

Matthias

**Comment by hbarsnes** [comment]
Hi Matthias,

Thank you for the kind words about our tools! :)

Comparison across datasets is something that has been on our TODO list for quite a while, but we have not yet found the time to implement it. At the moment your best option would therefore be to process the two datasets separately, export the suitable reports from Reporter (i.e. at the protein, peptide or PSM level) and then compare those reports, for example in Excel. If doing this at the protein level you have to be careful with how you handle the protein groups though!

@mvaudel has some experience in combining reports from Report, so he might be able to give you some additional tips.

Best regards,
Harald

**Comment by MBeyens** [comment]
Thank you for your fast reply!

OK, so you would compare on peptide level? Do you have any idea what kind of ratio I need to compare with. At the moment I'm trying to figure out what all these Reporter generated ratios mean (not so easy without wiki). 
Nevertheless, I am also looking forward to the reply of your colleague. 

Best regards
Matthias

**Comment by hbarsnes** [comment]
Hi Matthias,

Sorry for the later reply. I was hoping @mvaudel would reply. :)

> OK, so you would compare on peptide level?

Yes, that would be recommended.

> Do you have any idea what kind of ratio I need to compare with.

Generally I would used the normalized ratios, unless you want to do the normalization yourself.

> At the moment I'm trying to figure out what all these Reporter generated ratios mean (not so easy without wiki).

Let us know if you have any specific questions about the columns in the export and we'll try to provide the documentation. The wiki will come later, as soon as we move the tool from the beta stage. :)

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Matthias,

As we didn't hear back from you I assume that you managed to get the required information from the peptide exports and was able to compare your TMT experiments?

I will therefore close this issue, but please don't hesitate to reopen it, or set up a new one, if you have more questions.

Best regards,
Harald
