### ISSUE TITLE
Top-Down Proteomics Searches in SearchGUI

### ISSUE THREAD

**Issue by lparsons42** [compomics/searchgui#149]
Earlier versions of SearcGUI (for example 3.1.4) had "Top-Down" as an enzyme choice when configuring the search.  I don't see this any more in newer versions (such as 3.2.20).  Is there still a way to use SearchGUI to search through top-down proteomics data?  It does not appear that setting "Digestion" to "Whole Protein" gives parameters that make sense for top-down, unless I am misreading some of them.

thank you
Lee

**Comment by hbarsnes** [comment]
Hi Lee,

Setting "Digestion" to "Whole Protein" should be equivalent to the old "Top-Down" option. We simply renamed it when reformatting and extending our enzyme support. But it could be that we made some errors during the updating of the code. Are there any particular parameters you think are incorrect for top down searches when using the "Whole Protein" option?

Best regards,
Harald

**Comment by lparsons42** [comment]
Thank you Harald I saw that option and was wondering if that was what I needed.  One setting that I am not sure of yet is the "peptide length" setting as Top Down can effectively produce much longer peptides than Bottom Up.  I have some Top Down data from a recently published paper that I will put through SearchGUI soon to see if we can match their published interpretation or what would need to be changed in order to do so.  

thank you!
Lee

**Comment by hbarsnes** [comment]
Hi Lee,

Note that the peptide length settings are not automatically changed according to the selected digestion type and would thus have to be changed separately. But I would assume that most search engines would disregard the peptide length settings when the top down option is selected. This would have to be verified for each search engine though. We don't have a lot of experience with top down data ourselves, so we very much appreciate your testing. Keep us posted. :)

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Lee,

As I didn't hear back from you I assume that your top down searches went ok? I will therefore close the issue, but please don't hesitate to reopen it if you still experience any problems with the top down option.

Best regards,
Harald
