### ISSUE TITLE
Fasta file format

### ISSUE THREAD

**Issue by talpa25** [compomics/searchgui#150]
Dear devs,

i have a self-made non-complete covered pisum database from RNA-seq. Some Proteins contain gaps in their sequence. How can i format the Fasta file best for peptide shaker? Are there any special characters allowed in the fasta file for search-gui?

best and thanx in advance

**Comment by mvaudel** [comment]
Hi,

In general search engines don't cope well with sequence gaps. If gaps represent undefined number of amino acids it is best to give the different sequence fragments as individual sequences in the fasta file with each having a unique identifier. If you know the number of undefined amino acids, you can put an 'X' for each of them and the software will try all possibilities up to a certain number of Xs in the sequence. Note that the latter will induce longer computation times and higher chances of false positive identification.

When working with home made databases, please note that search engines have hard coded requirements on the format of the fasta file headers, you will find more help on this here:
http://compomics.github.io/projects/searchgui/wiki/databasehelp.html#non-standard-fasta

Hope this helps,

Marc

**Comment by hbarsnes** [comment]
Issue assumed solved. If this is not the case, please let us know and we'll reopen the issue.
