### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by tivdnbos** [compomics/searchgui#151]
Hi,

If I run in SearchGUI a spectrum file against a big fasta file (containing generic headers and short (peptide) sequences), my VM goes out of memory. 

Fasta-file: 7.5GB, containing generic headers and short (6-30AA) peptide sequences
VM: 16 cores, 117GB RAM (of which 115GB assigned to SearchGUI), Ubuntu 16.10.
When SearchGUI tries to import the database (before the actual search), it takes 61GB of RAM on my machine; when I adjust the advanced settings, it goes up to 90GB of RAM; and when I than start the search (X!Tandem), it takes the full 115GB of RAM and extra in my swap until it runs out of memory.
Do you know how to resolve this?

Best,
Tim

**Comment by mvaudel** [comment]
Hi,

Sorry to read that you are experiencing memory issues. It is not clear to me how the index of the 7.5GB file can take up to 60 GB of RAM. We have tested our tools on quite large fasta files and never observed this. We are currently refactoring this code anyway so hopefully the problem will disappear.

X!Tandem is usually not memory hungry. Can you check whether it was the SearchGUI or the X!Tandem processes that were using all the RAM?

Apologies for the inconvenience,

Marc

**Comment by tivdnbos** [comment]
Hi, 

Thanks, no apologies :) I'll redo the search when I have a slightly smaller database (I estimate 6 GB), hopefully today, and I'll let you know! But, the X!Tandem run was without refinement (second) search, so that should have even a smaller memory usage.

Best, 
Tim

**Comment by tivdnbos** [comment]
Hi, 

My VM was upgraded to 197GB RAM, and again, during the import of the database SearchGUI took up to 70GB RAM, and afterwards (when adjusting the advanced settings) up to 100GB RAM. Next, I started the search and the spectrum-to-sequence matching (111688 ks modelled) took up to 172GB RAM (of which 100GB RAM for SearchGUI + 72GB RAM for X!Tandem).

Best, 
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

> UPDATE: It crashed during PeptideShaker analysis... So, I've upgraded my VM to 300G RAM, of which 295G RAM assigned to PeptideShaker - I'll let you know the result!

Any updates on this one? Can we close the issue?

Best regards,
Harald

**Comment by tivdnbos** [comment]
Hi, 

I still have this issue, but after a skype call with Marc we think it should be fixed with the new version of PeptideShaker. When this version is out, I'll let you know of course.

Best, 
Tim

**Comment by mvaudel** [comment]
And we made some good progress on the new version, should have something to test in the coming weeks/months :)

**Comment by hbarsnes** [comment]
This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue and letting us know. :)

**Comment by hbarsnes** [comment]
Issue assumed resolved with the release of the new versions. If this is not the case, please let us know and we'll reopen the issue.
