### ISSUE TITLE
Isotopes and X!Tandem

### ISSUE THREAD

**Issue by AlexandreBurel** [compomics/searchgui#156]
Hi guys !

I have a problem when I run X!Tandem with SearchGUI, I always get a few PSMs with a delta of 1 or 2 (XTandem documentation defines it as "the spectrum mh minus the calculated mh").
In the general settings of SearchGUI, I have set the Isotopes min and max to 0 but it changes nothing.

I looked over the X!Tandem parameters and I did not see anything like that (min and max), there's only a "spectrum, parent monoisotopic mass isotope error" (yes or no) : http://www.thegpm.org/tandem/api/spmmie.html
When I run X!Tandem with this parameter at "no", I have the results I'm expecting (deltas in the tolerance I have set).

Is it possible to add this setting to the specific X!Tandem settings dialog box ?

Otherwise, great work you have made here :-)

**Comment by hbarsnes** [comment]
Hi Alexandre,

Thanks for telling us about this. I've had a look at our code and noticed that we always set this parameters to "yes" and that it currently cannot be altered by the user. We will add support for changing this parameter in the next SearchGUI release in the advanced X!Tandem settings.

I will let you know when the new version is available. It may take some time though as we are in the middle of a large improvement of the backend code that we first have to complete.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Alexandre,

This issue has now finally been solved with the new beta releases of SearchGUI and PeptideShaker. Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

Best regards,
Harald

**Comment by AlexandreBurel** [comment]
Great news, thank you guys :)
