### ISSUE TITLE
Problem in making decoy database with "*" symbol

### ISSUE THREAD

**Issue by UKQIDA** [compomics/searchgui#160]
Hi,
When making a decoy database with searchCLI (v3.2.20), it gave the following error:

Running SearchGUI decoy function using the following command:
java -Djava.awt.headless=true -cp D:\proteoannotator\ProteoAnnotator-1.7.86\mzid
lib-1.7\searchgui\SearchGUI-3.2.20.jar eu.isas.searchgui.cmd.FastaCLI -in D:\pro
teoannotator\pa_test\withmsgf1\PXD000548_withmsgf_combined.fasta -decoy
Reindexing: PXD000548_withmsgf_combined.fasta.
java.lang.IllegalArgumentException: An error occurred while parsing the sequence
 of A_ENSP00000431089 at line 9: java.lang.IllegalArgumentException: No amino ac
id found for letter *.
        at com.compomics.util.experiment.identification.protein_sequences.Sequen
ceFactory.createFastaIndex(SequenceFactory.java:780)
        at com.compomics.util.experiment.identification.protein_sequences.Sequen
ceFactory.getFastaIndex(SequenceFactory.java:708)
        at com.compomics.util.experiment.identification.protein_sequences.Sequen
ceFactory.getFastaIndex(SequenceFactory.java:638)
        at com.compomics.util.experiment.identification.protein_sequences.Sequen
ceFactory.loadFastaFile(SequenceFactory.java:579)
        at eu.isas.searchgui.cmd.FastaCLI.call(FastaCLI.java:108)
        at eu.isas.searchgui.cmd.FastaCLI.<init>(FastaCLI.java:59)
        at eu.isas.searchgui.cmd.FastaCLI.main(FastaCLI.java:218)
SearchGUI decoy function finished.

The input fasta file contain lines such as:
>generic|A_ENSP00000431089|
*LR*L
>generic|A_ENSP00000428393|
*LQ*L
>generic|A_ENSP00000427969|
RIL*WW*LLL
>generic|A_ENSP00000429952|
VLL***WLLL

Running the much older version didn't gave such errors.

Thanks,
Da

**Comment by hbarsnes** [comment]
Hi Da,

I'm afraid you'll have to remove the stars before giving the FASTA file to SearchGUI. The reason being that these cannot be converted to specific amino acids and wildcards are not supported. In older versions I think we used to silently delete them, but we figured out that this might not be the best solution as it hid the underlying issue from the user, especially when the stars have specific meaning, e.g. representing stop codons when doing translation.

Best regards,
Harald

**Comment by UKQIDA** [comment]
Thanks for the explanation. We will change our code then.

**Comment by hbarsnes** [comment]
Note that if the stars do represent wildcards, you could consider replacing them with X's. Adding wildcards will however impact the mapping of the peptides to the proteins and to some extent slow down the processing.

I will now close the issue, but don't hesitate to reopen it if you have more related questions.
