### ISSUE TITLE
FATAL: Error reading index (fasta-index/pepix)

### ISSUE THREAD

**Issue by microalgues** [compomics/searchgui#161]
Good morning,
I have a problem with Comet and Tide. Attached is one of error's report.
What can I do?
Thanks in advance,
Xavier

[report.txt](https://github.com/compomics/searchgui/files/1677632/report.txt)

**Comment by hbarsnes** [comment]
Hi Xavier,

From the error report it seems like Comet is completing fine? Have you tried running Comet on its own?

As for Tide, I have no idea what the fasta-index/pepix is, and as this error happens inside Tide (and not inside the SearchGUI code itself) there is not much we can do from our end. If the error is consistent I'd recommend contacting the Tide developers directly: https://groups.google.com/forum/#!forum/crux-users.

Best regards,
Harald

**Comment by microalgues** [comment]
Hi Harald,
Running Comet on its own works fine. With Tide I couldn't finish the analysis because my computer crashed. Anyway, the point is that I am not able to complete a single analysis with all search algorithms at the same time. I got a new fail (I excluded Comet and Tide).

- Wed Jan 31 11:05:37 CET 2018        Zipping output files.
- Wed Jan 31 11:05:58 CET 2018        Processing identification files with PeptideShaker.
- Wed Jan 31 11:08:23 CET 2018        PeptideShaker processing canceled. See the PeptideShaker log for details
- Wed Jan 31 11:08:24 CET 2018        Search Canceled!
- Wed Jan 31 11:08:24 CET 2018        Error: Stream closed
- Wed Jan 31 11:08:24 CET 2018        An error occurred while running SearchGUI. Please contact the developers.
- Wed Jan 31 11:08:24 CET 2018        The search or processing did not finish properly!

The search was canceled and after that I tried to open the search files(zip) from PeptideShacker but it didn't work.
Do you have any suggestion?

[report3.txt](https://github.com/compomics/searchgui/files/1686021/report3.txt)

With thanks,
Xavier

**Comment by hbarsnes** [comment]
Hi Xavier,

The "Error: Stream closed" error is a bit strange. Do you run SearchGUI/PeptideShaker on a distributed system or a system where automatic backups are occurring which could result in the file system changing during the processing of the files?

I also note that the MyriMatch search does not seem to complete? At least there is no output file: "Could not find MyriMatch result file for 20140621_E_ULG_PC_LC_0002_iTRAQ_R1_membranaires_Trinity_MGFPeaklist.mgf". Perhaps try without MyriMatch as well?

As for why PeptideShaker is failing I would need the PeptideShaker log file. You'll find this file in the PeptideShaker-1.16.15\resources folder. The file is called PeptideShaker.log.

Best regards,
Harald

**Comment by microalgues** [comment]
Hi Harald,

I think there is not automatic backups in my system, which is Ubuntu 16.04.
This time I have tried with X!Tandem, MS Amanda, MS-GF+, OMSSA and Comet.
For me it looks OK, but some messages are given after MS Amanda running (Am I running short of memory/threads?):
- Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

And I got with Comet:
- Load spectra:Error - spectrumNativeID filter larger than 256 characters. 
 6940

Are this analysis OK? Should I trust these results?
Thank you so much,
Xavier

[report4.txt](https://github.com/compomics/searchgui/files/1698827/report4.txt)

**Comment by hbarsnes** [comment]
Hi Xavier,

Seems like Mono is having problems. I recommend contacting the MS Amanda developers directly: https://groups.google.com/forum/#!forum/msamanda.

Same goes for the warning from Comet: https://groups.google.com/forum/#!forum/comet-ms, as it seems to be kicking out 6940 of your spectra. But you could also try shortening the spectrum titles in your mgf file to see if that helps?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Xavier,

As the issues seem to all stem from the search engines and not from SearchGUI itself, I will now close the issue. But please feel free to reopen it (or create a new one) if you still think the problems can be fixed with changes in SearchGUI.

Best regards,
Harald
