### ISSUE TITLE
SearchGUI for peptidomics 

### ISSUE THREAD

**Issue by sgielis** [compomics/searchgui#164]
Dear all,

I was wondering if it is possible to use SearchGUI and PeptideShaker for peptidomics experiments.
I would like to identify peptides based on a database containing peptide sequences. Hence, no 
further in silico (enzyme) digestion is wanted. Can I do this by setting the digestion to 'Whole Protein'?

Best regards,

Sofie

**Comment by hbarsnes** [comment]
Hi Sofie,

I know that other users have used SearchGUI and PeptideShaker for peptidomics experiments, but I'm unsure how successful it has been given that the search engines are generally made for searching against protein sequence databases. Choosing "Whole Protein" as the digestion would be the correct setting though. Note that some search engines may cope better with peptidomics data than others, so be sure to test more than one search engine and compare the results.

Best regards,
Harald

**Comment by sgielis** [comment]
Hi Harald,

Thank you for the answer!

I have another small question concerning peptidomics and in silico digestion steps.
Often, unspecific cleavage/no enzyme specificity is chosen to digest protein databases. 
I was wondering how SearchGUI carries out this unspecific digestion. Does it give all the possible peptides for every protein or does it apply a random cleavage that is different every time you use this option?

Kind regards,

Sofie

**Comment by hbarsnes** [comment]
Hi Sofie,

> I was wondering how SearchGUI carries out this unspecific digestion.

SearchGUI is simply a wrapper for the different search engines, and it's up to the search engines how they implement the unspecific digestion (and all the other search options). We don't have much experience with unspecific digestion ourselves, but I would imagine that most (hopefully all) of the search engines inspect all possible peptides, as this is the only way in which the results will be consistent. The easiest way to test this is simply to run an unspecific digestion search multiple times (preferably for one search engine at the time) and see if you get the same results or not. Do note that unspecific digestion searches are generally rather time consuming though.

Best regards,
Harald

PS: I will now close this issue (as the initial question has been answered), but don't hesitate to open a new one if you have more questions.
