### ISSUE TITLE
Edit button on SearchGUI Search Settings is not functioning

### ISSUE THREAD

**Issue by umihairunanis** [compomics/searchgui#166]
Hi,

I seem to have a problem with the Search Settings. I cannot add or edit Spectrum matching at identification settings. Hope you can help me to solve this issue.

Thanks.

Regards,
Anis
![capture](https://user-images.githubusercontent.com/37907832/38098540-eadeacf8-33aa-11e8-8bc8-709274e3e694.JPG)

**Comment by umihairunanis** [comment]
Hi,

Here is the log of the tool.
[SearchGUI 3.2.20 log.txt](https://github.com/compomics/searchgui/files/1862410/SearchGUI.3.2.20.log.txt)

Thanks.

Anis

**Comment by mvaudel** [comment]
Hi again,

I see that you are using an older version of the tool. Can you try to update to the latest version and see if the problem persists?

Hope this helps,

Marc

**Comment by volkyx** [comment]
I got the similar problem and solved that way. 
Go to your user folder and find .compomics folder. In the .compomics folder remove ptmFactory-4.12.1.json file. Restart the SearchGUI. It should work now. 
Just check your settings again if everything set.

Best
Volkan

**Comment by umihairunanis** [comment]
Thanks for your help!

I've settled the problem too.

Regards,
Anis
