### ISSUE TITLE
searchgui_out not showing search engine results

### ISSUE THREAD

**Issue by antortjim** [compomics/searchgui#167]
I have tried to reproduce part 1.3 of the CompOmics tutorial, available at https://drive.google.com/open?id=0B4sW8rLWPbRyaDBXMDVXOWVaUkk by using the SearchGUI CLI. But my searchgui_out.zip only contains the `.par` file (listing the parameters of the run) and `searchGUI_input.txt` (listing the provided spectrum files). Why isn't the output of the Search Engines included? It is included when ran from GUI.

This is how I ran the program:
`java   -Djava.awt.headless=true -cp ~/opt/SearchGUI-3.2.23/SearchGUI-3.2.23.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files qExactive01819.mgf -output_folder results -id_params tutorial.par`

- I added the `-Djava.awt.headless=true` as instructed following issue #86 (I also got the same error).
- The params file was generated using 
`java -cp ~/opt/SearchGUI-3.2.23/SearchGUI-3.2.23.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out tutorial -db uniprot-human-reviewed-april-20178.fasta -enzyme 'Trypsin' -specificity '0' -fixed_mods 'Carbamidomethylation of C' -variable_mods 'Oxidation of M' -mc '2' -prec_tol '10' -frag_tol '0.02' -fi 'b' -ri 'y'`. The flags should follow what was instructed to do in the tutorial using the GUI.
- The database and the spectrum were downloaded from the link available in resources in part 1.3 https://drive.google.com/file/d/0B4sW8rLWPbRydlFNWEthX1hLUEk/view

I tried manually providing the xtandem_folder using the path saved in the GUI under Edit > Software Locations (I added the flag `-xtandem_folder "$HOME/opt/SearchGUI-3.2.23/resources/XTandem/linux/linux_64bit"`) but still no result. Remarkably, the CLI run was instantaneous, whereas it takes ~30 for the GUI, which indicates that the search engines are probably not being called.

```
Tue Apr 24 11:37:02 CEST 2018 Validating MGF file: qExactive01819.mgf

Tue Apr 24 11:37:02 CEST 2018 Indexing spectrum files.
Tue Apr 24 11:37:02 CEST 2018 Extracting search settings.



Processing: qExactive01819.mgf (1/1)
Tue Apr 24 11:37:02 CEST 2018 Zipping output files.

10% 20% 30% 40% 50% 60% 70% 80% 90%
Tue Apr 24 11:37:02 CEST 2018 Search Completed (93.0 milliseconds).



Search Completed.
```

I am running this on a Ubuntu 16.04 with Java version 1.8.0_161

**Comment by hbarsnes** [comment]
Hi,

You need to turn on the search engines you want to run via the search engine specific options, e.g. for X! Tandem you add "-xtandem 1". See https://github.com/compomics/searchgui/wiki/SearchCLI for more details.

BTW, I'd also recommend using complete paths when referring to files or folders.

Best regards,
Harald

**Comment by antortjim** [comment]
Hi

Right! I checked that section and I misread the default thinking they were all ON by default. :man_facepalming: :man_facepalming:  Thanks for your help! I will take care of the paths too. :grinning: 

Best
Antonio
