### ISSUE TITLE
Validation fails for .MGF files

### ISSUE THREAD

**Issue by pieeye75** [compomics/searchgui#168]
When using Search GUI 3.2.22, 23 or 24 the validation of the MGF fails with the following error;  "An error occurred while validating the MGF file: null"
I do not get this error if there is a *.cui present that was created with an earlier version of Search GUI. I'm assuming the search works, but I have not tested this.

The MGF was created using AB_SCIEX_MS_Converter.exe. I see the error using both Win 7 and Win server 2012 R2 environments. Both are 64-bit systems. The same files are fine when I use v3.2.20 or earlier.

The log for both systems is attached.
[SearchGUI 3.2.24 log_win7.txt](https://github.com/compomics/searchgui/files/1949150/SearchGUI.3.2.24.log_win7.txt)
[SearchGUI 3.2.24 log_Winserver2012.txt](https://github.com/compomics/searchgui/files/1949151/SearchGUI.3.2.24.log_Winserver2012.txt)

A dropbox link to 2 MGFs that fail validation is below.

https://www.dropbox.com/s/ctru0xxfeyt3642/SGUI_MGF.zip?dl=0

thanks

**Comment by hbarsnes** [comment]
Hi,

Thanks for telling us about this. The problem seems to be that your mgf files end with ".MGF" instead of ".mgf". We'll release new versions of SearchGUI and PeptideShaker that also supports the upper case version as soon as possible. In the meantime, please rename the file endings to lower case and you should be able to process the mgf files.

Best regards,
Harald

**Comment by pieeye75** [comment]
Ah, okay, we’ve this problem in the past, I didn’t even think about that. The Sciex software automatically uses uppercase for the extension.

Thanks

**Comment by hbarsnes** [comment]
Hi again,

We've just released a new version of SearchGUI that should fix the problem without the need to rename the mgf file endings. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
