### ISSUE TITLE
Old MS-GF+ version

### ISSUE THREAD

**Issue by chambm** [compomics/searchgui#172]
Is there a reason MS-GF+ was last updated in 2015?

**Comment by hbarsnes** [comment]
We kept updating it as long as Sangtae was working on it. After that we had some issues with the initial GitHub releases (from late 2017) and just never got around to testing the more recent releases. However, we happened to be testing the current MS-GF+ release just two weeks ago and the issues we had seem to have be resolved. We will do a bit more testing and hopefully include the latest version of MS-GF+ in the next SearchGUI release.

In the meantime you can always replace the MS-GF+ version in SearchGUI with the latest MS-GF+ version yourself. Unless the MS-GF+ command line has been altered it should just be a matter of replacing the content in the resources\MS-GF+ folder in SearchGUI, or if using the GUI use the Edit > Software Locations option and change the path for MS-GF+.

**Comment by hbarsnes** [comment]
Just released SearchGUI v3.3.0 updating MS-GF+ to the latest release. Everything seems to work fine (the only new parameter is the -task option), but please let us know if you come across any issues.
