### ISSUE TITLE
MyriMatch does support terminal modifications at specific amino acids

### ISSUE THREAD

**Issue by chambm** [compomics/searchgui#173]
MyriMatch's motifs allow specifying (via '!') where the mod occurs inside a motif:
DynamicMods = "(!Q * -17"
says that the N-terminus may be modified by -17 if the first AA is Q.

**Comment by hbarsnes** [comment]
So the same on the C-term would then be: `DynamicMods = "Q)! * -17"` right?

Is this also supported for the static modifications, e.g. `StaticMods = "(!Q -17"`?

A related question, is there a way to separate terminal modifications that only occur on the protein n-term from those occurring on the peptide n-term? At the moment we have to set protein n-term modifications as variable peptide n-term modifications for MyriMatch and then remove them in the post-processing.

And finally, where can we find the documentation of the command line options for MyriMatch?

**Comment by chambm** [comment]
> So the same on the C-term would then be: DynamicMods = "Q)! * -17" right?

Yes, but you don't need the '!' if the mod is to occur on the last character in the motif (which is most of the time of course).

> Is this also supported for the static modifications, e.g. StaticMods = "(!Q -17"?

Unfortunately no. The StaticMods syntax is much simpler because the underlying implementation is much simpler.

> A related question, is there a way to separate terminal modifications that only occur on the protein n-term from those occurring on the peptide n-term? At the moment we have to set protein n-term modifications as variable peptide n-term modifications for MyriMatch and then remove them in the post-processing.

Also unfortunately no. The mod motif only looks at the peptide sequence (with '(' and ')' at the termini). It doesn't consider the peptide's position in the protein.

> And finally, where can we find the documentation of the command line options for MyriMatch?

http://htmlpreview.github.io/?https://github.com/ProteoWizard/pwiz/blob/master/pwiz_tools/Bumbershoot/myrimatch/doc/index.html

**Comment by hbarsnes** [comment]
I've just released SearchGUI v3.3.1 which adds the supports for terminal modifications at specific amino acids for MyriMatch.

>> And finally, where can we find the documentation of the command line options for MyriMatch?
>
> http://htmlpreview.github.io/?https://github.com/ProteoWizard/pwiz/blob/master/pwiz_tools/Bumbershoot/myrimatch/doc/index.html

Is the same information also available for DirecTag? As I could not find a doc folder in the related DirecTag folder? (We used to refer users to http://fenchurch.mc.vanderbilt.edu/bumbershoot/directag.)

**Comment by chambm** [comment]
> Is the same information also available for DirecTag? As I could not find a doc folder in the related DirecTag folder? (We used to refer users to http://fenchurch.mc.vanderbilt.edu/bumbershoot/directag.)

It seems I never did a manual for DirecTag. Only for MyriMatch and TagRecon. This is the best reference for now: https://github.com/ProteoWizard/pwiz/blob/master/pwiz_tools/Bumbershoot/directag/directagAPIConfig.h - but er, it's missing comments. :)
