### ISSUE TITLE
can I get the protein expression level in searchGUI?

### ISSUE THREAD

**Issue by yekaizhou** [compomics/searchgui#174]
Hi Harald and Marc,
It is said that searchGUI and PeptideShaker are linked, and the protein expression level(MS2 quantification) will be shown in PeptideShaker. According to the manual, the PeptideShaker is just an visualization software, and it is searchGUI that do the calculation. So there ought to be MS2 quantification data in the output file of searchGUI? However, I cannot find these data in .xml(x!tandem is used). Do I missed something in the output file or the MS2 quantity is calculated in PeptideShaker?

Best regards
Yekai Zhou

**Comment by hbarsnes** [comment]
Hi Yekai,

PeptideShaker not only visualizes the search results from SearchGUI but also processes and merges the results from the different search engines. This includes taking the peptide-to-spectrum matches and figuring out which to trust and which not to trust (based in false discovery rate), and then performs protein inference to arrive at the list of the most likely proteins in the sample. Only then can the MS2 protein quantification be calculated, explaining why you don't find this information in the results from SearchGUI.

For more details I'd recommend taking a look at our tutorials: http://compomics.com/bioinformatics-for-proteomics

Best regards,
Harald

**Comment by yekaizhou** [comment]
Hi Harald,

Thanks a lot for replying to me! And our lab have decided to use PeptideShaker as the final weapon.

By the way, we are more interested in the quantity of proteins, but it seems that the MS2 quantification data analyzed in the software cannot be exported? There is all other data in the default protein report.xls but seems nothing about MS2 quantification.

Best regards,
Yekai Zhou

**Comment by hbarsnes** [comment]
Hi again,

The MS2 quantification values are in the default protein report. The column is called 'Spectrum Counting'. You can also get more details by setting up your own custom reports via 'Add new report type' in the bottom left corner of the 'Export Features' dialog.

See also Chapter 4.1 about Spectrum Counting in our tutorials: https://compomics.com/bioinformatics-for-proteomics/quantification/.

Best regards,
Harald

**Comment by yekaizhou** [comment]
Hi Harald,

I have tried to export the default protein report in CLI mode, but the file exported contains no data like this:
![image](https://user-images.githubusercontent.com/39112978/39858252-90d83f7e-5468-11e8-8476-a3334700b343.png)

and my command code looks like below: 
`java -cp PeptideShaker-1.16.22.jar eu.isas.peptideshaker.cmd.ReportCLI -in "/home/software/protemics/myCpsFile.cpsx" -out_reports "/home/software/protemics/" -reports "7" `

Best regards,
Yekai Zhou

**Comment by hbarsnes** [comment]
Hi Yekai,

The default protein report only includes proteins passing the validation threshold at 1% FDR. You can make your own custom reports that also includes the non-validated proteins, but I'd recommend first figuring out why you have no validated proteins.

Best regards,
Harald

**Comment by yekaizhou** [comment]
Hi Harald,

We employed iTRAQ to conduct our experiments and I think the parameters in .par file are set accordingly, and the .fasta is downloaded from the right web, so maybe the MS rawdata from iTRAQ is not validated, or there is something wrong in my operation?

PS: firstly searchGUI (x!tandem only) converted .mgf to .xml, then PeptideShaker further developed the .xml to .cpsx, finally the default protein data is reported.

Best regards,
Yekai Zhou

**Comment by hbarsnes** [comment]
Hi Yekai,

If you click the icons in the right-most column in the protein table in PeptideShaker you can see why the proteins where not validated.

Note that you need a target-decoy FASTA file (with the decoys added in SearchGUI) to validate the proteins via FDR in PeptideShaker.

Best regards,
Harald

PS: I assume you already looked at the tutorials? As most of this is explained in more detail there.
