### ISSUE TITLE
Request for supporting MSFragger

### ISSUE THREAD

**Issue by qi6** [compomics/searchgui#177]
Hi,
I am wondering if there is any plan for supporting MSFragger engine (Kong, 2017, Nature Methods)?
Thanks,
Qi

**Comment by mvaudel** [comment]
Hi,
Yes, we looked into it as soon as the paper was published, but currently their license does not allow us to integrate it. We are looking at alternatives for open modification search.
Hope you understand,
Marc

**Comment by qi6** [comment]
Thanks, mvaudel.

**Comment by qi6** [comment]
Hi Marc,
I am think is that possible for SearchGUI to provide APIs to integrate MSFragger, but does not include MSFragger software in SearchGUI releases. Instead, let the users to acquire MSFragger, then put the MSFragger in SearchGUI resources folder? I am not sure if this can compatible with MSFragger licence.
Thanks,
Qi

**Comment by mvaudel** [comment]
Hi Qi,

I am also not sure whether this is possible, we will investigate this. We have quite a long todo list so please be patient :-)

Thanks for the suggestion,

Marc
