### ISSUE TITLE
Simultaneous search of PTMs @ Residues AND @ Protein N-term

### ISSUE THREAD

**Issue by 1Moe** [compomics/searchgui#178]
Hi Marc and Harald, 
I'm sure this has been asked/ explained before but I couldn't find a solution.
I am interested in searching for PTMs on C, K, H AND protein-N-term.

I can only do C,K,H but I'm unsure how to include protein-N-term.
I assume that it can be defined in the "Type" and "Pattern" fields under the Edit Modification menu
How do I do this in SearchGui? Is this possible in the GUI or do I need to run it from commandline? Do I need to do separate searches? In general, how many PTMs do you search for simultaneously anyway?

Regards
Moe

**Comment by mvaudel** [comment]
Hi Moe,

If you set a an N-term modification with C, K, or H as pattern, the search engines will look for any protein N-term that ends with these amino acids. If you want to search for this modification on C, K, H, or protein N-term, then I would recommend building 4 modifications, one on C, on on K, one on H, and one on protein N-term, and search with all of them. 

We recommend running a single search with all modifications to give fair competition between the peptide candidates. You can do that in both GUI and command line mode. How many modifications to include is a tricky question: too many modifications will reduce your discrimination power through enlargement of the search space, while with too few modifications you might miss peptides or introduce false positives. The best is to use all modifications that are expected in your sample. If you are not sure about the modifications in the sample you can run an open space search (eg with MS-Fragger). If you have many modifications, using Percolator might help distinguishing the good ids from the rest.

These were not easy questions, hope it makes sense :-)

Marc

**Comment by 1Moe** [comment]
Thanks Marc,

I've got 3 PTMs as follows
+58 on C,K,H, N-term
+76 on K, N-term
+96 on K, N-term

Basically, this meant that I had to set up 6 modification in my search settings (I've attached a screenshot).

1. +58 on C,K,H
2. +58 on Protein N-term
3. +76 on K
4. +76 on Protein N-term
5. +96 on K
6. +96 on Protein N-term

Interestingly, I get slightly different PTM hits/IDs using the 6 mods compared with the 3 mod search (without the 3 N-term mods) but no additional hits - so far - on the N-term.

1. +58 on C,K,H
2. +76 on K
3. +96 on K

Any idea why?
Thanks again, much appreciated and very helpful!

![ptm settings](https://user-images.githubusercontent.com/12740165/40822156-027d48ba-65bf-11e8-8560-d6fff5f24d3e.PNG)

**Comment by mvaudel** [comment]
Hi,

My best guess is that adding additional modifications changes the distribution of scores, so the hits that are close to the threshold differ when searching with different sets of modifications. Did you try using Percolator for the validation of hits? It should be able to pick this up. The data would also improve if you have access to an instrument with higher resolution. 

Hope this helps,

Marc

**Comment by 1Moe** [comment]
Hi Marc,

I'm keen to give percolator a go, but have no experience with it. what's the workflow?
I've got my SearchGui and Peptideshaker project and just installed Percolator version 3.02.0, Build Date Feb  2 2018 09:19:12.

I've run the percolator example successfully https://github.com/percolator/percolator/wiki/Example
What input file(s) and command(s) do I use with SearchGui/PeptideShaker?

Thanks
Moe

**Comment by hbarsnes** [comment]
Issue assumed resolved with PeptideShaker v3.0.0. If this is not the case, please let us know and we'll reopen the issue.
