### ISSUE TITLE
Support for Andromeda on Linux

### ISSUE THREAD

**Issue by antortjim** [compomics/searchgui#179]
Hi there!

I wanted to report an error with the search engine **Andromeda**.
The line of the error is 
`Tue Jun 05 11:54:45 CEST 2018 Error: conf/databases.xml (No such file or directory)
`
**This error does not occur when running other search engines, for example msgf.** I have tried running SearchGui 3.3.1 and still the same error happens.
The mgf file is the same one used in the compomics tutorial (qExactive01819).
Hopefully it's a stupid error on my side, but I haven't been able to figure it out.
In case it's happening to more people, I am posting it here.

Thanks beforehand!

Best regards
Antonio

The system settings:
**OS**
`Ubuntu 16.04 64 bits`
**Java version**
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

```

This is the full SearchGUI log:
```
java -Djava.awt.headless=true -cp /home/antortjim/opt/SearchGUI-3.3.3/SearchGUI-3.3.3.jar eu.isas.searchgui.cmd.SearchCLI \ 
  -spectrum_files /home/antortjim/example/data/mgf/example.mgf \ 
  -output_folder /home/antortjim/example \ 
  -id_params /home/antortjim/example/settings/example.par \ 
  -output_data 1 \ 
  -andromeda 1

Tue Jun 05 11:54:44 CEST 2018 Validating MGF file: /home/antortjim/example/data/mgf/example.mgf
Tue Jun 05 11:54:45 CEST 2018 Andromeda configuration.

Tue Jun 05 11:54:45 CEST 2018 Error: conf/databases.xml (No such file or directory)
Tue Jun 05 11:54:45 CEST 2018 An error occurred while running SearchGUI. Please contact the developers.
java.io.FileNotFoundException: conf/databases.xml (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at java.io.FileWriter.<init>(FileWriter.java:90)
        at eu.isas.searchgui.processbuilders.AndromedaProcessBuilder.createDatabaseFile(AndromedaProcessBuilder.java:166)
        at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:1828)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Tue Jun 05 11:54:45 CEST 2018 The search or processing did not finish properly!
```

**Comment by hbarsnes** [comment]
Hi Antonio,

I'm afraid that Andromeda is only supported on Windows, hence it won't work on Ubuntu. The Andromeda developers are however working on a Linux version that works via Mono. It is still in beta testing though, but we'll include it in SearchGUI as soon as it becomes available.

Best regards,
Harald

**Comment by antortjim** [comment]
Hi Harald

That's fine, didn't know Andromeda is Windows only for now. Thanks for the update!
I guess we should leave the issue open until the Mono version is supported then :)

Thanks for your help.

Best regards,
Antonio

**Comment by chrishuges** [comment]
any update on this now that maxquant is released on Linux? Coming in the next release?

**Comment by antortjim** [comment]
The only "Linux version" of MaxQuant I have seen is supported only running Mono and using a GUI.

http://www.coxdocs.org/doku.php?id=maxquant:common:download_and_installation

Have you seen a version running on Linux natively (and with a CLI)? That would be amazing :o Even though I would still prefer the Compomics suite ;)

**Comment by chrishuges** [comment]
The link you posted also describes running maxquant from command line. There is no need to use the GUI.

Although, I am not sure if they have provided a standalone Andromeda for Linux yet. I will investigate this further.

**Comment by CarlosHorro** [comment]
Hi,

We were given the beta version of Andromeda, which, after some tests, finally seems to work on Linux via Mono (without any GUI, just working using the command line). However we are still waiting for its final version published to include it into SearchGUI.

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
Hi all,

After such a long time and having tested many different Andromeda and MaxQuant versions (and Andromeda running under new Linux dotnet environment without success), Andromeda command client has been integrated into MaxQuant package and, unless there is an unexpected change, this will not be changed anymore.
So, I think we may discard having Andromeda running on Linux and I will close this issue.
I will reopen it again if there is a change on this at some point in the future.

Greetings,
Carlos
