### ISSUE TITLE
SearchGUI PathSettingsCLI error

### ISSUE THREAD

**Issue by bernt-matthias** [compomics/searchgui#180]
when running `searchgui eu.isas.searchgui.cmd.PathSettingsCLI -temp_folder $TMP_FOLDER` I get:

```
java.io.FileNotFoundException: /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/mulled-v1-804f89c8212ddcc336cddfff779465f6df8af85f84deb98439d15fb605d7903d/share/searchgui-3.2.24-0/resources/conf/paths.txt (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at java.io.FileWriter.<init>(FileWriter.java:90)
        at eu.isas.searchgui.preferences.SearchGUIPathPreferences.writeConfigurationToFile(SearchGUIPathPreferences.java:248)
        at eu.isas.searchgui.cmd.PathSettingsCLI.setPathSettings(PathSettingsCLI.java:87)
        at eu.isas.searchgui.cmd.PathSettingsCLI.call(PathSettingsCLI.java:41)
        at eu.isas.searchgui.cmd.PathSettingsCLI.main(PathSettingsCLI.java:152)
```

the paths.txt does not exist and the user should not be able to write there anyway. 

just trying to incorporate this into the searchgui galaxy tool as suggested here: https://github.com/compomics/searchgui/issues/107 .. ping @bgruening 

I'm also wondering if it is necessary to set `-log` (or asked the otherway round: what exactly happens if I do not set it) or any of the other options if we work in a shared environment. We need to ensure that Searchgui or FastaCLI does not use any data from the home but from some temporary location in order to fix: https://github.com/galaxyproteomics/tools-galaxyp/issues/293.

**Comment by CarlosHorro** [comment]
Hi @bernt-matthias ,

I'm a bit confused about the execution context. Where are you executing that line?:

`searchgui eu.isas.searchgui.cmd.PathSettingsCLI -temp_folder $TMP_FOLDER`

Greetings,
Carlos

**Comment by bgruening** [comment]
@CarlosHorro I think the execution context is inside a Galaxy job. The underlying problem is that SearchGUI still seems to make the assumption that there is a HOME dir somewhere.

**Comment by bernt-matthias** [comment]
@CarlosHorro If I remember correctly the problem comes with this line:

https://github.com/bernt-matthias/tools-galaxyp/blob/4e5da3aae79929240d46a260c1ac0592eb7a7fdb/tools/peptideshaker/searchgui.xml#L45

in my branch of the Galaxy tool where I try to fix https://github.com/galaxyproteomics/tools-galaxyp/issues/293.

In the end we are looking for the best way to make SearchGUI run in a clean environment (no data from HOME, etc.)

**Comment by CarlosHorro** [comment]
Hi all,

Checking current (official) SearchGUI wrapper, SearchGUI is not using a home folder, it's using a temporary folder set to `pwd`:
-temp_folder `pwd`

The wrapper has also a variable called $HOME which actually refers to the same folder, the working directory of the Galaxy process. As an example, this was the directory pointed by $HOME used in one execution on my laptop:
"/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/316/working

This folder is actually a temporary folder so I cannot think on any problem using this configuration on a shared environment.

I hope I answered the question but I'm not sure yet.
If I missed the point again, could you summarise the exact problem here (with the current officially available wrapper) again, please? I think there are different things mixed in this issue and it will be better to clarify them one by one, step by step.

Greetings,
Carlos

**Comment by bernt-matthias** [comment]
OK. Then we add the `-temp_folder` parameter to the searchgui call -- might help.

But the actual problem is from FastaCLI which tries to access the users home $HOME (https://github.com/galaxyproteomics/tools-galaxyp/issues/293). 

When I tried to fix this with a call to PathSettingsCLI I got the problem reported here (access to some nonextended paths.txt in the conda environment)

**Comment by hbarsnes** [comment]
> OK. Then we add the -temp_folder parameter to the searchgui call -- might help.

BTW, @bernt-matthias Why was it removed in the first place? As it is there it the version of the wrapper that we use as far as I could see from what @CarlosHorro showed me yesterday.

**Comment by bernt-matthias** [comment]
Thanks for the detailed comments. There is an important point with the paths.txt

> When using non-standard paths to where the temp files are stored, i.e. using something else that the user home folder, will result in the creation of a file called paths.txt containing the references to the paths that should be instead of user home. This file is stored in the given subfolder of SearchGUI (or PeptideShaker) searchgui-X.Y.Z/resources/conf/paths.txt

This does not work in a multi user environment for multiple reasons: 
- this refers to the installation directory which is not writable by users (in galaxy the path is owned by the galaxy system user)
- but more important if multiple users access it at the same time one user will read/overwrite the data from other users, i.e. the paths stored in the file will be wrong in both cases (but, overwriting should cause an exception since it shouldn't be possible with linux default permissions)

Note that this won't work even in single user environments if the user starts multiple processes at the same time that use different temp directories.

**Comment by bernt-matthias** [comment]
> Why was it removed in the first place? As it is there it the version of the wrapper that we use as far as I could see from what @CarlosHorro showed me yesterday.

That's correct. The `--temp_folder` parameter was removed in my branch in favor of using `PathSettingsCLI` which should do the same. 

I added `PathSettingsCLI` because the latest searchgui wrapper included calls that did not specify a temporary directory (and I hoped that this simplifies the wrapper). For example the FastaCLI did not specify a temp_folder and caused this problem: https://github.com/galaxyproteomics/tools-galaxyp/issues/293

According to the documentation FastaCLI does not have a temp_folder parameter anyway, so one would need to use PathSettingsCLI (which seems not work at the moment in multi user environments). 

Just tried FastaCLI --temp_folder .. and it seems to work. So I will remove PathSettingCLI in my branch again and add  --temp_folder to all searchgui calls. This should work.

**Comment by bernt-matthias** [comment]
Hmm: `IdentificationParametersCLI` has no --temp_folder option

**Comment by bernt-matthias** [comment]
Some of the calls use an `--exec_dir` parameter which is not documented. Can someone clarify what this is doing?

**Comment by CarlosHorro** [comment]
> Thanks for the detailed comments. There is an important point with the paths.txt
> 
> When using non-standard paths to where the temp files are stored, i.e. using something else that the user home folder, will result in the creation of a file called paths.txt containing the references to the paths that should be instead of user home. This file is stored in the given subfolder of SearchGUI (or PeptideShaker) searchgui-X.Y.Z/resources/conf/paths.txt
> 
> This does not work in a multi user environment for multiple reasons:
> 
> this refers to the installation directory which is not writable by users (in galaxy the path is owned by the galaxy system user)
> but more important if multiple users access it at the same time one user will read/overwrite the data from other users, i.e. the paths stored in the file will be wrong in both cases (but, overwriting should cause an exception since it shouldn't be possible with linux default permissions)
> Note that this won't work even in single user environments if the user starts multiple processes at the same time that use different temp directories.
---
Trying to go step by step I will just reply to this until this point is clear.

In a normal SearchGUI’s galaxy tool execution (using current official wrapper), paths.txt is not created until running time, into the working folder of the job, in such a way that paths.txt locations point to different subfolders into that working folder. This in an example of one paths.txt file in my computer (located at /Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/318/working/bin/resources/paths.txt) whilst I was running a job:

searchgui_temp=/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/317/working
comet_temp=/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/317/working
andromeda_temp=/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/317/working
utilities_user_preferences=/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/317/working
ptm_configuration=/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/317/working
enzyme_configuration=/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/317/working
fasta_indexes=/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/317/working/fasta_indexes
gene_mapping=/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/317/working/gene_mapping
pride_annotation=/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/317/working/pride
identification_parameters=/Users/carlos.horro/GitHub/galaxy/database/jobs_directory/000/317/working/identification_parameters

So, this file is unique per execution and it should work fine in shared environments. Is it ok?

**Comment by bernt-matthias** [comment]
Found the answer to the `--exec_dir` question myself. This is essentially a parameter to the python wrapper that calls the java code. Its commented in the source that this leads to copying the java files to the given directory (but I don't know where this is done). 

Since my call to PathSettingsCLI did not included this parameter the paths.txt was written to the conda distribution -- which did not work.

**Comment by hbarsnes** [comment]
> Note that this won't work even in single user environments if the user starts multiple processes at the same time that use different temp directories.

Correct. Which is why we only recommend to run one instance of the same jar file at the same time. If you want to run multiple copies of, for example, PeptideShaker, you need two copies of PeptideShaker, each with its own temp folder, hence avoiding the issue with using the same user home folder.

I thought this was how Galaxy worked in the first place?

> According to the documentation FastaCLI does not have a temp_folder parameter anyway, so one would need to use PathSettingsCLI (which seems not work at the moment in multi user environments).

It does, it is just the documentation that is missing. Will correct this asap.

> Hmm: IdentificationParametersCLI has no --temp_folder option

Why would it need one? All this command line does is take a set of parameters provided by the user and put them in a json file at the location decided by the user. No use of the temp folder.

**Comment by bernt-matthias** [comment]
OK. I think a got it. .. see https://github.com/galaxyproteomics/tools-galaxyp/pull/312

Thanks a lot for your comments and patience.

**Comment by hbarsnes** [comment]
@bernt-matthias If think this issue can now be closed right?
