### ISSUE TITLE
SearchGUI Comet error

### ISSUE THREAD

**Issue by markmipt** [compomics/searchgui#183]
Hi all,
I tried to process .mgf file with SearchGUI using Comet search engine, but got an error:

> Thu Sep 20 13:28:22 MSK 2018        Indexing spectrum files.
> Thu Sep 20 13:28:22 MSK 2018        Extracting search settings.
> Thu Sep 20 13:28:22 MSK 2018        Processing confetti_trypsin_01.mgf with Comet.
>  Comet version "2018.01 rev. 0" 
> Thu Sep 20 13:28:23 MSK 2018        Comet finished for confetti_trypsin_01.mgf (665.0 milliseconds).
> Thu Sep 20 13:28:23 MSK 2018        Error: Source '/home/mark/overfit_clean/mgfs/confetti_trypsin_01.comet.pep.xml' does not exist
> Thu Sep 20 13:28:23 MSK 2018        An error occurred while running SearchGUI. Please contact the developers.
> Thu Sep 20 13:28:23 MSK 2018        The search or processing did not finish properly!
> Thu Sep 20 13:28:23 MSK 2018        Search Canceled!
> Thu Sep 20 13:28:24 MSK 2018        The search or processing did not finish properly!

The searches with same parameters using X!Tandem, MSGF+ and Tide work fine. I'm using SearchGUI v.3.3.3 and PeptideShaker v.1.16.29 under Linux Arch.

Regards,
Mark

**Comment by hbarsnes** [comment]
Hi Mark,

Seems like there is a problem with the Comet search resulting in there being no Comet results. Seems like the search does not even start. Would it be possible for you to share the mgf and search parameters so that I can try to reproduce the issue?

Best regards,
Harald

**Comment by markmipt** [comment]
Hi Harald, 

Please find .mgf, .fasta and search parameters by the link: http://pubdata.theorchromo.ru/peptideshaker/

Regards,
Mark

**Comment by hbarsnes** [comment]
Hi Mark,

Thanks for sharing the files. I don't see anything unusual about them though and can search them with Comet without any problems on my end. But I'm running Windows, so there maybe there is something with your Linux setup not being compatible with Comet? I'd recommend contacting the Comet developers directly via https://groups.google.com/forum/#!forum/comet-ms.

Best regards,
Harald

**Comment by markmipt** [comment]
Yes, you are right! I've tried a standalone version of Comet and it also not working. Closing the issue as not related with SearchGUI

**Comment by markmipt** [comment]
Hi Harald,

Previously, the problem was connected with Comet and Linux (keywords for google: "VSYSCALL is now disabled on latest linux distros"). However, when we fixed this problem - the standalone Comet (v. 2018012) starts working, but SearchGUI version still gives no results. When I've replaced comet.exe (distributed with SearchGUI) with the standalone version - SearchGUI starts working.

So, it is better to update Comet distributive in the next SearchGUI release.

Regards,
Mark

**Comment by hbarsnes** [comment]
Hi Mark,

Thanks for the update. I just released SearchGUI v3.3.4 which updates Comet to the latest version.

Best regards,
Harald

**Comment by markmipt** [comment]
Probably you will have to update Comet again in the near future) 
See details here: https://groups.google.com/forum/#!topic/comet-ms/hyFl_ArgNGs

**Comment by hbarsnes** [comment]
> Probably you will have to update Comet again in the near future). See details here: https://groups.google.com/forum/#!topic/comet-ms/hyFl_ArgNGs

Sure, I will do so as soon as Jimmy releases a new version. :)

**Comment by Dmorgen** [comment]
Hi,
The problem occurs again with the newest SearchGUI version
D.

**Comment by hbarsnes** [comment]
Hi D,

Does the problem also occur with the standalone version of Comet? If so, you need to contact the Comet developers via https://groups.google.com/forum/#!forum/comet-ms.

If Comet version 2019.01 rev. 3 does not have the same problem I will release a new version of SearchGUI as soon as possible.

Best regards,
Harald

**Comment by Dmorgen** [comment]
Got the same issue with myrimatch too…

David.

**Comment by hbarsnes** [comment]
Hi David,

> Got the same issue with myrimatch too…

The MyriMatch executable included in SearchGUI has not been updated in a long time. Basically due to MyriMatch not being developed/maintained anymore. There is therefore not a lot we can do in that regard. You may try to find the source and build your own version of MyriMatch. But I'd recommend rather just using one or more of the other search engines included in SearchGUI.

Best regards,
Harald

**Comment by Dmorgen** [comment]
Will do, thanks!

D.
