### ISSUE TITLE
THISP database errors with SearchGUI and SearchCLI version 3.3.3

### ISSUE THREAD

**Issue by catherine-data-analysis** [compomics/searchgui#184]
Hi @hbarsnes 
I am having problems using THISP databases with SearchGUI 3.3.3 and SearchCLI (I selected X!Tandem, MyriMatch and MS-GF+ as search engines). I have had to replace all ' in the fasta file and all * in the protein sequences and the error message persists with "non unique accession number found". The THISP databases author suggests that the SearchGUI parser is using only the first part before the | as the accession and therefore creating the duplicate error. Can you please advise?
![screenshot from 2018-10-08 12-01-44](https://user-images.githubusercontent.com/31210056/46722495-e6c96b80-cc75-11e8-868f-319b62f4ea43.png)
![screenshot from 2018-10-08 11-32-51](https://user-images.githubusercontent.com/31210056/46722513-f21c9700-cc75-11e8-9117-715446bb5536.png)

**Comment by hbarsnes** [comment]
Hi,

I'm not too familiar with the THISP database. But if I download this file ftp://ftp.peptideatlas.org/pub/PeptideAtlas/THISP/2018-10-01/PA_THISP_Level4_2018-10-01.fasta and use the following steps the issues seem to be resolved:

1. Remove all * from the sequences
2. Replace all ' from the headers
3. Replace ">Microbe_sp|" with ">generic_Microbe_sp|" and ">Microbe_tr|" with ">generic_Microbe_tr|"
4. Replace ">IMGT_" with ">generic_IMGT_".

This ensures that all the headers are in a format that SearchGUI is able to understand. See https://github.com/compomics/searchgui/wiki/DatabaseHelp for details.

Let me know if the above works for you as well.

Best regards,
Harald

**Comment by catherine-data-analysis** [comment]
Thank you very much, @hbarsnes 
I will try that.

Kind regards,
Catherine

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
