### ISSUE TITLE
Tide crashes wrong parameter num-threads

### ISSUE THREAD

**Issue by FantacticMisterFox** [compomics/searchgui#185]
Can not run Tide crashes with the following:
Do not find parameter to set num-threads neither in the search setting nor in Tide Settings.
Bug?

```
Wed Oct 10 16:50:32 CEST 2018        Processing 180228_StS_flowrate_Bd16_ctrl_rep1.mgf with Tide.

FATAL: Value of 'num-threads' must be between 0 and 64

USAGE:

  crux tide-search [options] <tide spectra file>+ <tide database>



Wed Oct 10 16:19:35 CEST 2018        Tide Searching finished for 180228_StS_flowrate_Bd16_ctrl_rep1.ms2 (321.0 milliseconds).

Wed Oct 10 16:19:35 CEST 2018        Error: Source '/homes/biertruck/john/programms/spekral-analysis/SearchGUI-3.3.5/resources/Tide/linux/linux_64bit/crux-output/180228_StS_flowrate_Bd16_ctrl_rep1.tide-search.target.txt' does not exist
Wed Oct 10 16:19:35 CEST 2018        An error occurred while running SearchGUI. Please contact the developers.
Wed Oct 10 16:19:35 CEST 2018        The search or processing did not finish properly!

Wed Oct 10 16:19:35 CEST 2018        Search Canceled!
```

**Comment by hbarsnes** [comment]
If running SearchGUI from the command line the setting you are looking for is -threads. If running from the graphical user interface of SearchGUI you can change the number of threads via Edit > Processing Settings in the main SearchGUI dialog. In the backend this value will then be converted to the num-threads options for the Tide command line (and similarly for the other search engines).

**Comment by FantacticMisterFox** [comment]
thanks this solved it. I ran it on a cluster and it detected all 80 cores.
