### ISSUE TITLE
(ana)conda linux 64bit Version 2.1.4-3 instead of 3.3.5. 

### ISSUE THREAD

**Issue by robert-winkler** [compomics/searchgui#187]
Hi, 
conda install -c bioconda searchgui
installs version  2.1.4-3 instead of 3.3.5. on (ana)conda linux 64bit.
Thus, every time running it requires an upgrade.
Best, Robert

**Comment by CarlosHorro** [comment]
Hi,

Thank you for telling us, we have checked it and we are in contact with the bioconda team in order to solve this problem.

Greetings,
Carlos

**Comment by robert-winkler** [comment]
Thanks a lot, Carlos!
Anyway, Anaconda completey screwed up my Fedora 28 installation (e.g. broke dnf, a "known" issue, I was not aware of).
The next future I use SearchGUI the traditional way.
Best, Robert
