### ISSUE TITLE
(ana)conda install of searchgui broken on Win10

### ISSUE THREAD

**Issue by robert-winkler** [compomics/searchgui#188]
(base) C:\>conda install -c bioconda searchgui
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - searchgui
  - mono[version='>=4.0.0']

on Windows 10

**Comment by CarlosHorro** [comment]
Hi,

I'm afraid that bioconda does not currently guarantee that their packages work on Windows platforms. I think they are working on that as we still have an open issue related to this (about other tool).

Greetings,
Carlos

**Comment by robert-winkler** [comment]
Thanks Carlos!
Anyway, the basic idea of conda is to have the things working on different platforms. So I hope they can figure this out.
Best, Robert

**Comment by CarlosHorro** [comment]
Hi,

As Bioconda team does not still seem to be working on getting their packages to work on Windows, I think I will close this issue, and I will reopen it if, at some point, they add support for windows.
