### ISSUE TITLE
Parameters PAR file problems

### ISSUE THREAD

**Issue by iquasere** [compomics/searchgui#189]
Greetings

I have encountered several problems concerning the use of custom parameters by SearchCLI:
-first I attempted to use the SearchCLI parameters tool as such
```
java -cp ~/SearchGUI-3.3.3/SearchGUI-3.3.3.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out parameters.par -db db.fasta –prec_tol 10 –frag_tol 0.02 –enzyme Trypsin –fixed_mods Carbamidomethylation of C –variable_mods Oxidation of M –mc 2
```
but the parameters file that it produces uses the default parameters, not including, for example, the PTMs. 

Using SearchCLI with such file
```
java -cp ~/SearchGui-3.3.3/SearchGUI-3.3.3.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files spectra_folder -output_folder output_folder -id_params parameters.par -xtandem 1 -myrimatch 1 -msgf 1
```
it warns me that it could not find the file
```
Could not find the default configuration file (hard-coded defaults in use).
```
and that it switched to use default parameters (not really different since those were already the ones I'm stuck with). Trying to give my custom parameters directly to SearchCLI also doesn't work
```
java -cp ~/SearchGui-3.3.3/SearchGUI-3.3.3.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files spectra_folder -output_folder output_folder -id_params parameters.par -db db.fasta –prec_tol 10 –frag_tol 0.02 –enzyme Trypsin –fixed_mods Carbamidomethylation of C –variable_mods Oxidation of M –mc 2 -xtandem 1 -myrimatch 1 -msgf 1
```
which is evidenced by the html report it generates, where the PTMs show to be not considered.
```
FIXED_MODIFICATIONS=
VARIABLE_MODIFICATIONS=
```
So, I have three troubles to shoot here:
1) The parameters file generated by the IdentificationParametersCLI just contains the standard parameters
2) SearchCLI can't locate such file, switching to the default parameters
3) Giving the parameteres directly to SearchCLI fails the same way

Thank you for your attention

**Comment by hbarsnes** [comment]
Hi,

When providing the modifications on the command line you have to surround them with quotes, e.g. –fixed_mods "Carbamidomethylation of C". Otherwise the options will not be parsed correctly.

Best regards,
Harald

**Comment by iquasere** [comment]
Thank you for the quick response, Harald. I forgot to say that I had already tried that, but it didn't help

**Comment by iquasere** [comment]
Beginning of parameters.par always looks like
```
{
  "marshallableParameterType": "identification_parameters",
  "name": "parameters",
  "description": "DB: db.fasta.\n",
  "defaultDescription": true,
  "searchParameters": {
    "precursorAccuracyType": "PPM",
    "fragmentAccuracyType": "DA",
    "precursorTolerance": 10.0,
    "precursorToleranceDalton": 0.5,
    "fragmentIonMZTolerance": 0.5,
    "ptmSettings": {
      "fixedModifications": [],
      "variableModifications": [],
      "refinementVariableModifications": [],
      "refinementFixedModifications": [],
      "colors": {},
      "backUp": {}
    },
    "nMissedCleavages": 2,
    "digestionPreferences": {
      "cleavagePreference": "enzyme",
      "enzymes": [
        {
          "id": 0,
          "name": "Trypsin",
          "aminoAcidBefore": [],
          "aminoAcidAfter": [],
          "restrictionBefore": [],
          "restrictionAfter": [],
```

**Comment by hbarsnes** [comment]
You have also tried using complete paths in the command line when referring to files and folders?

**Comment by iquasere** [comment]
Hand't thought about that, no, but it didn't solve the problem.

**Comment by iquasere** [comment]
Could you please show a working example of the IdentificationParametersCLI tool or the SearchCLI with arguments specified directly in the command? No files needed, just to check the syntax. Maybe this is something like the "" that I am overlooking.

**Comment by hbarsnes** [comment]
Here's one that works fine for me:

java -cp SearchGUI-3.3.3.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out C:\Users\Harald\Desktop\SearchGUI-3.3.3\output\parameters.par -db C:\Users\Harald\Desktop\uniprot-human-reviewed-trypsin-june-2017_concatenated_target_decoy.fasta -fixed_mods "Carbamidomethylation of C" -variable_mods "Oxidation of M"

Which results in the parameter file being created and the following message printed in the terminal:

Identification parameters file created: C:\Users\Harald\Desktop\SearchGUI-3.3.3\output\parameters.par

**Comment by iquasere** [comment]
I always get the file built as well, but always the same default file. It ends in success, but seem to not update the variables concerning to parameters that I am changing. Does the file generated contain the modified parameters? Also, does SearchCLI manage to read that file? I always get the 
```
Could not find the default configuration file (hard-coded defaults in use).
```
message when searching with Myrimatch, and I gues the other search engines are also not making use of the modified parameters, since the html with the parameters listing always shows the unmodified list of parameters.

**Comment by iquasere** [comment]
After manually editing the parameters file, the search engines seem to work with the altered arguments, and since that "Could not find the default configuration file (hard-coded defaults in use)." message only originated on the Myrimatch search, it might mean that only that tool made no use of the custom parameters. So, my 2nd issue seems to be adressed just for Myrimatch, since I find the reference to the modifications on the configuration files for X!Tandem (~/SearchGUI-3.3.3/resources/XTandem/linux/linux_64bit/parameters_searchGUI.xml) and MS-GF+ (~/SearchGUI-3.3.3/resources/MS-GF+/params/Mods.txt) but I can't find it in the Myrimatch command
```
~/SearchGUI-3.3.3/resources/MyriMatch/linux/linux_64bit/myrimatch -cpus 16 -ProteinDatabase /path/to/db.fasta /path/to/spectra_folder/spectrum.mgf -OutputFormat mzIdentML -workdir /path/to/output_folder/.SearchGUI_temp -OutputSuffix .myrimatch -DecoyPrefix "" -MinPeptideLength 8 -MaxPeptideLength 30 -MaxResultRank 10 -SpectrumListFilters "" -FragmentMzTolerance "0.5 daltons" -MonoPrecursorMzTolerance "10.0 ppm" -PrecursorMzToleranceRule "mono" -StaticMods "C 57.021464" -DynamicMods "M 0 15.994915" -MaxDynamicMods 2 -StatusUpdateFrequency 10 -NumChargeStates 4+ -TicCutoffPercentage 0.98 -MinPeptideMass 600.0 -MaxPeptideMass 5000.0 -UseSmartPlusThreeModel true -ComputeXCorr false -NumIntensityClasses 3 -ClassSizeMultiplier 2 -NumBatches 50 -MaxPeakCount 300 -MonoisotopeAdjustmentSet [0,1] -FragmentationAutoRule false -FragmentationRule "cid" -CleavageRules "Trypsin" -MinTerminiCleavages 2 -MaxMissedCleavages 2
```

**Comment by hbarsnes** [comment]
> Does the file generated contain the modified parameters? Also, does SearchCLI manage to read that file?

Yes, here's the ptm section from the created file:

```
"ptmSettings": {
      "fixedModifications": [
        "Carbamidomethylation of C"
      ],
      "variableModifications": [
        "Oxidation of M"
      ],
```

> Could not find the default configuration file (hard-coded defaults in use).

This message from MyriMatch can be ignored. For some reason it is always printed. And if you look closer at your MyriMatch command line you can find your ptms here "-StaticMods "C 57.021464" -DynamicMods "M 0 15.994915".

Very strange that you are not able to create the parameter file though. Can you send me the current IdentificationParametersCLI command line after adding quotes and complete paths?

**Comment by iquasere** [comment]
Ah hadn't noticed the Myrimatch arguments. Here follows the command
```
java -cp ~/SearchGUI-3.3.3/SearchGUI-3.3.3.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -out parameters.par -db db.fasta –prec_tol 10 –frag_tol 0.02 –enzyme Trypsin –fixed_mods "Carbamidomethylation of C" –variable_mods "Oxidation of M" –mc 2
```
The thing is, the file is generated, with the success message. But it maintains the default parameters. What makes me think that the variables concerning those parameters are not being updated.

**Comment by hbarsnes** [comment]
We managed to produce the issue on Linux on our end as well now. No idea why it works on Windows and not on Linux though. We'll look into it and get back to you.

**Comment by iquasere** [comment]
Thank you, Harald. Also, notice that when giving the parameters directly to SearchCLI, such as in
```
java -cp ~/SearchGui-3.3.3/SearchGUI-3.3.3.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files spectra_folder -output_folder output_folder -id_params parameters.par -db db.fasta –prec_tol 10 –frag_tol 0.02 –enzyme Trypsin –fixed_mods Carbamidomethylation of C –variable_mods Oxidation of M –mc 2 -xtandem 1 -myrimatch 1 -msgf 1
```
the result is the same, it generates a parameters file, but with the default parameters. So the problem must be in not updating the variables.

**Comment by hbarsnes** [comment]
After lots of debugging I think I finally found the source of the issue!

Turns out that there are more than one type of dash/hyphen, i.e. "-" vs. "–". (Note that the difference is not visible in all fonts!)

If you have a closer look at your final command line above you will see that not all of the dashes are of the same type. The following "–prec_tol 10 –frag_tol 0.02 –enzyme Trypsin –fixed_mods Carbamidomethylation of C –variable_mods Oxidation of M –mc 2" are of the wider/longer type. These parameters are therefore ignored, while the ones using the shorter correct dash, e.g "-xtandem 1", are parsed and end up in the parameter file. (You still need to add the quotes around the modification names though.)

For some reason the Windows terminal does not distinguish between the two types (even when copy-pasted into the terminal), while the terminals for Linux and Mac does. Explaining why the issue is not reproducible on Windows.

Any idea how the longer dashes were introduced? Do they come from a copy-paste? Or are you able to type both versions on your keyboard? Very odd that you end up combining both versions in the same command line though?

**Comment by iquasere** [comment]
It was exactly that, it occured because of me using PowerPoint to keep track of my progress, and ending up writing the command on PowerPoint before copying it to bash. That converted the hyphens to the longer version. The shorter ones are in the pieces of command that I copied from the SearchCLI documentation, and the longer ones I probably wrote on PowerPoint. Well spotted, Harald, and thank you a lot for the support!
