### ISSUE TITLE
Peptideshaker error in SearchGUI-3.3.5

### ISSUE THREAD

**Issue by thiagobiocouto** [compomics/searchgui#190]
Good day.

Just started to get this error when processing identification files with PeptideShaker-1.16.31.

Kindly help me in this regard. Thanking you,

Best regards, Thiago 

Thu Oct 25 12:42:41 GFT 2018        Spectrum_1488_novo.mgf already exists. Conversion canceled.

Thu Oct 25 12:42:41 GFT 2018        Indexing spectrum files.
Thu Oct 25 12:42:41 GFT 2018        Extracting search settings.

Thu Oct 25 12:42:41 GFT 2018        Processing Spectrum_1488_novo.mgf with MS Amanda.

Reading settings file...
Settings file successfully read.
Input files contain 1 spectra

Searching file 'Spectrum_1488_novo.mgf'...
  Searching spectra 1 - 1 of 1 spectra
     Starting search against fwd database
     Search against fwd database finished.
  Search finished for 1/1 spectra
File 'Spectrum_1488_novo.mgf' finished.

Done.

Thu Oct 25 12:42:42 GFT 2018        MS Amanda finished for C:\Users\fabia\OneDrive\Área de Trabalho\Cetene_Thiago\Spectra\Spectrum_1488_novo.mgf (501.0 milliseconds).

Thu Oct 25 12:42:42 GFT 2018        Zipping output files.

Thu Oct 25 12:42:42 GFT 2018        Processing identification files with PeptideShaker.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/C:/Users/fabia/Downloads/PeptideShaker-1.16.30%20(1)/PeptideShaker-1.16.31/lib/gson-2.4.jar) to field java.awt.Color.value
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by hbarsnes** [comment]
Hi,

Which version of Java are you using? If you are running Java 9 or 10 I'd recommend switching to the more stable Java 8 which does not seem to have the above issue.

However, as these are just warnings, can't they just be ignored? Or does the processing of the data stop? 

Best regards,
Harald

**Comment by thiagobiocouto** [comment]
Hi, thank's for help me.

Sometimes the processing is canceled

**Comment by thiagobiocouto** [comment]
Problem solved after switching to the Java 8

Thank u
