### ISSUE TITLE
Andromeda Unhandled Exception

### ISSUE THREAD

**Issue by ghost** [compomics/searchgui#191]
Dear searchGUI team,

I tried to use SearchGUI with my LC/MS/MS raw data, and I only chose Andromeda, here is the error report I got, I cannot attach my raw data since it's too big.

Regards
Chenxi

[SearchGUI Report 2018-11-05 12.05.04.txt](https://github.com/compomics/searchgui/files/2548147/SearchGUI.Report.2018-11-05.12.05.04.txt)

**Comment by hbarsnes** [comment]
Hi Chenxi,

Given that the error occurs inside Andromeda I'm afraid there is not much we can do on our side.

I'd recommend contacting the Andromeda developers directly at https://groups.google.com/forum/#!forum/andromeda-list. You'll find the specific Andromeda command line used in the SearchGUI-X.Y.Z\resources\SearchGUI.log file.

Best regards,
Harald

**Comment by chenxihuang** [comment]
Dear Harald,

I tried directly load my data in MaxQuant, and there is no error, and in the forum I saw the same error I got but no answer yet.
https://groups.google.com/forum/#!searchin/andromeda-list/mslib%7Csort:date/andromeda-list/vWClGpTQST8/p5swUOW-DQAJ

![20181105134050](https://user-images.githubusercontent.com/12170447/47998654-6c6afa80-e100-11e8-947f-f8310ec9ddf3.png)

**Comment by hbarsnes** [comment]
Hi Chenxi,

I'm sorry that the Andromeda Google Group has not provided an answer.

The above error seems to indicate that the issue is due to the spectrum file though. Could you try running Andromeda through SearchGUI with a smaller/simpler mgf file?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
