### ISSUE TITLE
iodoTMT reagents

### ISSUE THREAD

**Issue by verheytb** [compomics/searchgui#193]
Hello,

I am using IdentificationParametersCLI and it doesn't seem to be capable of iodoTMT reagents which target cysteines. I'm wondering whether there is a workaround or whether we will have to go and use another software pipeline.

Thanks.

**Comment by hbarsnes** [comment]
Hi Ted,

We would have to add the iodoTMT reagents to our list of supported modifications, but this should be quite easily done. I will try to get to it this weekend and get back to you. I assume the reagents listed [here](https://www.thermofisher.com/order/catalog/product/90101) are the ones you would need right?

Best regards,
Harald

**Comment by verheytb** [comment]
Yes, that is the one, thanks very much!

**Comment by hbarsnes** [comment]
Hi Ted,

I've now added support for iodoTMT and released new versions of the tools. Note that I don't have access to any iodoTMT data though, so please don't hesitate to reopen the issue if you should come across any problems when processing iodoTMT data.

Best regards,
Harald

**Comment by verheytb** [comment]
Thank you, this increased our detection dramatically.
