### ISSUE TITLE
Adding Heme group

### ISSUE THREAD

**Issue by baxa** [compomics/searchgui#194]
Hi - is it possible to include a Heme group as a possible modification?  I wasn't able to make my own since there is no Fe in the composition window.

**Comment by hbarsnes** [comment]
Hi again,

I've just released new versions of both SearchGUI and PeptideShaker where Fe is added as a possible ion in the composition dialog. I also added "Heme B of C" as a new default modification.

I will now close the issue, but don't hesitate to reopen it if you have more related questions.

Best regards,
Harald

**Comment by baxa** [comment]
Great - thank you!
