### ISSUE TITLE
'Path configuration completed' after attempting to run a search.

### ISSUE THREAD

**Issue by TessaGillett** [compomics/searchgui#197]
Hi,

I've been trying to run a search from the command line (after first setting parameters and specifying path settings) as follows:

`java -Xms128M -Xmx80G -cp ./ext_tools/SearchGUI-3.3.9/SearchGUI-3.3.9.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files filename.mgf -output_folder ./outputdir/ -id_params ./outputdir/sample_searchgui.par -xtandem 1 -msgf 1 -omssa 1 -ms_amanda 0 -myrimatch 0 -comet 1 -tide 1 -andromeda 0 -threads 20 -species "Rattus norvegicus" -output_option 1 -mgf_spectrum_count 150000 -missing_titles 1 -protein_index 1 -correct_titles 1 -temp_folder ./outputdir/`
(Edited a bit for readability)

However, what I get is the message 'Path configuration completed.' and besides that nothing actually seems to happen. (Even though the path configurations are already set with eu.isas.searchgui.cmd.PathSettingsCLI, right?) There's no error message, so I'm having a hard time finding the cause. Any idea what I'm doing wrong?

Thank you!
Tessa

**Comment by hbarsnes** [comment]
Hi Tessa,

If the temp paths are already set via PathSettingsCLI you do not have to include the -temp_folder option as part of the SearchCLI command line. This should not affect the running of the actual SearchCLI command line though.

Another thing you can simplify is to remove -ms_amanda 0, -myrimatch 0, and -andromeda 0, as the default value is 0 for all of these. Same for -correct_titles 1, as here 1 is the default.

Furthermore, we very much recommend using complete paths when referring to files or folders. But that could be part of the "Edited a bit for readability"?

The -species "Rattus norvegicus" option I don't recognize. Where did this come from? Maybe it's an old deprecated option? The same goes for -protein_index 1?

The rest of the command line looks ok to me. But if you still experience issues check the log file SearchGUI.log. By default it should be in the SearchGUI-3.3.9\resources folder. But given that you changed the temp folder (temp_folder ./outputdir/) you should rather look in outputdir folder I guess.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Tessa,

No worries. Happy to help. :)

Best regards,
Harald
