### ISSUE TITLE
Fasta parsing

### ISSUE THREAD

**Issue by srithegreat** [compomics/searchgui#198]
Hi,

I have a custom fasta database with decoys, which I search with multiple search engines. When I import the results in PeptideShaker, it throws an error:
java.lang.IllegalArgumentException: Non unique accession number found 'rp'!

My fasta headers look like this:
 >rp|Q8IWF2-id12299_REVERSED|FXRD2_HUMAN-id12299 FXRD2_HUMAN-id12299-REVERSED
 
>rp|O43247-id12300|TEX33_HUMAN-id12300 TEX33_HUMAN-id12300
 
>rp|O43247-id12300_REVERSED|TEX33_HUMAN-id12300 TEX33_HUMAN-id12300-REVERSED
 
>rp|O43247-id12301|TEX33_HUMAN-id12301 TEX33_HUMAN-id12301

I have checked and the ID information after the first pipe is unique in entire file.

Any help appreciated.

Regards,
Srikanth

**Comment by hbarsnes** [comment]
Hi Srikanth,

Please see our database help wiki. In particular the section about non-standard FASTA headers: https://github.com/compomics/searchgui/wiki/DatabaseHelp#non-standard-fasta. You will need to convert your custom headers to this format in order for our tools to be able to parse your FASTA file correctly. Should be straightforward though?

Best regards,
Harald

**Comment by srithegreat** [comment]
Thanks for that, I have changed the database accordingly and now its working. Only thing is had to research the entire data (which is painstaking).
You can close the issue. Can we expect regular expression for headers in future releases?

**Comment by hbarsnes** [comment]
> Can we expect regular expression for headers in future releases?

Sorry, no plans for this at the moment.
