### ISSUE TITLE
FastaCLI terminates before end

### ISSUE THREAD

**Issue by TessaGillett** [compomics/searchgui#199]
Hi,

I'm trying to add some decoys to a fasta file I've made, but I have the problem that FastaCLI stops running before the end. At first I thought it wasn't doing anything towards adding any decoys at all, as it just terminates after `Reindexing: filename.fasta`.

However, using a much smaller test file, it seems that it's pretty consistent in terminating either after a certain number of lines or certain amount of time. (With the larger file I'm guessing it doesn't reach 10% and so doesn't report any progress.) With this test file, I first get to 60%. If I double it, it reports 30% and if I triple it, 20%.

The command I'm using:
`java -Xms128M -Xmx80G -cp /home/tessa/code/ext_tools/SearchGUI-3.3.9/SearchGUI-3.3.9.jar eu.isas.searchgui.cmd.FastaCLI -decoy -in ./testFile.fa `

Output:
```
An error occurred when setting path configuration. Default paths will be used.
Reindexing: testFile.fa.
10% 20% 30% 40% 50% 60%
```

Any idea what's going wronf? (To be complete: I have also done it with proper path configurations and though this solves the path config error, as expected it doesn't change the actual problem.)
Any help would be great!
Tessa

**Comment by hbarsnes** [comment]
Hi Tessa,

Would it be possible for you to share one of the smaller failing FASTA files? Then I can try to reproduce the issue on my end and hopefully locate the problem?

Best regards,
Harald

**Comment by TessaGillett** [comment]
Thank you for the quick reply! I just realised that the file that I thought was much smaller, is actually twice as big, so I don't think I can add it here. Do you have an email address I can send it to through WeTransfer?

**Comment by hbarsnes** [comment]
> Do you have an email address I can send it to through WeTransfer?

You can send the download link to harald.barsnes AT gmail.com.

**Comment by TessaGillett** [comment]
Ah, found the problem. There was a duplicate header in my fasta file - my bad. Thanks for the help!

(Even though this shouldn't happen, it might be useful to add an error message for when it does?)

**Comment by hbarsnes** [comment]
The error messages are currently hidden in the SearchGUI log file (SearchGUI-X.Y.Z\resources\SearchGUI.log). This is of course not optimal. We fixed this recently for the other command lines, where the stack trace is still sent to the log file, but an error message referring to the log file is printed in the terminal. But we seem to have forgotten the FastaCLI. Will correct this and release a new version as soon as possible.

**Comment by TessaGillett** [comment]
Hi Harold,
Just to get back to you on that: I do think it's something that has happened other times as well as I've been using SearchGUI/PeptideShaker these last few weeks. (The lack of error messages, I mean.) I think I opened another issue a few weeks ago where I accidentally added two non-existent flags to my command and SearchGUI stopped working without any pointers towards the cause (as far as I remember anyway - I might be mistaken). And at the moment I'm grappling with a `<CompomicsError>PeptideShaker processing failed. See the PeptideShaker log for details.</CompomicsError>` where there in fact isn't anything in the logfile but a few lines on the amounts of memory and version info.

Do you think there could be something in my setup causing this? I'm running SearchGUI/PeptideShaker through a snakemake pipeline, but I don't think that should interfere.

**Comment by hbarsnes** [comment]
Hi Tessa,

The improved error handling was added in SearcGUI v3.3.10 and PeptideShaker v1.16.36. So first, please make sure that you are using the latest versions.

Also, make sure that the log file is actually used. You can change the paths to the temp folders via PathSettingsCLI (either via SearchGUI or PeptideShaker). See the wiki for details.

A final tip, if the SearchGUI to PeptideShaker pipeline fails, it may be easier to debug the two separately and then later put them together once the issue has been resolved.

Best regards,
Harald

**Comment by TessaGillett** [comment]
Hi Harald,
Thanks again for the quick reply! You're right, I forgot that I did have a look previously whether the command would run outside of the pipeline, but I got the same result. Turns out I'm using v1.16.35 though, so I'll update it and see what happens.

**Comment by TessaGillett** [comment]
Found the problem! Thanks again for all the help.
