### ISSUE TITLE
Error when failing to write files

### ISSUE THREAD

**Issue by iustin94** [compomics/searchgui#200]
Hi, 
I am running the searchCLI in a docker container with mounted volumes. I have this issue that sometimes I forget to run the docker container as sudo and the searchCLI is not able to write the files to the volume because of lack of privileges. At the same time, it does not throw any error regarding this, instead it finishes quietly. Is there a way to get feedback from searchCLI on whether or not it was able to write the result files?

**Comment by CarlosHorro** [comment]
Hi,

I've been testing SearchCLI in Docker with mounted volumes. After removing permissions to write on the output folder, I can see this output when executing SearchCLI:
```

Tue Jan 22 13:28:56 GMT 2019 Error: /myresources-out/searchgui_out.zip (Permission denied)
Tue Jan 22 13:28:56 GMT 2019 An error occurred while running SearchGUI. Please contact the developers.
Tue Jan 22 13:28:56 GMT 2019 The search or processing did not finish properly!
Tue Jan 22 13:28:56 GMT 2019 Failed to write to the report file!

```

Don't you receive this type of output?
I'm executing SearchCLI like this:
`
docker run -v /Users/carlos.horro/shared/docker-searchgui:/myresources -v /Users/carlos.horro/shared/docker-searchgui-out:/myresources-out quay.io/biocontainers/searchgui:3.3.9--1 searchgui eu.isas.searchgui.cmd.SearchCLI -spectrum_files  /myresources/qExactive01819-done-via-DockerGUI.mgf -output_folder /myresources-out -id_params  /myresources/SEARCHGUI_IdentificationParameters.par`

**Comment by CarlosHorro** [comment]
Are there any news about this issue?

**Comment by iustin94** [comment]
Hi! No, I didn't get around to trying to reproduce it. I guess the issue
can be closed.
