### ISSUE TITLE
SearchCLI on a cluster

### ISSUE THREAD

**Issue by getiria-onsongo** [compomics/searchgui#201]
I would like to run SearchCLI on a cluster with multiple nodes that use the PBS scheduler. Is there a utility for running SearchCLI on a cluster that harnesses the power of multiple nodes?

**Comment by hbarsnes** [comment]
Hi Getiria,

We don't have any specific setups for running SearchCLI on a cluster. The closest is the Pladipus project (https://compomics.github.io/projects/pladipus.html), although I don't think this is really what you want?

However, as SearchCLI simply searches one mgf file at the time it should not be too difficult to spread this across a cluster. You could also consider running the individual search engine on separate nodes for the same mgf file, but not sure how to optimize this approach.

Best regards,
Harald

**Comment by getiria-onsongo** [comment]
Thanks!
