### ISSUE TITLE
Providing the name of the output zip in SearchGUI command

### ISSUE THREAD

**Issue by ypriverol** [compomics/searchgui#202]
@hbarsnes would be great if we can provide to the command `java -cp SearchGUI-X.Y.Z.jar eu.isas.searchgui.cmd.SearchCLI` the output name of the zip we want to generate and not only a name of a folder.

**Comment by hbarsnes** [comment]
Should not be a problem. Will try to implement it and release a new version as soon as possible.

**Comment by hbarsnes** [comment]
Support for controlling the name of the zip file is now available via the new SearchCLI option -output_default_name in SearchGUI v3.3.13.
