### ISSUE TITLE
Adding modification through command line

### ISSUE THREAD

**Issue by EhsanIrajizad** [compomics/searchgui#207]
Hello,

Could you please let me know how can I add modification through command line?
I have already added using the interface, but I can not see them when I want to run the software using the command line.

Modifications are:
Hypusine | H(9) C(4) N O | 87.068414 | K
Deoxyhypusine | H(9) C(4) N | 71.073499 | K, Q
Spermine | H(16) C(7) N(2) | 128.131349 | Q
Spermidine | H(23) C(10) N(3) | 185.189198 | Q
Acetyldeoxyhypusine | H(11) C(6) N | 97.089149 | K
Acetylhypusine | H(11) C(6) N O | 113.084064 | K

Thanks a lot,
Ehsan

**Comment by hbarsnes** [comment]
Hi Ehsan,

There is currently no support for adding modifications via the command line, but modifications added via the graphical interface should be available for use on the command line. The modifications are stored in the file .compomics\ptmFactory-X.Y.Z.json which you as a default will find in your user home folder. So if using the command line on a different machine than the one used for create the modifications, be sure to move this file as well.

Best regards,
Harald

**Comment by EhsanIrajizad** [comment]
Thanks for your suggestion.
Now it is working!
Thanks
