### ISSUE TITLE
Progenesis + SearchGUI

### ISSUE THREAD

**Issue by m-i-c-h-ael** [compomics/searchgui#208]
Hi all,
I believe to have seen somewhere that SearchGUI/PeptideShaker can be used with ProgenesisQI for quantification. Which data-format do I need to export from Progenesis for this?
I tried with 'Mascot' (.mgf) for which the search in SearchGUI seemed to work OK, but PeptideShaker doesn`t.
From the log:
Mon Mar 04 11:25:04 CET 2019: PeptideShaker version 1.16.38.
Memory given to the Java virtual machine: 18641584128.
Total amount of memory in the Java virtual machine: 128974848.
Free memory: 118019256.
Java version: 1.8.0_201.
java.lang.NullPointerException
	at com.compomics.util.experiment.biology.Peptide.getPotentialModificationSites(Peptide.java:1067)
	at com.compomics.util.experiment.biology.PTMFactory.getExpectedPTMs(PTMFactory.java:436)
	at eu.isas.peptideshaker.fileimport.PsmImporter.importAssumptions(PsmImporter.java:526)
	at eu.isas.peptideshaker.fileimport.PsmImporter.importPsm(PsmImporter.java:331)
	at eu.isas.peptideshaker.fileimport.PsmImporter.access$000(PsmImporter.java:69)
	at eu.isas.peptideshaker.fileimport.PsmImporter$PsmImporterRunnable.run(PsmImporter.java:1415)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

(Progenesis version is 4.1.6675.48614; PeptideShaker-1.16.38 and SearchGUI-3.3.13 are run on Windows 7 64-bit.)

Thank you.

**Comment by hbarsnes** [comment]
Hi Michael,

Exporting to mgf from Progenesis is the correct option. The error you are seeing is rather a general issue in PeptideShaker with regards to the handling of post-translational modifications. Which search engines are you using? And which post-translational modifications?

BTW, when getting the PeptideShaker identifications back into Progenesis you should use the Progenesis export option found in the Export > Follow Up Analysis menu option.

Best regards,
Harald

**Comment by m-i-c-h-ael** [comment]
Hi Harald,

thanks a lot for the quick response.
I`m indeed using quite a few and some strange mods: 
Fixed: Carbamidomethyl
Variable: Phoshpo on S,T,Y, Dehydration of S and T and a self defined modification (+43.00)  on S and T.

Search engine is MS-GF+.

Thank you,
Michael

**Comment by hbarsnes** [comment]
Hi Michael,

I'd recommend reducing the number of variable modifications if possible. Or consider if you can make more of them fixed?

Switching the search engine is also an option. X! Tandem is usually the one that results in less issues when it comes to handling the modifications.

Finally, you can try some of the suggestions I recently made at the end of this issue: https://github.com/compomics/peptide-shaker/issues/348.

Best regards,
Harald

**Comment by m-i-c-h-ael** [comment]
Hi,
I already started a new search only with phosphorylation to see if this works.

For this project it would be kind of important to have these many mods, but I`ll see if I can loose one or two. How will searchGUI handle a fixed and variable mod on the same residue? Will it add the variable on top of the fixed or instead? Or is this not possible at all? (Or depend on the individual search engine?)

I`ll also try X!Tandem instead and reducing to 1 core.

Best,
Michael

**Comment by hbarsnes** [comment]
Hi Michael,

> How will searchGUI handle a fixed and variable mod on the same residue? Will it add the variable on top of the fixed or instead? Or is this not possible at all? (Or depend on the individual search engine?)

This depends on the search engine, with perhaps the exception being terminal modifications which (as far as I remember) can always be combined with a modification on the side chain of the first/last amino acid.

Best regards,
Harald

**Comment by m-i-c-h-ael** [comment]
Hi,
I played around a bit more with the searches and it seems the problem is coming from the modification I defined myself. As this is not in Unimod I had left the "Accession" and "PSI-MS Name" blank.
Do you think this may be the cause of the problem? If so, do I need to add my modification to Unimod or should I make up an accession and name to continue?

Thank you!

**Comment by hbarsnes** [comment]
Hi Michael,

The mapping to Unimod is only relevant when exporting the data as mzIdentML and does not have any impact on the error above.

If none of the other suggestions worked, I'm afraid you will have to wait for the new version of PeptideShaker that we are currently working on. It should hopefully solve the problem. I cannot at this time give you a timeline for when the new version will be available, but we are at the stage of trying to sort out the last remaining issues.

I will let you know as soon as the new version is available for testing.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Michael,

This issue should hopefully be solved in the new beta releases of SearchGUI and PeptideShaker. 

Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.
If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

If the issue has been solved, it would also be great of you could let us know by replying to this original issue. :)

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved with the release of the new versions of the tools. If this is not the case, please let us know and we'll reopen the issue.
