### ISSUE TITLE
automatic update broken in conda installation

### ISSUE THREAD

**Issue by mglubber** [compomics/searchgui#210]
I installed SearchGUI through conda (i.e. `conda install -c conda-forge -c bioconda searchgui`) on Ubuntu 16.04, which installed version 3.3.10-0. When starting SearchGUI, the 'new version available' popup appears, and if I select "Yes" to update,  the new version (3.3.13) is downloaded to `$CONDA_ENV_PATH/bin/searchgui`. 

However, SearchGUI is started through `$CONDA_ENV_PATH/bin/searchgui` which is a symlink to the python script `$CONDA_ENV_PATH/share/searchgui-3.3.10-0/searchgui`.  This means that despite the new version being downloaded, the old version is run, and the next time I start the program I'm prompted to update again. 

If I copy the `searchgui` python script to the directory of the new version, update the `jar_file` variable in the script to the new version number (`jar_file = 'SearchGUI-3.3.13.jar'`), and change the symlink at `$CONDA_ENV_PATH/bin/searchgui` to the new directory ( `$CONDA_ENV_PATH/share/searchgui-3.3.10-0/searchgui -> $CONDA_ENV_PATH/share/SearchGUI-3.3.13/searchgui`), everything launches correctly. 

The new version of SearchGUI that's automatically downloaded doesn't include the `searchgui` python script, or another script called `conda_build.sh`. 

If the automatic updates can't be made to handle installation through conda, the check should be disabled by default. Also, the version of SearchGUI isn't actually shown anywhere in the GUI that I can find (i.e. the 'Help' or 'About' windows), which makes confirming the running version difficult.

**Comment by CarlosHorro** [comment]
Hi Mark,

You are right about we didn't foresee this mixed scenario using Conda packages and PeptideShaker's standard update mechanism. As this procedure is and must be kept apart from Conda, and packages installed via Conda should be kept updated just using Conda mechanisms, I think we should disable the check just when detecting the app installed into a Conda environment.

About SearchGUI version, it's shown when initialising the app, in the title of the initial window (the one with the inputs, outputs, search engines and so).

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
Hi, last updates seem to properly manage this issue, so I close it unless it is seen that something related has not been resolved.

Greetings,
Carlos
