### ISSUE TITLE
FastaCLI 

### ISSUE THREAD

**Issue by bernt-matthias** [compomics/searchgui#212]
Problem with FastaCLI that is running within the latest Galaxy wrappers (ie searchgui version 3.3.10): 

```
searchgui -Djava.awt.headless=true eu.isas.searchgui.cmd.FastaCLI --exec_dir="$cwd/bin" -in input_database.fasta -decoy
```

does not create any output.

outputs "Reindexing: input_database.fasta." 

end exits with exit code 0

here is the used input file: [input_database.txt](https://github.com/compomics/searchgui/files/3084941/input_database.txt)

**Comment by hbarsnes** [comment]
When running this locally I get the following error in the SearchGUI log file:

```
java.lang.IllegalArgumentException: Accession numbers cannot contain quotation marks: 'NP_414689.4 2'-5' RNA ligase [Escherichia coli str. K-12 substr. MG1655]'!
Please check your FASTA file.
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.createFastaIndex(SequenceFactory.java:817)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getFastaIndex(SequenceFactory.java:711)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getFastaIndex(SequenceFactory.java:641)
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:582)
	at eu.isas.searchgui.cmd.FastaCLI.call(FastaCLI.java:81)
	at eu.isas.searchgui.cmd.FastaCLI.<init>(FastaCLI.java:65)
	at eu.isas.searchgui.cmd.FastaCLI.main(FastaCLI.java:192)
```

In other words, you need to reformat your FASTA headers to remove the quotations from the accession numbers. 

BTW, you should get the same stacktrace in your log file?

**Comment by bernt-matthias** [comment]
Thanks for the answer. Need to check with the user. Might need a bit.

Do you think that it would be a good idea to present these log files to the user (in Galaxy or in general). Maybe indirectly by adding it the stderr? Would this be achieved by omitting the `-log` parameter from the `PathSettingsCLI`. 

Galaxy could then use this to provide a meaningful error.

**Comment by hbarsnes** [comment]
> Do you think that it would be a good idea to present these log files to the user (in Galaxy or in general). Maybe indirectly by adding it the stderr?

That is what we used to do before, but then the logs would get lost when the command line window was closed (at least if running outside of Galaxy). Which is why we started referring the users to the log file instead. But maybe this was not implemented in the SearchGUI version currently in Galaxy.

> Would this be achieved by omitting the -log parameter from the PathSettingsCLI.

No, omitting the -log parameter will send the log to the standard log file instead. Not sure if that even works on Galaxy.

**Comment by bernt-matthias** [comment]
In Galaxy the log file is just saved and nothing is done with it (only the admin might have a look). I guess appending (or prepending??) it to the stderr might be helpful. I could do this.

**Comment by hbarsnes** [comment]
The thing is that the log file also contains the full stack trace, which is something most users will not understand or care about. And generally, it is much cleaner to refer to the log file than to print potentially long stack traces to the command line window (again thinking of the non-Galaxy users here).

**Comment by bernt-matthias** [comment]
Just talking about Galaxy and its users. Currently neither Galaxy nor Galaxy users know about or have a chance to get the log file. 

The consequence for Galaxy itself is that it can't even detect that something went wrong (exit code seems to be zero) .. eventual messages on stderr/out (can't tell from my mind if there are any) may be to unspecific. If Galaxy would know about the error message (i.e. its in stderr / stderr) it could output something meaningful to the user (using the stdio tag).

Same hold for the users. Most of them won't even check the stderr (my experience) but report the error to the admin-- so it won't hurt them. Plus if Galaxy stdio parser would transform the Trace in a simple error message many of these cases might be avoided.

**Comment by hbarsnes** [comment]
In SearchGUI v4.0.28 we have added a new command line option -use_log_folder that if set to 0 ensures that both logs and errors are written to the standard output. This should make the error details and stack traces visible in settings where the log file option cannot be used, e.g. on Galaxy.

**Comment by bernt-matthias** [comment]
Is this option also availabale for SearchCLI, IdentificationParametersCLI, and PeptideShakerCLI in the latest versions? 

I just update the bioconda recipes and Galaxy wrappers.

**Comment by hbarsnes** [comment]
>Is this option also availabale for SearchCLI, IdentificationParametersCLI, and PeptideShakerCLI in the latest versions?

Ah, sorry, I only implemented it for SearchCLI and PeptideShakerCLI. I will have to look into IdentificationParametersCLI, FastaCLI, and others, and as well of course.

I'll reopen the issue until these have also been updated.

**Comment by hbarsnes** [comment]
> Is this option also availabale for SearchCLI, IdentificationParametersCLI, and PeptideShakerCLI in the latest versions?

Just released new versions in which the options are now available for all the CLIs.
