### ISSUE TITLE
nucleotide searching instead of amino acid search

### ISSUE THREAD

**Issue by EhsanIrajizad** [compomics/searchgui#213]
Hi,

Can we have nucleotide database and search against nucleotide instead of amino acid sequence in searchgui?

In another word, I want to find a new protein in my samples that does not exist in uniprot and I do not know the exact sequence but I know the gene name and I want to see what part of the gene has been translated.

Thanks a lot,
Ehsan

**Comment by mvaudel** [comment]
Hi Ehsan,

I am afraid SearchGUI cannot do the translation for you, you will need to use a dedicated tool to create the amino acid sequence and use this one in SearchGUI.

Hope it helps,

Marc
