### ISSUE TITLE
[Request] Implementation of new version MS-GF+

### ISSUE THREAD

**Issue by tivdnbos** [compomics/searchgui#214]
Hi,

I had some issues running Percolator and msgf2pin with the .mzid files of MS-GF+ in SearchGUI, which I didn't had when running MS-GF+ alone. I solved it by replacing the MS-GF+ jar file in SearchGUI by the newest version of MS-GF+, version 18 april 2019.
Can you implement the newest version in the next version of SearchGUI?

Thanks,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

Yes, we will update the MS-GF+ version in the next major release of SearchGUI. I just did some tests and the new MS-GF+ version seems to work fine in both SearchGUI and PeptideShaker as far as I can tell. There are some other unrelated issues we need to sort out first though. But I guess you have a fix that works for now anyway?

Best regards,
Harald

**Comment by tivdnbos** [comment]
Hi Harald,

Indeed, I have a fix that works.

Best regards,
Tim
