### ISSUE TITLE
Disagreement results

### ISSUE THREAD

**Issue by jordur** [compomics/searchgui#216]
Dear all, 
first of all apologize if this question will not be posted in the appropiate place . Don't hesitate to let me know the correct way to do it.
I am in charge of a bioinformatic shift from mascot searches to searchgui+peptideshaker since  our lab would be glad if they could use our obtained transcriptome sequences instead of NCBI or SwissProt databases. Moreover, I am on the way to convince them of a standalone software usage.
However, in order to convince them about that I should obtain similar results from some .pkl (that I transformed to .mgf with pride-inspector). In this sense, some interesting peptides were found with mascot as attached Figure1.
![Figure1](https://user-images.githubusercontent.com/3415289/60505998-2c770a00-9cc5-11e9-81a7-05f3228f8363.png)
Then, I tried to obtain similar results with SearchGUI with similar parameters regarding modified and fixed modifications, tolerance..etc.
Results don't agree at all :(
Moreover, I was able to find the peptide sequence found by Mascot on my transcriptome so I am not sure if the suite searchgui+peptideshaker could be useful or even the fact that our starting material seems to be scarce (venom proteins) could be a drawback in this case.
In advice will be really appreciated.
**Edited**: I found that while mascot found y ions, searchgui found b ions. Since I am not used to work with proteomic data I am not sure if that is a common issue or, instead, I can fix from SearchGUI menu.
Thank you for your hepl in advance

**Comment by hbarsnes** [comment]
Hi,

The search results will be somewhat dependent on the search engine used, but if the same (or very similar) search settings are used the differences are usually not that big.

Could you also share a screenshot of what you get from processing the same data in SearchGUI and PeptideShaker? And perhaps also a screenshot of the search settings used in SearchGUI vs. the ones used in Mascot?

Best regards,
Harald

PS: If you haven't already done so, it might also be worth taking a look at our tutorial material, especially chapter 1: https://compomics.com/bioinformatics-for-proteomics.

**Comment by jordur** [comment]
Hi @hbarsnes ,
thank you for your answer. I have already done your material since a workmate did a course years ago and actually this is the reason to let a try to SearchGUI and PepetideShaker. Thank you for your suggestion!
Here are required screenshots. I have done similar analysis for the same ,mgf (originally .pkl) file. In fact, you can see the diference on title 17. Same spectra but different identifications according to ion y or ion b selection: 
SearchGUI and PeptideShaker results:
![PS_CT10_results](https://user-images.githubusercontent.com/3415289/60521652-eb442180-9ce7-11e9-8d5f-0a8f1eab5751.png)
Mascot results:
![Mascot_Ct10_results](https://user-images.githubusercontent.com/3415289/60521674-f434f300-9ce7-11e9-8e9d-f701a409056b.png)
Those files were obtained with the following settings:
SearchGUI and PeptideShaker settings:
![PS_settings](https://user-images.githubusercontent.com/3415289/60521768-1dee1a00-9ce8-11e9-91fa-8ca87f8d628b.png)
![PS_settings_2](https://user-images.githubusercontent.com/3415289/60521776-2181a100-9ce8-11e9-89a6-c8092fef1fff.png)

And Mascot settings:
![mascot_settings](https://user-images.githubusercontent.com/3415289/60521797-27778200-9ce8-11e9-8a89-525d9f4d4bfe.png)

As you can see I used 5 different search engines with SearchGUI. Now, I am trying to set some advanced settings in order to reproduce mascot results.
Thank you very much for your help!

**Comment by hbarsnes** [comment]
Hi again,

Please check the "Precursor m/z Tolerance" setting in SearchGUI as it's now set to 1 **ppm**. In order to make it the same as the Mascot search you need to change it to 1.2 **Da**. And while you're at it, please also change the "Fragment m/z Tolerance" from 0.5 Da to 0.6 Da, again to make the settings the same.

Best regards,
Harald

**Comment by jordur** [comment]
Hi again!
You are absolutely right! I'm ashamed!  For those interested in that issue (Da or ppm) you will find some information [here](https://proteomicsnews.blogspot.com/2018/07/ppm-or-da-what-to-use-and-when-in-data.html). In fact, from your tutorial material, one question stands "What is the difference between using a mass tolerance in ppm or Dalton?". However, I was unable to find what I suspect is the [1.3e] answer ;)
Setting identical search conditions, SearchGUI improved results obtained from Mascot, since it finds a peptide not found with Mascot.
Thank you so much for your help! It has been really useful. 
I have a couple of questions now but I don't want to merge topics ;)
Kind regards,

**Comment by hbarsnes** [comment]
Hi,

Great! I will then close the issue, but feel free to open new ones if you have more questions.

As for the answer to question 1.3e, you can find all our suggested answers [here](https://drive.google.com/open?id=0B4sW8rLWPbRyV1ZnaVZoaHktWlE).

Best regards,
Harald
