### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by iquasere** [compomics/searchgui#217]
Greetings

I have been using searchcli before without an itch (great tool!) but recently I have begun getting this messages.
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/home/jsequeira/anaconda3/share/searchgui-3.3.10-0/lib/gson-2.4.jar) to field java.awt.Color.value
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Everything still seems to be working fine, however, I wanted to know if you are aware of this illegal reflective accesses and know if they will be a problem in the future. I started getting this warnings after I migrated from your standard SearchCLI to Cobra's SearchCLI. Could the Cobra environment be the problem? Or do the versions hosted here at github have the same warnings? (and possible impending doom)

Thank you for your attention
JS

**Comment by hbarsnes** [comment]
Hi JS,

As far as I know this error is specific to the Java version used and does not appear when using the standard Oracle versions, only with Open JDK. But unless it causes other issues I think it can safely be ignored.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.

**Comment by iquasere** [comment]
Sorry, I forgot about this issue. At the time, this was caused by using conda's searchgui, and I solved it by using the [searchgui distribution](http://genesis.ugent.be/maven2/eu/isas/searchgui/SearchGUI/3.3.16/SearchGUI-3.3.16-mac_and_linux.tar.gz) available at Gent University.
