### ISSUE TITLE
The parameter choose of TMT-10plex labeled data

### ISSUE THREAD

**Issue by ZJQcarrie1s** [compomics/searchgui#218]
Dear searchGUI team,

I tried to use SearchGUI with my TMT 10-plex labeled data of 10 different mixed samples, but when I choose the 'TMT 10-plex of K' and 'TMT 10-plex of peptide N-term' as variable modification, the output files only give some information like

`<Peptide id="PEP_270739">
      <PeptideSequence>EPIISSEEQKQLMLYYHRR</PeptideSequence>
      <Modification location="0" avgMassDelta="229.162932" monoisotopicMassDelta="229.162932">
        <cvParam cvRef="MS" accession="MS:1001460" name="unknown modification" value=""/>
      </Modification>`

 (↑above are MyriMatch searching results) There are only modification mass of 229.162932 in output files), but no information of reporter ions such as 126, 127C, 127N, 128C, 128N, 129C, 129N, 130C and 131N. I need to separate my 10 samples based on reporter ions or monoisotopic reporter mass, while I don't know how to set parameters correctly. Would you like to give me some information on how to do this? Thank you very much. 

Regards
Carrie Chou

**Comment by ZJQcarrie1s** [comment]
'I need to separate my 10 samples based on reporter ions or monoisotopic reporter mass'
Sorry I missed one word 'samples' above.

**Comment by hbarsnes** [comment]
Hi Carrie,

Have you had a look at our tutorials? If not, I'd recommend checking out the one about quantification using reporter ions. You can find it here: https://compomics.com/bioinformatics-for-proteomics/quantification.

Hopefully this will provide you the answers you need. If not, please let us know.

Best regards,
Harald

**Comment by ZJQcarrie1s** [comment]
> Hi Carrie,
> 
> Have you had a look at our tutorials? If not, I'd recommend checking out the one about quantification using reporter ions. You can find it here: https://compomics.com/bioinformatics-for-proteomics/quantification.
> 
> Hopefully this will provide you the answers you need. If not, please let us know.
> 
> Best regards,
> Harald



> Hi Carrie,
> 
> Have you had a look at our tutorials? If not, I'd recommend checking out the one about quantification using reporter ions. You can find it here: https://compomics.com/bioinformatics-for-proteomics/quantification.
> 
> Hopefully this will provide you the answers you need. If not, please let us know.
> 
> Best regards,
> Harald

Hi Harald,
Thank you for your kind reply! I have read the tutorials, but it seems not helpful for solving my problem. I'd like to describe my problem as simply as I can.
That is, I have a .mgf phosphoproteome data with 10 different samples labeled with TMT 10-plex, and I searched for phosphorylation sites with searchGUI (e.g MyriMatch), I set 'TMT 10-plex of K' and 'TMT 10-plex of peptide N-term' as fixed modification and 'Phosphorylation of S', 'Phosphorylation of T' and 'Phosphorylation of Y' as variable modifications, then I got the searching result. I only want to know these phosphorylation sites come from which sample of 10 via the information provided by output file such as .myrimatch.mzid in 'searchgui_out.zip'.
By the way, can the quantification results of Reporter 0.7.20 be saved as a text file? If can, it will be more helpful for me.
Looking forward to your reply. Thanks again.

Best regards,
Carrie

**Comment by hbarsnes** [comment]
Hi Carrie,

> I only want to know these phosphorylation sites come from which sample of 10 via the information provided by output file such as .myrimatch.mzid in 'searchgui_out.zip'.

To get this information you have to process/extract the reporter ions from the search output. This is not done in the search engines themselves, but rather in follow-up tools such as Reporter (http://compomics.github.io/projects/reporter.html).

> By the way, can the quantification results of Reporter 0.7.20 be saved as a text file? If can, it will be more helpful for me.

Yes. Please check out the Export options at the top of the main windows of Reporter.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

I forgot to mention that I would recommend changing the two TMT modifications to fixed instead of variable. It would speed up the search and in most cases you would expect these to be there for close to 100% of the peptides if the TMT labelling has worked correctly.

Best regards,
Harald

**Comment by ZJQcarrie1s** [comment]
> Hi again,
> 
> I forgot to mention that I would recommend changing the two TMT modifications to fixed instead of variable. It would speed up the search and in most cases you would expect these to be there for close to 100% of the peptides if the TMT labelling has worked correctly.
> 
> Best regards,
> Harald

Hi Harald,

Thank you for your patience! Now I finally have understood and worked out. The 3 tools are excellent and I will continue to study them.

Thanks again!

Best regards,
Carrie

**Comment by hbarsnes** [comment]
Hi Carrie,

Great! I will then close the issue, but please don't hesitate to open a new one if you have more questions later on.

Best regards,
Harald
