### ISSUE TITLE
MS-GF+ search failed

### ISSUE THREAD

**Issue by AnkeTraut** [compomics/searchgui#219]
Hello everybody,

I started working with SearchGUI some weeks before. Now I want to use a huge database (82 million entries) for a new project. For the first search I chose only X!Tandem and MS-GF+. After some hours I got first outputs from SearchGUI but only for X!Tandem. Here you can find output of the report:
...
Search progress: 30 / 30 tasks, 100,00%		1,12 hours elapsed
Writing results...
java.lang.NullPointerException
	at edu.ucsd.msjava.mzid.MZIdentMLGen.getDBSequence(MZIdentMLGen.java:671)
	at edu.ucsd.msjava.mzid.MZIdentMLGen.getPeptideEvidenceList(MZIdentMLGen.java:629)
	at edu.ucsd.msjava.mzid.MZIdentMLGen.addSpectrumIdentificationResults(MZIdentMLGen.java:347)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:391)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:105)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:56)

Fri Sep 20 13:54:59 CEST 2019        MS-GF+ finished for E:\180320_A_01.mgf (2 hours 7248.0 seconds).

Fri Sep 20 13:55:20 CEST 2019        Could not find MS-GF+ result file for 180320_A_01.mgf.
...

Have you any idea what happened? Is my database to big? Or are any other problems possible?

Thanks for helping
Anke

**Comment by hbarsnes** [comment]
Hi Anke,

This looks like a problem inside MS-GF+ and thus outside of our control. I'd recommend contacting the MS-GF+ developers directly via https://github.com/MSGFPlus/msgfplus. Hopefully they will be able to locate the source of the issue and potentially release a new version of MS-GF+ that we can then include in SearchGUI.

Best regards,
Harald

**Comment by AnkeTraut** [comment]
Hi Harald,

thank you very much for the fast answer. I will ask the MS-GF+ developer.

Best regards,
Anke

**Comment by hbarsnes** [comment]
For anyone else coming across this issue with MS-GF+ please see
see https://github.com/MSGFPlus/msgfplus/issues/77 for the followup by the MS-GF+ developers.
