### ISSUE TITLE
MS Amanda fails when parsing MGF files

### ISSUE THREAD

**Issue by MarcIsak** [compomics/searchgui#220]
Hi, 

I am using SearchGUI v.3.3.16, and tried to use MS Amanda as one of the search engines, along with X!tandem and Comet. While both X!Tandem and Comet managed to analyze each of my input MGF files, MS Amanda failed to analyze any of them. An example error message is:

_Thu Oct 10 23:28:13 CEST 2019        Processing Marc_P1908_284.mgf with MS Amanda.

Reading settings file...
Settings file successfully read.
Input files contain 81760 spectra

Searching file 'Marc_P1908_284.mgf'...
Error parsing mgf file at or after spectrum 'Marc_P1908_284.10.10.3 File:"Marc_P1908_284.raw", NativeID:"controllerType=0 controllerNumber=1 scan=10"'.
Error in parsing: RTINSECONDS=3.5201364
Search failed._

See attached report file. 

[report_1.txt](https://github.com/compomics/searchgui/files/3716253/report_1.txt)

First I converted my RAW files to MGF files with the standalone MSConvert. But since MS Amanda failed, I tried instead to generate the MGF files within SearchGUI followed by MS Amanda. It did not work either unfortunately. I noticed that the resulting MGF files differ in size depending on whether you use MSConvert as a standalone(Larger size) or within SearchGUI(Smaller sizes). 

Since both X!Tandem and Comet managed to analyze the files, one can assume that the MGF files aren't corrupt. 

Any ideas what could be wrong here? 

Best,

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

It would seem like MS Amanda has a problem reading your retention time values. I don't see anything wrong with them though. I would recommend contacting the MS Amanda developers directly at https://groups.google.com/forum/#!forum/msamanda. Hopefully they will be able to locate the source of the problem and potentially release a new version that we can then include in SearchGUI.

> I noticed that the resulting MGF files differ in size depending on whether you use MSConvert as a standalone(Larger size) or within SearchGUI(Smaller sizes).

I would guess that you are not using peak picking when using MSConvert as a standalone? As this is the default when running MSConvert via SearchGUI. You can however change this in the MSConvert settings by clicking the related cogwheel icon.

Best regards,
Harald

**Comment by MarcIsak** [comment]
Hi Harald, 

I got in touch with one of the MS Amanda developers. Apparently, the bug that I reported here has been solved for the latest MS Amanda version. So, if SearchGUI incorporates the latest MS Amanda version, my issues should be solved. 

Best, 

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

> I got in touch with one of the MS Amanda developers. Apparently, the bug that I reported here has been solved for the latest MS Amanda version.

Yes, I saw that. I'm on the MS Amanda list as well. :)

The latest MS Amanda version is already included in a beta version of SearchGUI, which will hopefully become available soon. I will let you know when it can be downloaded. In the meantime I guess you can use the trick suggested by Victoria?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Marc,

We've now released new beta versions of SearchGUI and PeptideShaker (please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details), which among lots of other things, updates the MS Amanda version in SearchGUI to the latest release.

Perhaps you can give it a go and see if you experience the same issues as when manually updating the MS Amanda version in SearchGUI?

Best regards,
Harald

**Comment by MarcIsak** [comment]
Hi Harald, thanks for the new release. I am trying it out now. Unfortunately, the issues with MS Amanda are still around. This time I loaded other RAW-files into SearchGUI 4.0.0-beta, and used the in-built new ThermoRawFileParser for the conversion into MGF. But I go the following output from MS Amanda for one of the files: 

_Thu Nov 28 10:47:29 CET 2019        Processing Marc_P1812_181.mgf with MS Amanda.

Using output fileformat .csv
Using output filename 'D:\Data_SearchGUI\Output\.SearchGUI_temp\Marc_P1812_181.ms-amanda.csv'
Reading settings file...
Settings file successfully read.
Perform Search
Input files contain 90230 ms2 spectra
Searching file 'Marc_P1812_181.mgf'...
Error parsing mgf file at or after spectrum 'controllerType=0 controllerNumber=1 scan=136'.
Search failed.

Thu Nov 28 10:47:30 CET 2019        MS Amanda finished for D:\MS_files\hfx_marc_181219\Marc_P1812_181.mgf (1.7 seconds).

Thu Nov 28 10:47:30 CET 2019        Could not find MS Amanda result file for Marc_P1812_181.mgf._

This message is similar to the one I got after doing the modifications to SearchGUI 3.3.16, that Victoria Dorfer suggested in the MS Amanda Google group. Searching MGF-files with X!Tandem and Comet has never been a problem though, only MS Amanda gives me these issues.

Best,

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

Ok, so it seems clear that there still is an error in how MS Amanda parses your spectrum titles. We'll just have to wait for the MS Amanda developers to come up with a fix then. But as soon as the new version is available we'll include it in SearchGUI.

Best regards,
Harald

**Comment by hbarsnes** [comment]
For anyone else coming across the same problem with MS Amanda, please see https://groups.google.com/forum/#!topic/msamanda/l7PNtdHr9wY for the follow up by the MS Amanda developers.

(I will now close this issue as it is not really a SearchGUI issue. But we'll include the new MS Amanda version in SearchGUI as soon as it becomes available.)
