### ISSUE TITLE
mzML format instead of MGF

### ISSUE THREAD

**Issue by MarcIsak** [compomics/searchgui#221]
Hi, 

I wonder if it would be possible to include the option of using mzML files as spectra input, instead of MGF? I know that some of the included search engines can handle mzML, like Comet and X!Tandem. 

I have issues in importing my peptide search results from the SearchGUI - PeptideShaker workflow, as Skyline does not support MGF for chromatogram extraction but a lot of other spectra formats, such as mzML. 

Best,

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

Support for mzML has been on our wish list for a long time, but we simply have not had the resources to get around to implementing it. And I'm afraid this will not change in the immediate future, but we have not given up on getting to it at some point.

With regards to Skyline I think it should be fine to use the mzML file (of even the raw file) as input for the chromatogram extraction even though the mgf file was used as input for the search. As far as I remember Skyline is able to map between the two.

Best regards,
Harald

**Comment by hbarsnes** [comment]
New versions of SearchGUI and PeptideShaker have just been released and now include support for mzML as an additional spectrum input format.
