### ISSUE TITLE
Software do not keep the path of ProteoWizard

### ISSUE THREAD

**Issue by jpcouturepbs** [compomics/searchgui#222]
Hi there,
I've been trying to launch SearchGUI on a new computer we built, but I haven't been able to do so yet. For some reasons, when I add the path to the ProteoWizard software, SearchGUI seems to forget it. If i give the path, close the pop-up and reclick on the gear for ProteoWizard, the pop-up asking for the path for ProteoWizard comes again.

Also, I can't seem to change the memory allocation for searchGUI. If I add more memory, the software just do not keep it and reloads with the default 1.4G.

Can you help with this issue?
Thanks!
JP

**Comment by hbarsnes** [comment]
Hi JP,

Sounds like an issue with the resource settings. Please see Edit > Resource Settings and ensure that you are allowed to write into all the folders listed. You can also try setting the default path by right-clicking in the table and choose Set Default Path.

Best regards,
Harald

**Comment by jpcouturepbs** [comment]
That was exactly it, thanks a lot!
For some reasons, the pro version of Windows does not attributes the real admin powers to the admin. Really weird.

Anyways, we figured out how to do it.

Thanks again!

JP
