### ISSUE TITLE
New MS Amanda version

### ISSUE THREAD

**Issue by MarcIsak** [compomics/searchgui#223]
Hi Harald, 

I just got a message from one of the developers of MS Amanda. The issues I've experienced seems to have been solved. 

https://mail.google.com/mail/u/0/?tab=wm&pli=1#inbox/FMfcgxwDrlbPMlCXPzFPFjtVFQQDkmXt

So there's a new version of MS Amanda (v. 2.0.0.14665). There a download link in the message they sent me, so you can just click on the link attached here to find it. 

Best,

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

I've updated the beta release of SearchGUI to include the new MS Amanda version. You can find the links in in the message in the PeptideShaker group: https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM.

Please note that you will have to use the beta version of PeptideShaker to load the data from the beta version of SearchGUI.

Best regards,
Harald

**Comment by hbarsnes** [comment]
A new version of SearchGUI has just been released and now includes the latest version of MS Amanda.
