### ISSUE TITLE
SearchGui MZID not compatable with Scaffold

### ISSUE THREAD

**Issue by MJanech** [compomics/searchgui#227]
![2020-02-27_mzid_validation_screener_01](https://user-images.githubusercontent.com/61468641/75611518-1e45eb80-5ae9-11ea-94db-fa42bf36c9ad.png)
![2020-02-27_mzid_validator_screener_02](https://user-images.githubusercontent.com/61468641/75611519-1f771880-5ae9-11ea-9fa4-5a8bd92dc5cb.png)
[909c_DC1.msgf.mzid.validator_report.txt](https://github.com/compomics/searchgui/files/4270592/909c_DC1.msgf.mzid.validator_report.txt)
Uploading MZID files to visualize in Scaffold is occasionally successful but not always. The developers at Scaffold suggest the problem is that the MZID output by SearchGui include violations that are not tolerated by Scaffold. Attached are examples from a file generated from NIST serum reference material. The search engine selected was MS-GF.

**Comment by hbarsnes** [comment]
Aha, I thought you were referring to the PeptideShaker mzid exports (hence the moving of the issue), not the mzid exports from the individual search engines.

To request changes to the search engine mzid exports you have to contact the search engine developers directly, as we are not in control over these export formats or their formatting. But we will of course update the search eninge versions in SearchGUI if/when new versions become available.

For MS-GF+ you can contact the developers via https://github.com/MSGFPlus/msgfplus.

**Comment by MJanech** [comment]
Harald - Peptide shaker MZID output is also not compatible.

Mike

**Comment by hbarsnes** [comment]
> Harald - Peptide shaker MZID output is also not compatible.

Ah, ok. Can you send me the validation report for PeptideShaker as well then?

**Comment by hbarsnes** [comment]
> Harald - Peptide shaker MZID output is also not compatible.

I just validated the mzid export for the PeptideShaker example dataset and I did not get any errors btw.

**Comment by MJanech** [comment]
Harald – Thank you for the information. I’ll drop this line of inquiry.

Mike
