### ISSUE TITLE
SearchGUI stuck for two days

### ISSUE THREAD

**Issue by javanOkendo** [compomics/searchgui#231]
Path configuration completed.
Fri Apr 03 20:43:50 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T042_FT.mgf
Fri Apr 03 20:43:56 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T026_FT.mgf
Fri Apr 03 20:44:03 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T052_FT.mgf
Fri Apr 03 20:44:10 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T025_FT.mgf
Fri Apr 03 20:44:17 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T051_FT_R2.mgf
Fri Apr 03 20:44:24 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T053_FT.mgf
Fri Apr 03 20:44:31 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T062_FT_R2.mgf
Fri Apr 03 20:44:39 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T073_FT_R2.mgf
Fri Apr 03 20:44:46 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T061_FT_R2.mgf
Fri Apr 03 20:44:54 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T014_FT_R2.mgf
Fri Apr 03 20:45:02 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T077_FT.mgf
Fri Apr 03 20:45:07 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T069_FT_R2.mgf
Fri Apr 03 20:45:15 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T009_FT.mgf
Fri Apr 03 20:45:22 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T084_FT_R2.mgf
Fri Apr 03 20:45:30 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T064_FT_R2.mgf
Fri Apr 03 20:45:38 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T006_FT.mgf
Fri Apr 03 20:45:45 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T010_FT_R2.mgf
Fri Apr 03 20:45:53 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T075_FT.mgf
Fri Apr 03 20:46:00 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T054_FT.mgf
Fri Apr 03 20:46:07 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T037_FT.mgf
Fri Apr 03 20:46:14 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T080_FT.mgf
Fri Apr 03 20:46:21 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T049_FT.mgf
Fri Apr 03 20:46:28 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T007_FT_R2.mgf
Fri Apr 03 20:46:35 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T027_FT_R2.mgf
Fri Apr 03 20:46:43 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T011_FT_R2.mgf
Fri Apr 03 20:46:50 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T015_FT.mgf
Fri Apr 03 20:46:58 SAST 2020 Validating MGF file: /scratch/oknjav001/bal_mzML_raw_files/searchGUI/mgfSearchGUI/170909_CH_C1_T013_FT.mgf

makeblastdb command: 
/scratch/oknjav001/bal_mzML_raw_files/searchGUI/SearchGUI-3.3.17/resources/makeblastdb/linux/linux_64bit/makeblastdb -in HUMAN_uniprot-proteome_UP000005640_SG_191023_74034_concatenated_target_decoy.fasta 
-dbtype prot 

tide index command: 
/scratch/oknjav001/bal_mzML_raw_files/searchGUI/SearchGUI-3.3.17/resources/Tide/linux/linux_64bit/crux tide-index /scratch/oknjav001/bal_mzML_raw_files/searchGUI/SearchGUI-3.3.17/searchGUIAnalysis/HUMAN_u
niprot-proteome_UP000005640_SG_191023_74034_concatenated_target_decoy.fasta fasta-index --overwrite T --mods-spec C+57.021464,2M+15.994915 --nterm-peptide-mods-spec X+42.010565 --decoy-format none --outpu
t-dir crux-output --peptide-list F --verbosity 30 --min-length 6 --max-length 30 --min-mass 200.0 --max-mass 7200.0 --isotopic-mass mono --clip-nterm-methionine F --enzyme trypsin --missed-cleavages 2 --d
igestion full-digest 

ri Apr 03 20:47:06 SAST 2020 Indexing HUMAN_uniprot-proteome_UP000005640_SG_191023_74034_concatenated_target_decoy.fasta for Tide.

INFO: Beginning tide-index.
WARNING: The output directory 'crux-output' already exists.
Existing files will be overwritten.
WARNING: The file 'crux-output/tide-index.log.txt' already exists and will be overwritten.
INFO: CPU: srvcnthpc105.uct.ac.za
INFO: Crux version: 3.0.17109
INFO: Fri Apr  3 20:47:06 SAST 2020
INFO: Running tide-index...
WARNING: The output directory 'fasta-index' already exists.
Existing files will be overwritten.
INFO: Reading /scratch/oknjav001/bal_mzML_raw_files/searchGUI/SearchGUI-3.3.17/searchGUIAnalysis/HUMAN_uniprot-proteome_UP000005640_SG_191023_74034_concatenated_target_decoy.fasta and computing unmodified
 peptides...
INFO: Ignoring 30088 peptide sequences containing unrecognized characters
INFO: Reading proteins
INFO: Wrote 100000 peptides
INFO: Wrote 200000 peptides
INFO: Wrote 300000 peptides
INFO: Wrote 400000 peptides
INFO: Wrote 500000 peptides
INFO: Wrote 600000 peptides
INFO: Wrote 700000 peptides
INFO: Wrote 800000 peptides
INFO: Wrote 900000 peptides
INFO: Wrote 1000000 peptides
INFO: Wrote 1100000 peptides
INFO: Wrote 1200000 peptides
INFO: Wrote 1300000 peptides
INFO: Wrote 1400000 peptides
INFO: Wrote 1500000 peptides
INFO: Wrote 1600000 peptides
INFO: Wrote 1700000 peptides
INFO: Wrote 1800000 peptides
INFO: Wrote 1900000 peptides
INFO: Wrote 2000000 peptides
INFO: Wrote 2100000 peptides
INFO: Wrote 2200000 peptides
INFO: Wrote 2300000 peptides
INFO: Wrote 2400000 peptides
INFO: Wrote 2500000 peptides
INFO: Wrote 2600000 peptides
INFO: Wrote 2700000 peptides
INFO: Wrote 2800000 peptides
INFO: Wrote 2900000 peptides
INFO: Wrote 3000000 peptides
INFO: Wrote 3100000 peptides
INFO: Wrote 3200000 peptides
INFO: Wrote 3300000 peptides
INFO: Wrote 3400000 peptides

**Comment by hbarsnes** [comment]
The problem is the creation of the Tide index, which if using large databases usually requires large amounts of disk space. Perhaps you are running out of disk space?

In any case, unless you really care about running Tide, I would recommend to disable it and use some/one of the other search engines that do not rely on creating such an index.

You may also want to have a look at your database and potentially reduce its size. It seems like you are running against the UniProt human proteome set, which in addition to the ~20 000 reviewed sequences also contains ~55 000 unreviewed sequences. Unless you are particularly interested in the unreviewed sequences we generally recommend searching against only the reviewed sequences, especially for human where the protein annotation is very good.

**Comment by javanOkendo** [comment]
You maybe right because I am running this on the HPC server here at the University of Cape Town, South Africa. I will use only used the reviewed sequnces with the contaminants

**Comment by javanOkendo** [comment]
Why is MS-GF+ complaining when I use 2020-02-12-decoys-contam-UP000005640.fasta; it says "there too many redudant proteins" and then it crushes, I will deactivate it

**Comment by hbarsnes** [comment]
> Why is MS-GF+ complaining when I use 2020-02-12-decoys-contam-UP000005640.fasta; it says "there too many redudant proteins" and then it crushes, I will deactivate it

Not sure. To answer that you are better off contacting the MS-GF+ developers directly: https://github.com/MSGFPlus/msgfplus.

**Comment by javanOkendo** [comment]
When I run MS-GF+ alone from the searchGUI I get the following error. What could be invoking this error?
Sun Apr 05 01:35:01 SAST 2020: SearchGUI version 3.3.17.
Memory given to the Java virtual machine: 28631367680.
Total amount of memory in the Java virtual machine: 2058354688.
Free memory: 2015362984.
Java version: 1.8.0_152-release.
Exception in thread "SwingWorker-pool-1-thread-1" Exception in thread "SwingWorker-pool-1-thread-2" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1734)
	at java.awt.EventQueue.isDispatchThread(EventQueue.java:1049)
	at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1361)
	at javax.swing.SwingWorker.doneEDT(SwingWorker.java:740)
	at javax.swing.SwingWorker.access$100(SwingWorker.java:225)
	at javax.swing.SwingWorker$2.done(SwingWorker.java:302)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:251)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1734)
	at java.awt.EventQueue.isDispatchThread(EventQueue.java:1049)
	at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1361)
	at javax.swing.SwingWorker.doneEDT(SwingWorker.java:740)
	at javax.swing.SwingWorker.access$100(SwingWorker.java:225)
	at javax.swing.SwingWorker$2.done(SwingWorker.java:302)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:251)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hbarsnes** [comment]
If you only get this when running MS-GF+ and not for the other search engines, it sounds like an issue in MS-GF+ and not in SearchGUI. So again you'll have to contact the MS-GF+ developers. In order to make sure, you can first try to run the MS-GF+ command line directly, i.e. not via SearchGUI?

We've had similar issues in SearchGUI before though and it is related to referring to GUI components when running in an environment that does not have a graphical front end. The only way to fix it is to remove any references to such components when running in command line mode.

**Comment by hbarsnes** [comment]
> The only way to fix it is to remove any references to such components when running in command line mode.

In case that was unclear, this is then something that the MS-GF+ developers would have to take care of. Assuming that it is indeed an issue in MS-GF+ of course.

**Comment by javanOkendo** [comment]
This helps @hbarsnes  and I will get intouch with the MS-GF+ developers otherwise when I turnoff the MS-GF+ the other algorithms runs pretty well

**Comment by javanOkendo** [comment]
This helps @hbarsnes  and I will get intouch with the MS-GF+ developers otherwise when I turnoff the MS-GF+ the other algorithms runs pretty well
