### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/searchgui#232]
Hi I am having trouble using this file when in .fasta format. I get an error from SearchGUI. Would you mind helping me with making this database functional? Thanks!

[HOMD_db1.txt](https://github.com/compomics/searchgui/files/4448340/HOMD_db1.txt)

**Comment by hbarsnes** [comment]
Here you go: [HOMD_db1-fixed.zip](https://github.com/compomics/searchgui/files/4449251/HOMD_db1-fixed.zip)

And here's what I did to fix the file: 1) opened it in WordPad and saved it as a standard text file (as it contained lots of non-text content that was not visible in a standard text editor), and 2) removed all if the quotation marks (') from the protein names (as these are not supported).

**Comment by CarlaCristinaUranga** [comment]
Thanks you guys are awesome, as usual.

**Comment by CarlaCristinaUranga** [comment]
Hi, I am working at the J. Craig Venter Institute and we are trying to install both SearchCLI and Peptide Shaker onto our server, however, Peptide Shaker source links seem to be broken. Would you mind letting us know how to install it onto our server (via IT)? We don't need the GUIs. The CLI versions of both are fine. Thank you!

**Comment by hbarsnes** [comment]
> Would you mind letting us know how to install it onto our server (via IT)?

Please see https://github.com/compomics/searchgui/issues/233 for a follow-up of this question.
