### ISSUE TITLE
CLI versons of SearchCLI and PeptideShaker server installation issues

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/searchgui#233]
Hi, I am working at the J. Craig Venter Institute and we are trying to install both SearchCLI and Peptide Shaker onto our server, however, Peptide Shaker source links seem to be broken. Would you mind letting us know how to install it onto our server (via IT)? We don't need the GUIs. The CLI versions of both are fine. Thank you!

**Comment by hbarsnes** [comment]
Hi Carla,

I'm not sure which "source links" you are referring to? The download links for both SearchGUI and PeptideShaker seem to work fine as far as I can tell.

To install our tools on your server all you have to do is to download the SearchGUI and PeptideShaker zip files, and unzip them in the wanted folder on your server. There is no additional installation required.

Best regards,
Harald
