### ISSUE TITLE
cannot load main class

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/searchgui#234]
Hi I am trying to run SearchGUI from the command line and get the following error:
Error: Could not find or load main class eu.isas.searchgui.cmd.SearchCLI

I checked the java version and here it is:

[curanga@lserver2 SearchGUI-4.0.0-beta]$ java -version
java version "1.7.0_15"
Java(TM) SE Runtime Environment (build 1.7.0_15-b03)
Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)
[curanga@lserver2 SearchGUI-4.0.0-beta]$ 
 
If you could help me fix this I would greatly appreciate it.

**Comment by hbarsnes** [comment]
Can you please share the SearchGUI command line you are trying to run? It is probably just a minor detail that has to be changed.

**Comment by CarlaCristinaUranga** [comment]
Here are the commands:


java -cp SearchGUI-4.0.0.jar eu.isas.searchgui.cmd.SearchCLI
-spectrum_files “/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/mgf/ “
-fasta_file “/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/HOMDdb.fasta/”
-output_folder “/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/mgf/”
-id_params “saliva.par”


Best,

Carla

**Comment by hbarsnes** [comment]
Hi Carla,

If you are running the beta version you need to add "-beta" after the version number. :)

Best regards,
Harald

**Comment by CarlaCristinaUranga** [comment]
Ok, it is starting to work, I am on a Linux machine and I think my syntax
is incorrect for specifying folder locations? Could it be my file paths are
too long? I super checked the file paths and the names and the syntax but
am still getting the following error log:

Thu Apr 16 15:46:41 PDT 2020: SearchGUI version 4.0.0-beta.
Memory given to the Java virtual machine: 28631367680.
Total amount of memory in the Java virtual machine: 2058354688.
Free memory: 1983119200.
Java version: 1.8.0_232.
java.io.FileNotFoundException:
“/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf”
not found.
at
com.compomics.software.cli.CommandLineUtils.getFiles(CommandLineUtils.java:199)
at
eu.isas.searchgui.cmd.SearchCLIInputBean.getSpectrumFiles(SearchCLIInputBean.java:448)
at
eu.isas.searchgui.cmd.SearchCLIInputBean.isValidStartup(SearchCLIInputBean.java:731)
at eu.isas.searchgui.cmd.SearchCLI.<init>(SearchCLI.java:88)
at eu.isas.searchgui.cmd.SearchCLI.main(SearchCLI.java:374)

Here are my commands:

java -cp SearchGUI-4.0.0-beta.jar eu.isas.searchgui.cmd.SearchCLI
-fasta_file “
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/HOMDdb.fasta/”
-spectrum_files “
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/”-output_folder
“/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/output/”
-msgf 1 -id_params “
/local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/saliva.par/”

**Comment by hbarsnes** [comment]
Try changing the command line to:

java -cp SearchGUI-4.0.0-beta.jar eu.isas.searchgui.cmd.SearchCLI
-fasta_file /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/HOMDdb.fasta
-spectrum_files /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf -output_folder /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/mgf/output -msgf 1 -id_params /local/ifs2_projdata/0780/projects/SMU_MUC/curanga/fasta/SearchGUI-4.0.0-beta/saliva.par

**Comment by CarlaCristinaUranga** [comment]
That is working I am SOOO excited Harald as usual you are awesome. THANK
YOU! Thank you for making this accessible and democratizing proteomics. I
hope you guys win the Nobel prize some day!

Best wishes,
Carla

**Comment by hbarsnes** [comment]
Thanks! Happy to help. Sadly, I don't think there is a Nobel Prize in bioinformatics. Yet. ;)
