### ISSUE TITLE
Missed cleavages in X!Tandem

### ISSUE THREAD

**Issue by tivdnbos** [compomics/searchgui#236]
Hi,

I noticed something strange when using X!Tandem in SearchGUI 3.3.17. If I set the number of max missed cleavages at 2, I still have peptides with three missed cleavages when imported in PeptideShaker. Any idea why?

All the best,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

Strange. Which enzyme are you using? And can you check the "scoring, maximum missed cleavage sites" option in your X!Tandem settings file? You'll find the file under resources\XTandem.

Best regards,
Harald

**Comment by tivdnbos** [comment]
Aha, the problem was that I allowed unanticipated cleavages from the refinement search step (advanced settings - refinement). 

Best,
Tim

**Comment by hbarsnes** [comment]
Ah, yes, that would explain it. :)

So we can close the issue then?
