### ISSUE TITLE
OMSSA Help

### ISSUE THREAD

**Issue by EAD1994** [compomics/searchgui#238]
Hello,

I have recently starting using SearchGUI for peptidomics applications and one of the search engines that I am using is OMSSA. I am having a bit of trouble, as when I change the peptide length in the advanced parameters section, the intensity cutoff increment value changes to 4.0 from 5.0E-4. For some reason, if I try to change the value back to 5.0E-4, it will not save and it will stay at 4.0. Is there a reason why this is happening?

Thanks.
Ed

**Comment by hbarsnes** [comment]
Hi Ed,

Thanks for letting us know! There was a mix up when saving some of the variables. This has now been corrected and a new version of SearchGUI will be released within a day or two.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Ed,

The new version of SearchGUI is now online. It should solve the reported bug, but if not please let me know and I'll reopen the issue.

Best regards,
Harald
