### ISSUE TITLE
Can I use fasta file of nucleotide sequences as my search database?

### ISSUE THREAD

**Issue by nattzy94** [compomics/searchgui#239]
I would like to replicate the following step from [this paper](https://www.nature.com/articles/ncomms6429):

> The remaining 904,922 (80%) unmatched spectra were exported and searched against a custom database generated from RNA-seq data comprising all the transcribed regions16. The nucleotide database was concatenated to common contaminants and its decoy version and searched using Mascot v2.3 in all six frames with the following parameters: enzyme specificity trypsin, two missed cleavage sites, carbamidomethyl (Cys), oxidation (Met), deamidation (N), and Gln to pyro Glu (N-terminal Q) and TMT-6plex (N termini and Lys) as static modifications.

I currently have a fasta file containing 200,000 transcript sequences from my RNAseq experiment and I would like to search my MS files against the fasta file. From what I saw in the tutorial, SearchGUI seems to take a database in protein sequence format. My question is, 

1. Is it possible to input my fasta file (containing nucleotide sequences) into SearchGUI?
2. And how do I get SearchGUI to search the fasta file in all 6 translation frame?

Thank you!

**Comment by hbarsnes** [comment]
I'm afraid that SearchGUI only supports databases in protein sequence format. So you would have to do the six reading frame translation before giving the resulting FASTA file to SearchGUI.

Not sure which tools are recommended for doing this though, but I assume there are tools that can do this for you.

**Comment by mvaudel** [comment]
Hi,
As Harald said inferring peptides from genomics or transciptomics databases is beyond the scope of SearchGUI. You can try customProDB (https://www.ncbi.nlm.nih.gov/pubmed/?term=24058055) for this.
Hope it helps,
Marc

**Comment by nattzy94** [comment]
Okay, thank you. I'll try out the suggestions here.
