### ISSUE TITLE
Configuration settings, CLI command for the SearchGUI analysis

### ISSUE THREAD

**Issue by PRprog** [compomics/searchgui#241]
Hi,
I have several questions/suggestions:
- Is there any way to set up the starting directory of SearchGUI in configuration settings?
- When I write the "Name" in the "Identification settings", the not allowed characters (e.g. "%") cause a warning dialog window to appear. Hitting the "escape" or "return" keyboard does not dismiss the warning dialog. (Only a mouse click on OK works.) Is it possible to correct this?
- Is it possible to save the actual SearchGUI analysis settings (e.g. the opened parameters, the selected search engines etc.)? Or at least if it is possible to remember it for the next start of SearchGUI.
- How can I obtain actual command line command for running the analysis from the command line? I mean when I set the parameters, select the engine, raw files etc - how can I transfer this information created in the SearchGUI window to a command line?

Thank you!
Best regards,
Pavel

**Comment by hbarsnes** [comment]
Hi Pavel,

> Is there any way to set up the starting directory of SearchGUI in configuration settings?

Not sure what you mean by "the starting directory of SearchGUI"? But you can change all temporary paths via the [PathSettingsCLI](https://github.com/compomics/searchgui/wiki/SearchCLI#pathsettingscli) if running via the command line or via Edit > Resource Settings if running via the GUI.

> When I write the "Name" in the "Identification settings", the not allowed characters (e.g. "%") cause a warning dialog window to appear. Hitting the "escape" or "return" keyboard does not dismiss the warning dialog. (Only a mouse click on OK works.) Is it possible to correct this?

I'm afraid this is a Java standard. At least it is not something we added ourselves. You can escape the need to use the mouse by clicking the space bar though.

> Is it possible to save the actual SearchGUI analysis settings (e.g. the opened parameters, the selected search engines etc.)? Or at least if it is possible to remember it for the next start of SearchGUI.

The selected search engines should already be remembered between each time you run the GUI. Is this not the case for you?

As for the opened parameters I assume you mean the search settings? If so, no, this will not be remembered between each run as the assumption was that it should be easy enough to reselect the given settings from the drop down menu?

If running multiple searches in a row you do not have to close SearchGUI in between each run, hence the settings should stay selected. And if running lots of searches in a row it is probably recommend to instead go for the command line.

> How can I obtain actual command line command for running the analysis from the command line? I mean when I set the parameters, select the engine, raw files etc - how can I transfer this information created in the SearchGUI window to a command line?

There is currently no direct support for this. As you may have seen we do print the individual search engine command lines (and the PeptideShakerCLI command line if the PeptideShaker option is used), but given that when running SearchGUI one is not directly running the SearchCLI command line this command line is not directly available. I guess the assumption is that one would be using either the GUI or the command line.

The SearchCLI command line is pretty straightforward to set up though. Please see https://github.com/compomics/searchgui/wiki/SearchCLI for details.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

> When I write the "Name" in the "Identification settings", the not allowed characters (e.g. "%") cause a warning dialog window to appear. Hitting the "escape" or "return" keyboard does not dismiss the warning dialog. (Only a mouse click on OK works.) Is it possible to correct this?

Turns out I was too quick to blame Java. The issue was rather that the enter key was picked up as another key stroke that resulted in a retesting of the content of the text field. Has now been fixed and should work as expected in the next release.

Best regards,
Harald

**Comment by PRprog** [comment]
Hi Harald,
- by **_starting directory_** I mean (and I did not explain it in detail) the raw file directory, i.e. the directory that will be available in the window that appears after clicking on "Add" button for addition of raw files (or also the "Browse" for the output folder). This could be as another option in the "Edit -> Resource Settings".
- thank you for modification of the "incorrect character warning" window in the next version of the program. For the some people may be annoying to try to remove ten times the error messages by enter or escape.
- **_saving the analysis settings_** was meant for the purpose of consecutive searches with possibly changing only the input raw files or so. Yes, the engine is remembered, but if I check also the PeptideShaker option, I have to fill up the names in the window again. This is not that critical, but it may help. Regarding the running multiple searches in a row, I have another issue here that I will open in a new thread soon.
- the SearchCLI command line is nice and I like the possibility to use it. However, it may be faster for me to set everything up in a SearchGUI, then go e.g. to "Edit -> Current CLI Command" or something like this and to copy from the window the actual command (or series of commands) to run the created analysis. This would help me to avoid possible errors that certainly appear, when I start to create it on my own.

Best regards,
Pavel

**Comment by PRprog** [comment]
Hi again,
one more request for SearchGUI: when I try to rerun the analysis with changed parameters, do I always have to change the output directory in order not to overwrite the previous results?
![results_overwrite](https://user-images.githubusercontent.com/63408887/81504565-5720ee80-92ea-11ea-8416-32b8af7971ab.jpg)
And could it be possible - when selecting "No" in the "overwrite question dialogue" - to let the SearchGUI create automatically a new result name formed e.g. as the original name concatenated with some number string like "_001" or so?

Next to it, I have noticed in the researched results that one protein sequence (Serpin A3-3) with the same ID number (A0A452DJA9) was reported twice (on the rank positions 3 and 4) in the PeptideShaker view:
![two_proteins](https://user-images.githubusercontent.com/63408887/81504493-e2e64b00-92e9-11ea-89f9-e75718aeabdf.jpg)
The researched results are here:
[standard_bsa_digest_results_after_analysis_rerun.zip](https://github.com/compomics/searchgui/files/4606037/standard_bsa_digest_results_after_analysis_rerun.zip)
Thank you for your support.
Best regards,
Pavel

**Comment by hbarsnes** [comment]
Hi Pavel,

> do I always have to change the output directory in order not to overwrite the previous results?

Please check out the Output options found via Edit > Advanced Settings. If you choose to include the date in the name of the zip file it should work the way you want?

> I have noticed in the researched results that one protein sequence (Serpin A3-3) with the same ID number (A0A452DJA9) was reported twice (on the rank positions 3 and 4) in the PeptideShaker view

This is due to protein inference grouping. Please have a look at our tutorial material (https://www.compomics.com/bioinformatics-for-proteomics) and particularly Chapter 1.4 Section C, to see how PeptideShaker deals with protein inference grouping. You can also directly click the colored square in front of the given protein groups to see more details on the group.

Note that you have a lot of protein groups, mainly due to searching with a database containing all the isoforms. Generally this is not needed unless you are particularly interested in separating the isoforms, and even then you'd need to identify peptides that are different between the isoforms to do so. Most other peptides will be shared between the isoforms, which is what you see in your example above.

The short answer to why the same protein can occur more than once in the protein (group) list, is that it can be the representative protein for multiple protein groups, and given that in many cases there is no clear "best" representative the same protein can occur twice (or more). Please see the tutorial material for more details.

> by starting directory I mean (and I did not explain it in detail) the raw file directory, i.e. the directory that will be available in the window that appears after clicking on "Add" button for addition of raw files (or also the "Browse" for the output folder). This could be as another option in the "Edit -> Resource Settings".

SearchGUI does remember the folder of the last used FASTA file between runs, but apparently not the folder of the last used spectrum file. Should not be too hard to add. I will try to include it in the next major release.

> saving the analysis settings was meant for the purpose of consecutive searches with possibly changing only the input raw files or so. Yes, the engine is remembered, but if I check also the PeptideShaker option, I have to fill up the names in the window again. This is not that critical, but it may help.

In my mind this sounds more like a situation where the command line should be used. I do not think we'll prioritze implementing such a feature given that the command line is our intended solution to these kinds of setups.

> the SearchCLI command line is nice and I like the possibility to use it. However, it may be faster for me to set everything up in a SearchGUI, then go e.g. to "Edit -> Current CLI Command" or something like this and to copy from the window the actual command (or series of commands) to run the created analysis. This would help me to avoid possible errors that certainly appear, when I start to create it on my own.

I see your point. I will add it on the list of requested features, but I cannot guarantee that we will get to it any time soon.

Best regards,
Harald

**Comment by PRprog** [comment]
Hi Harald,
thank you for responeses and for the future updates of my "little" wishes. :-)
> > do I always have to change the output directory in order not to overwrite the previous results?

>Please check out the Output options found via Edit > Advanced Settings. If you choose to include the date in the name of the zip file it should work the way you want?

In a certain sense yes. My main aim was to distinguish the particular ID analysis runs from each other. This is now true when I check this option. However, it only adds date and time to the SearchGUI output, and the PeptideShaker result file gets rewritten (without notification). So I would suggest to add the date-time stamp also to the PeptideShaker result file when created from SearchGUI directly.

Additionally, I am missing a kind of "sample name" or "project name" in the result file. Yes, this may be included in the output directory name, but e.g. the project details parameters (i.e. "Project Name", "Sample Name", "Replicate") in the PeptideShaker setting of the SearchGUI could be possibly used to be included both in the name of the PeptideShaker result file and in the name of the SearchGUI output as well. This could be again an option in the SearchGUI -> Edit > Advanced Settings window (similary as the "Include Date in File Name" option).

Best regards,
Pavel

**Comment by hbarsnes** [comment]
Hi Pavel,

> So I would suggest to add the date-time stamp also to the PeptideShaker result file when created from SearchGUI directly.
> Additionally, I am missing a kind of "sample name" or "project name" in the result file.

Both good suggestions. I will look into adding support for this in the next major release of SearchGUI.

Best regards,
Harald

**Comment by hbarsnes** [comment]
The feature requests should hopefully be implemented as wanted in the new release that has just been made available. If this is not the case, please let us know and we'll reopen the issue.
