### ISSUE TITLE
Multiple searches in a row - increased search time by repeating the same search

### ISSUE THREAD

**Issue by PRprog** [compomics/searchgui#242]
Hi,
I noticed that when I open SearchGUI, run a simple DB search with a single Thermo QExactive raw file and repeat the search again after finishing the previous search, the time necessary for running the second (or any other further search) substantially increases. Going deeper into the problem I noticed, that in the following searches the resulting file "searchGUI_input.txt" in the "searchgui_out.zip" file contains the same peaklist for the input raw file several times. As the result of this fact, the same DB search for the same input file is run several times, which is completely unnecessary and prolongs the analysis time.
I run the SearchGUI 3.3.19 + Peptide Shaker 1.16.45 on a PC with Windows 10 with Java 64bit. I use ProteoWizard for data conversion.
This behaviour seems to be independent of DB search engine selected for actual search.
Results files showing this behaviour are available at
[https://filesender.cesnet.cz/?s=download&token=cf815590-84af-da7e-d7c4-786666e62e32](https://filesender.cesnet.cz/?s=download&token=cf815590-84af-da7e-d7c4-786666e62e32)

Thank you!
Best regards,
Pavel

**Comment by hbarsnes** [comment]
Hi Pavel,

Please try the new SearchGUI 3.3.20 that I released yesterday. It should hopefully take care of this problem as well.

Best regards,
Harald

**Comment by PRprog** [comment]
Hi Harald,
yes, you are right, this issue does not happen since the SearchGUI version 3.3.20. Thank you!
Best regards,
Pavel
