### ISSUE TITLE
OMSSA Search Question

### ISSUE THREAD

**Issue by EAD1994** [compomics/searchgui#243]
Hello,

I have been having some issues when using the OMSSA search engine on SearchGUI. For some reason, I am not getting any results from OMSSA and if I look at the SearchGUI report after the search has been completed, I get a message saying "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information." I also get another message saying "Could not find OMSSA result file for x.mgf." I am wondering if anybody can help me out with this issue? I am also using MS-GF+ and X!Tandem but I do not get this issue with these other search engines. 

Thanks in advance,
Eduardo

**Comment by hbarsnes** [comment]
Hi Eduardo,

OMSSA is a rather old search engine and is in some cases not able to deal with modern-size proteomics data sets. If you share the complete error message from OMSSA I might be able to tell you way it fails in this particular case, but as a general tip I'd recommend using the more modern search engines instead. The gain by also including OMSSA will in any case be limited.

Best regards,
Harald

**Comment by EAD1994** [comment]
Hi Harald,

It seems like the issue may be peptide length dependent. I initially had changed the peptide length search parameter from 8-30 to 4-65 AAs in the advanced parameters section and this is when the error occurred. I then changed the peptide length to 4-50 AAs and I did not get this issue anymore.

Thanks,
Eduardo

**Comment by hbarsnes** [comment]
Hi Eduardo,

Great that you found a solution. I will then close the issue. But do no hesitate to open a new one if you come across other problems.

Best regards,
Harald
