### ISSUE TITLE
conda -fasta_files

### ISSUE THREAD

**Issue by KunathBJ** [compomics/searchgui#244]
Hello,

We've tried using conda to implemente SearchGui into one of our pipeline on centos.
Generating the parameter file seems to have worked just fine but when trying to run the search using such command:
```
java -cp SearchGUI-4.0.1-SNAPSHOT.jar eu.isas.searchgui.cmd.SearchCLI \
    -spectrum_files $mgf \
    -fasta_files /scratch/2011-07-08.hybrid.proteomics.final.unix.crap_concatenated_target_decoy.fasta \
    -output_folder $out \
    -id_params param.par \
    -xtandem 1 \
    -msgf 1 \
    -comet 1 \
    -andromeda 0 \
    -threads $THREADS \
    -output_default_name "$PREFIX" \
    -output_option 0 \
    -output_data 1 \
    -output_date 1 
```
I get an issue like this:
```
Java version: 11.0.1-internal.
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -fasta_files
        at org.apache.commons.cli.Parser.processOption(Parser.java:363)
        at org.apache.commons.cli.Parser.parse(Parser.java:199)
        at org.apache.commons.cli.Parser.parse(Parser.java:85)
        at eu.isas.searchgui.cmd.SearchCLI.<init>(SearchCLI.java:86)
        at eu.isas.searchgui.cmd.SearchCLI.main(SearchCLI.java:374)

```
I use the same database with the typical searchgui approach on the same machine and the file worked just fine.
Is there something different there? Am I not supposed to provide the decoy database?

Thanks a lot,
Ben

**Comment by hbarsnes** [comment]
Hi Ben,

If you change "-fasta_files" to "-fasta_file" the unrecognized option message should go away.

Best regards,
Harald

**Comment by KunathBJ** [comment]
That was quite dumb from me.
Don't know how I missed that..

Thanks a lot ^^
