### ISSUE TITLE
Multiple issues with SearchGUI-3.3.20.jar, command line mode, -cp eu.isas.searchgui.cmd.SearchCLI

### ISSUE THREAD

**Issue by VladimirRoudko** [compomics/searchgui#245]
Hello,

I have setup for a MS/MS processing pipeline including SearchGUI-3.3.20 and PeptideShaker-1.16.45 tools (in command line format) on Ubuntu system and run into a few issues asocciated with the search step. 

More specifically, I tested the same database file (generated by SearchGUI-3.3.20.jar eu.isas.searchgui.cmd.FastaCLI , including decoys). against each available MS/MS search engine in SearchGUI-3.3.20 separately: xtandem, omssa, msgf, ms_amanda, myrimatch, comet, tide, andromeda, novor, directag. Each run was submitted through SGE, 10 cores per run, with clean copy of the software (e.g. independent local installation from source). Out of 10 separate runs, **myrimatch** and **andromeda** produced tool-specific errors, omssa did not finish processing in observable time, directag did not find any PSM matches, and the rest of the tools finished reporting positive outputs by PeptideShaker.  I was wondering if it is possible to fix these tools-specific bugs of myrimatch and andromeda.
**1. Here is the STDOUT of myrimatch search containing the error message:**
Thu Jun 18 11:06:49 EDT 2020 Processing 01CPTAC_COprospective_W_VU_20150901_01CO006_f01.mgf with MyriMatch.

Process #0 (acmilan) is starting.
MyriMatch 2.2.10165 (2016-11-7)
FreiCore 1.6.11103 (2017-7-14)
ProteoWizard MSData 3.0.11841 (2018-3-8)
ProteoWizard Proteome 3.0.11579 (2017-11-14)
Vanderbilt University (c) 2012, D.Tabb/M.Chambers/S.Dasari
Licensed under the Apache License, Version 2.0

**Could not find the default configuration file (hard-coded defaults in use).**
Reading "/nfs/scratch/vova/compomics/pipeline/qsub_test/compomics_output_5/01CPTAC_COprospective_W_VU_20150901_01CO006/peptide_database/human.frameshift.10_concatenated_target_decoy.fasta"
Read 3996622 proteins; 26.3175 seconds elapsed.
Reading spectra from file "/nfs/scratch/vova/compomics/pipeline/qsub_test/compomics_output_5/01CPTAC_COprospective_W_VU_20150901_01CO006/mgf_input/01CPTAC_COprospective_W_VU_20150901_01CO006_f01.mgf"
myrimatch: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.

I assumed, the issue is the identification file, despite the fact it was correctly generated by searchgui. Also, the same identification file worked for other successful searches:

Identification parameters file created: /nfs/scratch/vova/compomics/pipeline/qsub_test/compomics_output_5/01CPTAC_COprospective_W_VU_20150901_01CO006/identification.par

Identification parameters configuration:

IDENTIFICATION_FILE="identification.par"
java $JAVA_OPTS -cp $search eu.isas.searchgui.cmd.IdentificationParametersCLI \
	-out "${IDENTIFICATION_FILE}" \
	-db "peptide_database/"${PEPTIDE_LIST}"_concatenated_target_decoy.fasta" \
	-prec_tol 10 \
	-frag_tol 0.05 \
	-enzyme Trypsin \
	-mc 2 \
	-fixed_mods "Carbamidomethylation of C" \
	-variable_mods "Oxidation of M"

**2. Here is STDOUT of andromeda search containing the error message:**

Thu Jun 18 11:25:35 EDT 2020 Andromeda configuration.

**Thu Jun 18 11:25:35 EDT 2020 Error: conf/databases.xml (No such file or directory)**
Thu Jun 18 11:25:35 EDT 2020 An error occurred while running SearchGUI. Please contact the developers.
Thu Jun 18 11:25:35 EDT 2020 The search or processing did not finish properly!
Path configuration completed.
<CompomicsError>PeptideShaker processing failed. Please see the PeptideShaker log file: /nfs/scratch/vova/compomics/pipeline/qsub_test/compomics_output_8/01CPTAC_COprospective_W_VU_20150901_01CO006/PeptideShaker-1.16.45/resources/PeptideShaker.log</CompomicsError>

The PeptideShaker log file contains the following:

Thu Jun 18 11:25:35 EDT 2020: PeptideShaker version 1.16.45.
Memory given to the Java virtual machine: 21474836480.
Total amount of memory in the Java virtual machine: 2155872256.
Free memory: 2142562304.
Java version: 11.0.7.
java.io.FileNotFoundException: search_output/searchgui_out.zip not found.
	at com.compomics.software.cli.CommandLineUtils.getFiles(CommandLineUtils.java:200)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLIInputBean.getIdentificationFiles(PeptideShakerCLIInputBean.java:314)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLIInputBean.isValidStartup(PeptideShakerCLIInputBean.java:435)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:942)

Also, upon inspection of SearchGUI  conf folder, I did not find the requested databases.xml file:

ls compomics_output_8/01CPTAC_COprospective_W_VU_20150901_01CO006/SearchGUI-3.3.20/resources/conf/
default_SearchGUI.parameters
gene_mappings    
paths.txt                    
searchgui-splash.png
firstRun                      
JavaOptions.txt  searchGUI_configuration.txt  taxonomy

Could you please help me to fix these tool-specific bugs?

Thank you!
Vladimir

**Comment by hbarsnes** [comment]
Hi Vladimir,

> Reading spectra from file "/nfs/scratch/vova/compomics/pipeline/qsub_test/compomics_output_5/01CPTAC_COprospective_W_VU_20150901_01CO006/mgf_input/01CPTAC_COprospective_W_VU_20150901_01CO006_f01.mgf"
myrimatch: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.

To me this looks more like an issue with the mgf file. As the first line above ("Reading spectra from file …") ought to be followed by something like:

```
Read 11332 spectra with 1380026 peaks; 3.22048 seconds elapsed.
Preparing 11332 spectra.
```

I cannot tell from the error what the underlying issue is though. How was the mgf file created?

> Error: conf/databases.xml (No such file or directory)

The database file in question will be created by Andromeda in the SearchGUI-3.3.20\resources\Andromeda\windows\conf folder. However on your Ubuntu setup this file will never be created, as Andromeda is currently only supported on Windows.

Best regards,
Harald

**Comment by VladimirRoudko** [comment]
Hello Harald,

Thank you for your prompt response! 

Mgf files were created with MSConvert, ProteoWizard package.  Same files worked well with other searching algorithms, like Xtandem or comet. Could it be that Myrimatch requires more specific format as an input?

Concerning the Andromeda - thank you for the explanation! I will exclude Andromeda from the pipeline later on.  Just out of the curiosity - is there any plan to support Andromeda on Linux platform?

Thank you!
Vladimir

**Comment by VladimirRoudko** [comment]
Hello Harald,

After searching around I found the solution - it was an issue with locale settings. Just in case if it helps in future, the solution is to add two lines in the local environment configuration file:

LANG=/usr/lib/locale/en_US
export LC_ALL=C; unset LANGUAGE


After sourcing the config with these two lines, myrimatch works perfectly.

I am closing the issue, as it has solved all my initial requests.

Thank you again!
Vladimir

**Comment by hbarsnes** [comment]
Hi Vladimir,

> I will exclude Andromeda from the pipeline later on. Just out of the curiosity - is there any plan to support Andromeda on Linux platform?

There apparently is a version of Andromeda working on Linux, given that MaxQuant is now supported on Linux. However, we have been unable to get a hold of the standalone version of Andromeda that works on Linux. But when/if we do, we'll of course include it in SearchGUI.

> After searching around I found the solution - it was an issue with locale settings.

Aha, that could indeed be an issue. Great that you were able to figure it out.

Best regards,
Harald
