### ISSUE TITLE
How to configure fractions in searchGUI

### ISSUE THREAD

**Issue by wanghao1991217** [compomics/searchgui#246]
I have thermoRAW files with 6 fractions of each sample. and I cannot find where to set fractions in the searchGUI. Can someone tell me how to do it ? thank you!

**Comment by hbarsnes** [comment]
Hi,

There is no configuration required to process fractions in SearchGUI, simply selected all of the raw files representing the different fractions as the spectrum input. Each spectrum file will then be processed individually. If you later want to merge the fractions and look at the data as a single dataset, you can do this in [PeptideShaker](http://compomics.github.io/projects/peptide-shaker.html).

Best regards,
Harald

**Comment by wanghao1991217** [comment]
> Hi,
> 
> There is no configuration required to process fractions in SearchGUI, simply selected all of the raw files representing the different fractions as the spectrum input. Each spectrum file will then be processed individually. If you later want to merge the fractions and look at the data as a single dataset, you can do this in [PeptideShaker](http://compomics.github.io/projects/peptide-shaker.html).
> 
> Best regards,
> Harald

Thank you. I will try it later.

**Comment by kazbek966** [comment]
Could you please provide step-by-step instruction on how to merge individually selected files into different fractions. That step is a bit elusive.

**Comment by hbarsnes** [comment]
> Could you please provide step-by-step instruction on how to merge individually selected files into different fractions. That step is a bit elusive.

I'm afraid that this is not something that is supported at the moment. Each spectrum file is simply treated as a single fraction.
