### ISSUE TITLE
understanding identification.par file

### ISSUE THREAD

**Issue by VladimirRoudko** [compomics/searchgui#248]
Hello,

I noticed a couple of confusing lines. When I configure my identification parameters file introducing precursor and fragment tolerances in Da:

java $JAVA_OPTS -cp $search eu.isas.searchgui.cmd.IdentificationParametersCLI \
	-out "${IDENTIFICATION_FILE}" \
	-db "${PEPTIDE_DB}/"${PEPTIDE_LIST}"_concatenated_target_decoy.fasta" \
	-prec_tol 0.01 \
	-prec_ppm 0 \
	-frag_tol 0.5 \
	-frag_ppm 0 \
       .........

I get the following lines in *.par file:

"searchParameters": {
    "precursorAccuracyType": "DA",
    "fragmentAccuracyType": "DA",
    "precursorTolerance": 0.01,
    "precursorToleranceDalton": 0.5,
    "fragmentIonMZTolerance": 0.5,

Why  "precursorToleranceDalton" equals 0.5, if my precursorTolerance is 0.01 and its measured in Da? is it supposed to be the same number (0.01)?

Thank you,
Vladimir

**Comment by hbarsnes** [comment]
Hi Vladimir,

Some of the search engines only support tolerances in Dalton, hence we have to keep the tolerance in both ppm and Dalton. If I remember correctly, the precursorToleranceDalton is an option that is only used if the precursorAccuracyType is set to ppm and a given search engine requires Dalton. But in your case the type is already in Dalton and the precursorToleranceDalton option should not be used. I guess we in that case simply forgot to update the precursorToleranceDalton value. In any case, that setting has been removed from the upcoming new versions.

Best regards,
Harald

**Comment by VladimirRoudko** [comment]
Hello Harald,

Thank you for the explanation! It clarifies everything and I am closing the issue then).
Vladimir
