### ISSUE TITLE
Out of Memory during decoy generation

### ISSUE THREAD

**Issue by andrewjmc** [compomics/searchgui#249]
I have a large (13 Gb) metaproteomic database which I am using for searching a small number of differentially abundant spectra (~30k). I would love to use SearchGUI for the ability to use multiple tools in parallel with simple configuration.

However, I could not use the database in the GUI (froze with no error), and with FastaCLI I got an out of memory error despite offering 50 Gb:

```
java -Xmx50G -cp SearchGUI-3.3.20.jar eu.isas.searchgui.cmd.FastaCLI -in Homo_sapiens_viruses_bacteria_fungi_archaea_2020_03_10.fasta -decoy
Input: Homo_sapiens_viruses_bacteria_fungi_archaea_2020_03_10.fasta

Name: Homo_sapiens_viruses_bacteria_fungi_archaea_2020_03_10
Version: 3.8.2020
Decoy Tag: null
Type: UniProt
Last modified: Mon Aug 03 13:45:15 BST 2020
Size: 28045072 sequences

Fri Aug 07 11:51:23 BST 2020 Appending Decoy Sequences. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%Reindexing: Homo_sapiens_viruses_bacteria_fungi_archaea_2020_03_10_concatenated_target_decoy.fasta.
Ran out of memory!
```

Is the index mandatory for running searches through SearchCLI without integrating with PeptideShaker? Can the memory usage of the indexing process be reduced?

Thanks,

Andrew

**Comment by dominik-kopczynski** [comment]
Hi Andrew and again sorry for my delayed reply. Thank you for the provided commend. I will try to reproduce your error and comment on it asap.

**Comment by andrewjmc** [comment]
Thanks!

**Comment by dominik-kopczynski** [comment]
Here is the current state: in the new SearchGUI version 4.0.0 (currently in beta state), this feature is deactivated that after target-decoy generation an index is generated. However, it happened that another bug sneaked in, which is causing an error in this function. Hence, thank you for hinting at this bug ;-) I'm working on fixing the bug. Will keep you informed.

**Comment by hbarsnes** [comment]
Issue assumed resolved with the new releases. If this is not the case, please let us know and we'll reopen the issue.
