### ISSUE TITLE
OMSSA on macOS

### ISSUE THREAD

**Issue by f6v** [compomics/searchgui#252]
I didn't manage to run the OMSSA on macOS Catalina 10.15.7.

```
(base) ➜ file omssacl
omssacl: Mach-O universal binary with 2 architectures: [ppc:Mach-O executable ppc] [i386]
omssacl (for architecture ppc):	Mach-O executable ppc
omssacl (for architecture i386):	Mach-O executable i386
```

If I understand correctly, the included executable doesn't support 64 bit architecture, and Catalina refuses to run 32 bit apps.

**Comment by hbarsnes** [comment]
I'm afraid OMSSA is not maintained anymore (and hasn't been for some time), hence there is no way in which we can obtain 64 bit versions of OMSSA. I would recommend that you use the other included search engines instead. The bonus is that most of these are more modern search engines and may even give you better search results.
