### ISSUE TITLE
Unspecific Digestion and Amanda settings_SearchGUI.xml

### ISSUE THREAD

**Issue by sheep71** [compomics/searchgui#254]
When searching with unspecific digestion (Search Settings - Identification settings - Spectrum Matching - Digestion) and MS AMANDA, in the corresponding settings_SearchGUI.xml (/resources/MS Amanda/windows) the value for missed_cleavages is erroneously set to 50 leading to the following error:

From the Log: 
Reading settings file...
Allowed values for missed cleavages parameter are between 0 and 5
Error reading settings file ...

**Comment by hbarsnes** [comment]
Thanks for the tip! I've now fixed the problem and released a new version of SearchGUI. If the unspecific searches still do not work as wanted, please let me know and I'll reopen the issue.
