### ISSUE TITLE
can't open the output CPSX file 

### ISSUE THREAD

**Issue by vipulbatra1985** [compomics/searchgui#255]
I am exploring searchGUI and am not able to open the peptide shaker output file neither with searchGUI nor with peptide share executable jar file. I am using ver. 3.3.21. Please help.

**Comment by hbarsnes** [comment]
I would recommend first having a look at our tutorial material: https://www.compomics.com/bioinformatics-for-proteomics. If you are still stuck, please let us know and we'll try to help as best we can.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
