### ISSUE TITLE
adding support for TMTPro

### ISSUE THREAD

**Issue by chrishuges** [compomics/searchgui#256]
Hi,

Is it possible to add support here and in SearchGUI for TMTPro?

Modification mass is: 304.207145

Formula is: H(25) C(8) 13C(7) N 15N(2) O(3)

[Thermo](https://www.thermofisher.com/document-connect/document-connect.html?url=https%3A%2F%2Fassets.thermofisher.com%2FTFS-Assets%2FLSG%2Fmanuals%2FMAN0018773_TMTproMassTagLabelingReagentsandKits_UG.pdf&title=VXNlciBHdWlkZTogVE1UcHJvIE1hc3MgVGFnIExhYmVsaW5nIFJlYWdlbnRzIGFuZCBLaXRz), [Unimod](https://www.ebi.ac.uk/ols/ontologies/unimod/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUNIMOD_2016)

Thanks!
Chris

Edit - I mean built in support for those of us using the CLI where adding custom mods is not straightforward in my experience.

**Comment by hbarsnes** [comment]
Hi Chris,

TMTPro has already been added to the new major release of SearchGUI which we are aiming to release next week.

Best regards,
Harald

**Comment by chrishuges** [comment]
Ah perfect! Thanks!

**Comment by hbarsnes** [comment]
The new versions of the tools have just been released and support for TMTPro has been included. Please let us know if it does not work as wanted and we'll reopen the issue.
