### ISSUE TITLE
Converting to filename.mgf to peak list.

### ISSUE THREAD

**Issue by chrishuges** [compomics/searchgui#258]
Hi,

I have a question about SearchGUI version 4.0.0. I am running it from the command line on a single raw file to test the new version out and I get the messages:

```
bash-4.2$ ./rawDataProcessing_tmt16No57cMs3HumanTrypsinCombined.sh |& tee -a dataProcessing.txt

Data processing proceeding in the directory: /projects/ptx_results/2020/Fusion/10-Oct/Samples/CH/


Database file already exists: ./uniprotHumanCrapTargetDecoyNov2020.fasta

Parameters file exists: databaseSearchParameters.par.

MGF output for inputFile already exists, skipping file.


Wed Nov 04 11:33:28 PST 2020 Importing spectrum files.
Wed Nov 04 11:33:28 PST 2020 Importing spectrum files completed (25.0 milliseconds).


Processing: inputFile .raw.mgf (1/1)
Wed Nov 04 11:33:28 PST 2020 Converting spectrum file inputFile.raw.mgf to peak list.
```

My SearchGUI command is:

```
java -Xmx120g -cp ./searchGuiLocation/SearchGUI.4.0.0.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files ./inputFile.raw.mgf -fasta_file ./uniprotHumanCrapTargetDecoyNov2020.fasta -output_folder ./outputFolder -id_params ./databaseSearchParameters.par -output_option 1 -xtandem 1
```

It seems to take forever on this 'converting spectrum to peak list'. I have left it for almost an hour now with no progress...it doesn't seem to be writing any files. I wonder what this process is and why it needs to convert an mgf to a peak list when it already is one?

For reference, the mgf was created with RawTools and works fine with the previous versions of SearchCLI. The SearchGUI log file is pretty empty and nothing indicating an error there, just memory being passed to Java:

```
Wed Nov 04 11:33:27 PST 2020: SearchGUI version 4.0.0.
Memory given to the Java virtual machine: 114532810752.
Total amount of memory in the Java virtual machine: 2022178816.
Free memory: 1979942056.
Java version: 1.8.0_151.
```

Happy to provide any files or info!

Thanks,
Chris

**Comment by chrishuges** [comment]
For reference, my mgf looks like:

```
BEGIN IONS
TITLE=Spectrum_3
PEPMASS=411.054412841797
CHARGE=2+
RTINSECONDS=0.411112256
SCANS=3
RAWFILE=/projects/ptx_results/2020/Fusion/10-Oct/Samples/CH/inputFile.raw
126.29401 9.4783
144.61601 17.8956
163.05202 17.4176
```

**Comment by hbarsnes** [comment]
Hi Chris,

Thanks for testing the new releases! Upgrading your Java version ought to solve the problem. Should work fine with Java 9 and newer.

Best regards,
Harald

**Comment by chrishuges** [comment]
Hi Harald,

Upgrading to java above the version I had (in this case I went to version 15) fixed this issue for me. 

Thanks!
Chris
