### ISSUE TITLE
adding the underscore back on the searchgui output

### ISSUE THREAD

**Issue by chrishuges** [compomics/searchgui#259]
In the old SearchCLI, it used to add '_searchgui_out.zip' to the search output. In version 4.0.0, it adds 'searchgui_out.zip' without the leading underscore. Not really a bug or a big deal at all...just is a bit cleaner with the leading underscore. Possible to get it back?

Thanks,
Chris

**Comment by hbarsnes** [comment]
Hi Chris,

Yes, this should not be a problem. I'll include it in the next release.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Just released SearchGUI v4.0.1 which should solve this problem by re-adding the underscore in the cases where it had been removed.
