### ISSUE TITLE
SearchGUI4.0.1 ERROR

### ISSUE THREAD

**Issue by vipulbatra1985** [compomics/searchgui#261]
I am trying to analyses 8 .raw files on Search GUI 4.0.1 using Comet search engine and getting following in the bug report within a second :

comet command: 
D:\SearchGUI-4.0.1\resources\Comet\windows\windows_64bit\comet.exe D:\demo_searchGUI\raw_hf\A1-1.mzml 

java.io.FileNotFoundException: Source 'D:\demo_searchGUI\raw_hf\A1-1.comet.pep.xml' does not exist
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2995)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2936)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Similarly, while using andromeda : 
makeblastdb command: 
D:\SearchGUI-4.0.1\resources\makeblastdb\windows\makeblastdb -in uniprot-proteome_UP000009136_concatenated_target_decoy.fasta -dbtype prot 

java.io.FileNotFoundException: D:\SearchGUI-4.0.1\resources\Andromeda\windows\temp\uniprot-proteome_UP000009136_concatenated_target_decoy.fasta (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileWriter.<init>(Unknown Source)
	at com.compomics.util.experiment.io.biology.protein.converters.GenericFastaConverter.convertFile(GenericFastaConverter.java:40)
	at eu.isas.searchgui.processbuilders.AndromedaProcessBuilder.createGenericFastaFile(AndromedaProcessBuilder.java:224)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2303)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Please Help to resolve.

**Comment by hbarsnes** [comment]
Please follow up this issue under the SearchGUI issue tracker: https://github.com/compomics/searchgui/issues/261

**Comment by vipulbatra1985** [comment]
No its stuck on 6% saying importing peaks list.

**Comment by hbarsnes** [comment]
Would it be possible for you to share the spectrum file you are trying to search? You can send it to me directly at harald.barsnes@gmail.com.

**Comment by vipulbatra1985** [comment]
I have used the same spectrum files on earlier version successfully many a times. Let me try on the newer version 4.0.2 and will send you the files afterwards.

**Comment by vipulbatra1985** [comment]
Same output: Sat Nov 07 09:57:54 IST 2020        Error: Source 'D:\demo_searchGUI\raw_hf\A1-1.comet.pep.xml' does not exist
Sat Nov 07 09:57:54 IST 2020        An error occurred while running SearchGUI. Please contact the developers.
Sat Nov 07 09:57:54 IST 2020        The search or processing did not finish properly!
[SearchGUI 4.0.2 log.txt](https://github.com/compomics/searchgui/files/5504292/SearchGUI.4.0.2.log.txt)

I have sent you the 8 .raw files files which are fractions of a biological replicate of 1 experiment

**Comment by hbarsnes** [comment]
Thanks for sharing the raw files. I've only tested the A1-1.raw file so far, but I can convert and search it without any issues.

Can you also share the complete Comet output shown in the SearchGUI dialog when it is running?

And perhaps you can also share your search settings and your FASTA file?

**Comment by vipulbatra1985** [comment]
Here is the complete Comet output : Sun Nov 08 13:17:34 IST 2020        Converting raw files.
Sun Nov 08 13:17:34 IST 2020        A1-1.mzml already exists. Conversion canceled.


Sun Nov 08 13:17:34 IST 2020        Importing spectrum files.
Sun Nov 08 13:17:34 IST 2020        Importing spectrum files completed (106.0 milliseconds).

Sun Nov 08 13:17:34 IST 2020        Processing A1-1.mzml with Comet.



Sun Nov 08 13:17:34 IST 2020        Comet finished for A1-1.mzml (55.0 milliseconds).

Sun Nov 08 13:17:34 IST 2020        Error: Source 'D:\demo_searchGUI\raw_hf\A1-1.comet.pep.xml' does not exist
Sun Nov 08 13:17:34 IST 2020        An error occurred while running SearchGUI. Please contact the developers.
Sun Nov 08 13:17:34 IST 2020        The search or processing did not finish properly!

Sun Nov 08 13:17:34 IST 2020        Searching Canceled!
----------------------------------------------------------------------------------------
I have shared the settings and database file on email.

**Comment by hbarsnes** [comment]
Thanks again for sharing the files. However, I have again no issues searching the A1-1.raw file.

From your output above it would seem like Comet isn't even starting on your file though. Here's that I get for the same file:

```
Mon Nov 09 11:25:09 CET 2020        Processing A1-1.mzml with Comet.

 Comet version "2019.01 rev. 5"
 
 Search start:  11/09/2020, 11:25:10 AM
 
 - Input file: C:\Users\Harald\Downloads\raw_hf\A1-1.mzml
 
   - Load spectra: 22740
 
     - Search progress:   0%  1%  [...]  99%100%
 
     - Post analysis:  done
 
 Search end:    11/09/2020, 11:28:35 AM, 3m:25s
 
Mon Nov 09 11:28:36 CET 2020        Comet finished for A1-1.mzml (3 minutes 27.0 seconds).
```

Are you able to search the same file with any of the other search engines?

Could you perhaps try deleting the A1-1.mzml file and redo the search? Perhaps something went wrong with the initial conversion from raw to mzml?

Two additional things you can check is that you are not running out of disk space and that you have installed SearchGUI in a location where you have write access to the hard drive?

**Comment by vipulbatra1985** [comment]
None of the files could be searched with any of the other search engines.  For other search engines its usually stuck at 43% at the step that says "Converting spectrum file A1-1.mzml to peak list." 

I tried deleting .mzml files, however, no success.

I have enough disk space. 

Does the location of peptide shaker matter?  Did you try the search with my search settings and database

**Comment by hbarsnes** [comment]
> Does the location of peptide shaker matter?

I assume you mean SearchGUI (as PeptideShaker does not come into the picture until later), but no, the location should not matter beyond it being in a location where you have write access.

> Did you try the search with my search settings and database?

Yes, all works fine on my end.

Which Java version are you using? You need at least Java 9.

**Comment by vipulbatra1985** [comment]
SAME ERRORS: 
jshortcut.dll loaded via tmp generated pathname: C:\Users\Tyrone\AppData\Local\Temp\jshortcut-3108992309764914633.dll


ThermoRawFileParser command: 
D:\SearchGUI-4.0.4\resources\ThermoRawFileParser\ThermoRawFileParser.exe -i=D:\demo_searchGUI\raw_hf\A1-1.raw -o=D:\demo_searchGUI\raw_hf -f=1 -e 



comet command: 
D:\SearchGUI-4.0.4\resources\Comet\windows\windows_64bit\comet.exe D:\demo_searchGUI\raw_hf\A1-1.mzml 

java.io.FileNotFoundException: Source 'D:\demo_searchGUI\raw_hf\A1-1.comet.pep.xml' does not exist
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2995)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2936)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by hbarsnes** [comment]
> Which Java version are you using? You need at least Java 9.

I cannot see that you replied to this one?

You can perhaps also try deleting the D:\demo_searchGUI\raw_hf\A1-1.mzml file and run SearchGUI again? Could be that something went wrong the first time the mzml file was created?

If this does not help, you can try running the Comet command line directly from the terminal? That should hopefully provide additional information as to why Comet does not seem to start its search.

**Comment by hbarsnes** [comment]
As I did not hear back from you I'm assuming the issue was resolved? If this is not the case, please let me know and I'll reopen the issue.
