### ISSUE TITLE
Use SearchCLI through Bioconda

### ISSUE THREAD

**Issue by iquasere** [compomics/searchgui#262]
Greetings! I have installed searchgui with Bioconda in a fresh environment, but I cannot find the CLI executable. How can I access SearchCLI installed with Bioconda?

**Comment by CarlosHorro** [comment]
Hi @iquasere ,

Conda packages are installed into your conda installation folder, which depends on the OS and the folder you chose when you installed Conda. In my case, I use MacOs and I installed miniconda into the folder 

/Users/carlos.horro/miniconda3

So my Conda packages are downloaded to 

/Users/carlos.horro/miniconda3/pkgs

But, my uncompressed SearchGUI Conda package (ready to execute) is located at:

/Users/carlos.horro/miniconda3/share

There (changing my local installation folder by yours), you will find a folder with the SearchGUI version you installed and the jar with the SearchCLI executable.

By the way, the last stable version we currently have available in Bioconda is 3.3.10, but we are already working with Bioconda team for having ready version 4 soon.

Greetings,
Carlos

**Comment by iquasere** [comment]
Ok, I see the problem was I was trying again to only run the searchgui jar, without the CLI tools specification. Thank you for your attention ^^
