### ISSUE TITLE
Searches Not Completing v4.04

### ISSUE THREAD

**Issue by lpaul-BioAnalysis** [compomics/searchgui#265]
To whom it may concern,

The searches are not finishing (after 12 hours, X!Tandem). See attached. This is also occurring when I am using Comet and Meta Morpheus. It is stuck on the generation of the peak lists.

Lake

**Comment by hbarsnes** [comment]
Please ensure that you are using Java 9 or newer.

**Comment by lpaul-BioAnalysis** [comment]
Thanks. I am on Windows with Java 8. Can you pint me to the download for Java 9 for windows?

Lake

**Comment by lpaul-BioAnalysis** [comment]
I found out where to download it. Thanks. I just needed to read your instructions!

**Comment by lpaul-BioAnalysis** [comment]
It works! Thanks again for the help!
