### ISSUE TITLE
ControllerType=0

### ISSUE THREAD

**Issue by lpaul-BioAnalysis** [compomics/searchgui#266]
All,

I ran into another problem. After converting the files using the ThermoRawFile Parser to mzxml, successfully  running the searches using X!Tandem, I discovered this "Controllertype-0" error after importing into Skyline. Skyline cannot associate the raw data files with the search results. The previous versions (MS CONVERT) could. 

Can we use the MSCONVERT so as to circumvent this problem? It is grayed out and does not give me an option to select it.

My down stream processing uses Skyline and the older versions of SearchGUI worked well with Skyline.

Thanks,

Lake

**Comment by hbarsnes** [comment]
> After converting the files using the ThermoRawFile Parser to mzxml, successfully running the searches using X!Tandem

I assume you mean mzML and not mzXML. In any case, X! Tandem only supports search in mgf if searched via SearchGUI, i.e. the mzML file is converted to mgf before being searched with X! Tandem

> Can we use the MSCONVERT so as to circumvent this problem? It is grayed out and does not give me an option to select it.

We could look into this, but it would be better to fix the problem with Skyline. Can you provide more details on the error you are seeing in Skyline?

**Comment by lpaul-BioAnalysis** [comment]
Thanks.

That is the only error I am getting in Skyline during the import process.

**Comment by hbarsnes** [comment]
I'm afraid I'm not a Skyline user myself and thus do not have it installed so that I can test. Which files are you uploading to Skyline? Are you also uploading the mzML file generated by ThermoRawFileParser along with the raw file and the search results?

**Comment by hbarsnes** [comment]
BTW, are you trying to use the X! Tandem results directly in Skyline or the mzIdentML export of the results from PeptideShaker?

**Comment by lpaul-BioAnalysis** [comment]
The results directing into Skyline. Load up the .xtan.xml file into Skyline

**Comment by lpaul-BioAnalysis** [comment]
I got the MetaMorpheus .mzid search result files to work in Skyline. I am now trying Comet.

BTW, I am testing out the search engines to see which ones work best with my system.

**Comment by hbarsnes** [comment]
> The results directing into Skyline. Load up the .xtan.xml file into Skyline.

Seems like you'll have to rename your mzML file into "controllerType=0.mzML". At least then I'm able to load the project in Skyline. 

It seems like Skyline expects the spectrum titles to be of a given type in the X! Tandem result files, i.e. starting with the name of the spectrum file used for the search. But there is no requirement for this in generic mgf headers, hence their parsing breaks down.

But at least the easy workaround above seems to solve the problem until Skyline makes their parsing more generic.

**Comment by lpaul-BioAnalysis** [comment]
Easy for you! LOL. Just rename the .mzML into controllertype=0.mzML? Simple as that?

**Comment by hbarsnes** [comment]
> Just rename the .mzML into controllertype=0.mzML? Simple as that?

Yup. You probably need the upper case "T" in "Type" though, but not sure.

Or if you do not want to rename the mzML file you can instead do a search and replace in the X! Tandem xml file replacing "Description">controllerType" with "Description">[name of your mzml file].controllerType".
