### ISSUE TITLE
Stalled out search

### ISSUE THREAD

**Issue by jdlarson09** [compomics/searchgui#269]
I am using SearchGui/peptideshaker to work up some tryptic digests. . I have converted my samples files from .d to .mgf with MSConvert but when I use SearchGUI to start my search it successfully imports the spectrum files but gets stalled out at converting the spectrum files to the peak list. It will stay at this point for days without erroring out or making any progress. Interestingly, a coworker was able to use SearchGui/peptide shaker with my samples files with no issue whatsoever on their computer. I am using the most up to date versions of the programs but they are using much older versions

![Capture](https://user-images.githubusercontent.com/75331009/100780009-6ff80b00-33c6-11eb-8dc1-dee4bceef0e8.PNG)

**Comment by hbarsnes** [comment]
The latest versions of SearchGUI and PeptideShaker now required Java 9 or newer. I would guess that you are using Java 8 (or older). If you update your Java version the issue will hopefully be solved.

**Comment by jdlarson09** [comment]
Thank you. I updated Java previously but it was only updating that version. I downloaded a newer version and it now works.
