### ISSUE TITLE
PeptideShaker: Importing data cancelled

### ISSUE THREAD

**Issue by pasequeira** [compomics/searchgui#270]
Dear all, 

I am trying to upload my data from SearchGUI to Peptide Shaker but the import is cancelled almost at the end. It gives the following error: 
![error_peptideshaker](https://user-images.githubusercontent.com/74972868/100880631-db180f00-34a4-11eb-81ea-8ea664bafd0b.png)

Thank you so much for the help
Patrícia

**Comment by pasequeira** [comment]
I am trying to identify peptides and not protein, so I was expecting to have few results. But most of the times I manage to opened, so I thought it could be some problem related with the software.  

Can you upload the files you've asked? 
[report.txt](https://github.com/compomics/searchgui/files/5629805/report.txt)
[PeptideShaker 2.0.5 log.txt](https://github.com/compomics/searchgui/files/5629809/PeptideShaker.2.0.5.log.txt)

**Comment by hbarsnes** [comment]
It indeed seems like your in a situation we have not considered given the low amount of overall identifications. Would it be possible for you to share the data you are trying to load so that I can reproduce and hopefully fix the issue?

**Comment by pasequeira** [comment]
Yes, for sure, I will send it by email. 

Thanks ;)

**Comment by hbarsnes** [comment]
Great! I think I already have a fix ready, but would be best to test it before releasing a new version. Please send the data to harald.barsnes@gmail.com.

**Comment by hbarsnes** [comment]
Thanks for sharing the data! I've just released a new version of PeptideShaker that should allow you to open this particular dataset. If you still experience problems, please let me know and I'll reopen the issue.
