### ISSUE TITLE
problems with identifying proteins after search with X!Tandem

### ISSUE THREAD

**Issue by AnkeTraut** [compomics/searchgui#271]
Hallo everybody,

I have a problem and a more general question. Hopefully you can help me.

First, I want to start with the general question:
I often search the same raw files several times with different parameters/databases/aso and combine the results later in a full version of scaffold from ProteomSoftware. I found several times that the number of spectra differ slightly between the different searches from the same raw files. And of cause I don't reflect the number of the identified spectra - I mean the number of the recorded spectra. How is this possible? Have you any idea? If I use only results from Mascot - the number of spectra is identical.

Second, I searched 12 different raw files with three different database (increasing in size) and X!tandem implemented in SearchGUI (version 3.3.21 - I use an older version caused for reproducibility inside the project). I used the same mgf-files (generated from the msconvert implemented in searchGUI) for the three searches but with the biggest database I could not identfiy any protein in three of the 12 samples. When I used the same *.mgf files and a smaller database (which was also included in the bigger database) I found same number of proteins compared to the other samples. Have you any idea what happened?
I repeated the search several time with new *.raw files and I generated *.mgf files by msconvert as stand alone software but I got always the same output for the bigger databse. What can I do?

Thank you very much for helping

**Comment by hbarsnes** [comment]
> I often search the same raw files several times with different parameters/databases/aso and combine the results later in a full version of scaffold from ProteomSoftware. I found several times that the number of spectra differ slightly between the different searches from the same raw files. And of cause I don't reflect the number of the identified spectra - I mean the number of the recorded spectra. How is this possible? Have you any idea? If I use only results from Mascot - the number of spectra is identical.

The number of spectra should of course be the same and independent of the search settings. To me this sounds like an internal issue in how Scaffold his handling the identifications. However, I have no experience with Scaffold myself and hence cannot comment on why this would be the case. Have you tried contacting the Scaffold developers?

You can perhaps also try loading your search results in [PeptideShaker](https://github.com/compomics/peptide-shaker) instead? At least then we would be able to explain it if you see similar issues there.

> Second, I searched 12 different raw files with three different database (increasing in size) and X!tandem implemented in SearchGUI (version 3.3.21 - I use an older version caused for reproducibility inside the project). I used the same mgf-files (generated from the msconvert implemented in searchGUI) for the three searches but with the biggest database I could not identfiy any protein in three of the 12 samples. When I used the same *.mgf files and a smaller database (which was also included in the bigger database) I found same number of proteins compared to the other samples. Have you any idea what happened?

Are you still referring to loading the search results in Scaffold? If so, I would again recommend that you contact the Scaffold developers directly. But as a general comment it could be that by using the larger database you are impacting the protein inference complexity and perhaps Scaffold has some sort of filter kicking out peptides that map to too many proteins (or something similar)? Also, greatly increasing the number of proteins in your database may also impact the FDR-calculations at the protein level and potentially result in more protein matches being filtered out? I'm just speculating here though.

And again I'd recommend contacting the Scaffold developers. Or try loading the data in PeptideShaker.

**Comment by AnkeTraut** [comment]
I have now contact to Sceffold deveolpers...
Thanks for helping
