### ISSUE TITLE
Conversion of spectrum file to peak list

### ISSUE THREAD

**Issue by Kabir12321** [compomics/searchgui#278]
Hello all,

I am trying to convert an MGF file to the peak list using searchgui. However, it seems the process gets stuck at that step. Following is the message that appears in the progress report.

~Converting spectrum file XXX.mgf to peak list.

Any help is gladly accepted.

Best,
Kabir

**Comment by hbarsnes** [comment]
Hi Kabir,

Do you know which Java version you are using? As SearchGUI (and PeptideShaker) now requires Java 9 or newer. Hopefully an upgrade to a more recent Java version will solve the problem.

Best regards,
Harald

**Comment by Kabir12321** [comment]
This has solved the problem.

Thanks, Harald!
