### ISSUE TITLE
Error: Cannot read the array length because "" is null

### ISSUE THREAD

**Issue by TjorvenH** [compomics/searchgui#279]
Dear SearchGUI team,

while testing SearchGUI for some metaproteomics data, I got this error when running X!Tandem:

       Error: Cannot read the array length because "" is null
       An error occurred while running SearchGUI. Please contact the developers.
       The search or processing did not finish properly!

This worked properly in another test, so I am not sure what happened. Any help would be appreciated!

Thank you and best regards!

**Comment by hbarsnes** [comment]
Hi,

Do the other search engines also have issues with the same dataset? And have you tried changing the search settings slightly to see if this has any effect? Finally, are there any additional messages in the SeachGUI log file? You can find the log via the main SearchGUI dialog > Help menu > Bug Report.

Best regards,
Harald

**Comment by TjorvenH** [comment]
The full error message was:

java.lang.NullPointerException: Cannot read the array length because "<local6>" is null
    at eu.isas.searchgui.SearchHandler.getXTandemFiles(SearchHandler.java:1463)
    at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2653)
    at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:832)

While the same file with the same settings was running smoothly this time, it would be interesting whether this error occured by chance or has some other cause.
Thank you!

**Comment by hbarsnes** [comment]
Thanks for the full error message. I assume you are using the most recent version of SearchGUI? If so, the issue seems to be related to the temp folder where the results are temporarily stored before being moved to final zip file output (unless you changed the default output type). Is it possible that you are running more than one search from the same SearchGUI installation at the same time? As this can mess up the temp folder usage.

BTW, are you running SearchGUI via the graphical interface or via the command line?

**Comment by TjorvenH** [comment]
Indeed, it's the most recent version. No, it was one search running (via the graphical interface), and I did not change the output type.

**Comment by hbarsnes** [comment]
And there are no errors from X! Tandem directly? In other words, does the X! Tandem search itself provide any errors messages?

Also, what do you choose as your output folder? Can it be that it is on a shared drive or a network drive that might be altered along the way?

**Comment by TjorvenH** [comment]
There were no error messages by X!Tandem. However, the output folder is on a network drive - maybe the connection failed during the search. I'll look into that. Thanks a lot!
