### ISSUE TITLE
update Comet past 2020.01 rev1

### ISSUE THREAD

**Issue by chrishuges** [compomics/searchgui#280]
Hi, 

It seems there was a bug in the 2020.01 rev1 release of Comet that has now been fixed in 2020.01 rev2. I have noticed this in my own searches where Comet just isn't generating any results. Possible to get this update in the next release?

I check the release notes and it doesn't look like Comet has been updated recently (I am using SearchGUI 4.0.8). 

Thanks,
Chris

**Comment by hbarsnes** [comment]
Hi  Chris,

I was not aware that Comet 2020.01 rev2 had been re-released, as there were some issues with the initial release and it had to be retracted. Thanks for letting me know!

A new SearchGUI version is now available which includes Comet 2020.01 rev2.

Best regards,
Harald
