### ISSUE TITLE
unable to open Multiple .d Bruker files and MSconvert not working

### ISSUE THREAD

**Issue by Maithy15** [compomics/searchgui#281]
1.When I try to select multiple .d files in Search GUI it complains that the files have the same name even though all my files have unique names. When I convert the files using MS convert it does not complain anymore.
2. When I just load one .d file in search GUI and try to use the MSconvert from Search GUI itself it complains that the appropriate output version (mgf/mzml) is not selected even though it is.

**Comment by hbarsnes** [comment]
Thanks for letting us know about the issues with converting Bruker .d files. I'm afraid we do not have much experience with converting Bruker .d files ourselves. Would it be possible for you to share a couple of these files so that we can try to reproduce the issue on our side?

**Comment by Maithy15** [comment]
Thanks for the help. You can find the .d files here https://fz-juelich.sciebo.de/s/8GFsAhdUd2Q3Vwf. The zip file contains three measurement files, all are Trypsin digests of _A.thaliana_ proteome.

**Comment by hbarsnes** [comment]
Thanks for sharing the files! I've just released SearchGUI 4.0.15 which should solve the problem. If this is not the case, please let me know and I'll reopen the issue.

Note that you should choose the .d files as input and not the parent folder, as this would also select the .baf file and result in the issue with non-unique file names.
