### ISSUE TITLE
Help with [Error] D:\file.mzML does not have any valid spectra when using MS-GF+

### ISSUE THREAD

**Issue by ttessie2** [compomics/searchgui#282]
This is my first time setting up searchgui so I'm not entirely familiar with everything yet. I'm using an mzML file as input and I'm getting this error. I used MSConvert on the RAW file (not through searchgui) to generate the mzML file. I've used this mzML file with MS-GF+ in the past and it worked without any issues. However, at the time I was using MS-GF as a standalone and not with searchgui.

**Comment by hbarsnes** [comment]
When using mzML as input we simply forward this file to MS-GF+. In other words, we do not alter the mzML file in any way. I would therefore recommend that you take a closer look at the search settings being used. Maybe your search settings are too restrictive? Remember to also check the MS-GF+ specific search settings available by clicking the cog wheel after MS-GF+ in the main SearchGUI dialog.

You may also want to take a look at the MS-GF+ command line being used. It is written to the SearchGUI log file which you can find via the SearchGUI Help menu under Bug Report. Perhaps comparing it to the one from the standalone version will enable you to spot any differences and make changes if required.

**Comment by ttessie2** [comment]
Hi Harald,
Thanks for that. I realized I was screwing something up in the parameter file. Just took some time to familiarize myself with it.
