### ISSUE TITLE
Unable to download SearchGUI 4.0.18

### ISSUE THREAD

**Issue by Luq16** [compomics/searchgui#283]
Hello,
I am unable to SearchGUI 4.0.18 for windows.

Thank you.

**Comment by hbarsnes** [comment]
Thanks for letting us know. I was just informed that the server where the downloads are stored is down. Hopefully it will be back online soon. I will keep you posted.

**Comment by hbarsnes** [comment]
The downloads should now work again. There however seems to be an issue with the download speed. But hopefully this should be fixed soon as well.
