### ISSUE TITLE
Protein label in Tandem XML file abbreviates protein name

### ISSUE THREAD

**Issue by tivdnbos** [compomics/searchgui#284]
Hi,

I've noticed that longer protein names get abbreviated with "..." in the Tandem XML file when using X!Tandem in SearchGUI 4.0.18;
more specifically in the label name from the <group> or <protein> tag. 
Is there a way to resolve this? 

Best,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

I'm afraid that this is outside of our control and something X! Tandem does on its own. As far as I know there is no way to change this. Generally you should depend on accession numbers and not potentially very long protein names though?

Best regards,
Harald
