### ISSUE TITLE
Changes to peptide length range not being saved for Comet

### ISSUE THREAD

**Issue by kevinkovalchik** [compomics/searchgui#285]
Hello!

When I change the peptide length range in the Comet Advanced Settings it isn't triggering a prompt to save the changes when I close the settings window, and when reopening the settings the peptide lengths are back to the defaults. If I change the peptide length and another setting then I am prompted to save the changes, but when reopening the settings the peptide length remains at the default.

For other search engines this doesn't seem to happen.

I've found this is in v4.0.18 and also an copy of v4.0.3 I have. I'm using the Linux versions.

Best wishes,
Kevin

**Comment by hbarsnes** [comment]
Hi Kevin,

Thanks for letting us know! You are indeed correct, neither the min nor the max peptide length value for Comet is actually stored. I'll fix this and release a new version as soon as possible.

Best regards,
Harald

**Comment by kevinkovalchik** [comment]
Okay, thanks!

**Comment by hbarsnes** [comment]
I've just released SearchGUI 4.0.19 which should solve this problem. If this is not the case, please let me know and I'll reopen the issue.
