### ISSUE TITLE
Search-gui Andromeda issue

### ISSUE THREAD

**Issue by NoeGuilloy** [compomics/searchgui#289]
Hi,
I am getting an issue during the search with andromeda.

![andromeda error](https://user-images.githubusercontent.com/65976013/111385287-f0463180-8680-11eb-8d15-424622d91801.png)

I am using a custom fasta database which contains 100K proteins and work well using Maxquant or Xtandem/msgf on Linux.

Here is the .par file of the search.
[TIms andro.txt](https://github.com/compomics/searchgui/files/6152461/TIms.andro.txt)

Thanks !
Noé

**Comment by hbarsnes** [comment]
Hi Noé,

I'm afraid that when Andromeda breaks there is not all that much we can do on our end. Especially given that it can be quite difficult to make sense out of the error messages it provides. You can try setting up an issue with the Andromeda developers (https://groups.google.com/g/andromeda-list)?

Regarding Andromeda working fine inside MaxQuant, I think this can be explained by the two Andromeda versions not being identical. We have been waiting for an updated standalone version of Andromeda for quite some time, but it seems like it will not become available anytime soon.

Unless you really need to use Andromeda I would recommend that you instead go for one (or more) of the other search engines included in SearchGUI?

Best regards,
Harald
