### ISSUE TITLE
mzML parsing error

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/searchgui#292]
Hi, any idea as to why I am getting this error (please see attached)? The error occurred when parsing the mzML file. I am using SearchGUI 4.0.22 CLI.

Thanks!

Carla Uranga

[SearchGUI.log](https://github.com/compomics/searchgui/files/6200470/SearchGUI.log)

[sal6_rep1.log](https://github.com/compomics/searchgui/files/6200476/sal6_rep1.log)

**Comment by hbarsnes** [comment]
Hi Carla,

There seems to be an error when parsing the mzML file: "An invalid XML character (Unicode: 0x0) was found in the element content of the document."

Could it be that the mzML contains non-standard characters? Where did the file come from?

If you can share the file I can always take a closer look.

Best regards,
Harald

**Comment by CarlaCristinaUranga** [comment]
Ok so something is happening now, but the results are not generated. Please
see attached.

Best,
Carla

**Comment by hbarsnes** [comment]
> Please see attached.

Seems like the attachement was lost along the way. You need to upload it via the issues page. Attaching it to the email does not work. I also have trouble downloading the mzml file you sent me. For some reason I only get a preview but no download option...

Best regards,
Harald

**Comment by hbarsnes** [comment]
Never mind the issues with downloading the mzml file. I figured it out. :)

**Comment by hbarsnes** [comment]
Hi again. I have no problems parsing the mzml file you sent me. Are you sure it's the same as the one where you have the issue above?

**Comment by CarlaCristinaUranga** [comment]
So on the server it seems to be an issue with MS-GF+, which does not complete processing and does not produce an output file. I am able to run it on my desktop with a smaller database (to test), so it should run on the CLI, but for some reason it is not. Thank you so much Harald!

Carla

[sal_7.log](https://github.com/compomics/searchgui/files/6205329/sal_7.log)
[SearchGUI.log](https://github.com/compomics/searchgui/files/6205330/SearchGUI.log)

**Comment by hbarsnes** [comment]
Seems to be an issue with the size of the database: https://github.com/compomics/searchgui/issues/293

Can you try increasing the amount of memory given to SearchGUI (and as a consequence to MS-GF+)?

Or simply skip MS-GF+. :)

**Comment by CarlaCristinaUranga** [comment]
So I tried a really small database and am still having issues with msgf on the CLI:

rev_human.fasta
SearchGUI.log
sal_7.log

**Comment by CarlaCristinaUranga** [comment]
[sal_7.log](https://github.com/compomics/searchgui/files/6206679/sal_7.log)
[SearchGUI.log](https://github.com/compomics/searchgui/files/6206680/SearchGUI.log)

I am not sure it is a database size issue. Thank you kindly for your attention to this!

Kind regards,

Carla

**Comment by hbarsnes** [comment]
From the SearchGUI log file it seems like you are trying to run Andromeda? However, Andromeda is not support on Linux.

**Comment by CarlaCristinaUranga** [comment]
Hi Harald you were right, it was a database size issue. I am now working with a 1 GB database and it is working. Thank you so much! It is great to know what we can and cannot do with SearchGUI.
Best wishes,
Carla
