### ISSUE TITLE
Trouble importing FASTA database

### ISSUE THREAD

**Issue by ttessie2** [compomics/searchgui#296]
Just updated to the most recent SearchGUI and I get this error when importing a database file:
"There was an error importing the FASTA file: Duplicated accession number: O95825"
I'm not sure why I'm getting this error, the file doesn't have any duplicate accession numbers. I've been using this database file in SearchGUI lately without any issues.

**Comment by hbarsnes** [comment]
Thanks for letting us know. I made a mistake when adding the check for duplicate headers. I will release a new version in a couple of minutes.

**Comment by hbarsnes** [comment]
I have just released a new version of SearchGUI that should solve the problem (while still keeping the check for duplicated accession numbers). If this is not the case, please let me know and I'll reopen the issue.

**Comment by ttessie2** [comment]
Thank you, the issue is resolved!
