### ISSUE TITLE
Official explanation of all the columns of the output

### ISSUE THREAD

**Issue by abrozzi** [compomics/searchgui#301]
Dears,
after a deep Google search and git search I could only retrieve partial explanations on the value reported in each column of the output:

```
"Protein.Inference"`              "Main.Accession"                 "Description"                   
"Protein.Group"                  "Descriptions"                   "Gene.Name"                      "Validated.Coverage...."        
"Confident.Coverage...."         "All.Coverage...."               "Possible.Coverage...."          "X.Peptides"                    
"X.Validated.Peptides"           "X.Unique.Peptides"              "X.Validated.Unique.Peptides"    "Non.Enzymatic.Peptides"        
"X.PSMs"                         "X.Validated.PSMs"               "Spectrum.Counting"              "Spectrum.Counting.NSAF"        
"Spectrum.Counting.emPAI"        "Spectrum.Counting.NSAF...."     "Spectrum.Counting.emPAI...."    "Spectrum.Counting.NSAF..ppm."  
"Spectrum.Counting.emPAI..ppm."  "Spectrum.Counting.NSAF..fmol."  "Spectrum.Counting.emPAI..fmol." "MW..kDa."                      
"Protein.Length"                 "X.Peptides.Fraction.11"         "X.Spectra.Fraction.11"          "Score"                         
"Raw.Score"                      "Confidence...."                 "Validation"                     "Decoy"
```

Do you provide an official explanation text file for each column including formulas to calculate the value?

Thank you very much! Much appreciated!
-A

**Comment by hbarsnes** [comment]
I assume you are referring to the PeptideShaker exports? If so, you can find the description for each term by opening the Export menu in PeptideShaker, selecting Identification Features and then clicking the "Add new report type" link at the bottom left. In the dialog that shows up you can then select the section you want the details for.

Here's an example:

![Feature descriptions](https://user-images.githubusercontent.com/13151214/116871572-bf13c780-ac14-11eb-8815-884137d90da2.png)

**Comment by abrozzi** [comment]
Brilliant! Yes I was referring to that export.
```Spectral.Counting NSAF``` I believe has this formula:

https://github.com/moldach/proteomics-spectralCount-normalization

For ```Spectral.Counting``` I read on a Google Group that the number of spectra for a peptide is weighted by the number of times a peptide is occurring in a validated protein (https://groups.google.com/g/peptide-shaker/c/_RMzv5vlGlM/m/kpR_PauVBQAJ)

My fault, is there a single place where all these important info are documented?

Much appreciated!
-A

**Comment by hbarsnes** [comment]
> My fault, is there a single place where all these important info are documented?

I'm afraid not. But it seems like you found the information you needed?
