### ISSUE TITLE
Inclusion of Trypsin/LysC 

### ISSUE THREAD

**Issue by jackframar** [compomics/searchgui#302]
Could the combination of Trypsin/LysC be added to the list of available enzymes? Thanks!

**Comment by hbarsnes** [comment]
Please correct me if I'm wrong, but if Trypsin cuts after R and K, and LysC cuts after K (both with the P-rule), then why would you need a separate Trypsin/LysC combination? Wouldn't Trypsin alone already cover this..?

Note that you may create your own enzymes via Edit > Enzymes. However the use of more than one enzyme at the time is not directly supported, at least not by most if the search engines themselves.

**Comment by mammmals** [comment]
LysC should be able to cleave K's with a +1 proline, generally we search trypsin/lysC digests by removing the P-rule and allowing cleavage at all K/R's.

**Comment by hbarsnes** [comment]
Issue assumed resolved, if this is not the case, please let us know and we'll reopen the issue.
