### ISSUE TITLE
FastaCLI: skip duplicates rather than error

### ISSUE THREAD

**Issue by jcanderan** [compomics/searchgui#304]
Hello,

Is there a possibility to allow FastaCLI to skip duplicate accessions rather than error out? Sometimes the same accession is in multiple proteomes on Uniprot.

Naturally, one could already check for this outside of SearchGUI but it's already being done by FastaCLI.

Thanks!

**Comment by hbarsnes** [comment]
If your FASTA file contains duplicate accessions, I would very much recommending taking a closer look at how you generate the FASTA file in the first place. Not sure how you would end up with a duplicated entries if you use the proteomes from UniProt? Unless you are merging proteomes and using that as your FASTA file? Not sure in which situations that would make sense though?

**Comment by jcanderan** [comment]
For example:

https://www.uniprot.org/uniprot/A0A1V0QD85 is in two proteomes, which are in two different pan proteomes.

If you generate a FASTA with those two pan proteomes (e.g., a metaproteomics pipeline, such as [this one](https://www.sciencedirect.com/science/article/pii/S2405471218303569)) you would have duplicate accessions.

This doesn't happen often because it's likely that those two different proteomes end up in the same pan proteome, but it's not the case for this protein.

Either way, it's not a big deal to check outside SearchGUI. I just figured it might be a better way to handle the issue rather than erroring out although the fact that it errored out did help me identify there was this particular issue because I hadn't encountered it before so a warning message (if it skips) is still useful.
