### ISSUE TITLE
Support of Bruker timsTOF PASEF .d files 

### ISSUE THREAD

**Issue by hcadre** [compomics/searchgui#307]
Dear All, 
since the Bruker timsTOF instruments are seemingly becoming very popular and find dissemination in more and more proteomics labs, I am wondering whether there are any plans to also support direct upload and analysis of .d PASEF files within the SearchGUI environment?
Best, 
Hannes

**Comment by hbarsnes** [comment]
Hi Hannes,

We have no plans for direct support for .d PASEF files at the moment. But I assume that you can convert them outside of SearchGUI and provide the mgf or mzML files as input?

Best regards,
Harald
