### ISSUE TITLE
precursor charge issue

### ISSUE THREAD

**Issue by chlobard** [compomics/searchgui#310]
Hello,
When I use the new search gui version, in order to interrogate WIFF file (or MGF comming from wiff file, it does not work (search canncelled).
When I use the 3.3.20 version, i cannot start with WIFF file, I have to convert it in mgf using MSconvert (same version than in the search GUI application but it does not work by the application) and after I have to upload the MGF in the application searchGUI. At this moment a message appears :" your file ... contains spectra wihout precursor charges.... " I have to say "yes" and the process keep going but the results were not consistent to what we have observed in the raw data. 

Have you an idea to solve this issue.

Thank you in advance,
Best,

Chloé

**Comment by hbarsnes** [comment]
Hi Chloé,

I'm afraid we do not have much experience with WIFF files ourselves. But when you get the question about whether you want to add the missing charges it simply means that the given mgf file contains at least one spectrum where the precursor charge is not defined. The reason for asking the question is that some search engines will simply kick out any spectrum where the precursor charge is not defined. And when selecting the "Yes" option we are adding the charge range defined in the SearchGUI Advanced Settings (found via the Edit menu). In this dialog you can also disable the check for missing charges (which should simply be the same as choosing the "No" option when asked if you want to add the missing charges).

I think it therefore makes sense that adding such a charge range may impact the search results (depending on the search engines used). Maybe you can try not adding the charges and see if that makes a difference for the search engines you use? And if it brings the results closer to the search using the raw data?

You may also want to test different search engines to see how that affects the results.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. It this is not the case, please let us know and we'll reopen the issue.
