### ISSUE TITLE
Recently i started using searchGUI for peptide data analysis, but encountered some problem

### ISSUE THREAD

**Issue by manishsansi** [compomics/searchgui#313]
I started uysing searchgui.. but trapped in a problem /error.. here i am attaching bug report please try to solve
[SearchGUI 4.1.1 log.txt](https://github.com/compomics/searchgui/files/7448435/SearchGUI.4.1.1.log.txt)

**Comment by hbarsnes** [comment]
I don't see any real errors in the log file. Could you also share a screenshot of what the problem looks like in SearchGUI?

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
