### ISSUE TITLE
download website is down

### ISSUE THREAD

**Issue by mknierman** [compomics/searchgui#314]
The download website is down.   Error message is "genesis.ugent.be took too long to respond"

**Comment by hbarsnes** [comment]
Thanks for letting us know! I will look into it and get back to you.

**Comment by hbarsnes** [comment]
I’m afraid that it is taking longer than we hoped for to get the server back online.

In the meantime you can download the latest version of SearchGUI here:  https://iomics.ugent.be/maven2/eu/isas/searchgui/SearchGUI/4.1.3/SearchGUI-4.1.3-windows.zip and https://iomics.ugent.be/maven2/eu/isas/searchgui/SearchGUI/4.1.3/SearchGUI-4.1.3-mac_and_linux.tar.gz

And if you also need PeptideShaker, you can find it here:
https://iomics.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/2.2.2/PeptideShaker-2.2.2.zip

**Comment by hbarsnes** [comment]
The server is now finally back online and the normal links are working again.
