### ISSUE TITLE
Problem with target-decoy database

### ISSUE THREAD

**Issue by kromer-m** [compomics/searchgui#315]
Hi,
I have the following issue:
MS-GF+ apparently is not capable to recognize target-decoy database created by SearchGUI. When decoys are appended by SearchGUI, the header of decoy protein looks like this:

`>sp|XXXALBU_BOVIN|XXX`

On the other hand, when I create decoy database directly by MS-GF+ (outside SearchGUI) it looks like this:

`>XXX_sp|ALBU_BOVIN|`

When SearchGUI search with MS-GF+ is started with its own target-decoy database, it produces the error:

```
Error while indexing: database_concatenated_target_decoy.revCat.fasta (too many redundant proteins)
If the database contains forward and reverse proteins, run MS-GF+ (or BuildSA) again with "-tda 0"
If the decoy protein names do not start with XXX either rename them, or use the -decoy switch

```

The identical problem happens when loading MS-GF+ created revcat.fasta database in PeptideShaker (duplicated accession number error occurs). When for the same data I load database created by SearchGUI, everything goes smoothly.

Conclusion is that apparently SearchGUI places recognition prefixes in front of the accession number, while MS-GF+ places (and looks for) the prefix at the start of the fasta header.

Do you have any idea, how to fix this?

Thank you!

**Comment by hbarsnes** [comment]
You are correct in that SearchGUI and MS-GF+ are annotating the decoys differently. Generally, we do not use the decoy option in MS-GF+ when running SearchGUI but rather treat all sequences equally and instead utilize the target-decoy information when later (re-)processing the data in PeptideShaker and there calculating the FDR.

You therefore have two options: i) turn off the "Search Decoy Database" option in the advanced MS-GF+ settings (which is the default) and add the decoys via SearchGUI when when selecting the FASTA in SearchGUI, or ii) turn the "Search Decoy Database" option on, do not add the decoys when selecting the FASTA in SearchGU, and rather create the decoys via MS-GF+.

The choice all depends on what you want to do with the output. If you plan on later processing the data in PeptideShaker (and potentially merging it with the results from other search engines) you should go for the first option. If you only plan to use MS-GF+ and do not want to process the output in PeptideShaker, you should go for the second option.

**Comment by kromer-m** [comment]
Great, thank you for the answer!
