### ISSUE TITLE
calculate pvalues with tide

### ISSUE THREAD

**Issue by stsour** [compomics/searchgui#316]
Hello, 

I am trying to search CPTAC data with SearchGUI using Tide. The indexing goes fine, but I have not been able to get p-values for the PSMs.  Here is a (partial) error message that I get when I set -tide_compute_p '1' :

> Processing: 01CPTAC_CCRCC_W_JHU_20171007_LUMOS_f15.mzML (1/25)
> 
> Wed Jan 12 22:04:11 EST 2022 Converting spectrum file 01CPTAC_CCRCC_W_JHU_20171007_LUMOS_f15.mzML for Tide.
> 10% 20% 30% 40% 50% 60% 70% 80% 90%
> 
> tide search command: 
> /scratch/tsour.s/S1_tide/SearchGUI-4.1.3/resources/Tide/linux/linux_64bit/crux tide-search --compute-sp F /scratch/tsour.s/S1_tide/SearchGUI-4.1.3/resources/temp/peak_lists/01CPTAC_CCRCC_W_JHU_20171007_LUMOS_f15.ms2 /scratch/tsour.s/S1_tide/SearchGUI-4.1.3/resources/temp/search_engines/tide/fasta-index --overwrite T --top-match 10 --precursor-window 20.0 --precursor-window-type ppm --fileroot 01CPTAC_CCRCC_W_JHU_20171007_LUMOS_f15 --exact-p-value T --output-dir /scratch/tsour.s/S1_tide/SearchGUI-4.1.3/resources/temp/search_engines/tide/crux-output --spectrum-min-mz 0.0 --min-peaks 20 --spectrum-charge all --max-precursor-charge 7 --remove-precursor-peak F --remove-precursor-tolerance 1.5 --print-search-progress 1000 --use-flanking-peaks F --use-neutral-loss-peaks F --mz-bin-width 0.02 --mz-bin-offset 0.0 --num-threads 28 --concat F --txt-output T --sqt-output F --pepxml-output F --mzid-output F --pin-output F --verbosity 30 
> 
> 
> Wed Jan 12 22:04:33 EST 2022 Processing 01CPTAC_CCRCC_W_JHU_20171007_LUMOS_f15.ms2 with Tide.
> 
> INFO: Beginning tide-search.
> WARNING: The output directory '/scratch/tsour.s/S1_tide/SearchGUI-4.1.3/resources/temp/search_engines/tide/crux-output' already exists.
> Existing files will be overwritten.
> WARNING: The file '/scratch/tsour.s/S1_tide/SearchGUI-4.1.3/resources/temp/search_engines/tide/crux-output/01CPTAC_CCRCC_W_JHU_20171007_LUMOS_f15.tide-search.log.txt' already exists and will be overwritten.
> INFO: CPU: c0355
> INFO: Crux version: 3.0.17109
> INFO: Wed Jan 12 22:04:33 EST 2022
> INFO: Running tide-search...
> INFO: Number of Threads: 28
> FATAL: Tide-search with XCorr p-values and variable bin width is not allowed in this version of Crux.
> 

I have set the mz_bin_width to 0.02, in line with the tide documentation. I've also removed any modifications from the termini. 
Is there a different version of Crux that I need to be using?

Thanks,
Shiri

**Comment by hbarsnes** [comment]
Hi Shiri,

I would recommend that you contact the Tide developers directly as they will hopefully know more about this limitation and how to deal with it. You can contact them here: https://groups.google.com/g/crux-users.

In the meantime I will look into updating Tide/Crux to the latest version.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

On second thought, it is probably better that you wait with contacting the Tide/Crux developers until after I've updated the Tide/Crux version in SearchGUI. A new version of SearchGUI should be available later today or tomorrow.

Best regards.
Harald

**Comment by hbarsnes** [comment]
Hi Shiri,

The new SearchGUI version has now been released. Please give it a try and see if it solves the Tide issue.

Best regards,
Harald

**Comment by stsour** [comment]
Hi Harald, 

It seems to be working now. 

I did run into the error `Cannot run program "/scratch/tsour.s/S1_tide/SearchGUI-4.1.6/resources/Tide/linux/crux" (in directory "/scratch/tsour.s/S1_tide/SearchGUI-4.1.6/resources/Tide/linux"): error=2, No such file or directory`. The crux file was in "/scratch/tsour.s/S1_tide/SearchGUI-4.1.6/resources/Tide/linux/linux/crux" so I just moved it. 

This may have caused another issue though, because now I am seeing this message when searching the raw files:

>INFO: Starting search.

> FATAL: PSM p-value should not be equal to 0.0
> *** Error in `/scratch/tsour.s/S1_tide/SearchGUI-4.1.6/resources/Tide/linux/crux': double free or corruption (!prev): 0x00000000e5ce4870 ***
> FATAL: PSM p-value should not be equal to 0.0
> ======= Backtrace: =========
> /lib64/libc.so.6(+0x81329)[0x2b166ff7c329]
> /scratch/tsour.s/S1_tide/SearchGUI-4.1.6/resources/Tide/linux/crux[0xef01d2]
> /scratch/tsour.s/S1_tide/SearchGUI-4.1.6/resources/Tide/linux/crux[0xf03b52]
> /lib64/libc.so.6(+0x39ce9)[0x2b166ff34ce9]
> /lib64/libc.so.6(+0x39d37)[0x2b166ff34d37]
> /scratch/tsour.s/S1_tide/SearchGUI-4.1.6/resources/Tide/linux/crux[0x7594a9]
> /scratch/tsour.s/S1_tide/SearchGUI-4.1.6/resources/Tide/linux/crux(_ZN21TideSearchApplication6searchEPv+0x2727)[0x9273a7]
> pure virtual method called
> /scratch/tsour.s/S1_tide/SearchGUI-4.1.6/resources/Tide/linux/crux[0xf3d0a5]
> /lib64/libpthread.so.0(+0x7ea5)terminate called without an active exception

Even though it says fatal, the search is still processing through all my raw files.

**Comment by hbarsnes** [comment]
Hi Shiri,

Thanks for lettering me know about the folder error! This has now been fixed and a new version released (with the only change being the moving of the crux executable that you already did manually).

As for the fatal Tide error I'm afraid it does not makes more sense to me than to you. I would recommend that you contact the Tide developers if you want to know more.

Best regards,
Harald

**Comment by stsour** [comment]
Ok, thanks for your help!

**Comment by hbarsnes** [comment]
I will then close this issue, but do not hesitate to open a new one if you come across other problems.
