### ISSUE TITLE
Any way to generate decoy database using peptide reversed strategy?

### ISSUE THREAD

**Issue by nattzy94** [compomics/searchgui#317]
Hi,

I am trying to analyse my mass spec data using 2 search engines - tide and X!tandem. I am running X!Tandem via SearchGUI whereas for tide I am running it via the MS toolkit crux. `crux tide` generates a target-decoy database using a peptide reversal method where the target protein database is first _in silico_ digested into a target peptide database. The target peptides are then reversed to generate the decoy peptide database.

I would like to keep the searches between the 2 search engines consistent by using the same input database. I can use the databases generated by tide as input to SearchGUI's X!Tandem. However, there does not seem to be a `no-digestion` option available. Furthermore, SearchGUI would not be able to link the peptides with the original protein it came from.

Is there a way for SearchGUI to generate decoy databases using a peptide reversal strategy? Otherwise, I can just re-do my tide searches using the protein reversal method instead.

Thanks!

**Comment by hbarsnes** [comment]
Is there any reason why you cannot simply run Tide via SearchGUI as well? This would ensure that the same database is used?

As for a "no digest" option, you can try the "Whole Protein" option when selecting the enzyme. However, note that the support for peptide databases may not be as good for all of the search engines as this is generally not what they were initially intended for.

> Is there a way for SearchGUI to generate decoy databases using a peptide reversal strategy?

No, I'm afraid this is not something we currently support.

**Comment by nattzy94** [comment]
Okay, thanks! I will try out your suggestions.
