### ISSUE TITLE
Adding additional elements to the composition editor

### ISSUE THREAD

**Issue by EuanGor** [compomics/searchgui#319]
There appears to be only 17 elements available for selection in the composition editor (when adding a new modification) - is there a simple way to extend this dropdown to include a greater number of elements?  This is on the latest windows release. 

thanks,

Euan

**Comment by hbarsnes** [comment]
Hi Euan,

Adding new elements is not very difficult, but I'm afraid it is not something users can do themselves. However, if you send me the list of the particular elements you are missing I can add them and release a new version.

Best regards,
Harald

**Comment by EuanGor** [comment]
Hi,

thanks for the reply.  I would find it useful to have, Cl, Co, Ni, Mn, Li, hopefully others would find it useful too,

regards,

Euan

**Comment by hbarsnes** [comment]
Hi Euan,

I've now added the requested elements (Li was already there though) and released a new version of SearchGUI.

Please let me know if it does work as wanted and I'll reopen the issue.

Best regards,
Harald
