### ISSUE TITLE
About Non standard fasta issue

### ISSUE THREAD

**Issue by kyungsikshi** [compomics/searchgui#325]
I have to use non standard fasta format for searchGUi
I made a fasta file in to the format that was told in http://compomics.github.io/projects/searchgui/wiki/DatabaseHelp.html
However it seems that peptide shaker can not read the result. 

>generic|NP:001234943.1-1
MNNNWLSFPLSPTHSSLPAHDLQATQYHQFSLGLVNENMENPFQNHDWSLINTHSSSEVPKVADFLGVSKSENESDLAASLNEIQSNDSDYLFTNNSLVPMQNPAVDTPSNEYQENANSSLQSLTLSMGSGKDSTCETSGDNSTNTTTTTTVEAAPRRTLDTFGQRTSIYRGVTRHRWTGRYEAHLWDNSCRREGQSRKGRQVYLGGYDKEEKAARSYDLAALKYWGTSTTTNFPISNYEKELDEMKHMTRQEFVAAIRRKSSGFSRGASMYRGVTRHHQHGRWQARIGRVAGNKDLYLGTFSTEEEAAEAYDIAAIKFRGLNAVTNFDMSRYDVKAILESNTLPIGGGAAKRLKEAQALESSRKREEMIALGSSTFQYGTTSSNSRLHAYPLMQHHHQFEQPQPLLTLQNHDINSHFSHQQDPLHQGYIQTQLQLHQQQSGGSSSYSFQNNNINNAQFYNGYNLQNHPALLQGMINMGSSSSSSVLENNNSNNNNVGGFVGSGFGMASNATSGNTVGTAEELGLVKVDYDMPTGGYGGWSAAAAAESMQTSNSGVFTMWND
>generic|NP:001234960.2
MVVSKCLSLTLHVPTHPSTPFLTPPSKKTPTLSYSSTHFSFQTKLNKAFPTSYNHSLTKHFPMKCSNSSSYTSPPDFELESDDPTLTNEDLKPTTPSQRTFSGFEIASLWVGLVVGVPSYYLAGSLVDLGMAWWQGIATVVAANMILLVPLVLTGHAGTRYGISFPVLVRSSFGINGAHVPTLIRALIGCGWYGIESWIGGEAIFLLLPKAMKEATSLSQSLPWLGTSPLEFACFLVFWVAQLAFVWKGIDGIRKLEKYSAPILVALTSCLLIWSCVKAGGIGHMLSLSSRLSTSEFWSVFFPSLTANISFWATVAINIPDFTRYAKSQKDQVIGQIGLPIFMGAFTFVGLAVTSSTKVIFGQVISDPILLLGQIGGLTTKIVAILGISLAIITTNIAANVVAPANALVNLSPKWFTFRRGALLTALLGIAFQPWRLLKSSESFVYTWLVGYSALMGPIAGIVLADYYIVQKTNLNVSDLYSRSPYGAYRYSRGFNVAAILALVVGVLPVVPGFLQKVGIATSVPNTFVVIYNNAWFVSFFSAGFLYLVLSNLRGKPGNSAARDPLLPTAK
......

there are about 70000 more proteins in this fasta file.
I wish you could tell me how can I change the fasta format

**Comment by kyungsikshi** [comment]
[fail_report.txt](https://github.com/compomics/searchgui/files/9178005/fail_report.txt)

file:///C:/Users/Jeonghoon%20Kim/Desktop/SearchGUI%20Report%202022-07-25%2013.24.17.html

These are the reports. Thank you

**Comment by hbarsnes** [comment]
Can you please also share the PeptideShaker log file? You can find it via the PeptideShaker Welcome Dialog > Settings & Help > Help > Bug Report.

**Comment by kyungsikshi** [comment]
[logdata.txt](https://github.com/compomics/searchgui/files/9180446/logdata.txt)

Here is the log file. Thank you

**Comment by kyungsikshi** [comment]
Mon Jul 25 13:24:09 KST 2022: PeptideShaker version 2.2.9.
Memory given to the Java virtual machine: 274877906944.
Total amount of memory in the Java virtual machine: 134217728.
Free memory: 120172376.
Java version: 15.0.2.
 

I can only see this part when the error happens

**Comment by hbarsnes** [comment]
So what does the actual error look like? Can you share a screenshot?

I don't see anything wrong with your custom FASTA format though. Hence I don't think this is the cause of the issue.

**Comment by kyungsikshi** [comment]
![image](https://user-images.githubusercontent.com/109936994/180766625-e4f5c441-be87-40e7-9cb0-2f51c6bc4823.png)

![image](https://user-images.githubusercontent.com/109936994/180767483-6a283759-301f-4823-8ee4-b02072064a0f.png)


Mon Jul 25 20:23:21 KST 2022        Converting raw files.
Mon Jul 25 20:23:21 KST 2022        4.mzml already exists. Conversion canceled.


Mon Jul 25 20:23:21 KST 2022        Importing spectrum files.
Mon Jul 25 20:23:21 KST 2022        Importing spectrum file 4.mzml
Mon Jul 25 20:23:21 KST 2022        Importing spectrum files completed (61.0 milliseconds).


Mon Jul 25 20:23:21 KST 2022        Processing 4.mzml with MS-GF+.

MS-GF+ Release (v2022.04.18) (18 April 2022)
Java 15.0.2 (Oracle Corporation)
Windows 10 (amd64, version 10.0)
Loading database files...
Warning: Sequence database contains 2100 counts of letter 'X', which does not correspond to an amino acid.
Creating the suffix array indexed file... Size: 71830347
AlphabetSize: 28
Suffix creation: 15.73% complete.
Suffix creation: 34.67% complete.
Suffix creation: 52.21% complete.
Suffix creation: 67.10% complete.
Suffix creation: 85.20% complete.
Sorting suffixes... Size: 17210368
Sorting: 10.46% complete.
Sorting: 21.50% complete.
Sorting: 26.15% complete.
Sorting: 31.38% complete.
Sorting: 38.35% complete.
Sorting: 46.48% complete.
Sorting: 48.81% complete.
Sorting: 55.20% complete.
Sorting: 63.91% complete.
Sorting: 70.31% complete.
Sorting: 73.79% complete.
Sorting: 77.86% complete.
Sorting: 87.16% complete.
Counting number of distinct peptides in aritaunkong_duplicate4_concatenated_target_decoy.csarr using aritaunkong_duplicate4_concatenated_target_decoy.cnlcp
Counting distinct peptides: 19.63% complete.
Counting distinct peptides: 40.65% complete.
Counting distinct peptides: 62.23% complete.
Counting distinct peptides: 83.95% complete.
Loading database finished (elapsed time: 51.69 sec)
Reading spectra...
Opening mzML file 4.mzml
Ignoring 0 profile spectra.
Ignoring 9092 spectra having less than 10 peaks.
Reading spectra finished (elapsed time: 80.82 sec)
Using 12 threads.
Search Parameters:
	PrecursorMassTolerance: 10.0 ppm
	IsotopeError: 0,1
	TargetDecoyAnalysis: false
	FragmentationMethod: HCD
	Instrument: QExactive (Q-Exactive)
	Enzyme: Tryp
	Enzyme file: C:\Users\Jeonghoon Kim\Desktop\SearchGUI-4.1.14-windows\SearchGUI-4.1.14\resources\temp\search_engines\msgf\params\enzymes.txt
	Enzyme info: Added new enzyme Trypsin_(no_P_rule) with target residues RK
	Enzyme info: Added new enzyme CNBr with target residues M
	Enzyme info: Added new enzyme Pepsin_A with target residues LF
	Enzyme info: Added new enzyme Thermolysin with target residues AILMFV
	Enzyme info: Added new enzyme Lys-C_(no_P_rule) with target residues K
	Enzyme info: Added new enzyme Arg-C_(no_P_rule) with target residues R
	Enzyme info: Added new enzyme Chymotrypsin_(no_P_rule) with target residues YLFW
	Enzyme info: Added new enzyme Asp-N_(ambic) with target residues DE
	Enzyme info: Added new enzyme Arg-N with target residues R
	Enzyme info: Added new enzyme LysargiNase with target residues RK
	Protocol: Standard
	NumTolerableTermini: 2
	IgnoreMetCleavage: false
	MinPepLength: 6
	MaxPepLength: 20
	MinCharge: 1
	MaxCharge: 4
	NumMatchesPerSpec: 10
	MaxMissedCleavages: 2
	MaxNumModsPerPeptide: 10
	ChargeCarrierMass: 1.00727649 (proton)
	MinNumPeaksPerSpectrum: 10
	NumIsoforms: 128
Post translational modifications in use:
	Fixed (static):     Carbamidomethyl on C (+57.0215)
	Variable (dynamic): Oxidation on M (+15.9949)

Spectrum 0-12476 (total: 12477)
Splitting work into 36 tasks.
Search progress: 0 / 36 tasks, 0.00%		0.00 seconds elapsed
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Loading built-in param file: HCD_QExactive_Tryp.param
Search progress: 1 / 35 tasks, 30.80%		28.19 seconds elapsed
Search progress: 2 / 36 tasks, 30.66%		28.82 seconds elapsed
Search progress: 3 / 36 tasks, 31.27%		29.34 seconds elapsed
Search progress: 4 / 36 tasks, 31.47%		29.45 seconds elapsed
Search progress: 5 / 36 tasks, 33.04%		31.28 seconds elapsed
Search progress: 6 / 36 tasks, 33.25%		31.36 seconds elapsed
Search progress: 7 / 36 tasks, 33.39%		31.36 seconds elapsed
Search progress: 8 / 36 tasks, 33.60%		31.44 seconds elapsed
Search progress: 9 / 36 tasks, 34.16%		31.86 seconds elapsed
Search progress: 10 / 36 tasks, 34.55%		32.07 seconds elapsed
Search progress: 11 / 36 tasks, 35.18%		32.53 seconds elapsed
Search progress: 12 / 36 tasks, 35.35%		32.56 seconds elapsed
Search progress: 12 / 36 tasks, 61.44%		1.00 minutes elapsed
Search progress: 13 / 36 tasks, 62.12%		1.05 minutes elapsed
Search progress: 14 / 36 tasks, 64.21%		1.16 minutes elapsed
Search progress: 15 / 36 tasks, 64.61%		1.17 minutes elapsed
Search progress: 16 / 36 tasks, 66.62%		1.22 minutes elapsed
Search progress: 17 / 36 tasks, 69.37%		1.29 minutes elapsed
Search progress: 18 / 36 tasks, 71.92%		1.38 minutes elapsed
Search progress: 19 / 36 tasks, 72.08%		1.38 minutes elapsed
Search progress: 20 / 36 tasks, 72.34%		1.38 minutes elapsed
Search progress: 21 / 36 tasks, 72.56%		1.39 minutes elapsed
Search progress: 22 / 36 tasks, 73.25%		1.40 minutes elapsed
Search progress: 23 / 36 tasks, 73.46%		1.40 minutes elapsed
Search progress: 24 / 36 tasks, 73.63%		1.40 minutes elapsed
Search progress: 25 / 36 tasks, 87.17%		1.60 minutes elapsed
Search progress: 26 / 36 tasks, 92.92%		1.71 minutes elapsed
Search progress: 27 / 36 tasks, 96.19%		1.80 minutes elapsed
Search progress: 28 / 36 tasks, 97.21%		1.89 minutes elapsed
Search progress: 29 / 36 tasks, 97.62%		1.91 minutes elapsed
Search progress: 30 / 36 tasks, 98.34%		1.98 minutes elapsed
Search progress: 31 / 36 tasks, 98.58%		1.99 minutes elapsed
Search progress: 32 / 36 tasks, 98.79%		2.00 minutes elapsed
Search progress: 32 / 36 tasks, 98.84%		2.00 minutes elapsed
Search progress: 33 / 36 tasks, 99.36%		2.04 minutes elapsed
Search progress: 34 / 36 tasks, 99.63%		2.05 minutes elapsed
Search progress: 35 / 36 tasks, 99.78%		2.05 minutes elapsed
Search progress: 36 / 36 tasks, 100.00%		2.06 minutes elapsed
Search progress: 36 / 36 tasks, 100.00%		2.06 minutes elapsed
Writing results...
Writing results finished (elapsed time: 15.15 sec)
File: C:\Users\Jeonghoon Kim\Desktop\.SearchGUI_temp\4.msgf.mzid
MS-GF+ complete (total elapsed time: 219.74 sec)


Mon Jul 25 20:27:01 KST 2022        MS-GF+ finished for 4.mzml (3 minutes 40.0 seconds).

Mon Jul 25 20:27:02 KST 2022        Zipping output files.

Mon Jul 25 20:27:05 KST 2022        Processing identification files with PeptideShaker.

Mon Jul 25 20:27:09 KST 2022        PeptideShaker processing failed. See the PeptideShaker log for details.

Mon Jul 25 20:27:09 KST 2022        Searching Canceled!
Mon Jul 25 20:27:44 KST 2022        The search or processing did not finish properly!


Thank you!

**Comment by hbarsnes** [comment]
Can you try processing the output from SearchGUI separately in PeptideShaker? That should give you a bit more information about what is happening.

**Comment by kyungsikshi** [comment]
![image](https://user-images.githubusercontent.com/109936994/180772536-e106fe53-9dd3-4d27-aa5b-776539c84ed0.png)
![image](https://user-images.githubusercontent.com/109936994/180772639-3fa15bd7-2c7b-44ff-96cf-53d04224daa5.png)
![image](https://user-images.githubusercontent.com/109936994/180772677-73ba1c4c-e337-45dc-b07f-fae569db928d.png)


Here you are!

**Comment by kyungsikshi** [comment]
I think searchingGui is done but the result are not shown in file that can be opened by peptideshaker

**Comment by hbarsnes** [comment]
You have to use the New Project option and not the Open Project option when processing the SearchGUI output in PeptideShaker. The Open Project option is for opening existing PeptideShaker projects.

**Comment by kyungsikshi** [comment]
As you said processing the output separately in the peptide shaker showed the problem I had.
There was invalid character like "-" or "*" in my amino acid sequence. Thank you for solving my problem.
Have a nice day!
