### ISSUE TITLE
ERRor!!!

### ISSUE THREAD

**Issue by pelintnp** [compomics/searchgui#326]
hello, I've been getting such an error since yesterday evening, why?
![searchgui error](https://user-images.githubusercontent.com/110257603/181826332-936bff9b-6a5d-41d9-af63-88f99f0da54a.jpg)

**Comment by hbarsnes** [comment]
Have you checked the content of the PeptideShaker log file? Any hints there?

It may also help to open the results from SearchGUI separately in PeptideShaker via the New Project option in PeptideShaker. This usually provides more information about the source of the problem.

**Comment by pelintnp** [comment]
Unfortunately I can't open them in peptide shaker because the search gui doesn't save the files properly.

**Comment by hbarsnes** [comment]
Are you sure that you do not have a file called searchgui_out.zip in the selected output folder for SearchGUI? It should contain the results from the individual search engines. If not, you can always disable the PeptideShaker post processing option and rerun the search, and then load the results in PeptideShaker separately.

> Have you checked the content of the PeptideShaker log file? Any hints there?

Did you have a look at log file indicated in your screenshot?

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
