### ISSUE TITLE
Stuck on "Importing spectrum file"

### ISSUE THREAD

**Issue by iquasere** [compomics/searchgui#328]
Running SearchCLI 4.0.33 in a Ubuntu container, with the command
```searchgui eu.isas.searchgui.cmd.SearchCLI -Xmx51200M -spectrum_files /path/to/spectra -output_folder output_folder -id_params params.par -threads 15 -fasta_file /path/to/decoy_database.fasta -xtandem 1 -myrimatch 1 -msgf 1```

SearchCLI gets stuck on 
```
Wed Aug 17 16:36:15 UTC 2022 Importing spectrum files.
Wed Aug 17 16:36:15 UTC 2022 Importing spectrum file input.mgf
```
Never goes further than this step. This never happened to me, it was working fine a few days ago, same version, same environment. Is there any place I can get more info on what is getting it stuck, consulting the log at ```/opt/conda/share/searchgui-4.0.33-0/resources/SearchGUI.log``` gives me no info:
```
Wed Aug 17 16:27:07 UTC 2022: SearchGUI version 4.0.33.
Memory given to the Java virtual machine: 53687091200.
Total amount of memory in the Java virtual machine: 2113929216.
Free memory: 2099833720.
Java version: 17.0.3-internal.
```

**Comment by iquasere** [comment]
Downgrading to 4.0.25 seems to have done the trick! Thank you again for these tools, they're amazing!

**Comment by hbarsnes** [comment]
Great that you were able to sort out the problem on your own! If possible, I would however recommend updating to the latest version (v4.1.16) instead of downgrading.

**Comment by iquasere** [comment]
That version is not available through Bioconda... though I would love it if it fixed the annoying problem with MS-GF+ and the databases (https://github.com/MSGFPlus/msgfplus/issues/43), I'm finding it now

**Comment by iquasere** [comment]
Actually, could you tell me how could I go around that problem, by splitting the database? I've already tested, and splitting it into two allows MS-GF+ to run to the end. However, how would I join the two outputs of the two runs into a single SearchGUI result? Do note that I am running SearchCLI

**Comment by hbarsnes** [comment]
> That version is not available through Bioconda

We will look into updating the version on Bioconda. No guarantees though, as the developer taking care of this part is sadly no longer part of our team. Any chance you can simply download and use the latest SearchGUI zip file instead?

>Actually, could you tell me how could I go around that problem, by splitting the database?

Well, you can always join the input later in PeptideShaker? The results will not be identical (compared to one larger search), but should be pretty close.
