### ISSUE TITLE
Installation issue of searchGui with Java

### ISSUE THREAD

**Issue by EmilieCarneiro** [compomics/searchgui#329]
Hello, 
I am trying to install searchGui and peptide shaker on my computer (windows 11 home). However, after unzipping both folders, when I click the .jar files I get an error message saying "Java is not installed. Do you want to download the latest version of java?"
If I click yes I am redirected to download 64-bit Java for Windows Version 8 Update 341. I installed it but the error message remains. I also installed Java JDK 19 and still the error message. Any idea how I can solve this problem? Thank you for your help.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/107934660/192107475-bb26c27a-8a10-4bf1-8336-72970041884a.png">

**Comment by hbarsnes** [comment]
Can you try right-clicking the jar file instead and choose "Open with..."?  and then see if you can choose Java JDK 19 there?

You can also try to override the default Java option by setting your own Java Home. This is done by creating a file called JavaHome.txt in the resources\conf folder of SearchGUI/PeptideShaker, with the path to the bin folder of the Java version to use, e.g., C:\Program Files\Java\jdk-14.0.2\bin\. If the folder does not exist (or it does not contain the required files), the default Java version will be used.

**Comment by hbarsnes** [comment]
Issue assumed resolved. It this is not the case, please let us know and we'll reopen the issue.
