### ISSUE TITLE
SearchCLI: MS-GF+ options

### ISSUE THREAD

**Issue by tivdnbos** [compomics/searchgui#332]
Hi,

I was wondering how I could define the following options in the SearchCLI search with MS-GF+:
- I would like to turn the MSGF+ addFeatures option to 1 (default 0); in SearchGUI this can be found under MS-GF+ Advanced Settings > additional output
- I have a target/decoy generic database with "decoy_" prefix as decoy-tag. How can I specify this in the SearchCLI? In SearchGUI, this can be defined in the "Edit fasta parsing" options.

Best,
Tim

**Comment by tivdnbos** [comment]
Thanks Harald!

**Comment by tivdnbos** [comment]
Hi Harald, 

Sorry to re-open this again.
Currently, the analysis works correctly, but the name of my output files isn't. I iterate over different fasta files to search one mgf file with the different databases, and use as -output_default_name the name of the fasta file (minus the .fasta extension). 
When I echo this command in bash, it looks correct; however msgf+ uses the name of the mgf. When I remove the -output_default_name option, I would expect searchgui_out, but it stays the mgf file name. 

Might this be a bug?

Best,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

The -output_default_name option only controls the name of the zipped (combined) export from SearchGUI and not the names of the individual search results files from the different search engines. For MS-GF+ the search results file will always be named "spectrum file name without extension" + ".msgf.mzid".

Best regards,
Harald

**Comment by tivdnbos** [comment]
Oooh, okay, I'll work around that then :) 

Thanks Harald!
