### ISSUE TITLE
Multiple enzyme digestion

### ISSUE THREAD

**Issue by carolinelennartsson** [compomics/searchgui#333]
Hi, 

I have an experiment in which the samples (for specific reasons) have been digested using a combination of enzymes, LysC, Asp-N and Glu-N with 8 missed cleavages. Is there a possibility of enabling multi enzyme digestion to searchGUI?  

Thank you for your help :)

**Comment by hbarsnes** [comment]
You can set up your own enzymes via the Edit > Enzymes menu option in the main SearchGUI window. The created enzyme will then afterwards be available in the drop-down menu in the search settings.

I'm not sure how easy it is to combine c-terminal and n-terminal enzymes though and if any of the search engines are able to support this. But just give it a go and see what happens.

**Comment by carolinelennartsson** [comment]
Thank you, I found it. :) I'll try it out!

**Comment by carolinelennartsson** [comment]
It can't handle digestion from both N- and C- term, unfortunately. All amino acids gets defined as "cleaved after".

**Comment by hbarsnes** [comment]
I've quickly looked at the support for combining multiple enzymes for each of the search engines, in particular combinations of n- and c-terminal enzymes, and it may seem like X! Tandem (and maybe Andromeda) is the only one with explicit support for this. See the details for X! Tandem here: https://www.thegpm.org/TANDEM/api/pcs.html.

However, you would then have to define the enzymes individually and be able to select more than one in the search settings in SearchGUI, and this is not something we support in SearchGUI (nor in the downstream analysis in PeptideShaker) at the moment.

Supporting multiple enzymes is on our todo list, but I'm not sure when we will get the time to implement it.

**Comment by hbarsnes** [comment]
Hi again. Seems like adding support for multiple enzyme selection in SearchGUI was easier than I thought! I think I now have a version working with X! Tandem. Needs a bit more testing before I'm confident to release a new version though, but I'll keep you posted.

**Comment by carolinelennartsson** [comment]
Thank you for looking into it! I know andromeda allows this already but I'm not sure of how the other softwares handles it. I'm looking forward to the update then. :)

**Comment by carolinelennartsson** [comment]
No problem, there seem to be some issues regarding the comet and X! Tandem searches. 

There seem to be an loading issue with Comet.

<img width="856" alt="Screenshot 2022-10-26 at 17 07 37" src="https://user-images.githubusercontent.com/70753896/198064287-a3e3cff0-661f-4d39-acdf-c89aac0ce3d2.png">  

And there also seem to be an issue with the target decoy concatenation of the database, when loading in peptideshaker. 

<img width="823" alt="Screenshot 2022-10-26 at 17 15 06" src="https://user-images.githubusercontent.com/70753896/198065968-54d77817-bfd5-4ede-8d50-18c35ced4cb0.png">

**Comment by hbarsnes** [comment]
> There seem to be an loading issue with Comet.

But weren't you using a combination of three enzymes? Comet only supports up to two.

> And there also seem to be an issue with the target decoy concatenation of the database, when loading in peptideshaker.

Seems like perhaps you have added some custom protein sequences to your database? Or rather non-standard headers? I'd recommend having a look at our Database help pages. In particular the section on non-standard headers: https://github.com/compomics/searchgui/wiki/DatabaseHelp#non-standard-fasta.

**Comment by carolinelennartsson** [comment]
Alright, that would fix the problem. Thank you!

**Comment by carolinelennartsson** [comment]
Yes, the issue is resolved. Thank you.
