### ISSUE TITLE
Question about FDR

### ISSUE THREAD

**Issue by KKKKK-tech** [compomics/searchgui#335]
I‘ve  set  the peptideFDR=0.02 in Search Setting, but when I got the result, there were still some data with an FDR>0.02. Does this mean that quality control with peptideshaker is also required?

**Comment by mvaudel** [comment]
Hi,
By default the tool will display all results and indicate whether a match passes the FDR threshold in the `Validation` column.
Hope it helps,
Marc

**Comment by KKKKK-tech** [comment]
Thank you for your quick reply. In fact, I want to export FDR, E-value and protein for each peptide as .txt file with PeptideShaker, but I don't know how to export FDR (instead of figure) . It seems that PS filters out data that smaller than FDR but does not show FDR for each peptide.

**Comment by hbarsnes** [comment]
Have you had a look at the reports available via the Export > Identification Features menu option in PeptideShaker? Here you can either use the standard reports or make your own custom reports. Hopefully this will allow you to export the information you are interested in?

**Comment by KKKKK-tech** [comment]
Yes, I have looked at that menu and tried all of the options, but still couldn't find FDR.
I wonder if the result of SearchGUI has taken control of the FDR after processing by PS and I just need to export files and process them, if so, I'll use other indicators to explain, like confidence or FDR plot.

**Comment by mvaudel** [comment]
You are correct that the FDR is not available as a column in the PSM/peptide/protein exports. The "Validation" column tells you whether a given match passes the threshold that you have set in the list of all matches ranked by score. When one says that a peptide passes a given FDR threshold, it is only relative to a set of other peptides. The FDR is thus a property of a set of matches but not an individual property of a peptide - a peptide does not have an FDR. 
If you are interested in a metric giving you the confidence in a given match, you can use the confidence column, which is 1-PEP. 
If you have a set of peptides and want to estimate the FDR in this set, you can export the decoys and count them to have an estimate of the number of false positives. Alternatively, summing the PEP, should give you a similar result.
Hope it is clearer, if you give us more information on what you are trying to achieve we might be able to help more :-)

**Comment by KKKKK-tech** [comment]
Thank you for the explanation. It seems that I didn't understand the meaning of FDR correctly. 
BTW, I found following issue in github and I knew that PEP was exactly what I needed!
[https://github.com/compomics/peptide-shaker/issues/213](url)
Thanks again for your kind assistance!
