### ISSUE TITLE
Myrimatch was unable to complete the search

### ISSUE THREAD

**Issue by KKKKK-tech** [compomics/searchgui#336]
Why does this happen?
![image](https://user-images.githubusercontent.com/74421386/202219444-af07b188-5386-4a62-9f6d-2fe85f00a83c.png)

BTW, here is an error occurred in the previous search, and all the files worked fine except for this one, is it a bug?
_Sat Nov 12 20:45:38 CST 2022        Could not find MyriMatch result file for 01CPTAC_LUAD_P_BI_20180419_BD_f01.mgf._

**Comment by hbarsnes** [comment]
I'm afraid that given that this behavior is inside MyriMatch there is not much we can do on our end, as all we do is to run the command lines of the individual search engines. You could try contact the developers of MyriMatch, although I'm not sure if it's being actively maintained anymore. I think that your best shot may be trying to go via the ProteoWizard/Bumbershoot developers (https://proteowizard.sourceforge.io/projects.html).

However, unless there is a specific reason why you need to run MyriMatch specifically, you can always replace MyriMatch by one of the other search engines included in SearchGUI?

**Comment by KKKKK-tech** [comment]
Thanks for your kind reply! I'll try to connect the proteowizard developers
