### ISSUE TITLE
Fasta Input With Wildcards Peptide Shaker

### ISSUE THREAD

**Issue by kostrouc** [compomics/searchgui#337]
Hi,

I am trying to search a fasta file in Peptide Shaker that contains wildcard characters in the sequence. Is there a recommended format that these gaps in sequences should be changed into? Attached is the format of the fasta file I am trying to search in Peptide Shaker and the error I recieve.

<img width="370" alt="fastaexample" src="https://user-images.githubusercontent.com/69212968/203087176-454d16a4-4138-45ee-a6d1-545f97f7cfc1.PNG">
<img width="758" alt="ps_error" src="https://user-images.githubusercontent.com/69212968/203088147-9849673c-abf2-408c-83aa-dace044eeeac.PNG">

**Comment by hbarsnes** [comment]
If all of the wildcard characters are at the end of your protein sequences, you can probably simply remove them? As they would have no impact on the list of possible peptide sequences anyway?

If they however are inside your protein sequences (don't see any examples of this above though?), you could either remove them there as well (although this would change the interpretation of the wildcards), or you will have to modify and split up the protein sequences before giving the FASTA file to SearchGUI/PeptideShaker.

**Comment by kostrouc** [comment]
Thank you!

**Comment by mvaudel** [comment]
Hi,
Wildcards should be denoted with an 'X'. Stars in sequences are often used to represent stop codons between exons. Can this be the case here?
Hope it helps,
Marc
