### ISSUE TITLE
Download site down, add mirror

### ISSUE THREAD

**Issue by JohnsonDylan** [compomics/searchgui#338]
I'm interested in using SearchGUI but the link to download is leading to a dead webpage: https://genesis.ugent.be/maven2/eu/isas/searchgui/SearchGUI/4.1.24/SearchGUI-4.1.24-windows.zip

I'm not sure how long this has been down but I wanted to bring it to attention. This applies to peptideshaker as well and presumably any other downloads through genesis.

A backup mirror for download would be nice

**Comment by hbarsnes** [comment]
Thanks for letting us know! Seems like the server where the downloads are located is indeed down at the moment. It will hopefully be back online soon. But I will check with the people responsible and keep you posted.

**Comment by hbarsnes** [comment]
The server is now back online and the downloads are available again. Thanks again for making us aware of the issue.
