### ISSUE TITLE
SearchGUI java error at start

### ISSUE THREAD

**Issue by LaszloGyoery** [compomics/searchgui#340]
When I try to start searchgui by clicking the .jar-file or by clicking "Start Search" in PeptideShaker I run into the following error message:
```
<ERROR>

java.lang.NullPointerException: Cannot invoke "com.compomics.util.parameters.UtilitiesUserParameters.getMemoryParameter()" because "this.userParameters" is null
	at com.compomics.software.CompomicsWrapper.launchTool(CompomicsWrapper.java:163)
	at eu.isas.searchgui.SearchGUIWrapper.<init>(SearchGUIWrapper.java:63)
	at eu.isas.searchgui.SearchGUIZipFileChecker.<init>(SearchGUIZipFileChecker.java:58)
	at eu.isas.searchgui.SearchGUIZipFileChecker.main(SearchGUIZipFileChecker.java:71)

The command line executed:
java -jar "C:\Users\steve\Downloads\SearchGUI-4.1.24\SearchGUI-4.1.24.jar" 

</ERROR>
```

What I tried:

- Java Versions 17, 18, 19
- giving PeptideShaker 2gb and 16gb of ram

Log from PeptideShaker:
```
Wed Nov 30 13:38:56 CET 2022: PeptideShaker version 2.2.17.
Memory given to the Java virtual machine: 8388608000.
Total amount of memory in the Java virtual machine: 134217728.
Free memory: 77619864.
Java version: 19.0.1.
1714 script command tokens
(C) 2009 Jmol Development
Jmol Version: 12.0.43  2011-05-03 14:21
java.vendor: Oracle Corporation
java.version: 19.0.1
os.name: Windows 11
memory: 54.1/134.2
processors available: 12
useCommandThread: false
```

I couldn't find any similar errors online. Does someone have an idea what this could be?

**Comment by hbarsnes** [comment]
The code above tries to access or create the following file and folder in your user home folder: /.compomics/userparameters.cup. Could you check that you have write access to the folder called C:\Users\steve\.compomics?

You can also change the default folder via the PeptideShaker Welcome dialog > Settings & Help > Settings > Resource Settings.

**Comment by LaszloGyoery** [comment]
Thanks for the quick answer!
I have the file userparameters.cup but it only contains the text "null". I have write access in the .compomics folder and it is not read-only. Also steve is an admin account on my machine. 
The Resource Settings also show a green checkmark for every directory.

**Comment by hbarsnes** [comment]
Aha! Can you try deleting the userparameters.cup file and then try starting SearchGUI by double clicking the jar file?

**Comment by LaszloGyoery** [comment]
That worked!
Thank you very much!
