### ISSUE TITLE
Hello, I am graduate student using peptide shaker.

### ISSUE THREAD

**Issue by kyungsikshi** [compomics/searchgui#347]
Is there any method or modification setting that I can detect disulfide bond?

Thanks a lot!

**Comment by hbarsnes** [comment]
The challenge with detecting disulfide bonds is that we tend to break them up as part of the sample preparation. It is also common to modify all of the cysteins with carbamidomethylation such that the disulfide bonds do not reform. Hence, in a standard proteomics experiment I do not think that there is a way in which you can later detect where the disulfide bonds were originally located. At least none that I can think of right now.

You could potentially skip the sample preparation step where the disulfide bonds are broken and treat the disulfide bonds as a special type of cross-linking. But I do not have any experience with this, and in any case you would need custom cross-linking software to analyze the resulting spectra as they would contain a combination of two peptides linked by a disulfide bond.
