### ISSUE TITLE
An issue using MSAmanda2.0 within the SearchGUI. Help wanted.

### ISSUE THREAD

**Issue by JuneCoco** [compomics/searchgui#348]
I encountered an issue while using MSAmanda2.0 within the newest version of SearchGUI on Linux. Running MSAmanda2.0 in SearchGUI, I did not receive any output even after several days. The log file only contained information about importing spectrum files and converting them to peak lists, without any errors. On the other hand, when I used the standalone version of MSAmanda2.0, it worked perfectly. Can you suggest a solution to this problem? Thanks!

Mon Mar 27 18:05:46 CST 2023 Importing spectrum files.
Mon Mar 27 18:05:46 CST 2023 Importing spectrum file samples_file_1.mzML
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Mar 27 18:06:23 CST 2023 Importing spectrum file samples_file_2.mzML
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Mon Mar 27 18:07:02 CST 2023 Importing spectrum files completed (1 minute 17.0 seconds).
Processing: file samples_file_1.mzML (1/2)
Mon Mar 27 18:07:02 CST 2023 Converting spectrum file samples_file_1.mzML to peak list.

**Comment by hbarsnes** [comment]
I'm pretty sure that this is not an issue with MS Amanda, but rather related to your Java version needing to be updated. Please download and install the latest Java version from https://adoptium.net/temurin/releases and then try again.

After installing the more recent Java version you may have to tell SearchGUI (and PeptideShaker) to use it as well. This can be done via the Edit > Java Settings menu option in SearchGUI. Simply change the Java path at the top to the path to the new Java installation.

**Comment by JuneCoco** [comment]
> I'm pretty sure that this is not an issue with MS Amanda, but rather related to your Java version needing to be updated. Please download and install the latest Java version from https://adoptium.net/temurin/releases and then try again.
> 
> After installing the more recent Java version you may have to tell SearchGUI (and PeptideShaker) to use it as well. This can be done via the Edit > Java Settings menu option in SearchGUI. Simply change the Java path at the top to the path to the new Java installation.

Thank you for your prompt response. Updating the Java JDK has successfully resolved the issue. Your assistance is greatly appreciated.
