### ISSUE TITLE
MSGFPlus.jar is zero length in SearchGUI-4.2.16-mac_and_linux.tar.gz

### ISSUE THREAD

**Issue by photocyte** [compomics/searchgui#354]
Hi there,

When I unpackage SearchGUI-4.2.16 (the most recent release, `SearchGUI-4.2.16-mac_and_linux.tar.gz` downloaded from http://compomics.github.io/projects/searchgui) on macOS (using the OS default `Archive Utility.app` `Version 10.15 (149.3.3)`), the `MSGFPlus.jar` file at path `SearchGUI-4.2.16/resources/MS-GF+/MSGFPlus.jar` is a 0-byte / empty file. Is there a problem with this archive, or perhaps the issue is on my end?

All the best,
-Tim

edit: to be clear, this is the `.tar.gz` file mentioned:
https://genesis.ugent.be/maven2/eu/isas/searchgui/SearchGUI/4.2.16/SearchGUI-4.2.16-mac_and_linux.tar.gz

**Comment by hbarsnes** [comment]
Hi Tim,

Thanks for letting us know! Seems like something went wrong in a recent merge. We'll look into it and release a new version as soon as possible.

In the meantime you can always download the latest version of MS-GF+ manually and replace the empty jar file. You can find the latest MS-GF+ release here: https://github.com/MSGFPlus/msgfplus/releases/tag/v2023.01.12

Best regards,
Harald

**Comment by photocyte** [comment]
Thank you! Looks like some other files might have been victim to it as well:
```
find  /Applications/SearchGUI-4.2.16 -size 0
/Applications/SearchGUI-4.2.16/resources/Comet/linux/comet.exe
/Applications/SearchGUI-4.2.16/resources/conf/firstRun
/Applications/SearchGUI-4.2.16/resources/MetaMorpheus/CMD.dll
```

**Comment by hbarsnes** [comment]
> Looks like some other files might have been victim to it as well

Yup, the first and last file on your list has already been re-added. (The second one should actually be empty. It's just a temp file that is deleted the first time you run the SearchGUI to check if we should ask for whether to add a desktop shortcut etc. (only on Windows though.))

I will release a new version later today, just thought I'd update to the latest Sage version first while I'm at it.

**Comment by hbarsnes** [comment]
SearchGUI v4.2.17 has just been released to fix the issue of the missing/empty files. Thanks again for telling us about this!
