### ISSUE TITLE
Failed to start getMemoryParameter()

### ISSUE THREAD

**Issue by JesusCastano01** [compomics/searchgui#355]
Hi,
I've been using SearchGUI for the past week, and today, suddenly, it stopped working for no reason. I'm a little bit confuse. Every time I tried to open it, an error message pops up, saying "Cannot invoke "com.compomics.util.parameters.UtilitiesUserParameters.getMemoryParameter()" because "this.userParameters" is null.

Any advice on how to fix this? As I said it suddenly stopped working, so I'm very confused about what could have happened.
Thanks,

![image](https://github.com/compomics/searchgui/assets/139022774/40ea4ef8-b994-42a0-b41d-bbc3075129bf)

@JesusCastano01

**Comment by hbarsnes** [comment]
It seems like your user parameters file may have gotten corrupted. Can you try going to the "user home folder"\.compomics and delete the file userparameters.cup? It will be recreated the next time you start either SearchGUI or PeptideShaker.

**Comment by JesusCastano01** [comment]
This worked! Thank you so much. I don't know how this happened, though. If you have any advice about how to prevent this from happening ever again, please let me know.

**Comment by hbarsnes** [comment]
Great! Not sure of there is much you can do to guarantee that it does not happen again besides making sure to allow the tools to close properly. I've only heard of this happening a couple of times before though, so it should not occur very often. At least you now know how to fix it. But if it starts happening often, please open a new issue and then we can have a closer look.
