### ISSUE TITLE
SearchGUI does not download

### ISSUE THREAD

**Issue by mi3-14** [compomics/searchgui#358]
Hi 

I am trying to download SearchGUI but I get the following error: 

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.57 (Debian) Server at genesis.ugent.be Port 443

Wondering what the issue is here and how to get around it?

Thanks

**Comment by hbarsnes** [comment]
Thanks for letting us know! It indeed seems like the server is down. I will look into it and get back to you.

**Comment by hbarsnes** [comment]
Should be back online now. Let me know if you still experience problems and I'll reopen the issue.
