### ISSUE TITLE
SearchGUI + X!Tandem results in some peptides not ending in K or R

### ISSUE THREAD

**Issue by prao123** [compomics/searchgui#367]
Hello!
I am using X!Tandem on SearchGUI (the latest version). The results output peptides which do not end in K or R and sometimes goes past K for a couple of amino acids more for e.g. GMGRWDPKNPN.
A previous post had mentioned this and the post mentions that the "second pass" feature of X! Tandem is to be blamed:
https://github.com/compomics/searchgui/issues/365

I cannot find an option to turn off this feature in SerarchGUI or X!Tandem options. How to deal with these peptides? 

Thank you.

**Comment by hbarsnes** [comment]
You can turn off the second pass search for X! Tandem by clicking the cogwheel to the right of where you select X! Tandem in the main SearchGUI dialog. See the Refinement options here:

![image](https://github.com/compomics/searchgui/assets/13151214/9dadd55f-bb18-4f4d-99ef-276febf35475)

It may however be better to finetune the more specific refinement parameters such as unanticipated cleavage. Click the question marks for more details for the individual parameters.

Finally, if you want only tryptic peptides, makes sure that you have selected the wanted enzyme specificity in the more general spectrum matching parameters:

![image](https://github.com/compomics/searchgui/assets/13151214/a1da82b2-8e13-47e5-8b7d-d7c8b1b607b8)

**Comment by prao123** [comment]
That "unanticipated cleavage" parameter makes sense. Will read a bit more about it before playing with it. Thank you.

**Comment by hbarsnes** [comment]
Ok, I will then close this issue, but do not hesitate to open a new one if you come up with more questions later.
