### ISSUE TITLE
Adding spectrum file(s) does not recognize .d as valid

### ISSUE THREAD

**Issue by tomthun** [compomics/searchgui#370]
When I select a .d - folder under spectrum file(s) this message pops up. 

![image](https://github.com/compomics/searchgui/assets/35220235/bf7a944b-dc9e-4a52-b287-6807738213f8)

How do i read in .d timstof raw files?

**Comment by hbarsnes** [comment]
We do not have much experience with timstof data ourselves but if the files can be converted with ProteoWizard (https://proteowizard.sourceforge.io) we should be able to convert them in SearchGUI too (as we are simply using msconvert from ProteoWizard for the conversion). Have you tried converting the files directly in ProteoWizard? Does that work?

Can you also confirm that the given folder actually contains one or more spectrum files? And if so, what is the file format of these files?

**Comment by tomthun** [comment]
The structure looks like this: 
![image](https://github.com/compomics/searchgui/assets/35220235/9a2c236a-0af6-4758-bb53-3bad901f3e0b)
You can also find the data here: [data](https://drive.google.com/file/d/1Jj8HG1x75Gug2nEQVZ2QsYxdVAvMEu2a/view)

I've also read that by referencing the location of your [ProteoWizard](http://proteowizard.sourceforge.net/) installation I may also provide additional raw file types as input, however even after installing proteoscape msconvert is grayed out and I cannot add the installation path.

**Comment by hbarsnes** [comment]
The msconvert settings will only be enabled if we detect a supported non-Thermo raw file in the provided spectrum files or folder. (For Thermo raw file we use ThermoRawFileParser instead.)

There were however a couple of raw file formats supported by msconvert that we had not added to our internal list of supported raw file extensions, including Bruker .tdf files, which seems to be the format of your raw data. This has now been corrected. (Note that there is also a .d file in your .d folder but it is empty.)

Furthermore, it seems like msconvert requires the .d folder as input and not the .tdf file directly. Support for this has now also been implemented.

After these changes the conversion from a .d folder to an mzML file seems to be working. It is however extremely slow and I have not yet had the patience to let the conversion complete. This is also the case when using msconvert directly though, hence I do not think there is much we can do with this on our end. Maybe there is something you can do with the msconvert filters to speed it up?

I will do some more testing and release a new version of SearchGUI (hopefully) later today after making sure that the resulting mzML file can actually be used by the search engines. In the meantime you can perhaps do some tests of converting your files directly in msconvert and see if you are able to increase the conversion speed somehow?

**Comment by hbarsnes** [comment]
SearchGUI v4.3.7 has now been deployed supporting the conversion of .d folders from Bruker instruments. Note that the conversion is still very slow though...

I will close the issue (given that the initial problem has been solved), but do feel free to add more comments, or open a new issue, if you find any solutions to the speed problem.

**Comment by tomthun** [comment]
Just one more question: Sage now natively works for timsDDA (but not timsDIA yet). Will the .d be conversed per default or only if i select the option for conversion?

**Comment by hbarsnes** [comment]
In SearchGUI we only support mgf and mzML (did not know that Sage supported timsDDA directly), hence the spectrum files will always be converted if not in either of these two formats. And not all search engines support both formats either. So sometimes we have to convert even if mzML is provided.
