### ISSUE TITLE
issue running Sage with multiplexed files

### ISSUE THREAD

**Issue by jcanderan** [compomics/searchgui#372]
Hello,

I receive the following error when trying to use Sage (through SearchGUI) with multiplexed (TMT-10) files:

```
Fri Jul 12 20:55:05 UTC 2024 Importing spectrum files.

Fri Jul 12 20:55:05 UTC 2024 Importing spectrum file 20170123.mzML

10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Fri Jul 12 20:55:20 UTC 2024 Importing spectrum files completed (14.7 seconds).

Processing: 17CPTAC_COprospective_W_PNNL_20170123_B5S1_f01.mzML (1/1)

Fri Jul 12 20:55:20 UTC 2024 Error: Cannot invoke "java.util.ArrayList.add(Object)" because the return value of "java.util.HashMap.get(Object)" is null
```

I've received the same error on two different systems (one Java 17, one 19). 

I can run Sage with label-free and Comet (etc) on multiplexed/labeled, so it seems to specifically be an issue with Sage multiplexed.

Edit: I looked into it more. It's not necessarily the file itself, but when you have the fixed mod when using Sage: "TMT 10-plex of peptide N-term" (TMT 10-plex of K" works fine).

Thanks!

**Comment by hbarsnes** [comment]
Thanks for lettings us know! It was just a silly copy-paste error that has now been fixed.

A beta version is available for testing: 
https://genesis.ugent.be/maven2/eu/isas/searchgui/SearchGUI/4.3.10-beta/SearchGUI-4.3.10-beta-windows.zip and https://genesis.ugent.be/maven2/eu/isas/searchgui/SearchGUI/4.3.10-beta/SearchGUI-4.3.10-beta-mac_and_linux.tar.gz

**Comment by hbarsnes** [comment]
A proper SearchGUI release is now available that includes the above fix for this bug. I will therefore close the issue.
