### ISSUE TITLE
Is MS Amanda 3.0 coming to SearchGUI? 

### ISSUE THREAD

**Issue by ec-ho-ra-mos** [compomics/searchgui#374]
After reading the MS2 Rescore paper, I attempted to use MS Amanda through SearchGUI. However, it appears that the version of MS Amanda in SearchGUI is still the previous one and not the updated v3.0, which includes the eight new output columns for rescoring.

**Comment by hbarsnes** [comment]
We are, together with the MS Amanda developers, currently working on updating the MS Amanda version in SearchGUI. A new SearchGUI release should be ready soon.

**Comment by hbarsnes** [comment]
SearchGUI v4.3.10 has just been released which includes MS Amanda v3.0.22.071. Hopefully you should then have the wanted columns in the MS Amanda output file.
