### ISSUE TITLE
Failure of "converting spectrum file ... to peak list"

### ISSUE THREAD

**Issue by LNVJN** [compomics/searchgui#376]
Hi,

During my attempt for peptide-to-spectrum matching by using SearchGui, the software do not progress over 50% ("converting spectrum file ... .mgf to peak list").

However, I do use the latest SearchGUI version (4.3.11), Java version 8 update 421 (64 Bit) with 15.6 GB memory. 

I tried my own mgf file, next to the "qExactive01819.mgf" file, but both attempts failed.

Any other solutions I can try?

![Schermafbeelding 2024-09-25 164840](https://github.com/user-attachments/assets/defa5b64-9692-456e-8057-73b14e69bfe7)

Thanks a lot!

**Comment by hbarsnes** [comment]
Hi! If you update to a more recent Java version this problem will most likely be resolved. You can download the latest Java releases here: https://adoptium.net/temurin/releases.

**Comment by LNVJN** [comment]
Hi,
Great, yes indeed, it worked when installing JDK23 instead of Java version 8.
Thanks a lot!
