### ISSUE TITLE
SearchCLI - version 2.0.3 still deleting output folder

### ISSUE THREAD

**Issue by cdlawless** [compomics/searchgui#55]
Hi Harald/Marc

The output folder is still being deleted when using searchCLI on linux.

Kind Regards

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

Please try the new v2.0.4 and see if that helps. If not, please send us your SearchCLI command line and we'll see if we can spot any problems.

Best regards,
Harald

**Comment by cdlawless** [comment]
Thanks Harald, v2.0.4 all worked fine.
