### ISSUE TITLE
comet generated command problem

### ISSUE THREAD

**Issue by jflucier** [compomics/searchgui#56]
Hello,

when I execute searchgui under centos6, Comet fails with this error message:

comet command: 
/home/jflucier/apps/compomics/SearchGUI-2.0.4/resources/Comet/linux/comet.exe \
-P /home/jflucier/apps/tutorial/searchgui/temp/comet.params \ /home/jflucier/apps/tutorial/searchgui/temp/peak_lists/test.ms2 

Thu Sep 17 14:08:28 EDT 2015 Processing test.mgf with Comet.

 Comet version 2015.02 rev. 0 
 Error - cannot open parameter file "". 

When you check the command generated by searchgui, there is a space between -P option and parameter. This is what generates the error. If you run the same command but written this way, it works:
/home/jflucier/apps/compomics/SearchGUI-2.0.4/resources/Comet/linux/comet.exe \
-P/home/jflucier/apps/tutorial/searchgui/temp/comet.params /home/jflucier/apps/tutorial/searchgui/temp/peak_lists/test.ms2 

Is it possible to correct this bug. Thank you in advance for your help.

JF

**Comment by hbarsnes** [comment]
Hi JF,

Thanks for telling us about this. The issue has now been fixed according to your suggestion, and a new SearchGUI version (v2.0.5) has just been released.

Best regards,
Harald
