### ISSUE TITLE
SearchGUI (2.0.4, windows) stalls when zipping output files

### ISSUE THREAD

**Issue by lparsons42** [compomics/searchgui#57]
I am running SearchGUI 2.0.4 in Windows (2008 enterprise server).  I ran SearchGUI with 8 MGF files, and after it completed the search (total ~20 hours) it went to "zipping output files" and never finished.  The files have been zipping now for more time than it took to run the search itself (22 hours and counting) and have shown no sign of progress.  The file system where the relevant files are located has ~170GB available and has not shown signs of filling at this stage.  SearchGUI has shown overall progress of 95% now since starting the zipping and has not moved.  

SearchGUI itself however is responsive.  There are no processes shown in task manager that are using an extreme amount of CPU (no processes in my name using more than 1%) or RAM.  

Can I cancel at this point and open the non-zipped output files in PeptideShaker?  Is there anything else useful I can do at this point?

thank you
Lee

**Comment by hbarsnes** [comment]
Hi Lee,

Thanks for telling us about this. I'm not sure why the zipping would take this long. Is the size if the zip file still increasing, i.e. is it still zipping?

If you cancel the zipping it may be that we then assume that the processing failed and remove the generated output. So to be on the safe side I'd recommend to copy the results to a new folder before canceling the zipping.

And yes, you should be able to open the non-zipped files in PeptideShaker.

Let me know if you come across any other issues or if you see the zipping issue on other datasets as well.

Best regards,
Harald

**Comment by lparsons42** [comment]
Harald

Thank you for the reply.  Currently, in the output folder that I specified in SearchGUI I see the .mgf files that I used as input, .cui files for each of them, and the parameters file that I set up.  There is currently no zip file at all in that directory.  

Does SearchGUI have it's own zip utility for this?  I just tried running "zip" or "pkzip" in a command prompt and both came back as not recognized; I wonder if maybe it fails to find a command and doess't know what to do?

**Comment by hbarsnes** [comment]
Hi Lee,

During the search the output is located in a temp file called .SearchGUI_temp, in the output folder you chose when starting the search. (This is done in order to make sure that we don't delete any files when cleaning up after the zipping process.) When the search is done the content of .SearchGUI_temp will be zipped into searchgui_out.zip and the temp folder deleted.

Do you have a folder called .SearchGUI_temp in your output folder? It should contain your search results.

And yes, SearchGUI as its own Java code for zipping, so no external libraries or commands are needed.

Could you send me your SearchGUI log file? You'll find this via Help > Bug Report. But if SearchGUI is running you can also locate it in the SearchGUI resources folder. The file is called SearchGUI.log. You cannot access the file when SearchGUI is running, so just make a copy and send it to me at harald.barsnes at gmail.com

Best regards,
Harald

**Comment by lparsons42** [comment]
Hello

Indeed there is a .SearchGUI_temp folder, however no zip file was ever created in it.  There is also no SearchGUI.log file in there.  I haven't cancelled the SearchGUI run yet, but it has not made any progress on creating an archive.

I tried to open the files from the .SearchGUI_temp folder in PeptideShaker, first copying that directory to a new directory.  That went very slowly, eventually timing out after ~25 hours had passed since the time I tried to start opening them. I don't know if these events are related or if there is anything we can get from that.

thank you
Lee

**Comment by hbarsnes** [comment]
Hi Lee,

The zip file is not created in the temp folder itself, rather the content in the temp folder is zipped into a zip file in the output folder you selected.

In any case, something clearly went wrong here. So could you please send me your SearchGUI log file? The file is called SearchGUI.log and is in the SearchGUI resources folder (not in the temp folder). Send it to me at harald.barsnes at gmail.com.

The content of this file may also explain why PeptideShaker is having problems, so lets deal with the SearchGUI issue first.

Best regards,
Harald

**Comment by lparsons42** [comment]
Harald

This problem is sounding familiar now (I had a similar problem with files not going where I expected in a previous version of SearchGUI).  The system I am running this from is configured such that the user home directory is not the optimal place for scratch files to go to, nor is it where the mass spec or search database files reside.  I expect I will find that the zip file was going to the home directory (where there is likely not enough space for it); was the log being written there as well?  I should be able to fish this file out shortly.

thank you
Lee

**Comment by hbarsnes** [comment]
Hi Lee,

The SearchGUI log file should always be in the SearchGUI resources folder, i.e., the folder called resources located in the SearchGUI jar file.

As for deciding where the SearchGUI temp files are located you can control this via Edit > Resource Settings. But in general I'd not recommend locating SearchGUI in a folder with limitations on space, as some of the search engines will write their results to local temp folders that we cannot control.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Lee,

As I didn't hear back from you is it correct to assume that you managed to solve this issue? If so, please let me know so that I can close the issue.

Best regards,
Harald

**Comment by lparsons42** [comment]
Harald

Indeed the problem seems to be on our end and some of the oddities that 
come with where space is actually available (rather than where some 
things end up installed).

thank you
Lee

**Comment by hbarsnes** [comment]
Hi Lee,

Ok, I'll then close this issue.

Best regards,
Harald
