### ISSUE TITLE
tide-index problem on HPC

### ISSUE THREAD

**Issue by jflucier** [compomics/searchgui#62]
Hello,

I am trying to run SearchGUICli on an HPC cluster. When I run searchgui on a single dataset that I send to compute nodes everything works well. When I try to submit multiple dataset to compute nodes, SearchGUI returns an error:

```
tide search command: 
/netmount/ip32_home/xroucou_group/apps/compomics/SearchGUI-2.0.5/resources/Tide/linux/linux_64bit/crux tide-search --compute-sp F /ltmp/jflucier/temp_ms/GUOT_L130704_001/peak_lists/GUOT_L130704_001.ms2 fasta-index --overwrite T --top-match 10 --precursor-window 0.006 --precursor-window-type mz --fileroot GUOT_L130704_001 --exact-p-value F --output-dir crux-output --spectrum-min-mz 0.0 --min-peaks 20 --spectrum-charge all --remove-precursor-peak F --remove-precursor-tolerance 1.5 --print-search-progress 1000 --use-flanking-peaks F --use-neutral-loss-peaks T --mz-bin-width 0.02 --mz-bin-offset 0.0 --concat F --txt-output T --sqt-output F --pepxml-output F --mzid-output F --pin-output F --verbosity 30 

Thu Oct 01 13:31:40 EDT 2015 Processing GUOT_L130704_001.mgf with Tide.

INFO: Beginning tide-search.
WARNING: The output directory 'crux-output' already exists.
Existing files will be overwritten.
INFO: CPU: cp2541
INFO: Thu Oct  1 13:31:40 EDT 2015
INFO: Running tide-search...
INFO: Reading index fasta-index
FATAL: Error reading index (fasta-index/protix)


Thu Oct 01 13:31:40 EDT 2015 Tide Searching Process Finished (120 milliseconds).

Thu Oct 01 13:31:40 EDT 2015 Error: Source '/netmount/ip32_home/xroucou_group/apps/compomics/SearchGUI-2.0.5/resources/Tide/linux/linux_64bit/crux-output/GUOT_L130704_001.tide-search.target.txt' does not exist
Thu Oct 01 13:31:40 EDT 2015 An error occurred while running SearchGUI. Please contact the developers.
java.io.FileNotFoundException: Source '/netmount/ip32_home/xroucou_group/apps/compomics/SearchGUI-2.0.5/resources/Tide/linux/linux_64bit/crux-output/GUOT_L130704_001.tide-search.target.txt' does not exist
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:1805)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:2082)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Thu Oct 01 13:31:40 EDT 2015 The search or processing did not finish properly!


```

when I look at beginning of log output, I see that tide-index was well executed:

```
makeblastdb command: 
/netmount/ip32_home/xroucou_group/apps/compomics/SearchGUI-2.0.5/resources/makeblastdb/linux/linux_64bit/makeblastdb -in hs.fasta -dbtype prot 



tide index command: 
/netmount/ip32_home/xroucou_group/apps/compomics/SearchGUI-2.0.5/resources/Tide/linux/linux_64bit/crux tide-index /netmount/ip32_home/xroucou_group/analysis/mass_spec/db/hs.fasta fasta-index --overwrite T --mods-spec C+57.021464,2M+15.994915 --nterm-peptide-mods-spec 1X+42.010565 --max-mods 5 --decoy-format none --missed-cleavages 2 --output-dir crux-output --peptide-list F --verbosity 30 --min-length 6 --max-length 30 --min-mass 200.0 --max-mass 7200.0 --monoisotopic-precursor T --clip-nterm-methionine F --enzyme trypsin --digestion full-digest 


Thu Oct 01 11:07:29 EDT 2015 Indexing hs.fasta for Tide.

INFO: Beginning tide-index.
WARNING: The output directory 'crux-output' already exists.
Existing files will be overwritten.
INFO: CPU: cp2541
INFO: Thu Oct  1 11:07:29 EDT 2015
INFO: Running tide-index...
INFO: Writing results to output directory 'fasta-index'.
INFO: Reading /netmount/ip32_home/xroucou_group/analysis/mass_spec/db/hs.fasta and computing unmodified peptides...


Thu Oct 01 11:08:16 EDT 2015 Tide Indexing Process Finished (47.424 seconds).

```

I think the problems comes from the fact that tide-index is generated in ./crux-output folder. This causes a problem when computes node executed execute on different datasets concurrently. The ./crux-output folder gets overwritten by each compute node execution. I specified a -temp_folder local to each compute node. I was wandering if it is possible to tell Searchgui to create the tide-index in this temps folder (i.e. $temp_folder/crux-output)? 

thanks for your help,

JF

**Comment by mvaudel** [comment]
Hi JF,

Thank you for reporting this issue. Most search engines are not made to be
operated on a cluster and will write information in their installation
folder. Moving the search engines in the temp folder is on our todo list
but we never really got the time to do it.

When working on a cluster, it is thus best to copy the search engines on
the cluster prior to execution and run them there. The easiest solution is
to keep a "clean" SearchGUI folder and copy it on the server which will run
the job prior to execution. This is also the most robust solution in case a
job fails.

Did you look at our solution for distributed computing, Pladipus (
compomics.github.io/projects/pladipus.html)? It has all hacks to run search
engines in a cluster readily implemented for you :)

Best regards,

Marc

2015-10-01 19:59 GMT+02:00 jflucier <notifications@github.com>:

**Comment by jflucier** [comment]
Hello Marc,

thanks for the quick response. I dont know if my explanation were clear. My
pipeline works well now with the exeption of tide-index and tide-search. I
think SearchGUI should create these commands for tide-index and tide-search:

tide index command:
/netmount/ip32_home/xroucou_group/apps/compomics/SearchGUI-2.0.5/resources/Tide/linux/linux_64bit/crux
tide-index /netmount/ip32_home/xroucou_group/analysis/mass_spec/db/hs.fasta
*$temp_folder/fasta-index* --overwrite T --mods-spec
C+57.021464,2M+15.994915 --nterm-peptide-mods-spec 1X+42.010565 --max-mods
5 --decoy-format none --missed-cleavages 2 --output-dir
*$temp_folder/*crux-output
--peptide-list F --verbosity 30 --min-length 6 --max-length 30 --min-mass
200.0 --max-mass 7200.0 --monoisotopic-precursor T --clip-nterm-methionine
F --enzyme trypsin --digestion full-digest


tide search command:
/netmount/ip32_home/xroucou_group/apps/compomics/SearchGUI-2.0.5/resources/Tide/linux/linux_64bit/crux
tide-search --compute-sp F test.ms2 *$temp_folder/**fasta-index* --overwrite
T --top-match 10 --precursor-window 0.006 --precursor-window-type mz
--fileroot test --exact-p-value F --output-dir *$temp_folder/*crux-output
--spectrum-min-mz 0.0 --min-peaks 20 --spectrum-charge all
--remove-precursor-peak F --remove-precursor-tolerance 1.5
--print-search-progress 1000 --use-flanking-peaks F
--use-neutral-loss-peaks T --mz-bin-width 0.02 --mz-bin-offset 0.0 --concat
F --txt-output T --sqt-output F --pepxml-output F --mzid-output F
--pin-output F --verbosity 30

I think it would be cleaner to generate index file in provided user
temp_folder then in execution folder. To test this solution, I have runned
the following commands successfully:

# convert my mzML file to ms2 format (supported by tide):
/netmount/ip32_home/xroucou_group/apps/pwiz_release-3_0_8789/msconvert
/netmount/ip32_home/xroucou_group/no_backup/public_data/test.mzXML --ms2
--outdir ./ --outfile test.ms2

# run the tide-index with output in temp folder:
/netmount/ip32_home/xroucou_group/apps/compomics/SearchGUI-2.0.5/resources/Tide/linux/linux_64bit/crux
tide-index /netmount/ip32_home/xroucou_group/analysis/mass_spec/db/hs.fasta
*/ltmp/jflucier/temp_ms/test/**fasta-index* --overwrite T --mods-spec
C+57.021464,2M+15.994915 --nterm-peptide-mods-spec 1X+42.010565 --max-mods
5 --decoy-format none --missed-cleavages 2 --output-dir
*/ltmp/jflucier/temp_ms/test/crux-output* --peptide-list F --verbosity 30
--min-length 6 --max-length 30 --min-mass 200.0 --max-mass 7200.0
--monoisotopic-precursor T --clip-nterm-methionine F --enzyme trypsin
--digestion full-digest

# run tide-search
/netmount/ip32_home/xroucou_group/apps/compomics/SearchGUI-2.0.5/resources/Tide/linux/linux_64bit/crux
tide-search --compute-sp F test.ms2 */ltmp/jflucier/temp_ms/test/*
*fasta-index* --overwrite T --top-match 10 --precursor-window 0.006
--precursor-window-type mz --fileroot test --exact-p-value F --output-dir
*/ltmp/jflucier/temp_ms/test/crux-output* --spectrum-min-mz 0.0 --min-peaks
20 --spectrum-charge all --remove-precursor-peak F
--remove-precursor-tolerance 1.5 --print-search-progress 1000
--use-flanking-peaks F --use-neutral-loss-peaks T --mz-bin-width 0.02
--mz-bin-offset 0.0 --concat F --txt-output T --sqt-output F
--pepxml-output F --mzid-output F --pin-output F --verbosity 30


These commands work well and I think this update would make SearchGUI
portable to HPC. This would really help me as this is the last step to
taking this software to the HPC mode. If for some reason, you dont want to
adapt the SearchGUI code to output in tempfolder, please just give me a
pointer to which file I should look into to patch SearchGUI on my side.

Thanks again in advance for all your help Marc,

JF




IMPORTANT: Veuillez penser à l'environnement avant d'imprimer ce courriel

Jean-Francois Lucier
Bioinformatic Research Agent
Département de Biologie / Dept of Biology
Centre de calcul scientifique / Center for Scientific Computing
Université de Sherbrooke
2500, boulevard de l'Université
Sherbrooke (Québec) J1K 2R1
CANADA

**Comment by hbarsnes** [comment]
Hi JF,

If I remember correctly, I think that we initially were not able to put the index anywhere but in the Tide folder. But seems like you've found a way around this. I'll test this as soon as possible, and if it all works as indicated above, we'll include it in the next SearchGUI release.

Best regards,
Harald

**Comment by jflucier** [comment]
Thanks again Harald for your great support.

When do you think you will be able to make this new release available?
Before I launch my analyses without Tide, I just want an approximate
expected time if your able to provide me one. There is no pressure there
since there is a workaround (removing tide). I have many analyses to launch
ASAP for my boss for paper we are ready to submit with the exception of one
figure that needs completion with these mass spec results. I will base my
decision on the timeframe you provide me.

While waiting for your response, I took a look at the SearchGUI and
compomics-utilities code, It seems you have already organised the Comet
software execution in SearchGUI using temp folder provided by user.

Thank you again very much for your help.

JF



IMPORTANT: Veuillez penser à l'environnement avant d'imprimer ce courriel

Jean-Francois Lucier
Bioinformatic Research Agent
Département de Biologie / Dept of Biology
Centre de calcul scientifique / Center for Scientific Computing
Université de Sherbrooke
2500, boulevard de l'Université
Sherbrooke (Québec) J1K 2R1
CANADA

**Comment by hbarsnes** [comment]
Hi JF,

Hopefully I'll get it done by tomorrow. If not then early next week.

And yes, we already use the same approach for Comet, so should not be too hard to reuse for Tide.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi JF,

I had a quick go at trying to run command lines similar to what you have running on your side and I cannot get it to work...

Here's my command line (as you can see this is on Windows):
crux tide-index C:\Users\hba041\My_Git_Applications\peptide-shaker.wiki\data\2015_08_25\uniprot-human-reviewed-trypsin-august-2015_concatenated_target_decoy.fasta C:\Users\hba041\Desktop\test\temp2\fasta-index --overwrite T --mods-spec C+57.021464,2M+15.994915 --decoy-format none --missed-cleavages 2 --output-dir C:\Users\hba041\Desktop\test\temp2\crux-output --peptide-list F --verbosity 30 --min-length 6 --max-length 30 --min-mass 200.0 --max-mass 7200.0 --monoisotopic-precursor T --clip-nterm-methionine F --enzyme trypsin --digestion full-digest

No matter what I do I end up with the following error:
FATAL: Error reading proteins from C:\Users\hba041\My_Git_Applications\searchgui\resources\Tide\windows/C:\Users\hba041\Desktop\test\temp2\fasta-index/protix

So clearly Tide is confused about the folders used. This looks very familiar to what I had the last time I tried changing the Tide temp folders. But perhaps you can see what I'm doing wrong?

BTW, if you look at the Tide index documentation (http://cruxtoolkit.sourceforge.net/tide-index.html), it does not really seem to support changing the temp folder beyond changing the name of the folder? ("<index name> – The desired name of the binary index" and "--output-dir <string> – The name of the directory where output files will be created. Default = crux-output".)

Could it be that your trick only works on Linux..?

Best regards,
Harald

**Comment by mvaudel** [comment]
Hi again JF,

If I may add a comment on "There is no pressure there since there is a
workaround (removing tide).", Tide is a faster version of Comet so we would
not recommend using both at the same time in order not to give extra weight
to this algorithm. So if you have Comet results already I would say you are
good to go for your paper, and we will fix the Tide issue for the next one?

Best regards,

Marc


2015-10-01 22:35 GMT+02:00 jflucier <notifications@github.com>:

**Comment by jflucier** [comment]
Hello Harald, Marc,

you guys are awesome. Thanks so much for all your replies.

I will follow you advice Marc and run pipeline without Tide. In fact, I
didn't know it was a faster comet software.

Harald, I will try those on a windows VM and see if I can get this to work
on windows.

Thank so much guys for all your help, I will keep in touch concerning the
development and tests linked to the execution of tide and ms amanda on
linux.

JF

IMPORTANT: Veuillez penser à l'environnement avant d'imprimer ce courriel

Jean-Francois Lucier
Bioinformatic Research Agent
Département de Biologie / Dept of Biology
Centre de calcul scientifique / Center for Scientific Computing
Université de Sherbrooke
2500, boulevard de l'Université
Sherbrooke (Québec) J1K 2R1
CANADA

**Comment by mvaudel** [comment]
Hi JF,

I am now encountering the same issue as you with Tide. It seems to be the indexing of the database which poses problem. Do you still have the database at hand so that I can forward it to the developers?

Thank you and best regards,

Marc

**Comment by jflucier** [comment]
Hey Marc,

test are going well concerning SearchGUI on Sherbrooke's HPC. We are currently fine tuning parameters passed to search engines. I can't distribute as of today (currently being liscenced by university) the full database i am using. However, the databaase is the file attached to this discussion thread + inhouse entries.

**Comment by jflucier** [comment]
Hey Marc,

Test are going well with SearchGUI on Sherbrooke's University HPC. I can't distribute my full database as it is under liscencing procedure with University. However, it is based on the file downloadable below plus some inhouse entries I can't distribute.

Here is the link for download:
https://drive.google.com/file/d/0B-d3q8QV4q3oTmFyYjFwN19QTlU/view?usp=sharing

Hope this helps.

Thanks again for all your help. If you require something else from me, do not hesitate.

JF

**Comment by mvaudel** [comment]
Hi JF,

That is great to hear, thanks for your help!

Marc
