### ISSUE TITLE
Msconvert

### ISSUE THREAD

**Issue by DennisLinke** [compomics/searchgui#63]
Hey Marc, Hi Harald,

Thanks for implementing MS-Convert into SearchGUI, which makes it way more easier to run searches with SearchGUI in combination to PeptideShaker.
However, I might wonder if there is any chance to run the MS-Convert process of multiple MS-input files in parallel? 

In my case, I have 7 LC-ESI MS runs (5 hour gradients, Q Exactive) which I convert using the build-in msconvert option in SearchGUI. Currently, the conversion process is performed step by step; and the searches are only started after all files were converted. This process takes a lot of time, unfortunately...

Is there any chance to start the conversion process of the first .raw file and then trigger the database search(es) for this file, while in parallel to the database searches the second .raw file is converted to reduce the "entire process time" required.
Alternatively, would it be possible to run all file conversion processes in parallel prior database search?

Best regards
Dennis

**Comment by hbarsnes** [comment]
Hi Dennis,

At the moment we have no plans of  paralyzing the msconvert process, but we'll put it on the wish list for new features.

However, I'm not sure if this would really increase the overall speed of the processing? Especially not if we run msconvert at the same time as the search engines, as this would just slow down the search engines. Then I'd prefer the second option of running all the file conversions in parallel prior to starting the search. We actually already convert all the files before starting the search, so this option would require the least amount of changes to our current structure. I'm still not convinced that the speed improvement would be significant? Maybe you could do some tests in the GUI (or command line) version of msconvert to see if converting multiple files in parallel is any faster than converting one at the time?

@mvaudel Do you have any comments on this? I would think that the msconvert step would mainly be limited by the reading/writing to the disk which is hard to speed up by using multiple threads? 

Best regards,
Harald

**Comment by DennisLinke** [comment]
Hi Harald,

I just finished some benchmarks using two (smaller) MS files (called a1.raw & b2.raw)
The test system:

Configuration A: JBOD 4xSSD
Configuration B: 1 single SSD

Results of both were quite similar. After starting the msconvert process via command line, I directly stopped the time by watch. So little difference of up to 3 seconds are caused by human error ;)
 
At first, I was converting a1.raw file alone. Converting time was about 2:17 min (for configuration A & B).

For parallel conversion, I started the conversion process of b2.raw and of a1.raw (via two terminals, of course). Here, the time required for the file a1.raw was 2.20 min (Configuration A) and 2:22 min (Configuration B), respectively.

Of course, the time required for these files was little compared to database searches in general. However, there was no (or just a little) loss in time while converting the two .raw files [a1.raw & b2.raw] in parallel.

Best regards,
Dennis

**Comment by mvaudel** [comment]
Hi guys,

It should be possible to start the conversions in parallel, but as Harald
mentioned pure conversion is generally limited by the IO so you will not
gain too much there. The only point where I would expect some improvement
is when you run filters, e.g. peak picking. I can look into it but am also
not sure how clean it would be when reporting the progress.

Best regards,

Marc

2015-10-02 15:59 GMT+02:00 DennisLinke <notifications@github.com>:

**Comment by hbarsnes** [comment]
Hi Dennis,

We've just released SearchGUI v2.1.1 which includes multithreading of msconvert. And it seems like your initial tests were correct, multithreading is a lot faster then doing then one at the time. :)

Best regards,
Harald
