### ISSUE TITLE
exporting in pepXML and or prot.xml format

### ISSUE THREAD

**Issue by SimionKreimer** [compomics/searchgui#64]
Hi,
Is it possible to export PeptideShaker PSM scoring in a pepXML format and also to export the protein scores as something similar to the prot.xml output like with PeptideProphet and ProteinProphet? I've been able to export the PeptideShaker results in the .mzIdentML, but I would like to convert to pepXML for further analysis, is there a tool to do this? I've learned that IDconvert (proteowiz) doesn't do it.

Best, Simion

**Comment by mvaudel** [comment]
Hi Simion,

Sorry these formats are not supported at the moment. We opted for the
standard mzIdentML and did not look into pep/protXML because they are not
standard and their implementation varies from one tool to the other. May I
ask why you would need them for?

Best regards,

Marc

2015-10-08 17:42 GMT+02:00 SimionKreimer <notifications@github.com>:

**Comment by SimionKreimer** [comment]
I completely understand why you went with mzIdentML but there is another script I need to use that currently only takes pepXML and prot.XML results. Do you have any suggestions about converting between the two formats?

**Comment by mvaudel** [comment]
No sorry, we are not using these. My best guess would have been
proteowizard but as you pointed out it seems that they don't write protXML.
Maybe OpenMS or the TPP? Can you by any chance find a replacement for this
script?

2015-10-08 17:54 GMT+02:00 SimionKreimer <notifications@github.com>:

**Comment by SimionKreimer** [comment]
I found that the OpenMS IDFileConverter transforms the mzIdentML export to pepXML quiet nicely (at least well enough for what I'm doing). ProteoWiz ID convert gives a lot of errors.
Best, Simion

**Comment by hbarsnes** [comment]
Hi Simion,

Good to hear that you found a solution. Even though I'd still recommend trying to find pipelines that rely on the current standard formats.

I will now close the issue, but don't hesitate to open a new issue if you have other questions.

Best regards,
Harald
