### ISSUE TITLE
Search-gui command line error "Unrecognized option: -spectrum_files"

### ISSUE THREAD

**Issue by somakray** [compomics/searchgui#67]
Hi,

While trying to run search-gui 2.1.4 from the command line, I'm getting the following error. Nothing got recorded in the log-file though. The program runs fine from the GUI(I've used X!Tandem only so far). 

SearchGUI processing failed. See the SearchGUI log for details.
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -spectrum_files

        at org.apache.commons.cli.Parser.processOption(Parser.java:363)
        at org.apache.commons.cli.Parser.parse(Parser.java:199)
        at org.apache.commons.cli.Parser.parse(Parser.java:85)
        at eu.isas.searchgui.cmd.PathSettingsCLI.main(PathSettingsCLI.java:127)

**Comment by hbarsnes** [comment]
Hi,

Can you show me the command line you are trying to run? It seems like you might be using the wrong class, i.e., PathSettingsCLI instead of SearchCLI?

Have you had a look at http://compomics.github.io/searchgui/wiki/searchcli.html?

Best regards,
Harald

**Comment by somakray** [comment]
Thanks for pointing it out.  I was using  PathSettingsCLI and not SearchCLI which caused the problem
