### ISSUE TITLE
Feature Request - Save the advanced SearchGUI settings

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#68]
Maybe it is not really feasible, but it would be great I think if the "SearchGUI_out zip folder" and the "SearchGUI Report" would have the same time stamp, or at least the same time format.

Think the slight time-off set is not really a problem (5-10 seconds usually), but in my case the one is in "24h"-format (14.13.22) and the other in "12h"-format (e.g. 02.13.29).

And, possible to do the "Include Date in Filename" as Default setting? Or can I set that somehow on my side?

**Comment by mvaudel** [comment]
Hi again,

For now the include date in filename and packaging options of the results
are things you need to set for every search. Saving these parameters has
long been on our todo list but we never really got to it...

I will look into having a uniform time format, thanks for the hint!

Best regards,

Marc

2015-11-18 18:47 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
that would be great! highly appreciated!

**Comment by hbarsnes** [comment]
The same time stamp format is now used for both the SearchGUI zipped output and the SearchGUI report, using the 24 hour format. The two time stamps themselves cannot be identical as there might be more zip files than reports (if the advanced zip options are used).

The fix will be included in the next releases, but I'm closing the issue now before I forget it. ;-)

**Comment by ulriche** [comment]
great news!!!

**Comment by hbarsnes** [comment]
Just noticed that there was a second part to this issue, the saving of the SearchGUI advanced settings between each run, so I reopend the issues until this has been fixed as well. :-)

**Comment by ulriche** [comment]
great, thanks.

**Comment by hbarsnes** [comment]
Hi Ulrich,

The advanced settings are now finally saved between each time you run SearchGUI. So we can now finally close this issue. :)

Best regards,
Harald

**Comment by ulriche** [comment]
Yeah!!! Great news!!! Big big thanks!!!
