### ISSUE TITLE
PSM report - Isotope Number reported as "0" when "<0" and "corrected ppm"-feature request

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#69]
Hey PeptideShaker Team,

is it possible that the Isotope Number "0" is reported when it is actually "<0", e.g. "-1"? at least in my MSGF+ results it looks this way.

And regarding the "precurser m/z error [ppm]": is it possible to add an "isotope corrected" column to account for the isotope offset? otherwise I end up with crazy numbers such as "156587 ppm".

thanks in advance and all the best
u

**Comment by mvaudel** [comment]
Hi Ulrich,

The default isotopic correction is limited to 0-4 in the online version of
PeptideShaker but will be a user parameter in the next release. On our side
including -1 isotopes adds only false positives though. I must say I have
troubles figuring what a -1 isotope would be. Is that something you see in
your design specifically?

Best regards,

Marc

2015-11-18 20:17 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
Sorry for the late follow up. Forgot to check in here again. I never understood the "-1" either, but Sangtae back then tried to explain me why it is needed but I never really understood it. But I dug his reply out of my email account - maybe it helps you! ;-)

"Regarding your question, I think it's mainly due to deisotoping algorithms rather than modifications. Sometimes, if there's tiny peak at mono-1, the algorithm reports that as the mono mass. If you don't like to see them, you can do it by specifying "-ti". "-ti 0,2" will correct only for +1 and +2 errors."

Usually I stuck then with "0 to 2", but I think the MS-GF+ default in SearchGui was "-1 to 2", so I went for my trials with that one. But guess will just go back to "0 to 2" again, and maybe set it as default also in MS-GF+ within SearchGUI maybe.

Big thanks again.
u

**Comment by ulriche** [comment]
Just in case it got lost in my initial post:

Is an "isotope corrected" ppm-column in planning? think it would be nice to have! ;-)

**Comment by mvaudel** [comment]
Hi again,

It was also our understanding that this option would correct for random
peaks appearing exactly at a chimeric -1 isotope. This heavily depends on
the resolution of the instrument and the deisotoping algorithm. Our default
settings are for MS1 Orbitrap data, and as far as we tested there -1
isotope produced only false positives. The ppm column is already corrected,
with limitation to 0-4 isotopes. You will be able to set these boundaries
in a coming version :)

Best regards,

Marc

2015-11-28 22:07 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
sounds great - looking forward to the upcoming version! :-)

**Comment by ulriche** [comment]
just saw that my PeptideShaker wants to update already! Will wait 'til tomorrow but then giving Comet another round! fingers crossed!

**Comment by ulriche** [comment]
one thing - as we agree that we shouldn't use the "-1" option, can you adapt the "advanced settings" for comet? currently I have to include "-1" if I want "+1,+2" additionally to the conventional "0". thanks!

**Comment by hbarsnes** [comment]
Hi Ulrich,

You'd have to ask Jimmy about changing the isotope correction for Comet, as we only use his default options, see http://comet-ms.sourceforge.net/parameters/parameters_201502/isotope_error.php.

Best regards,
Harald

**Comment by ulriche** [comment]
yeah, just realized that it was "MS-GF+" that allowed the precise specification. sorry for that. but just posted on the comet page - let's see what he thinks!

**Comment by ulriche** [comment]
Jimmy had maybe a good idea why in his hands the "-1" often gives IDs with high confidence:

"The -1 offset is a bit weird to explain but there are high confidence IDs from that offset.  A lot of those could be due to deamidation where that modification isn't searched for explicitly but found with this offset."

but not sure how it is handled for the peak assignment though.

**Comment by ulriche** [comment]
update:

"The presumption is that enough of the MS2 peaks (half of them) are unchanged between the unmodified and deamidated peptide so there's enough to still get a good match between the deamidated spectrum and the unmodified peptide sequence."

**Comment by mvaudel** [comment]
Hi Ulrich,

That makes sense. But in our samples we have very little deamidation and
when there is some we look for it rather than hoping that it will be
rescued by an incorrect isotopic mapping ;)

Best regards,

Marc

2015-12-03 21:22 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
very good point. in my case I try to avoid searching for it, as I typically have already quite a lot of variable modifications in my searches. c o m p l i c a t e d ! ! !

**Comment by mvaudel** [comment]
Hi again,

I am not sure whether it is better to leave the search engine the
possibility to find the deamidated precursor - even on peptides which
cannot be deamidated - and then only partially interpret the spectrum. I
would feel more confident having a fair competition between deamidated and
not deamidated peptides.

Best regards,

Marc

2015-12-08 2:48 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
Definitely true. Only reason for me to stay away from deamidation is as we have already quite a lot of variable modifications (6 for a TMT experiment and more for dimethyl ones) per default, on top of searching for semi-tryptic peptides. thus our search space is already rather big and not sure if I want to increase it  on top of that by deamidation. thus the "-1" sounds tempting, and if PeptideShaker could kick the ones out that are "-1" but don't have Gln or Asn, it could be maybe not even such a bad way to do it (at least for our case and as long as it is documented).

**Comment by mvaudel** [comment]
Hi again,

I am not sure whether includig a -1 "modification" on all peptides is a
smaller search space than including deamidation on peptides which can be
deamidated, we would need to see the occurrences of Gln and Asn in
peptides. And as said, given that your spectra will only be partially
annotated, their score will not be illustrative of the actual quality of
the PSM, and will thus poorly compare to other matches in the dataset. I
will try to see how we can manage this in PeptideShaker, but I must say I
am not really enthusiastic about this one :)

Best regards,

Marc

2015-12-09 2:59 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
hmmm ... very good points. I somehow assumed that the "-1" could be a "search engine"-wise fast fix for deamidation as I assumed increasing the search space in MS1 adds less additional search time than in MS2 (hope you know what I mean), which is in our cases already rather elaborate. but maybe that's a miss-conception on my side.

I agree, the partial annotation could be really a problem, especially when trying to convince reviewers that it is what i see and try to sell (but guess in crucial cases I would rerun the searches with deamidation anyway and hope that it shows up again). i guess it is thus more a bit of a philosophical problem and doesn't "scream" for a PeptideShaker fix (but could be nice to be included). but what should be fixed is, that if I use -1, that peptideshaker recognizes it as "-1" and reports it as "-1" and the right ppm-error. if I get that, I am already more than happy! ;-)

**Comment by mvaudel** [comment]
Hi Ulrich,

No worries, we just need to make a few adjustments to the gui to support
any kind of isotopes :)

Best regards,

Marc

2015-12-09 19:54 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by hbarsnes** [comment]
Hi Ulrich,

Please check out the new SearchGUI version where you can now control the isotope range directly in the main search settings. But do note that the range setting is ignored by most search engines, and does not directly translate for some of them, e.g., Comet still has it's three hardcoded options. But at least it gives you some control over the isotope range.

Best regards,
Harald

**Comment by ulriche** [comment]
sounds great. and yep, as far as I understood Jimi Comet will still have
only hard coded options. thus maybe better set in comet as "advanced
setting" maybe? along the line: noticed (and appreciated) that you
activated the semi-specific option within X! Tandem in the advanced
options. but fear it is not placed correctly as it is not a refinement
parameter but rather a global one, no? or is there a reason to rather hide
it there? cheers and thanks, u

**Comment by hbarsnes** [comment]
The isotope range is a general setting as it affects the later processing of the results as well, and hence it not just an advanced parameter for the search itself. (But Marc can provide more details here.)

Regarding the semi option in X!Tandem, there are actually two semi options in X!Tandem, one for the the "normal" search and one for the second pass search. So there is no hiding involved. At least not on our part. ;-)

**Comment by ulriche** [comment]
then I have to double check but thought that the one that gets evoked in
the refinement setting within SearchGUI goes towards the "global" one, at
least the "help page" link got me there if I remember correctly (but not
sure if i checked he parameter file). in case, any chance to enable also
the global "semi" option in the "advanced" X! Tandem settings?

regarding isotope range: agreed, but ... if not all of the search engines
can take it into account, but it is used as a global setting, how is it
taken into account then? weighted depending on the amount of search engines
that use it? and, without knowing the background, wouldn't the same hold
true most likely for "semi"-option? (if it is in any way linked with search
space size or similar)

**Comment by hbarsnes** [comment]
The "unanticipated cleavage" option in the refinement settings refers to this one: http://www.thegpm.org/TANDEM/api/ruc.html, and is not affected by choosing a semi enzyme in SearchGUI, as this only affects the "protein, cleavage semi" option (http://www.thegpm.org/TANDEM/api/pcsemi.html).

To change the "refine, cleavage semi" option you have to change it in the advanced settings. We thought about setting both options to "semi" if a "semi enzyme" was selected, but decided against this as it limits the user's options. And I guess that partly the "refine, unanticipated cleavage" option (which defaults to true), will cover most of the semi cleavages in the second pass search anyway?

Regarding the isotope range, I'm not sure what you mean by "take into account"? It's simply treated in the same way as all other differences between the search engines, as much as the best PSM across all the search engines (i.e., the one with the best overall evidence/score) is selected as the representative PeptideShaker PSM.

**Comment by ulriche** [comment]
my fault ... thought the plan was to get the "semi" out of the "global"
settings and get it into the "advanced" settings, as e.g. comet allows for
sub-options which other ones don't. thus I falsely assumed that this would
be the plan for X! Tandem.

regarding refinement: this may be true in shotgun proteomics where you have
typically many peptides per protein but to my understanding not necessarily
for our N-terminomics approaches where we ideally don't have a single
fully-tryptic (e.g.) peptide to begin with (but 1-2 semi tryptic ones), and
thus wouldn't get many hits into the 2nd pass. but maybe that's a
misconception from our side how X!Tandem does the refinement.

and regarding "taking into account": I understood you the way that it is
important for PeptideShaker to know how the Isotope Error was set to do
proper statistics during the downstream processing. And thus I thought,
that may be the same for the semi-option. think it can be quite confusing
if I can set a isotope error range in SearchGUI but which is not
necessarily reflected like that in the underlying search engines. thus I
thought about it more as an "advanced" option I guess.

**Comment by hbarsnes** [comment]
"for our N-terminomics approaches where we ideally don't have a single fully-tryptic". Which is exactly why you'd want to use the semi option in the first pass search. This should increases the chance of detecting the wanted proteins. However, I'm not sure if X!Tandems two stage search process is well-suited for your kind of data, so I'm not entirely sure if the end result will be as desired. All we can do on our side is expose all the parameters and allow you to edit them.

"important for PeptideShaker to know how the Isotope Error was set to do proper statistics during the downstream processing". Not really. The statistics are all based on the scores for the PSMs. But of course, ideally we'd be able to use the exact same search settings for all search engines. However, the minor differences in the settings available (in addition to the differences in the algorithms themselves) are what results in improved overall results when combining the search engine results. So this is not all bad.

**Comment by ulriche** [comment]
>
> "for our N-terminomics approaches where we ideally don't have a single
> fully-tryptic". Which is exactly why you'd want to use the semi option in
> the first pass search. This should increases the chance of detecting the
> wanted proteins.
>
yep, that's what I meant - guess I didn't phrase it perfectly.

> However, I'm not sure if X!Tandems two stage search process is well-suited
> for your kind of data, so I'm not entirely sure if the end result will be
> as desired. All we can do on our side is expose all the parameters and
> allow you to edit them.
>
agreed, that's why so far (in conjunction with TPP) we never used the
refinement module. thus I was surprised when the "semi" function showed up
there, and thought that the help page went to the global "semi" page - but
must have mixed that up. but still think it would be nice to have the
"global" semi option in the advanced settings.

> "important for PeptideShaker to know how the Isotope Error was set to do
> proper statistics during the downstream processing". Not really. The
> statistics are all based on the scores for the PSMs. But of course, ideally
> we'd be able to use the exact same search settings for all search engines.
> However, the minor differences in the settings available (in addition to
> the differences in the algorithms themselves) are what results in improved
> overall results when combining the search engine results. So this is not
> all bad.
>
not bad at all. btw. I am in contact with Jimmy already regarding my
"mgf/comet" problem, and he will contact the MSToolkit people next week.
will keep you posted.

**Comment by hbarsnes** [comment]
I'm closing this issue as the isotope correction issue has been solved in later releases. If this is not the case or if there are "sub issues" in this thread that are still open, please open a new issue.
