### ISSUE TITLE
MS Amanda matches reported with charge 0 and "Infinity" mass to charge and without matched fragment information

### ISSUE THREAD

**Issue by SimionKreimer** [compomics/searchgui#70]
Hi, very cool update, but I'm having some trouble with using MS Amanda. I carried out a few multi-engine searches combining MyriMatch, MSGF+, and MS Amanda using the most recent SearchGUI 2.2.2 in Linux and when I examined the results in PeptideShaker I noticed that the matches made by MS Amanda all showed 0 for the charge and none of the fragments were labelled as identified, even in high confidence matches. Maybe there is an issue with importing the MS Amanda results? I've put the search results into this dropbox folder: https://www.dropbox.com/sh/92jwwqs79te5f9q/AAD7kg8lwZIsIWn-qA5A4oWSa?dl=0

Best, Simion

**Comment by hbarsnes** [comment]
Hi Simion,

We didn't really change anything for MS Amanda in this version, so I assume that you see the same issues with earlier versions as well? Which operating system are you using? (As there are different versions of MS Amanda for the different operating systems.)

Not sure what you mean by "none of the fragments were labeled as identified"..?

In any case, I'll take a look at your data as soon as possible and get back to you.

Best regards,
Harald

PS: I'm having some problems downloading the zip file (on a poor wireless at the moment). Will try again later, but I'd also need the mgf files if they are not already included in your SearchGUI zip file.

**Comment by SimionKreimer** [comment]
I added the mgf files as requested. I did see this with version 2.1.4, but I haven't noticed the issue until recently (it may have been happening without my awareness).  By "none of the fragments were labeled as identified" I mean that with other search engines ions that were matched (e.g. b5, y11, etc.) are labelled in the spectrum when viewed in PeptideShaker. This does not seem to be happening with MS Amanda. I'm using Arch Linux and running the MS Amanda version included in the installation.

**Comment by hbarsnes** [comment]
Hi Simion,

Ok, I understand what you mean. Probably related to the missing charges then. Have you checked the charge column in the MS Amanda output file (it's just a tab separated text fiie)? If the charges are not there then it makes sense that PeptideShaker cannot find them. And what are your min and max precursor charge settings in the search parameters?

BTW, are you using the GUI or the command line?

Best regards,
Harald

(Still on the poor wireless...)

**Comment by SimionKreimer** [comment]
Hi Herald,
I checked the MS Amanda csv result file and there is a column for charge states, and most of them are set as 0. So it seems like this might be and issue with MS Amanda, not sure exactly what could be happening there, since it's still able to match many peptides and not all of the charge states are 0.

Best, Simion

**Comment by SimionKreimer** [comment]
I added one of the extracted csv files to the drop-box if you would like to take a look.

**Comment by hbarsnes** [comment]
Hi Simion,

Just had a quick look at your files and I cannot see anything wrong with neither the search settings nor the FASTA file. And the charge is clearly set to 0 in the MS Amanda csv output file, so I'm leaning towards this being a problem in MS Amanda.

I saw that you already contacted the MS Amanda list. Lets hope that they have an idea what is going on, as peptides with no charge will of course cause problems when trying to load the data in PeptideShaker.

I will try repeating the search on my side to see if I can reproduce the missing charges.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Simion,

I just wanted to confirm that I also get peptides with charge 0 when researching your mgf files with MS Amanda using your settings. I don't get any peptides with charge 0 when searching other datasets though. So there has to be something going wrong in MS Amanda with your particular settings. But no idea what that could be.

Perhaps you could try modifying your search settings to see if that has any effect? For example, try without the deamidations? (Not that I can see why that should matter...)

Best regards,
Harald

**Comment by ulriche** [comment]
... don't understand the full discussion unfortunately, but starting playing with MS Amanda myself yesterday and here a quick observation which goes along the same line I think:
all identifications that I have after "default PSM" export are Isotope Number "0" - so not a single +1 or +2. when I check the ppm column, I am perfectly in my "+/-15ppm" window, so I assume that this all worked. So I am wondering if maybe the "isotope error" is not used in MS Amanda. Haven't used MS Amanda so far, so not sure if it supports it, but I would guess so. hope that I don't cause even more confusion! all the best, u

PS: my charge states in the PSM default export file are all set. So guess it is a very different issue or non-issue!

**Comment by ulriche** [comment]
just realized that MS Amanda just doesn't support an isotope error, at least not via SearchGui. shouldn't do different stuff in parallel, makes me things mix up. so I guess all good in my case, at least for now! ;-)

**Comment by hbarsnes** [comment]
Update from the MS Amanda developers: 
"there was a bug in reporting charge states to the result file when disabling the low-ram-mode option. This will be fixed in the next version!"

We will update the MS Amanda version in SearchGUI as soon as the new version is available.

**Comment by hbarsnes** [comment]
Should be fixed in SearchGUI v2.6.0. If not, please let us know and we'll reopen the issue.
