### ISSUE TITLE
Mini Issue: semiArgC missing

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#71]
Maybe I just miss it, but don't find semiArgC predefined in SearchGUI. I can add it of course manually, but then MS Amanda does still not recognize it. possible? thanks in advance, u

**Comment by hbarsnes** [comment]
Hi Ulrich,

Seems like semi-ArgC was never added. Will be included in the next release. In the future we'll try to get rid of all the semi-enzymes and rather make the semi-specificity a separate option.

For now just add the following at the end of searchGUI_enzymes.xml and peptideshaker_enzymes.xml: 

<enzyme>
	<id> 28 </id>
	<name> Semi-Arg-C </name>
	<aminoAcidBefore> R </aminoAcidBefore>
	<restrictionBefore> </restrictionBefore>
	<aminoAcidAfter> </aminoAcidAfter>
	<restrictionAfter> P </restrictionAfter>
	<semiSpecific> yes </semiSpecific>
	<wholeProtein> no </wholeProtein>
</enzyme>

In the next version the MS Amanda enzymes will be generated based on these files. But for now just go into MS Amanda\windows\enzymes_SearchGUI.xml and add:

  <enzyme>
    <name>Semi-Arg-C</name>
    <cleavage_sites>R</cleavage_sites>
    <inhibitors>P</inhibitors>
    <position>after</position>
  </enzyme>

Best regards,
Harald

**Comment by ulriche** [comment]
awesome - it works. missed the additional enzyme definition within MS Amanda. big big thanks!!!
one more quick question: what are "maximum MGF File Size" and Maximum Spectra in MGF File" exactly doing?. Didn't have a mgf >1GB yet, but I had  more than 25k spectra and it searched still all of them. no?

**Comment by hbarsnes** [comment]
The "Maximum MGF File Size" is just a trick we added to tell SearchGUI when to start splitting the mgf files into smaller pieces. When an mgf file is bigger than the given limit we automatically split it into multiple files, each with as maximum as many spectra as set in the  "Maximum Spectra in MGF File" option. (For mgf files smaller than 1 GB the "Maximum Spectra in MGF File" has no impact.) As the PSMs are later merged when loaded in PeptideShaker the impact of the splitting should be minimal, but it is recommended to process the mgf files without splitting when possible.

This was something we added to be able to process files bigger than what was supported by some of the search engines, in particularly OMSSA. For the newer search engines splitting mgfs should not be necessary.

**Comment by ulriche** [comment]
that makes perfectly sense. thanks for that info!

**Comment by hbarsnes** [comment]
SearchGUI 2.3.0 and PeptideShaker 1.3.0 now includes support for Semi-Arg-C out if the box. :)

**Comment by ulriche** [comment]
yeah! happy holidays!
