### ISSUE TITLE
X!Tandem parameter file: variable N-terminal modifications

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#72]
Hey folks,

not sure as no results yet, but I am a bit confused about the X!Tandem parameter file - but it may be right (couldn't check anymore as I have to leave the lab now and fly to Europe tomorrow).

That are my SearchGUI settings:
![image](https://cloud.githubusercontent.com/assets/13509447/11970691/6fb533ec-a8e4-11e5-9223-f8803ca508a3.png)

why does it translate to:
![image](https://cloud.githubusercontent.com/assets/13509447/11970713/bfd682a4-a8e4-11e5-8064-35bdd6973be3.png)

-> I understand the first three, so fixed cmCys & TMT6@K, and variable Met-Ox.

but I don't understand the variable N-terminal ones. i guess the pyro-ones are handled by the quick-pyrolidone function, but what happens to the N-terminal acetyl and TMT? why do they end up in the "potential modification motif"? (on a sidenote, the quick acetyl option in X! Tandem only works for something like the first 50 aminoacids in a protein (but don't know the exact number), and is thus not sufficient in our cases. any idea?

all the best
u

**Comment by ulriche** [comment]
just remembered something ... think X! Tandem allows only one variable modification per residue (at least the TPP version couldn't). thus I wouldn't be able to do what I wanted with the current SearchGUI setup. the way to circumvent that at least within TPP was the following:

	
	<note type="input" label="residue, modification mass">+57.021464@C,+229.162932@K</note>

	
	<note type="input" label="residue, modification mass 1">+57.021464@C,+229.162932@K,+229.162932@[</note>

	
	<note type="input" label="residue, modification mass 2">+57.021464@C,+229.162932@K,+42.010565@[</note> 

so to do 3 iterative searches. not a perfect solution, but the best what we could came up with back then (and which also worked! ;-) ).

Not sure if a similar solution could be feasible for SearchGUI.

**Comment by mvaudel** [comment]
Hi Ulrich,

The most recent versions of X!Tandem support multiple modifications on the
same residue, but it is at another place in the xml file. Same for terminal
modifications. Can you attach the entire file?

Best regards,

Marc

2015-12-23 5:08 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
here we go ... didn't spot something obvious but guess that doesn't mean
that much at 2am! ;-)

<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="tandem-input-style.xsl"?>
<bioml>
<note>list path parameters</note>
<note type="input" label="list path, default
parameters">default_input.xml</note>
<note>This value is ignored when it is present in the default parameter
list path.</note>
<note type="input" label="list path, taxonomy
information">taxonomy_searchGUI.xml</note>

<note>spectrum parameters</note>
<note type="input" label="spectrum, fragment monoisotopic mass
error">0.05</note>
<note type="input" label="spectrum, parent monoisotopic mass error
plus">15.0</note>
<note type="input" label="spectrum, parent monoisotopic mass error
minus">15.0</note>
<note type="input" label="spectrum, parent monoisotopic mass isotope
error">yes</note>
<note type="input" label="spectrum, fragment monoisotopic mass error
units">Daltons</note>
<note>The value for this parameter may be 'Daltons' or 'ppm': all other
values are ignored</note>
<note type="input" label="spectrum, parent monoisotopic mass error
units">ppm</note>
<note>The value for this parameter may be 'Daltons' or 'ppm': all other
values are ignored</note>
<note type="input" label="spectrum, fragment mass type">monoisotopic</note>
<note>values are monoisotopic|average </note>

<note>spectrum conditioning parameters</note>
<note type="input" label="spectrum, dynamic range">100.0</note>
<note>The peaks read in are normalized so that the most intense peak
is set to the dynamic range value. All peaks with values of less that
1, using this normalization, are not used. This normalization has the
overall effect of setting a threshold value for peak intensities.</note>
<note type="input" label="spectrum, total peaks">50</note>
<note>If this value is 0, it is ignored. If it is greater than zero (lets
say 50),
then the number of peaks in the spectrum with be limited to the 50 most
intense
peaks in the spectrum. X! tandem does not do any peak finding: it only
limits the peaks used by this parameter, and the dynamic range
parameter.</note>
<note type="input" label="spectrum, maximum parent charge">6</note>
<note type="input" label="spectrum, use noise suppression">no</note>
<note type="input" label="spectrum, minimum parent m+h">500.0</note>
<note type="input" label="spectrum, minimum fragment mz">200.0</note>
<note type="input" label="spectrum, minimum peaks">8</note>
<note type="input" label="spectrum, threads">12</note>
<note type="input" label="spectrum, sequence batch size">1000</note>
<note>residue modification parameters</note>
<note type="input" label="residue, modification mass">57.021464@C
,229.162932@K</note>
<note>Carbamidomethylation of C,TMT 6-plex of K</note>
<note type="input" label="residue, potential modification mass">15.994915@M
</note>
<note>Oxidation of M</note>
<note type="input" label="residue, potential modification
motif">42.010565@229.162932@</note>
<note>The format of this parameter is similar to residue, modification mass,
with the addition of a modified PROSITE notation sequence motif
specification.
For example, a value of 80@[ST!]PX[KR] indicates a modification
of either S or T when followed by P, and residue and the a K or an R.
A value of 204@N!{P}[ST]{P} indicates a modification of N by 204, if it
is NOT followed by a P, then either an S or a T, NOT followed by a P.
Positive and negative values are allowed.
</note>

<note>protein parameters</note>
<note type="input" label="protein, taxon">all</note>
<note>This value is interpreted using the information in
taxonomy.xml.</note>
<note type="input" label="protein, cleavage site">[R]|{P}</note>
<note>this setting corresponds to the enzyme trypsin. The first characters
in brackets represent residues N-terminal to the bond - the '|' pipe -
and the second set of characters represent residues C-terminal to the
bond. The characters must be in square brackets (denoting that only
these residues are allowed for a cleavage) or french brackets (denoting
that these residues cannot be in that position). Use UPPERCASE characters.
To denote cleavage at any residue, use [X]|[X] and reset the
scoring, maximum missed cleavage site parameter (see below) to something
like 50.
</note>
<note type="input" label="protein, cleavage semi">yes</note>
<note type="input" label="protein, modified residue mass file"></note>
<note type="input" label="protein, cleavage C-terminal mass
change">17.002735</note>
<note type="input" label="protein, cleavage N-terminal mass
change">+1.007825</note>
<note type="input" label="protein, quick acetyl">yes</note>
<note type="input" label="protein, quick pyrolidone">yes</note>
<note type="input" label="protein, stP bias">no</note>
<note type="input" label="protein, N-terminal residue modification
mass">0.0</note>
<note type="input" label="protein, C-terminal residue modification
mass">0.0</note>
<note type="input" label="protein, homolog management">no</note>
<note>if yes, an upper limit is set on the number of homologues kept for a
particular spectrum</note>

<note>model refinement parameters</note>
<note type="input" label="refine">no</note>
<note type="input" label="refine, modification mass"></note>
<note type="input" label="refine, sequence path"></note>
<note type="input" label="refine, tic percent">20</note>
<note type="input" label="refine, spectrum synthesis">yes</note>
<note type="input" label="refine, maximum valid expectation
value">0.01</note>
<note type="input" label="refine, unanticipated cleavage">yes</note>
<note type="input" label="refine, cleavage semi">no</note>
<note type="input" label="refine, point mutations">no</note>
<note type="input" label="refine, saps">no</note>
<note type="input" label="refine, use potential modifications for full
refinement">no</note>
<note type="input" label="refine, potential N-terminus
modifications"></note>
<note type="input" label="refine, potential C-terminus
modifications"></note>
<note type="input" label="refine, potential modification mass"></note>
<note type="input" label="refine, potential modification motif"></note>
<note>The format of this parameter is similar to residue, modification mass,
with the addition of a modified PROSITE notation sequence motif
specification.
For example, a value of 80@[ST!]PX[KR] indicates a modification
of either S or T when followed by P, and residue and the a K or an R.
A value of 204@N!{P}[ST]{P} indicates a modification of N by 204, if it
is NOT followed by a P, then either an S or a T, NOT followed by a P.
Positive and negative values are allowed.
</note>

<note>scoring parameters</note>
<note type="input" label="scoring, minimum ion count">4</note>
<note type="input" label="scoring, maximum missed cleavage sites">1</note>
<note type="input" label="scoring, x ions">no</note>
<note type="input" label="scoring, y ions">yes</note>
<note type="input" label="scoring, z ions">no</note>
<note type="input" label="scoring, a ions">no</note>
<note type="input" label="scoring, b ions">yes</note>
<note type="input" label="scoring, c ions">no</note>
<note type="input" label="scoring, cyclic permutation">no</note>
<note>if yes, cyclic peptide sequence permutation is used to pad the
scoring histograms</note>
<note type="input" label="scoring, include reverse">no</note>
<note>if yes, then reversed sequences are searched at the same time as
forward sequences</note>

<note>output parameters</note>
<note type="input" label="output, log path"></note>
<note type="input" label="output, message"></note>
<note type="input" label="output, one sequence copy">no</note>
<note type="input" label="output, sequence path"></note>
<note type="input" label="output, path">output.xml</note>
<note type="input" label="output, sort results by">spectrum</note>
<note>values = protein|spectrum (spectrum is the default)</note>
<note type="input" label="output, path hashing">yes</note>
<note>values = yes|no</note>
<note type="input" label="output, xsl path">tandem-style.xsl</note>
<note type="input" label="output, parameters">yes</note>
<note>values = yes|no</note>
<note type="input" label="output, performance">yes</note>
<note>values = yes|no</note>
<note type="input" label="output, spectra">yes</note>
<note>values = yes|no</note>
<note type="input" label="output, histograms">no</note>
<note>values = yes|no</note>
<note type="input" label="output, proteins">yes</note>
<note>values = yes|no</note>
<note type="input" label="output, sequences">no</note>
<note>values = yes|no</note>
<note type="input" label="output, one sequence copy">no</note>
<note>values = yes|no, set to yes to produce only one copy of each protein
sequence in the output xml</note>
<note type="input" label="output, results">all</note>
<note>values = all|valid|stochastic</note>
<note type="input" label="output, maximum valid expectation
value">1.0</note>
<note>value is used in the valid|stochastic setting of output,
results</note>
<note type="input" label="output, histogram column width">50</note>
<note>values any integer greater than 0. Setting this to '1' makes cutting
and pasting histograms
into spread sheet programs easier.</note>
<note type="description">ADDITIONAL EXPLANATIONS</note>
<note type="description">Each one of the parameters for X! tandem is
entered as a labeled note
node. In the current version of X!, keep those note nodes
on a single line.
</note>
<note type="description">The presence of the type 'input' is necessary if a
note is to be considered
an input parameter.
</note>
<note type="description">Any of the parameters that are paths to files may
require alteration for a
particular installation. Full path names usually cause the least trouble,
but there is no reason not to use relative path names, if that is the
most convenient.
</note>
<note type="description">Any parameter values set in the 'list path,
default parameters' file are
reset by entries in the normal input file, if they are present. Otherwise,
the default set is used.
</note>
<note type="description">The 'list path, taxonomy information' file must
exist.
</note>
<note type="description">The directory containing the 'output, path' file
must exist: it will not be created.
</note>
<note type="description">The 'output, xsl path' is optional: it is only of
use if a good XSLT style sheet exists.
</note>

</bioml>

**Comment by ulriche** [comment]
any updates/ideas on that? haven't checked with the updated SearchGUI though.

**Comment by mvaudel** [comment]
Nope sorry, we have been busy with other issues :) Will come back to this
one next week!

2016-01-15 5:02 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
identified a 2nd issue along the line:

![image](https://cloud.githubusercontent.com/assets/13509447/12375966/0b1bb8ec-bc90-11e5-83af-86c44025f4dc.png)

instead of N-terminal TMT and TMT@K, X!Tandem seems to do 2x TMT@K and thus PeptideShaker loses one of the two ...

**Comment by hbarsnes** [comment]
> instead of N-terminal TMT and TMT@K, X!Tandem seems to do 2x TMT@K and thus PeptideShaker loses one of the two

As far as I remember this is simply the way that X!Tandem reports terminal modification, i.e. there is no special annotation and it just puts them on the first residue (it's the same for some of the other search engines as well). The challenge is how to interpret it in cases such as the one above.

It all seems to be ok if both modifications are fixed, but the problem occurs if one of them is fixed and the other variable, as all the properties of the modifications are identical and it becomes impossible to tell them apart.

So I assume that in your case one of them is fixed and the other variable?

**Comment by hbarsnes** [comment]
> but I don't understand the variable N-terminal ones. i guess the pyro-ones are handled by the quick-pyrolidone function, but what happens to the N-terminal acetyl and TMT? why do they end up in the "potential modification motif"? (on a sidenote, the quick acetyl option in X! Tandem only works for something like the first 50 aminoacids in a protein (but don't know the exact number), and is thus not sufficient in our cases. any idea?

The "Quick Acetyl" option (http://www.thegpm.org/TANDEM/api/pqa.html) only covers the protein n-term and should not interfere with your peptide acetylation PTM. (I don't see any limitation to the first 50 amino acids though? But you can always disable the "Quick Acetyl" option in the X!Tandem advanced parameters to be sure.)

If I use the same PTMs as the ones in your screenshot above I get the following:

```
<note type="input" label="residue, modification mass">57.021464@C,229.162932@K</note>
		<note>Carbamidomethylation of C,TMT 6-plex of K</note>
<note type="input" label="residue, modification mass 1">57.021464@C,229.162932@K,229.162932@[</note>
		<note>Carbamidomethylation of C,TMT 6-plex of K,TMT 6-plex of peptide N-term</note>
<note type="input" label="residue, modification mass 2">57.021464@C,229.162932@K,42.010565@[</note>
		<note>Carbamidomethylation of C,TMT 6-plex of K,Acetylation of peptide N-term</note>
<note type="input" label="residue, potential modification mass">15.994915@M</note>
		<note>Oxidation of M</note>
```

Which seems to be correct and in line with your suggestion from TPP? Maybe you were looking at the wrong parameter file?

**Comment by ulriche** [comment]
yep, TMT@K is fixed, TMT@Nter is variable. shall I contact Ron Beavis and
ask to change that so that nter modifications are reported as @[? or can
you? or wouldn't that fix the problem ?

**Comment by ulriche** [comment]
yeah, i noticed that yesterday. with the newer SearchGui the parameter file
looks good. but still didn't get any acetylated or pyro peptides (both with
the quick option). but didn't have time to fully follow up on that yet. but
will tmw.

**Comment by hbarsnes** [comment]
> yep, TMT@K is fixed, TMT@Nter is variable. shall I contact Ron Beavis and ask to change that so that nter modifications are reported as @[? or can you? or wouldn't that fix the problem ?

Would indeed be better to have the terminals annotated differently in the X!Tandem results file, but as this would alter the format I don't find it very likely that Ron Beavis would want to make this change, but feel free to ask him of course. But in any case we'll try to come up with a fix on our side.

**Comment by hbarsnes** [comment]
> yeah, i noticed that yesterday. with the newer SearchGui the parameter file looks good. but still didn't get any acetylated or pyro peptides (both with the quick option). 

Strange. With your settings (i.e. the ptms listed in the screenshot) I get both acetylated peptides and pyro peptides (all three types) with the two quick options turned on for a small TMT test dataset.

**Comment by ulriche** [comment]
i am currently having some other issues too. same file giving different
results (comet) when searched right after each other. maybe a Sunday
phenomenon, no idea. will do some fresh installs tmw just to be sure ...

**Comment by ulriche** [comment]
ok ... can confirm that now SearchGUI 2.3.5 is working now also with both my mgf-files, not sure what went wrong but restarting the computer helped.

I also figured out the different results when using comet. i had one difference in my searches or better peptide shaker imports: The Precursor Accuracy was set in one case to 20ppm and the other time ignored. Thought it shouldn't matter as the search setting was plus/minus 15. Opened a SearchGUI issue: https://github.com/compomics/peptide-shaker/issues/114 - hope it is not just a problem on my side again.

will continue testing X!Tandem as soon as Comet is running for me perfectly again.

On a side note: Also in contact with Jimmy again as depending on the mgf format I am getting different results using comet. He could reproduce that and is currently trying to figure out the problem (mgf #1 has the MS intensity and the 2nd one not; and the first file format has partly charges assigned for the fragment ions).

and sorry for hijacking my own thread.

**Comment by ulriche** [comment]
Running now X! Tandem over night on one of my datasets:

decided to do TMT@Nter and Acetyl@Nter as variable modification but the pyro-ones as "quick pyrolidone" as in the parameter file it looked like that with pyroE/Q/Cm as variable modifications X!Tandem would otherwise search for "-17" and "-18" for all n-termini and not only for the one with N-terminal E/Q/Cm.

fingers crossed, will report later tomorrow - but the parameter file looks really promising!

**Comment by hbarsnes** [comment]
I found and fixed some issues on how we handle the combination of fixed and variable modifications targeting the same terminal residue when parsing X!Tandem results. We will release a new version as soon as we've had the chance to look at the other reported issues.

BTW, please try to keep the issue reports specific to single problems (as far as possible). As otherwise it becomes very difficult for us to keep track of all the issues and to know when to close them...

**Comment by ulriche** [comment]
will give my best - sorry for that.

and big big thanks!

**Comment by hbarsnes** [comment]
The issues should have been fixed with the release of SearchGUI 2.5.0 and PeptideShaker 1.5.0. If not, please open a new issue.

**Comment by ulriche** [comment]
fear the problem is somehow back again - but haven't figured out yet what it is exactly. tried to first rule out that it was linked with the latest X! Tandem release, but it seems it doesn't.

it seems to be linked with the N-terminal modification that I create within the modification editor. somehow the "at peptide or protein N-terminus" is not getting "translated" correctly.

thus I get in the Tandem parameter file:
`... <note type="input" label="residue, potential modification motif">28.0313@</note>
which lacks the "["

can you check if you have the same behavior on your side? or if I am doing something wrong when creating the modification.

thanks.

curiosity question: for which kind of searches do you use the "Dimethylation of peptide N-term K" - so that the dimethyl is fixed to a N-terminal K. wouldn't you expect then both dimethylation of K and N-ter? or is it for something else? or is the "K" accidentally there?

`

**Comment by ulriche** [comment]
forgot ... for the latest SearchGUI (2.7.1) I get endless "Gs" for X! Tandem? any idea why?

![image](https://cloud.githubusercontent.com/assets/13509447/13663053/b6d9297a-e653-11e5-8e28-0c8a20b87310.png)

**Comment by hbarsnes** [comment]
> forgot ... for the latest SearchGUI (2.7.1) I get endless "Gs" for X! Tandem? any idea why?

Don't see the same on my side. Perhaps something special with your input of settings. Maybe you can contact the X! Tandem developers?

> it seems to be linked with the N-terminal modification that I create within the modification editor. somehow the "at peptide or protein N-terminus" is not getting "translated" correctly.

Again, I don't see the this on my side. Only tried with "Acetylation of peptide N-term" so far though. Maybe you could send me your search settings?

> curiosity question: for which kind of searches do you use the "Dimethylation of peptide N-term K" - so that the dimethyl is fixed to a N-terminal K. wouldn't you expect then both dimethylation of K and N-ter? or is it for something else? or is the "K" accidentally there?

I don't think that we use this modification ourselves. All I can do is refer to the Unimod term (http://www.unimod.org/modifications_view.php?editid1=36), and from there it could seem that the 'K' indeed should not be there? I guess it would be the same for "Dimethylation of peptide N-term K 2H(4)" as well then?

**Comment by hbarsnes** [comment]
> for the latest SearchGUI (2.7.1) I get endless "Gs" for X! Tandem? any idea why?

BTW, is this when running X! Tandem or when processing the results?

**Comment by ulriche** [comment]
when running XTandem

**Comment by ulriche** [comment]
can you test again with a NEW nterminal modification and then check the X!
Tandem parameter file? it worked for me for the ones that where in, but not
the one i created new. but will try again later today and on another
computer.

**Comment by ulriche** [comment]
finally found time to look into this again ...

when I use the dimethylation options that "ship with" SearchGUI (eg. 2H(6)), all is good:
![image](https://cloud.githubusercontent.com/assets/13509447/13680632/54a03d92-e6ae-11e5-80dc-74d2ccbe00ad.png)
Note that we have three separated searches (as intended): "modification mass, modification mass 1, and modification mass2"".

but as soon as I create a NEW N-terminal dimethylation modification - e.g. the following:
![image](https://cloud.githubusercontent.com/assets/13509447/13680963/c7168894-e6af-11e5-8da0-d663871a5f98.png)

then the X! Tandem parameter file looks like this:
![image](https://cloud.githubusercontent.com/assets/13509447/13680902/835c942c-e6af-11e5-93bc-2cbe9432b060.png)
Note: we only have one "separate search", and the acetylation is now a "potential modification". which is somewhat ok, but the N-terminal dimethylation is now a "potential modification motif", and I guess more important, it lacks the "[" after the "@".

and X! Tandem gives me within the SearchGUI window all the "Gs"
![image](https://cloud.githubusercontent.com/assets/13509447/13680919/99f0d130-e6af-11e5-9ced-cc630457a681.png)
but I think that is may due the messed up modification motif - potentially at least (I don't get it when using the internally saved N-terminal 2H(6) modification.

thus I assume it is rather a SearchGUI problem at the "modification creation" stage, and not really a X! Tandem problem, no? but I can definitely contact the X! Tandem people if we think the problem is on their side.

cheers and thanks, hope my screenshots help
u

**Comment by hbarsnes** [comment]
> thus I assume it is rather a SearchGUI problem at the "modification creation" stage, and not really a X! Tandem problem, no? but I can definitely contact the X! Tandem people if we think the problem is on their side.

It was a bug in how we handled terminal user PTMs without a specific target. Has now been fixed. Still don't get why this would result in the endless G's printed by X! Tandem though, probably some debug code inside X! Tandem (and I did check that I also got these when running X! Tandem outside SearchGUI, so clearly from X! Tandem and not from SearchGUI), but I guess it does not matter as they are gone after fixing the SearchGUI issue.

I will try to get the time to release a new version tomorrow, just need to finish this one first: https://github.com/compomics/searchgui/issues/95.

Note that you will have to recreate the user PTMs with this issue to fix the problem.

**Comment by ulriche** [comment]
i should add one more thing ... I know PS doesn't support MS1 quantitation, but it would be still great if it would be possible to evoke e.g. in X! Tandem and Comet (for the two I know it is possible), that let's say dm0@K and dm0@Nter are searched together, and dm6@K and dm6@Nter likewise. do you see a way to implement that?

**Comment by hbarsnes** [comment]
> I know PS doesn't support MS1 quantitation, but it would be still great if it would be possible to evoke e.g. in X! Tandem and Comet (for the two I know it is possible), that let's say dm0@K and dm0@Nter are searched together, and dm6@K and dm6@Nter likewise. do you see a way to implement that?

I think X! Tandem is the only search engine supporting something like this. That is if you mean something similar to the SILAC strategy shown here:http://www.thegpm.org/TANDEM/api/rmm.html?

But in any case, I don't see us implementing support for this in the near future. Does not make all that much sense until we also support MS1 quantification?

**Comment by ulriche** [comment]
think comet can also do it with the binary groups - see http://comet-ms.sourceforge.net/parameters/parameters_201502/variable_mod01.php (very bottom)

but your point is totally valid of course. maybe an easier solution: would it be possible to include something like a "Checkpoint" before the actual searches start. So more or the less right after all the parameter files are written, but before the searches are started? So that I could check the parameter quickly, and if needed, e.g. adapt them (ie use options that are not covered by SearchGUI)?

**Comment by hbarsnes** [comment]
> think comet can also do it with the binary groups - see http://comet-ms.sourceforge.net/parameters/parameters_201502/variable_mod01.php (very bottom

Yup, you're right. I forgot about that one.

> but your point is totally valid of course. maybe an easier solution: would it be possible to include something like a "Checkpoint" before the actual searches start. So more or the less right after all the parameter files are written, but before the searches are started? So that I could check the parameter quickly, and if needed, e.g. adapt them (ie use options that are not covered by SearchGUI)?

Sounds like a very customized setup for something that most users won't need. An easier solution that you can already try out is to start the search as normal and then cancel it has soon as the wanted search engine has started. You can then inspect or alter the parameter files and then run the search engine via the command line instead. The exact command line to use will have been printed to the SearchGUI log file. I agree that it's not a very generic or user friendly solution, but at least it should give you the ability to test some more uncommon setups? And the results should still be compatible with PeptideShaker.

**Comment by ulriche** [comment]
if that works, that is definitely good enough for me right now ... will
definitely give that a try.
