### ISSUE TITLE
Search parameter getting "emptied"

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#73]
Maybe it is a problem with my parameter files, but since I can include also peptide shaker parameters, I frequently end up with empty parameter files. so what I mean, after e.g. saving my search settings, and changing the advanced settings in X! Tandem, my SearchGUI settings get emptied (e.g. link to choosen database gets lost), same happened also with MS-GF+ or Comet, but less frequently. but could easily be a local problem here, just wondering if you or someone noticed something similar (or if there is a known way already how to avoid it). all the best, u

**Comment by hbarsnes** [comment]
Hi Ulrich,

I can confirm that I have the same bug on my side. We'll fix it in the next release.

Best regards,
Harald

**Comment by ulriche** [comment]
Hi Harald,

thanks for checking. got a bit worried that I am doing something just
stupidly wrong. Good to hear.

all the best and happy holidays

u

**Comment by hbarsnes** [comment]
The issue has been fixed with the release of SearchGUI 2.3.0. Please let us know if this is not the case and we'll reopen the issue.

**Comment by ulriche** [comment]
awesome. thanks guys!!!
