### ISSUE TITLE
SearchGUI 2.3.0 and Comet - no mgf to ms2 anymore?

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#74]
Heyjo,

is the new SearchGUI handling the mgf files differently now for Comet? i can successfully load (and convert to ms2) them with the old SearchGUI (2.2.2), but not with the new SearchGUI (2.3.0) . Is it trying now to read the mgf direcetly? I am getting things like:

- Load spectra:Malformed MGF spectrum entry. Exiting.
line :###FS:    #m/z: 231.95664 #charge   1
Mon Dec 28 13:49:22 PST 2015        Comet finished ...

with the new one but not with the old one which runs smoothly.

Converting spectrum file 1502_UE_..._1117.mgf for Comet/Tide.
Processing 1502_UE_..._1117.mgf with Comet.

hope you can help and that it is a small thing to fix. all the best from Austria,
u

**Comment by hbarsnes** [comment]
Hi Ulrich,

Yes, as the later Comet versions supports mgf directly we decided to skip the mgf to ms2 conversion. The goal being to remove any issues that could occur in the conversion. But if Comet has problems reading certain mgf files I guess we can look into making it possible to turn the conversion on or off in the advanced Comet settings (we still need it for Tide anyway, so the code is still there).

It works fine on our test mgf file though, so maybe you should contact Jimmy once again? Seems like the Comet mgf parser is just not ignoring the comment lines in your mgf file? How was the mgf file created?

Best regards,
Harald

**Comment by ulriche** [comment]
hmmm ... mgf is directly from the Bruker Impact Data Analysis software, and
indeed comet had initially an issue with some empty lines in it, but this
got resolved just recently, at least I didn't have problems when testing it
with comet in standalone.

comet release notes:

   - http://comet-ms.sourceforge.net/release/release_201502/

with that release it perfectly worked and I guess SearchGUI is using the
latest one. so not fully sure what the current problem is,.I am still on my
extended xmas family visiting tour, and thus not sure when I find the time
to check this. but will use the 2nd last SearchGUI version for now, and
will let you know when I know more. sounds reasonable?
u

PS: totally agree that if comet supports mgf directly, why not using mgf
directly. can be only a minor hick-up that I encounter right now.

**Comment by hbarsnes** [comment]
Yup, SearchGUI is using the latest Comet release. (But not the beta release you got directly from Jimmy though.)

**Comment by ulriche** [comment]
will double check (but not today) but thought the beta release was only
about the different Isotope ranges and that the last official comet release
could handle our mgfs already. but will try to start a quick search
tomorrow morning ideally.

**Comment by ulriche** [comment]
double checked now (couldn't wait), and indeed, that file also causes the
same problem with comet standalone. will have to check with jimmy - not
sure right now if it is the respective file or something else, but I was
sure this file worked at some point. will keep you posted, u

**Comment by hbarsnes** [comment]
The mgf parsing issues should have been solved in the new Comet maintenance release included in SearchGUI v2.3.5. If this is not the case please let us know and we'll reopen the issue.
