### ISSUE TITLE
MS Amanda and LysN or LysargiNase: Cannot digest database.

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#75]
maybe I am doing something wrong, but do LysN or LysargiNase work for you with MS Amanda? ArgC and GluC do, but the other two fail:

###
Searching file '1502_UE_xxx_1128.mgf'...
  Searching spectra 1 - 4000 of 67340 spectra
     Starting search against fwd database
     Loading database
Cannot digest database C:\...\00_db\UP_1511_human-can_concatenated_target_decoy.fasta
Loading database failed.
Search failed.
###

same error for LysN and LysargiNase, but GluC and ArgC run smoothly. Same behavior on your side?

**Comment by ulriche** [comment]
same problem with Asp-N and Asp-N (DE). No issue for CNBr, Chymotrypsin, Formic Acid, and Lys-C (e.g.).

**Comment by hbarsnes** [comment]
I can confirm that I get the same errors. None of the enzymes cleaving n-terminally to the targeted amino acid(s) seem to work in MS Amanda for some reason. In the MS Amanda log file (located in C:\ProgramData\MSAmanda\Logs) I see the following error message: "parsing "(?=[RK]" - Not enough )'s". Not that that tells me much... I'll contact the MS Amanda developers and get back to you.

**Comment by hbarsnes** [comment]
You can follow the reply from the MS Amanda developers here: https://groups.google.com/forum/#!topic/msamanda/wncHrV_JO7Y.

**Comment by ulriche** [comment]
cool, thanks.

**Comment by hbarsnes** [comment]
Update from the MS Amanda developers: 
 "there was a bug when using n-terminal enzyme digestion without any cleavage inhibitors. Thanks a lot for reporting this bug! It will be fixed in the next MS Amanda version!"

We will update the MS Amanda version in SearchGUI as soon as the new version is available.

**Comment by ulriche** [comment]
sounds great ... thanks for figuring that out

**Comment by hbarsnes** [comment]
Should be fixed in SearchGUI v2.6.0. If not, please let us know and we'll reopen the issue.
