### ISSUE TITLE
Comet's "Isotope Number -1" (Follow up of Issue #69)

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#77]
I thought that issue got resolved already, but it seems not or only partly... as comet reports also PSMs with an "Isotope Number" of "-1", and as e.g. MSGF+ also allows for it, I think it would be great if Peptide Shaker would report "-1" PSMs as "-1" and NOT as "0" with an extremely large "ppm" off-set. or is there something going wrong only on my side?

**Comment by ulriche** [comment]
along the line: is it possible that when I define the Isotope Range as 0-2 in SearchGUI that my "-1" get reported as "0", and my "+3" get reported as "+2"? (not sure if it is now a SearchGUI or PeptideShaker issue anymore)

**Comment by mvaudel** [comment]
You are correct this should have been taken care of when adding the
isotopes to the search parameters. If you search with -1 +2 the reported
isotopes should go between -1 and +2. Indeed if you set your parameters to
0-2 the software will not look for -1 and +3 and take the closest neighbor
:)

2016-01-19 5:16 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
but i can't set it -1 in SearchGui, can I? in my case the ok button gets
grayed out then, no?

**Comment by mvaudel** [comment]
Indeed, we require that it is a positive number. I will correct this. Sorry
for the inconvenience, since this setting does not make much sense I did
not test it :)

2016-01-19 17:29 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

> but i can't set it -1 in SearchGui, can I? in my case the ok button gets
> grayed out then, no?

**Comment by ulriche** [comment]
thanks man ... and no worries ... but this way you could implement now a
PeptideShaker filter to kick the "-1" out, right? ;-)

i don't mind having them in or not, still not sure what is better. just
didn't like them to be "0" with a huge ppm-error

big big thanks, really appreciated

**Comment by mvaudel** [comment]
A fix allowing the search with -1 is now implemented, and will be released
soon. I still need to work on the filtering :)

Best regards,

Marc

2016-01-19 18:14 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
thanks already!!!

**Comment by ulriche** [comment]
just tried the "-1" option for my comet results (Peptide Shaker 1.5.1 beta) - and voilà, worked perfectly.

nearly exactly the same results as with PS 1.4.0 but without any crazy ppm errors, all nicely within plus/minus 15ppm.

that's awesome!!!

**Comment by ulriche** [comment]
looking forward to the filtering option! :-)

**Comment by hbarsnes** [comment]
Import filters have been added in PeptideShaker v1.6.0. Please let us know if it does not work as wanted.
