### ISSUE TITLE
SearchGUI and Peptide Shaker don't start after updating Java to 8.71 (from 8.66)

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#79]
Maybe it is something specific with my computer here but after updating Java to 8.71 (from 8.66) both SearchGUI and PeptideShaker didn't start anymore. But after deinstalling 8.71 and installing 8.66 again, both worked perfectly fine again.

I also tried to do a fresh install of  PeptideShaker (1.4.0) when I had Java 8.71 installed, but that also didn't work.

**Comment by hbarsnes** [comment]
Works fine on my side after updating to Java 1.8.0_72 (8u72). No problems with 1.8.0_71 (8u71) either. Did you see any errors or did the tools simply not start? Do you see anything in the log files (resources/SearchGUI.log and resources/PeptideShaker) or in the startup logs (resources/conf/startup.log)?

Maybe something went wrong with the Java update? Perhaps you could try installing the new version once more and see if that solves the problem?

**Comment by ulriche** [comment]
interesting ... i just updated again (Version 8 Update 71 build 1.8.0_71-b15), restarted the system, and again it doesn't work.

I don't see any errors, the tools just don't start. i will try 1.8.0_72 next - if i find that one (the java console downloaded the other one).

**Comment by ulriche** [comment]
also tried 1.8.0_72 - did also not work.

but when I installed 8.66 again - it worked right away.

**Comment by ulriche** [comment]
ok - finally understand it. guess it is my fault.

when installing 8.72 it automatically deinstalled 8.66 -thus SG and PS couldn't start anymore. but when I installed 8.66 again, I could start them, and change within the GUI the java settings to point to 8.72, and now it works also from there.

makes sense somehow (but is there a way to change the java setting outside of the console, or is that a rather untypical behavior of java to deinstall the older version? it kept now e.g. both 8.71 and 8.71).

**Comment by hbarsnes** [comment]
Aha. I see what you mean. You've told SearchGUI and PeptideShaker to use a certain Java version and now that Java version cannot be found anymore. I will look into if it's possible to default to using a different Java version if the one set in SearchGUI or PeptideShaker cannot be found.

**Comment by ulriche** [comment]
thanks already ... but don't think it is a big issue as typically the old
versions stay.

**Comment by hbarsnes** [comment]
Fixed with the release of SearchGUI 2.5.0 and PeptideShaker 1.5.0.

**Comment by ulriche** [comment]
awesome!

**Comment by ulriche** [comment]
fear i had the same problem today again - after my java update 8.72 was gone and thus both SearchGUI and PeptideShaker were not starting again. but maybe it is because i set it to 8.72 after the last time and thus the automatic check for another Java Version didn't happen?

the weird thing was, that the 8.72 folder was still there but empty.

**Comment by hbarsnes** [comment]
I think we only check if the Java folder exists. If you delete the empty folder it should therefore be ok. But I'll look into if it's possible to also check the content of the folder as well.

**Comment by ulriche** [comment]
makes sense - the weird thing is I didn't delete the folder content, it
must have happened during the java update.

think it is not a big issue because it is something that shouldn't happen,
and what I have never seen before (could it be e.g. that it couldn't fully
delete the folder as SearchGUI blocked access to it?)

**Comment by hbarsnes** [comment]
Fixed in SearchGUI 2.7.0 and PeptideShaker 1.8.0.
