### ISSUE TITLE
X!Tandem parameter file: lysargiNase cleavage site definition

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#81]
Hey guys,

not fully sure if it is really a problem or not, but I noticed that when using lysargiNase in X! Tandem, the  "cleavage site" definition in the parameter file looks like that:
***\<note type="input" label="protein, cleavage site">|[RK]\</note>***

is the [X] before the pipe not needed to indicate cleavage after any residue? the thing is that my X! Tandem results are very poor (also compared to Comet), thus I am trying right now to figure out what is going wrong.

hope you can help
u

**Comment by hbarsnes** [comment]
Yes, this is wrong and has now been corrected. In the new version it will show [X]|[RK]. A new version will be released shortly.

**Comment by ulriche** [comment]
cool cool ... hope that fixes my low ID rate a bit. fingers crossed ...

**Comment by hbarsnes** [comment]
Should be fixed in SearchGUI v2.6.0. If not, please let us know and we'll reopen the issue.

**Comment by ulriche** [comment]
it definitely did - thanks for the fix!
