### ISSUE TITLE
X!Tandem parameter file - uncalled parameter

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#82]
a small thing that I noticed but not too important  ...

for X! Tandem you allow in the advanced settings to set a "E-value Cutoff"
http://www.thegpm.org/TANDEM/api/omvev.html

but as you set the "output, results" parameter to "all" (and not e.g. "valid")
http://www.thegpm.org/TANDEM/api/oresu.html

it is not used I think.

**Comment by hbarsnes** [comment]
Ah, yes, you are right. It seems like this has been changed since we first implemented support for X!Tandem many years ago. We'll look into adding support for "valid" and "stochastic" so that the e-value cutoff can be used.

**Comment by ulriche** [comment]
cool cool ... on a sidenote: while using TPP we also always used "all" for
the export and allowed PeptideProphet to do the evaluation part.

**Comment by hbarsnes** [comment]
In SearchGUI v2.6.0 one can now select the results output type in the X!Tandem advanced settings and if anything but "all" is selected the e-value cutoff setting will be used.
