### ISSUE TITLE
Cancelling SearchGUI deletes also successfully finished searches

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#83]
Maybe not really an issue but ...

i just cancelled one of my searches. I had set it up to run both X! Tandem and MS Amanda. but while X! Tandem was running, I figured out that I had forgotten to disable the low-ram mode for MS Amanda. So I canceled the SearchGUI run as soon as MS Amanda started. But unfortunately my X! Tandem results that I had seen in a "SearchGUI temp" folder got deleted then. possible? could be nice if they survived the cancelling (but next time I just copy them first - thus not a big deal), but maybe there is also a reason to just wipe them. 

btw. had both "Group Identification Files -> One zip per algorithm" and "Include Date in File Name" set in the advanced settings.

**Comment by mvaudel** [comment]
Hi Ulrich,

You are correct, we assume that when the user cancels the search the results need to be discarded. We can try to look into how to "rescue" partially completed searches, but am not sure how fast we can take care of this.

Best regards,

Marc

**Comment by ulriche** [comment]
good to know ... will just copy it the next time before I delete. not a big
deal, was just wondering if it was intentional.
all the best
u

**Comment by hbarsnes** [comment]
This has been fixed in SearchGUI v2.6.4, where the user will now be asked if partial results are to be kept or not if the user cancels the search. The user will have to move the search results manually before starting a new search though, as otherwise the old results will be overwritten.
