### ISSUE TITLE
Feature Request - Additional enzyme: ArgN

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#84]
Hey Guys,

it seems I need one more enzyme. after more testing it just became more and more evident (and I also somewhat expected it), that lysargiNase doesn't cleave in front of TMT-labeled lysine, thus rendering it to mirror ArgC and not trypsin anymore.

could you introduce ArgN as an enzyme in SearchGUI? will need it only as "semi specific" but guess for consistency also the non-semi would be great.

thanks already
u

**Comment by hbarsnes** [comment]
Sure, no problem. And just to be sure, Arg-N would only cleave n-terminally of arginine right? And with no P-rule I guess?

In other words we'll add:

```
	<enzyme>
		<id> 30 </id>
		<name> Arg-N </name>
		<aminoAcidBefore> </aminoAcidBefore>
		<restrictionBefore> </restrictionBefore>
		<aminoAcidAfter> R </aminoAcidAfter>
		<restrictionAfter> </restrictionAfter>
		<semiSpecific> no </semiSpecific>
		<wholeProtein> no </wholeProtein>
	</enzyme>
	<enzyme>
		<id> 31 </id>
		<name> Semi-Arg-N </name>
		<aminoAcidBefore> </aminoAcidBefore>
		<restrictionBefore> </restrictionBefore>
		<aminoAcidAfter> R </aminoAcidAfter>
		<restrictionAfter> </restrictionAfter>
		<semiSpecific> yes </semiSpecific>
		<wholeProtein> no </wholeProtein>
	</enzyme>
```

OK?

**Comment by ulriche** [comment]
n-terminally of Arg, yep.

i am never too sure about the P-rule thus yep, I would leave it out.

thanks
u

**Comment by hbarsnes** [comment]
Ok, will be included in the next release.

**Comment by ulriche** [comment]
cool, thanks!

**Comment by hbarsnes** [comment]
Arg-N has been added in SearchGUI v2.6.1 and PeptideShaker v1.7.0.

**Comment by ulriche** [comment]
thanks for that - really improved my data. somehow it is crazy, or maybe not, but my data set went from an ID rate of 12.5%  (10k PSMs) to 18% (15k PSMs) with comet.
