### ISSUE TITLE
MSGF+

### ISSUE THREAD

**Issue by ulrich-eckhard** [compomics/searchgui#85]
Hey folks,

having some issues with MSGF+, mainly its rather low ID rate compared to the others (X!Ta, Ms Amanda, Comet). So in my test data sets from today around 10% instead of 20% in the others. thus i started to test the "advanced" settings again, and interestingly, this time some made no difference at all and gave me exactly the same file size at the end and the exact same PSMs after PeptideShaker.

So I varied e.g. the instrument setting, which handles as far as I understand it also MS2 accuracy. Tested three of them, TOF, LTQ, and Orbi - but all gave the exact same result. Then I checked CID vs HCD, and again, exactly the same.

when I did this kind of testing the last time, they all made a difference. but maybe there is also something "special" with these data. just wondering if something is going wrong, especially as my ID rate is currently rather low - especially for LysR and GluC, and especially for the latter it frequently outperformed the others (but with data form an other instrument, so that could be also a reason).

can you look into that? would be great.

PS: I checked of course the SearchGUI report, and at least officially my settings were all set. so e.g. this:

**_Search Parameters:**_
-   PrecursorMassTolerance: 10.0ppm
-   IsotopeError: 0,1
-   TargetDecoyAnalysis: false
-   **_FragmentationMethod: HCD**_
-   **_Instrument: QExactive**_
-   Enzyme: Semi-LysargiNase
-   Protocol: TMT
-   NumTolerableTermini: 1
-   MinPeptideLength: 7
-   MaxPeptideLength: 35
-   NumMatchesPerSpec: 3

gave exactly the same result as:

**_Search Parameters:**_
-   PrecursorMassTolerance: 10.0ppm
-   IsotopeError: 0,1
-   TargetDecoyAnalysis: false
-   **_FragmentationMethod: CID**_
-   **_Instrument: TOF**_
-   Enzyme: Semi-LysargiNase
-   Protocol: TMT
-   NumTolerableTermini: 1
-   MinPeptideLength: 7
-   MaxPeptideLength: 35
-   NumMatchesPerSpec: 3

**Comment by ulriche** [comment]
but maybe it is just a coincidence ... but somehow it 'feels' odd.

but one good news, changing NumTolerableTermini has an effect - so that's good.

maybe MS-GF+ just doesn't like our Bruker Impact II data

**Comment by hbarsnes** [comment]
We haven't really played all that much with the MS-GF+ settings, but from what I can remember the changes were not very big for the settings we (briefly) compared. So feel free to test this in more detail and keep us posted. :)

**Comment by ulriche** [comment]
hmm ... good to know ... it is just that MSGF+ performs really poorly right now on LysR and GluC data, but does reasonable well with ArgC data. but didn't find a real pattern yet.

I somehow think I may just find too many decoys, as my ID rate for MSGF+ goes significantly up when importing the results from Comet, MSGF+, MsAmanda and X!Tandem at the same time.

what would be the best way to test that via SearchGUI - exporting all PSMs? so also the unvalidated ones and decoy ones and check/compare there?

in the past MSGF+ alsways performed great on our data, but these were on Orbitrap instruments (XL, Velos, QExact) and not on the Impact II.

**Comment by hbarsnes** [comment]
It could of course also be that we use MS-GF+ slightly differently than you did before, or that the MS-GF+ version in SearchGUI is not the same as the one you used before. And you should not rule out parsing issues when reading in the MS-GF+ mzIdentML file in PeptideShaker. Would be great if you could research your older data where you saw the bigger differences before? Just to check that this is still the case in the new setup? The exact MS-GF+ command lines are printed to the SearchGUI log file, So should be easy to compare to your previous command lines to detect difference?

**Comment by ulriche** [comment]
i will keep my eyes open ...  guess i should try the "TPP" route once to get a better comparison with my old data. maybe I find the time next week.

i am just really surprised - e.g. i get e.g. with Comet ID rates of 18% but for MSGF+ only 5% - I never had such a discrepancy. but i could really be the different instrument of course. i didn't spot anything obvious yet regarding parsing. and I will try to check the MS-GF+ options a bit more. and so far it looks "comparable" for ArgC but really bad for GluC and LysR - also something I don't fully grasp.

will give my best to find some time for some more thorough testing.

**Comment by ulriche** [comment]
... still not much success but stumbled over the following:

> In the Spectrum ID tab, you can thus see, for every match of every search engine, the search engine score and its associated PEP. Note that for the sake of readability, we don't display the raw score but -10.log(score) where log is base 10, and we set a maximum of 100
from: https://groups.google.com/forum/#!topic/peptide-shaker/8ChJOQ24mZY

could that explain my lower results for MSGF+ than e.g. Comet if the cut-off of 100 is too low for the MSGF+ scores? 

I had noticed already before that my scores (PSM Feature export after Peptide Shaker) in MSGF+ results are much higher than in Comet or any of the other search engines that I have tried so far (X! Tandem, Ms Amanda).

e.g.
- MSGF+: minimum Score: 75.36 vs. 6.04 in Comet. Maximum of course for both 100. Median for MSGF is 100, for Comet 40.32, and the average 96.06 for MSGF and 46.13 for Comet.
- when looking at the "Raw Score", the corresponding scores in MSGF range from 2.9x10-8 to 5.1x10-31, whereas in Comet they range from 2.5x10-1 to 2.02x10-25.
- and when I recalculate the Score (-10xlog(score) but don't set a maximum of 100, then my average for Comet is 48.30, but for MSGF it is 116.69.

thus I am really wondering if the cut-off of 100 punishes the "good" identifications of MSGF+? Or is it just a score that I see on the screen/export, but is actually not used for anything?

**Comment by mvaudel** [comment]
Hi Ulrich,

Yes, this log transformed score is only used for the display and export,
not for the internal processing where we use the score as provided by the
search engine. There should thus not be any bias or thresholding effect.

I can give a look at whether there are some limitations due to the capacity
of the object we use to store the score in, until now we have never seen
the need to estimate error rates at e-value < 1E-100 and assumed that
search engines would not give such good scores to false positives.

Best regards,

Marc

2016-02-07 2:51 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by ulriche** [comment]
good to know ... was just wondering.

Maybe MsAmanda is the "best" search engine to test it as the raw scores are even lower there ...

e.g. if I export all PSMs - so Confident/Doubtful/NotValidated and include all Decoys, I get for MsAmanda the following (for approx. 40000 PSMs):

- 16k confident: Raw scores from 1.72E-14 to 4.1E103; Scores from 100 to 100; Confidence from 77 to 100.
- 1k doubtful: 2.2E-10 to 9.51E-43; Scores from 97 to 100; Confidence from 57 to 100
- 23k not validated: 9.77E-1 to 5.22E-18; Scores from 0.1 to 100; Confidence from 0.0 to 95.09

for a decoy, my "lowest" raw score was 8.75E-27 (reported score of 100, calculated to be 260.6). so far away from the E-100 that you allow for.

**Comment by mvaudel** [comment]
Mmmmh these are very very low scores. I will ask Viktoria about it, maybe
it has something to do with the search.

2016-02-09 0:44 GMT+01:00 Ulrich Eckhard <notifications@github.com>:

**Comment by hbarsnes** [comment]
Hi Ulrich,

MS-GF+ has now become open-source and set up as a GitHub project: https://github.com/sangtaekim/msgfplus. So if you're still having problems with MS-GF+ I would recommend setting up an issue there?

And if you're still concerned about the low scores for MS Amanda I would recommend adding a new comment on their Google Group: https://groups.google.com/forum/#!forum/msamanda.

I will now close this issue, but feel free to open a new one if you come across other problems.

Best regards,
Harald
