### ISSUE TITLE
Comet: add more out parameters

### ISSUE THREAD

**Issue by wenbostar** [compomics/searchgui#87]
Hi,
Is it possible to make the command line of SearchGUI (eu.isas.searchgui.cmd.IdentificationParametersCLI) to support to set the following parameters of comet?
![image](https://cloud.githubusercontent.com/assets/5302110/12923379/7a687f4c-cf90-11e5-9d44-edddc6b02fe3.png)

Thanks a lot and best regards!
Bo

**Comment by hbarsnes** [comment]
Hi Bo,

I will add it to our feature request list. I'm not sure when we'll get the time to implement it though, but it should not be too difficult.

Best regards,
Harald

**Comment by wenbostar** [comment]
Hi Harald,
Great. Thanks a lot.
Best regards!
Bo

**Comment by hbarsnes** [comment]
Hi Bo,

In SearchGUI 2.7.0 the Comet output format can now be changed in the Comet advanced settings dialog.

Best regards,
Harald
