### ISSUE TITLE
Comet: description of parameter "-comet_num_ptms" 

### ISSUE THREAD

**Issue by wenbostar** [compomics/searchgui#88]
Hi,
Is the description of parameter "-comet_num_ptms" right?
![image](https://cloud.githubusercontent.com/assets/5302110/12923490/e7bdb09e-cf90-11e5-8011-5579f205b39b.png)
It's from version SearchGUI-2.6.3.
Best regards!
Bo

**Comment by hbarsnes** [comment]
Hoi Bo, 

No, this is clearly not correct. Thanks for letting us know. You can provide any positive integer value. The default value is 10. I will correct it in the next release (and on the wiki). 

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Bo,

The issue has been corrected in the new releases.

Best regards,
Harald

**Comment by wenbostar** [comment]
Great. Thank you very much.
Best regards!
Bo
