### ISSUE TITLE
Update X!Tandem to VENGEANCE (2015.12.15)

### ISSUE THREAD

**Issue by wenbostar** [compomics/searchgui#89]
Hi,
Is it possible to update X!Tandem to the latest version: VENGEANCE (2015.12.15)? There are several updates for this version.

http://www.thegpm.org/tandem/release.html 
![image](https://cloud.githubusercontent.com/assets/5302110/12938161/ee667c50-cfea-11e5-9f2a-8860dcf44079.png)

Best regards!
Bo

**Comment by hbarsnes** [comment]
Hi Bo,

Updating to the latest X!Tandem version will happen soon. However, we will most likely not implement all of the new features as not all of these are supported within the SearchGUI structure. Are there any of the new features you are particularly interested in?

Best regards,
Harald

**Comment by wenbostar** [comment]
Hi Harald,
Thanks a lot. I'm interested in the parameter of the maximum number of variable modification and the limit for peptide length.
Best regards!
Bo

**Comment by hbarsnes** [comment]
Ho Bo,

SearchGUI 2.7.0 now includes the latest X! Tandem version. Note that X! Tandem no longer releases 32 bit versions, so only the 64 bit versions have been updated.

Best regards,
Harald

**Comment by wenbostar** [comment]
Hi Harald,
Thank you very much.
Best regards!
Bo
