### ISSUE TITLE
Missing iTRAQ-115 reporter peaks

### ISSUE THREAD

**Issue by LZwart** [compomics/searchgui#90]
I am trying to analyse data from an 8-plex iTRAQ experiment with SearchGUI (2.6.1 and/or 2.6.4). I have attempted the analysis with MSGF+, X!TANDEM and ANDROMEDA search engines, leaving most of the default settings unchanged. 

When I viewed the results with PeptideShaker (1.7.1 and/or 1.7.4) and Reporter (0.2.13), I noticed that absolutely none of the identified proteins have iTRAQ-115 reporter ion peaks (regardless of the search engine used). When exporting the protein report from Reporter, the 115 sample ratio values are all 0 or NaN. I find this quite bizarre, since the sample labelled with the 115 tag is one of three biological replicates within the experiment, and the others are apparently detected. 

The data have also been analysed with MASCOT (by BGI), which was apparently able to detect the iTRAQ-115 reporter ions. This indicates that it is unlikely to be a problem with labelling of the sample.

I'm not sure if the problem is caused by a bug in the software or whether I've overlooked something critical.

Any suggestions?

**Comment by hbarsnes** [comment]
Hi,

Thanks for telling us about this. It's been a while since we processed iTRAQ data (we've switched to TMT ourselves), so there might be some detail we have forgotten to update. Would it be possible for you to share your iTRAQ data so that we can try to reproduce and hopefully fix the problem?

Best regards,
Harald

**Comment by LZwart** [comment]
Hi, Harald.

The .mgf file and the database that I've been using can be found here:
https://drive.google.com/folderview?id=0BxAv_RZ63HPvSENCM0RsMFFfems&usp=sharing.
Please let me know if you need any additional information.

All the best
Lizahn Zwart

On 10 February 2016 at 14:53, Harald Barsnes <notifications@github.com>
wrote:

> Hi,
>
> Thanks for telling us about this. It's been a while since we processed
> iTRAQ data (we've switched to TMT ourselves), so there might be some detail
> we have forgotten to update. Would it be possible for you to share your
> iTRAQ data so that we can try to reproduce and hopefully fix the problem?
>
> Best regards,
> Harald
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/compomics/searchgui/issues/90#issuecomment-182359519>.
>

-- 
This message and attachments are subject to a disclaimer. Please refer to 
http://www.it.up.ac.za/documentation/governance/disclaimer/ for full 
details.

**Comment by mvaudel** [comment]
Dear Lizahn,

It seems that Reporter is not picking your peaks, this can be due to a too
narrow tolerance in the reporter ions selection.

When creating the Reporter project, can you edit the quantification
settings, then go to "Reporter Ions" and adjust the "Reporter Tolerance
(m/z)" to the resolution of your measurement?

Sorry that the tool does not do it automatically at the moment, Reporter is
still in beta testing :-)

Hope this helps,

Marc

2016-02-10 15:11 GMT+01:00 LZwart <notifications@github.com>:

**Comment by LZwart** [comment]
Hi, Marc.

Thanks for the suggestion. I've changed the reporter tolerance from 0.0016 to 0.05 and it seems to make a difference, although most of the 115 ratios are still 0. Would you recommend another approach in addition to using Reporter? I find it quite useful so far, but it's always good to have something for comparison.  

I have been playing with the PeptideShaker output and when zooming in to the reporter region, I noticed a greyed-out peak that I think corresponds to the position of the iTRAQ-115 reporter. So it seems to be a problem with SearchGUI/PeptideShaker as well?

![grey peak](https://cloud.githubusercontent.com/assets/17159370/12950240/cae45ea8-d014-11e5-92d0-12e2f40fa006.png)

**Comment by mvaudel** [comment]
Hi again,

Indeed there was an error in our code for this ion. New versions will be
released very soon with a fix. Apologies for the inconvenience!

As alternative, the software coming with your instrument might support
iTRAQ quantification. Among academic software, MaxQuant, OpenMS, and the
TPP all support this technique :)

Best regards,

Marc

2016-02-10 16:30 GMT+01:00 LZwart <notifications@github.com>:

**Comment by LZwart** [comment]
That's great, thanks a lot for your help! :-)

**Comment by hbarsnes** [comment]
Hi Lizahn,

New versions of SearchGUI, PeptideShaker and Reporter have just been released which should fix the above problem. If you still experience any issues, please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by LZwart** [comment]
Hi, Harald and Marc

Thanks a lot for fixing the problem so quickly. I'll be repeating the analysis at once. 

All the best
Lizahn
