### ISSUE TITLE
Minor Fix needed for Dimethylation of K 2H(4)

### ISSUE THREAD

**Issue by ulriche** [compomics/searchgui#92]
Hey guys,

the modification "Dimethylation of K 2H(4)" is missing the "carbons" i fear.

![image](https://cloud.githubusercontent.com/assets/13509447/12987846/caa5a52a-d0b2-11e5-9abc-ba2c6d315987.png)

or wait, I guess it is one of the "silac K" ... but definitely something wrong here

**Comment by hbarsnes** [comment]
Maybe you're looking for a different modification, as this one maps to this Unimod entry: http://www.unimod.org/modifications_view.php?editid1=481. Seems ok to me?

**Comment by ulriche** [comment]
yep, it maps there ... but it is called dimeth4 and should be "4,4,5,5-D4 Lysine".

it is not a "dimethylated" K - it is "just" a "heavier" K, no?

**Comment by ulriche** [comment]
it is not a big thing, just thought it might be confusing ...
especially as the two namesakes are actually extra dimethyls!

![image](https://cloud.githubusercontent.com/assets/13509447/12990727/b72c7eca-d0c0-11e5-9779-041b8e4f4315.png)

**Comment by hbarsnes** [comment]
Yup, I agree, the name seems incorrect. I will double check with Marc. Probably an error from when we renamed all the modifications a while back.

**Comment by ulriche** [comment]
cool, thanks already.

**Comment by hbarsnes** [comment]
The modification has now been renamed "Label of K 2H(4)". This will hopefully reduce the confusion. :)
