### ISSUE TITLE
Using OpenMS FileConverter

### ISSUE THREAD

**Issue by Leprevost** [compomics/searchgui#93]
Hi,
Is it possible to add OpenMS FileConverter to do file conversion on Linux? I'm not talking about RAW files, just conversion between formats like mzXML/mzML to mgf. Since these formats are common, it would be great to have a tool like that available with SearchGUI.
Thanks!

**Comment by hbarsnes** [comment]
Hi,

Not really sure why you'd need OpenMS FileConverter for converting mzXML/mzML to mgf on Linux? You should already be able to do this with ProteoWizard if you install the Linux version? You won't be able to convert the vendor formats, but as neither mzXML nor mzML (or mgf for that matter) are vendor specific formats, conversion to mgf should be fine.

I've never tested this myself though, so I cannot guarantee that it'll work. So it would be great if you could give it a go and let us know if we need to make any changes in SearchGUI, or if there are any other limitations stopping this from working.

Best regards,
Harald

**Comment by Leprevost** [comment]
Hi @hbarsnes, thanks for the quick reply;

I tried to download and use ProteoWizard as SearchGUI suggests me (after setting a folder with mzXML files), but I always get this error message: 
    "The selected folder is not a valid ProteoWizard folder!". 

And since the msconvert tool only has the windows logo on it I concluded that it was not going to work on Linux. So What I normally do before using SearchGUI is to run the OpenMS program to convert between the formats. 

I guess by what you are saying is that ProteoWizard should be working on Linux too, right? So I could be doing wrong ? I'm downloading the '64 bit Linux version for end users', is that correct?

regards

**Comment by hbarsnes** [comment]
> I guess by what you are saying is that ProteoWizard should be working on Linux too, right? So I could be doing wrong ? I'm downloading the '64 bit Linux version for end users', is that correct?

Yes, at least that was what I thought (for non-vendor files). Especially given that they have a Linux version. And yes, the '64 bit Linux version for end users' should be the right one.

> And since the msconvert tool only has the windows logo on it I concluded that it was not going to work on Linux.

Originally this was only intended for the conversion of vendor raw files, and in these cases Windows is required. I guess one can argue that this is still the case for the complete conversion support. But we will consider changing it if non-vendor files can be converted on Linux (and OS X).

> but I always get this error message:  "The selected folder is not a valid ProteoWizard folder!".

It seems like we only check if the folder contains 'msconvert.exe'. But I see now that on non-Windows platforms it is simply called 'msconvert'. I will fix this in the next release. In the mean time it would be great if you could verify that the conversion to mgf works as wanted on Linux?

**Comment by hbarsnes** [comment]
> In the mean time it would be great if you could verify that the conversion to mgf works as wanted on Linux?

By using the msconvert command line directly I mean, see http://proteowizard.sourceforge.net/tools/msconvert.html.

**Comment by hbarsnes** [comment]
Here's a beta version that ought to allow you to use ProteoWizard conversion on Linux (and OS X) for the non-vendor file formats: https://www.dropbox.com/s/rto7ybkn0d3f8q7/SearchGUI-2.6.6-beta-mac_and_linux.tar.gz?dl=0

Please let me know if it works as wanted.

It would also be great if you could test what happens if you try to convert a vendor specific raw file? Hopefully you will get a meaningful error message.

**Comment by Leprevost** [comment]
I downloaded the beta version and downloaded ProteoWizard as indicated but still got the same error. Just as a test I changed the name of the binary to msconvert.exe, then it worked. I set a test analysis but just after pressing 'Start the Search' I got an error popup saying:

"An error occurred, if the problem persist contact the developers"

**Comment by Leprevost** [comment]
I changed the name of the binary back again to msconvert and opened SearchGUI again, then it loaded with ProteoWizard, with no errors. I added all the files for the analysis and then it started normally with the file conversion.
You probably have the binary name set twice on the source code, once when loading the folder and once when executing the program.

**Comment by hbarsnes** [comment]
Ah, yes, there was a second reference to 'msconvert.exe' that I forgot to change. There was one in the MSConvert Settings dialog and one in the ProteoWizard Settings dialog. The first was corrected while the second was not. Will be fixed in the next release. But great to hear that the conversion seems to work.

**Comment by Leprevost** [comment]
Yeah, Thanks for helping!

**Comment by hbarsnes** [comment]
SearchGUI 2.7.0 has now been released containing the same fix as in the beta version, plus the second reference to 'msconvert.exe' has been corrected as well.
