### ISSUE TITLE
Add modifications to SearchGUI 

### ISSUE THREAD

**Issue by getiria-onsongo** [compomics/searchgui#96]
Could you please add the following modifications to SearchGUI? 

1. Dimethylation of peptide N-term, +28.0313 Da

2. Dimethylation of K 2H(6)13C(2), +36.07567 Da

We would like to search data from an experiment where dimethylation reaction was used to label peptides with either light or heavy tags, and the dimethylated sites could be only on peptide N-terminus or on both N-terminus and K, based on different reaction chemistry. To perform a search, we need the above two modifications (for both variable and fixed modifications).

Thank.

**Comment by hbarsnes** [comment]
Hi,

We've now added the two requested modifications. If you update your SearchGUI version you should see them.

Note that you can always add your own modifications if there are special modifications that we have not included. You can do this via Edit > Modifications in the main SearchGUI dialog, then click Add in the User Modifications tab at the bottom.

Best regards,
Harald
