### ISSUE TITLE
Andromeda: unexpected results

### ISSUE THREAD

**Issue by LZwart** [compomics/searchgui#99]
Hi!

I've been comparing the results from different search engines using an 8-plex iTRAQ data set using SearchGUI. So far, MS-GF+ seems to be performing comparably to Mascot (independent analysis) and X!TANDEM has slightly fewer valid protein identifications. 

However, when I perform the search with Andromeda using exactly the same input files and parameters, only about half the number of valid protein identifications are made (about 2300 vs 5000). I've repeated the search with the UniProt database for my organism instead of my custom database and also with all of the default SearchGUI parameters, but it doesn't change much. 

I've looked at the Certificates of Analysis from PeptideShaker. The FNR is very high with the Andromeda search and while the number of validated PSM/peptides/proteins are always lower, all of the "Total Possible" numbers are similar to those obtained with MS-GF+. Could it have something to do with how the identifications are validated?

I would appreciate any suggestions/explanations.

Best regards
Lizahn Zwart

**Comment by mvaudel** [comment]
Hi Lizahn,

Thank you for this detailed and very informative report. From what you say
it seems that Andromeda introduces high scoring false positives hence
reducing the number of hits passing a given FDR threshold. Andromeda is
designed to run inside MaxQuant and it can be that it does not perform as
well on external data. Unless you have a specific interest in Andromeda I
would consider leaving it out for this analysis. I can give a look at your
results if you like and forward them to the Andromeda development team, but
I cannot promise anything in terms of speed as we are currently extremely
busy with a limited workforce :)

Best regards,

Marc

2016-03-21 9:34 GMT+01:00 LZwart <notifications@github.com>:

**Comment by ulrich-eckhard** [comment]
in our hands Andromeda also frequently performs "less" than Mascot or X!
Tandem e.g. and Jürgen Cox even says that MaxQuant (did all my Andromeda
Searches so far within MQ) is "less optimisitic" than the other two (MQ
Summer School). another thing that I frequently observe is that different
search engines perform better with different instrumentation. so e.g.
Thermo's Velos vs. QE vs. Bruker Impact II (a TOF). Another thing to
consider: we got the impression, that MQ is "easier" kicked off if the
calibration of the instrument is not ideal. so when it is e.g. more than
4ppm off (but hard to call the exact cut-off). I know it is doing some
recalibration, but for us results made huge differences if our instrument
was calibrated to plus/minus 2ppm around 0, or around +3 ppm e.g. but not
fully sure if that makes sense ...

**Comment by LZwart** [comment]
Thanks a lot for your comments! I can proceed without using Andromeda. I just thought it would be good to include it, being rather widely used. 
Marc, I would appreciate it if you could look at the results if/when you have time. Which results would you need to see, exactly?
On the topic of comparing search engines, could you perhaps tell me whether the default advanced parameters for each search engine in SearchGUI are optimised so that the searches with multiple search engines are comparable, or whether these parameters are optimised for the greatest sensitivity/specificity for each search engine individually?

Best regards
Lizahn

**Comment by mvaudel** [comment]
Hi again,

In order to reproduce your results I would need the mgf, fasta, and parameters file. However, I don't think I will be able to look into this in a near future as we are having some severe issues at the moment.

In general we let the advanced parameters to the default of the developers, unless more testing by us and our users show that default are not optimal anymore with modern datasets. Ideally we would like to maximize the individual performance of each search engine, but this is very dataset dependent. For the combination, we change mainly formatting options to simplify the post processing.

Hope this helps,

Marc

**Comment by LZwart** [comment]
Hi, Marc.

It's fine if you won't have time to look at it. I'm sure the other search engines will be sufficient.

Thanks a lot for your help and good luck dealing with the issues that you're having.

All the best
Lizahn
